force-app/main/default/objects/Case/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Contact.Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>$RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <formula>Student_Contact_For_Updates__r.SRN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Mentee.recordType-meta.xml
<RecordType>
    <fullName>Mentee</fullName>
    <active>true</active>
    <businessProcess>Behavior Management</businessProcess>
    <label>Mentee</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <businessProcess>Mentor</businessProcess>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mentor__c.field-meta.xml
<CustomField>
    <fullName>Mentor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mentor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mentor)</relationshipLabel>
    <relationshipName>Contacts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admission Cancelled</fullName>
            </value>
            <value>
                <fullName>Pursuing</fullName>
                <default>true</default>
                <label>Pursuing</label>
            </value>
            <value>
                <fullName>Detained</fullName>
            </value>
            <value>
                <fullName>Year Back</fullName>
            </value>
            <value>
                <fullName>Not Reported</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Contact__r.Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Parent_Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Parent_Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <formula>Contact__r.SRN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <formula>TEXT(Contact__r.Student_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Fee_ReminderToMentors_Batch.cls
global class Fee_ReminderToMentors_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Professor').getRecordTypeId();
        
        return Database.getQueryLocator([
            SELECT Id, Name, Record_Type_Name__c, hed__WorkEmail__c, Account_Name__c,
            (SELECT Id, Record_Type_Name__c, ContactId FROM Cases)
            FROM Contact 
            WHERE RecordTypeId = :contactRecTypeId AND Account_Name__c != 'REVA Academy for Corporate Excellence'
        ]);
    }
    
    global void execute(Database.BatchableContext bc, List<Contact> lstCon) {
        try {
            for (Contact professor : lstCon) {
                System.debug('Processing professor: ' + professor.Name);
                
                List<Case> relatedCases = [
                    SELECT Id, ContactId
                    FROM Case
                    WHERE ContactId = :professor.Id
                ];
                
                if (!relatedCases.isEmpty()) {
                    Case professorCase = relatedCases[0];
                    
                    List<CaseTeamMember> caseTeamMembers = [
                        SELECT Id, MemberId, Member.Name, ParentId
                        FROM CaseTeamMember
                        WHERE ParentId = :professorCase.Id
                    ];
                    
                    if (!caseTeamMembers.isEmpty()) {
                        Set<Id> memberIds = new Set<Id>();
                        for (CaseTeamMember ctm : caseTeamMembers) {
                            memberIds.add(ctm.MemberId);
                        }
                        
                        List<Student_Fee__c> fees = [
                            SELECT Id, Name, Due_Date__c, Amount_Pending__c, SRN_Number__c
                            FROM Student_Fee__c
                            WHERE Due_Date__c <=TODAY  AND Amount_Pending__c > 0 AND Contact__c IN :memberIds
                        ];
                        System.debug('Fees: ' + fees);
                        
                        if (!fees.isEmpty()) {
                            Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
                            List<Contact> contactstudentfee = [
                                SELECT Id, Name, SRN_Number__c, hed__WorkEmail__c, Mentor__c, Application_Number__c,
                                (SELECT Id, Name, Due_Date__c, Amount_Pending__c, SRN_Number__c
                                 FROM Student_Fees__r WHERE  Due_Date__c <=TODAY AND Amount_Pending__c > 0 AND Contact__c IN :memberIds)
                                FROM Contact WHERE Student_Status__c = 'Pursuing' AND Id IN :memberIds AND RecordTypeId = :contactRecTypeId
                            ];
                            
                            System.debug('ContactStudentFee: ' + contactstudentfee);
                            
                            List<string> lst_ToEmail = new List<string>();
                            List<Messaging.SingleEmailMessage> lst_Email = new List<Messaging.SingleEmailMessage>();
                            
                            if (professor.hed__WorkEmail__c != null && professor.hed__WorkEmail__c.contains('@')) {
                                lst_ToEmail.add(professor.hed__WorkEmail__c);
                            }
                            
                            List<OrgWideEmailAddress> oweaList = [
                                SELECT Id, DisplayName FROM OrgWideEmailAddress WHERE DisplayName = 'REVA Alerts' LIMIT 1
                            ];
                            
                            if (!oweaList.isEmpty()) {
                                OrgWideEmailAddress owea = oweaList[0];
                                
                                String emailBody = '<p>Dear Mr/ Ms. Mentor ' + professor.Name + ',</p>' +
                                    '<p>This is a reminder about the upcoming Fee Payment deadlines for your mentees.</p>' +
                                    '<table border="1" cellpadding="0" cellspacing="0" width="800px">' +
                                    '<tr>' +
                                    '<td style="color:#f57f26;padding: 5px;text-align: center;"><b>SRN Number</b></td>' +
                                    '<td style="color:#f57f26;padding: 5px;text-align: center;"><b>Application Number</b></td>' +
                                    '<td style="color:#f57f26;padding: 5px;text-align: center;"><b>Student Name</b></td>' +
                                    '<td style="color:#f57f26;padding: 5px;text-align: center;"><b>Total Pending Amount</b></td>' +
                                    '<td style="color:#f57f26;padding: 5px;text-align: center;"><b>Due Date</b></td>' +
                                    '</tr>';
                                
                                for (Contact mentor : contactstudentfee) {
                                    Decimal totalPendingAmount = 0;
                                    String strDateOfconf = '';
                                    String srnnumber = '';
                                    Date earliestDueDate = null;
                                    
                                    if (mentor.SRN_Number__c != null) {
                                        srnnumber = mentor.SRN_Number__c;
                                    }
                                    
                                    if (!mentor.Student_Fees__r.isEmpty()) {
                                        // Find the earliest due date
                                        
                                        for (Student_Fee__c studentFee : mentor.Student_Fees__r) {
                                            if (earliestDueDate == null || studentFee.Due_Date__c < earliestDueDate) {
                                                earliestDueDate = studentFee.Due_Date__c;
                                            }
                                            totalPendingAmount += studentFee.Amount_Pending__c;
                                        }
                                        
                                        // Format the earliest due date
                                        strDateOfconf = earliestDueDate != null ? DateTime.newInstance(earliestDueDate.year(), earliestDueDate.month(), earliestDueDate.day()).format('dd/MM/yyyy') : '';
                                        System.debug('Earliest Due Date: ' + strDateOfconf);
                                    }                            
                                    if (totalPendingAmount > 0) {
                                        emailBody += '<tr>' +
                                            '<td style="padding: 5px;text-align: center;">' + srnnumber + '</td>' +
                                            '<td style="padding: 5px;text-align: center;">' + mentor.Application_Number__c + '</td>' +
                                            '<td style="padding: 5px;text-align: center;">' + mentor.Name + '</td>' +
                                            '<td style="padding: 5px; text-align: center;">' + totalPendingAmount + '</td>' +
                                            '<td style="padding: 5px;text-align: center;">' + strDateOfconf + '</td>' +
                                            '</tr>';
                                    }
                                }
                                
                                emailBody += '</table>' +
                                    '<p>Please ensure your mentees are aware of the upcoming deadlines and take the necessary steps for fee payment.</p>' +
                                    '<p>Thank you for your attention to this matter.</p>' +
                                    '<p><b>Note:</b> In case the mentee has paid the fee and is not updated in the Student Portal, please ask the mentee to reach out to the Accounts Department, 1st Floor, Admin Block.</p>' +
                                    '<p>The mentee will not be allowed to write IA if the outstanding is not cleared.</p>' +
                                    '<p>Sincerely,<br>Office of Finance and Accounts,<br>REVA University</p>';
                                
                                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                                email.setToAddresses(lst_ToEmail);
                                email.setSubject('Fee Payment Reminder For Your Mentees');
                                email.setHtmlBody(emailBody);
                                
                                // Set the OrgWideEmailAddress
                                email.setOrgWideEmailAddressId(owea.Id);
                                
                                lst_Email.add(email);
                            }
                            
                            // Send emails
                            Messaging.sendEmail(lst_Email);
                        }
                    }
                }
            }
        } catch (Exception e) {
            // Log the exception or take appropriate action
            System.debug('Error in execute method: ' + e.getMessage());
            System.debug('Error in execute getcause method: ' + e.getCause());
            System.debug('Error in execute getLineNumber method: ' + e.getLineNumber());
            System.debug('Error in execute getStackTraceString method: ' + e.getStackTraceString());
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        // Implement the finish logic if needed
    }
}