force-app/main/default/objects/Case/fields/Case_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Case_Contact_Name__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Student_Contact_For_Updates__r.FirstName)) &amp;&amp; NOT(ISBLANK(Student_Contact_For_Updates__r.LastName)),
    Student_Contact_For_Updates__r.FirstName &amp; &quot; &quot; &amp; Student_Contact_For_Updates__r.LastName,
    Contact.FirstName &amp; &quot; &quot; &amp; Contact.LastName
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Mobile_Number__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Student_Contact_For_Updates__r.MobilePhone)),
    Student_Contact_For_Updates__r.MobilePhone,
    Contact.MobilePhone
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Hostel_Category__c.field-meta.xml
<CustomField>
    <fullName>Hostel_Category__c</fullName>
    <label>Support Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Housekeeping</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Vending Machine</fullName>
            </value>
            <value>
                <fullName>Washing Machine</fullName>
            </value>
            <value>
                <fullName>Medical Centre</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Food Booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Hostel_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Hostel_Sub_Category__c</fullName>
    <label>Hostel Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Hostel_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application Issue</fullName>
            </value>
            <value>
                <fullName>Carpentry</fullName>
            </value>
            <value>
                <fullName>Civil</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Laundry</fullName>
            </value>
            <value>
                <fullName>Medical Centre</fullName>
            </value>
            <value>
                <fullName>Mess</fullName>
            </value>
            <value>
                <fullName>Network Speed</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Password Issue</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Room Cleaning</fullName>
            </value>
            <value>
                <fullName>QR Code Issue</fullName>
            </value>
            <value>
                <fullName>Vending Machine</fullName>
            </value>
            <value>
                <fullName>Washing Machine</fullName>
            </value>
            <value>
                <fullName>Wifi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee Payment</fullName>
            </value>
            <value>
                <fullName>Payment Gateway Clarifications</fullName>
            </value>
            <value>
                <fullName>Program Fee</fullName>
            </value>
            <value>
                <fullName>Receipts</fullName>
            </value>
            <value>
                <fullName>Bus Fee</fullName>
            </value>
            <value>
                <fullName>Driver Behavior</fullName>
            </value>
            <value>
                <fullName>Driver Contact Number</fullName>
            </value>
            <value>
                <fullName>Duplicate Bus Pass</fullName>
            </value>
            <value>
                <fullName>If miss the REVA Bus, How to come by BMTC buses</fullName>
            </value>
            <value>
                <fullName>Issue of Bus Pass</fullName>
            </value>
            <value>
                <fullName>Pick Up stop changes</fullName>
            </value>
            <value>
                <fullName>Pick Up points and its timings</fullName>
            </value>
            <value>
                <fullName>Route Number</fullName>
            </value>
            <value>
                <fullName>Seat Availability</fullName>
            </value>
            <value>
                <fullName>Courses Related/Curricular</fullName>
            </value>
            <value>
                <fullName>Library Related</fullName>
            </value>
            <value>
                <fullName>Leaves/Medical Leaves</fullName>
            </value>
            <value>
                <fullName>Attendance</fullName>
            </value>
            <value>
                <fullName>Internal Assessment Marks</fullName>
            </value>
            <value>
                <fullName>Adress Proof Certicate</fullName>
            </value>
            <value>
                <fullName>Bonafide Certificate</fullName>
            </value>
            <value>
                <fullName>Change of Branch Fee</fullName>
            </value>
            <value>
                <fullName>Course Completion Certificate</fullName>
            </value>
            <value>
                <fullName>Medium of Instruction Certicate</fullName>
            </value>
            <value>
                <fullName>Migration Certificate</fullName>
            </value>
            <value>
                <fullName>Permanent Identity Card</fullName>
            </value>
            <value>
                <fullName>Scholarship Requests</fullName>
            </value>
            <value>
                <fullName>Sponsorships</fullName>
            </value>
            <value>
                <fullName>Student Profile Changes</fullName>
            </value>
            <value>
                <fullName>Study Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WhatsApp_Notification_Template__mdt/WhatsApp_Notification_Template__mdt.object-meta.xml
<CustomObject>
    <label>WhatsApp Notification Template</label>
    <pluralLabel>WhatsApp Notification Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/WhatsApp_Notification_Template__mdt/fields/Template_Field__c.field-meta.xml
<CustomField>
    <fullName>Template_Field__c</fullName>
    <label>Template Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Update_Student_Support_WAppNotification.cls
public class Update_Student_Support_WAppNotification {
    @InvocableMethod(label='Student Support Case Cahanged Notification' description='Send Support WhatsApp Notifications to student')
    public static void sendChangedCaseWhatsAppNotification(List<String> recordIds) {
        // Ensure that recordIds is not empty
        if (recordIds != null && !recordIds.isEmpty()) {
            // Make the callout asynchronously
            makeLeaveApprovalCallout(recordIds);
        } else {
            System.debug('Record IDs list is empty or null');
        }
    }

    @Future(callout=true)
    public static void makeLeaveApprovalCallout(List<String> recordIds) {
        // Fetch the related record data
        List<Case> requiredFields = [
            SELECT Contact.Name, Contact.MobilePhone,Case_Contact_Name__c,Contact_Mobile_Number__c,Hostel_Sub_Category__c, Hostel_Category__c, Sub_Category__c, CaseNumber, CreatedDate, Description, Status
            FROM Case
            WHERE Id IN :recordIds
            LIMIT 1
        ];
        // Check if related record is found
        if (!requiredFields.isEmpty() && !String.isBlank(requiredFields[0].Contact_Mobile_Number__c)) {
            Case requiredField = requiredFields[0];

            // Create WhatsAppNotification instance
            Yellow_AI_Utility.WhatsAppNotification notification1 = new Yellow_AI_Utility.WhatsAppNotification();
            notification1.templateId = 'complaintupdate_student';

            // Fetch keys from custom metadata based on templateId
            List<WhatsApp_Notification_Template__mdt> templateMetadata = [
                SELECT Template_Field__c, Template_ID__c
                FROM WhatsApp_Notification_Template__mdt
                WHERE Template_ID__c = :notification1.templateId
            ];
        System.debug('templateMetadata: ' + templateMetadata);
            // Populate the params map dynamically
            notification1.params = new Map<String, String>();
            for (WhatsApp_Notification_Template__mdt metadata : templateMetadata) {
                // Split values based on comma and add each as a separate key
                String[] keys = metadata.Template_Field__c.split(',');
                for (String key : keys) {
                    // You can set dynamic values for each key based on the related record
                    if (key.trim() == 'studentname') {
                        notification1.params.put(key.trim(), requiredField.Case_Contact_Name__c);
                    } else if (key.trim() == 'complainttype') {
                        // Assuming Start_Date__c is a Date field
                        String complaintType = requiredField.Hostel_Category__c + requiredField.Hostel_Sub_Category__c != '' ? '-'+requiredField.Hostel_Category__c: '';
                        notification1.params.put(key.trim() + ' ', complaintType);
                    } else if (key.trim() == 'complaintnumber') {
                        // Assuming End_Date__c is a DateTime field
                        notification1.params.put(key.trim() + ' ', requiredField.CaseNumber);
                    } else if (key.trim() == 'complaintcreationdate') {
                        notification1.params.put(key.trim() + ' ', String.valueOf(requiredField.CreatedDate));
                    } else if (key.trim() == 'complaintdescription') {
                        notification1.params.put(key.trim() + ' ', requiredField.Description);
                    } else if (key.trim() == 'complaintstatus') {
                        notification1.params.put(' ' + key.trim() + ' ', requiredField.Status);
                    }
                }
            }
			
            // Create list of notifications
            List<Yellow_AI_Utility.WhatsAppNotification> notifications = new List<Yellow_AI_Utility.WhatsAppNotification>{notification1};

            System.debug('notification1: ' + notification1);
            // Create map of phone numbers to notifications
            Map<String, List<Yellow_AI_Utility.WhatsAppNotification>> phoneNumbersToNotifications = new Map<String, List<Yellow_AI_Utility.WhatsAppNotification>>();
           // phoneNumbersToNotifications.put(requiredField.Contact_Mobile_Number__c, notifications);

            if(requiredField.Contact_Mobile_Number__c !=null){
                String plusRemoved = requiredField.Contact_Mobile_Number__c.replace('+', '');
                String correctedWhatsappNumber = plusRemoved.replace('-', '');
                phoneNumbersToNotifications.put(correctedWhatsappNumber, notifications);
            }  
             
            // Send notifications
            HttpResponse response = Yellow_AI_Utility.sendWhatsAppNotifications(phoneNumbersToNotifications);
            System.debug('WhatsApp notification response: ' + response);
        } else {
            System.debug('No related record found for the provided ID');
        }
    }
}