force-app/main/default/objects/Case/fields/Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Status__c</fullName>
    <label>Case Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Program related</fullName>
            </value>
            <value>
                <fullName>Academic Related</fullName>
            </value>
            <value>
                <fullName>IT Related</fullName>
            </value>
            <value>
                <fullName>Exam Related</fullName>
            </value>
            <value>
                <fullName>Connect with CoE Office</fullName>
            </value>
            <value>
                <fullName>Connect with Office of Registrar</fullName>
            </value>
            <value>
                <fullName>Connect with Alumni Office</fullName>
            </value>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Admission</fullName>
            </value>
            <value>
                <fullName>Hostel</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Maintainance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>HouseKeeping</fullName>
            </value>
            <value>
                <fullName>Mess</fullName>
            </value>
            <value>
                <fullName>Laundry</fullName>
            </value>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Health Center</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
                <isActive>false</isActive>
                <label>Food</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Mentor_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Mobile__c</fullName>
    <formula>Mentor__r.MobilePhone</formula>
    <label>Mentor Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Mentor_Name__c.field-meta.xml
<CustomField>
    <fullName>Mentor_Name__c</fullName>
    <formula>Mentor__r.FirstName &amp; &quot; &quot; &amp; Mentor__r.LastName</formula>
    <label>Mentor Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <formula>Contact.Program_Batch__r.Program_Batch_Name__c</formula>
    <label>Program Batch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Mentee.recordType-meta.xml
<RecordType>
    <fullName>Mentee</fullName>
    <active>true</active>
    <businessProcess>Behavior Management</businessProcess>
    <label>Mentee</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Mentor.recordType-meta.xml
<RecordType>
    <fullName>Mentor</fullName>
    <active>true</active>
    <businessProcess>Mentor</businessProcess>
    <label>Mentor</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Support_Request.recordType-meta.xml
<RecordType>
    <fullName>Support_Request</fullName>
    <active>true</active>
    <businessProcess>Behavior Management</businessProcess>
    <label>Support Request</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Academic_Program__c</fullName>
    <formula>IF( Record_Type_Name__c = &apos;Parent&apos;, ReportsTo.Primary_Academic_Program__r.Name,Primary_Academic_Program__r.Name)</formula>
    <label>Academic Program</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FetchCampusRecData.cls
/**
 * @description class to fetch data related to mentor mentee and support requests.
 * @author Keval | 25/11/2019
 */

 public without sharing class FetchCampusRecData {

    /**
     * @description this class is to fetch the cases with subject used in mentor and mentee component
     * @param userId String - User Id for case reference.
     * @return List<Case> - List of cases related to the user.
     */
   
    @AuraEnabled(cacheable=true)
    public static List<Case> getAllCases() {
        try{
         RecordType rt = [SELECT Id FROM RecordType 
                         WHERE SobjectType = 'Case' 
                         AND DeveloperName = 'Mentee' 
                         LIMIT 1];
        
        string contactId=[SELECT ContactId FROM User WHERE Id=:userInfo.getUserId() Limit 1].ContactId;
        List<Case> cases = [
            SELECT Id, CaseNumber, Program_Batch__c, Mentor_Name__c, Subject,Mentor_Mobile__c, Contact.Name 
            FROM Case 
            WHERE ContactId = :contactId AND RecordTypeId=:rt.Id ORDER BY CreatedDate DESC   
        ];
        // Print fetched case in debug logs
        system.debug(cases);
        if (cases.isEmpty()) {
           return null;
        }
        return cases;
    }
    catch(Exception e){ throw new AuraHandledException('Error fetching cases:' +e.getMessage());
    }
}

    /**
     * @description Fetches support request cases related to a specific user.
     * @param userId String - User Id for support request case reference.
     * @return List<Case> - List of support request cases related to the user.
     */
    @AuraEnabled(cacheable=true)
    public static List<Case> getAllCasesWithoutSubject() {
        try {
            RecordType rt = [SELECT Id FROM RecordType 
                             WHERE SobjectType = 'Case' 
                             AND DeveloperName = 'Support_Request' 
                             LIMIT 1];
            
            string contactId=[SELECT ContactId FROM User WHERE Id=:userInfo.getUserId() Limit 1].ContactId;
                
            List<Case> supportReqList = [
                SELECT Id, CaseNumber,Status,Category__c, Case_Status__c, Contact.Name
                FROM Case 
                WHERE ContactId = :contactId
                AND RecordTypeId=:rt.Id ORDER BY CreatedDate DESC
            ];
            
            return supportReqList;
        } catch(Exception e) { throw new AuraHandledException('Error fetching support request cases: ' + e.getMessage());
        }
    }
     
             /**
     * @This class is to fetch contact for campus recruitment drive
     * @param userId String - User Id for contact reference.
     * @return List<Contact> - List of contacts related to the user.
     */
        @AuraEnabled(cacheable=true)
        public static List<Contact> getContacts() {
            try {
                return [SELECT Id, Name, MobilePhone, Academic_Program__c FROM Contact LIMIT 50];
            } catch(Exception e) { throw new AuraHandledException('Error in fetching contacts: ' + e.getMessage());
            }
        }
    

}