force-app/main/default/objects/Case/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>As Soon As Possible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ManodhaaraAppointment__c/ManodhaaraAppointment__c.object-meta.xml
<CustomObject>
    <label>Manodhaara Appointment</label>
    <nameField>
        <displayFormat>MANO-{0000000}</displayFormat>
        <label>Manodhaara Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manodhaara Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ManodhaaraAppointment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>ManodhaaraAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ManodhaaraAppointment__c/fields/Reason_For_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Cancellation__c</fullName>
    <description>This field stores the reason for cancellation captured from UI</description>
    <label>Reason For Cancellation</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ManodhaaraAppointment__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Urgent</fullName>
            </value>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>Emergency</fullName>
            </value>
            <value>
                <fullName>Semi Urgent</fullName>
            </value>
            <value>
                <fullName>Not So Urgent</fullName>
            </value>
            <value>
                <fullName>As Soon As Possible</fullName>
                <isActive>false</isActive>
                <label>As Soon As Possible</label>
            </value>
            <value>
                <fullName>Critical</fullName>
                <isActive>false</isActive>
                <label>Critical</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WhatsAppNotificationsTest.cls
@isTest(SeeAllData=true)
public class WhatsAppNotificationsTest {
    
      // Mock class for HTTP callouts
    public class MockHttpResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // You can customize the response as needed for testing
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status": "success"}');
            res.setStatusCode(200);
            return res;
        }
    }

    @isTest
    static void testSendWhatsAppNotifications() {
        
        Profile testSystemAdminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
         User testSystemAdmin = new User(
            FirstName = 'Test',
            LastName = 'System Admin',
            Email = 'testuser@example.com',
            Username = 'test09878@example.com',
            Alias = 'TUser',
            CommunityNickname = 'testsystemadmin',
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = testSystemAdminProfile.Id,
            LanguageLocaleKey = 'en_US'
           // ManagerId = testCounsellor.id
        );
        insert testSystemAdmin;
        
        
        Contact testContact = new Contact(
                FirstName = 'Test Contact',
                LastName = 'Test Last',
                Email = 'testuser@example.com',
                MobilePhone = '917088142959'
                // Set other required fields
            );
            insert testContact;
        
        Case testCase = new Case(
                Subject = 'Test Case',
                ContactId = testContact.id,
                Description__c = 'Test Description'
                // Set other required fields
            );
            insert testCase;
        
        // Create a test appointment record
        ManodhaaraAppointment__c testAppointment = new ManodhaaraAppointment__c(
           Case__c = testCase.id,
               // LastName = 'Test Last',
                Email__c = 'testuser@example.com',
            Start_Date_Time__c = datetime.newInstance(2024, 1, 25, 3, 30, 0),
            End_Date_Time__c = datetime.newInstance(2024, 1, 25, 4, 30, 0),
            Appointment_Date__c = system.today(),
            Reason_For_Cancellation__c = 'Test Reason',
            Severity__c = 'As Soon As Possible'
            
        );
        insert testAppointment;

        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
        
        // Call the sendWhatsAppNotifications method
        Test.startTest();
        List<String> recordIds = new List<String>{testAppointment.Id};
        WhatsAppNotifications.Appointment_ApprovedNotifications(recordIds);
        Initiated_WhatsappNotification.Appointment_InitiatedNotifications(recordIds);
        Cancelled_WhatsappNotification.Appointment_CancelledNotification(recordIds);
        Test.stopTest();

        // Perform assertions based on your use case
        // For example, check if the callout was made successfully
        // Check if the DML operations were performed as expected
    }
}