force-app/main/default/objects/Case/fields/Hostel_Category__c.field-meta.xml
<CustomField>
    <fullName>Hostel_Category__c</fullName>
    <label>Support Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Housekeeping</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Vending Machine</fullName>
            </value>
            <value>
                <fullName>Washing Machine</fullName>
            </value>
            <value>
                <fullName>Medical Centre</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Food Booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Hostel_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Hostel_Sub_Category__c</fullName>
    <label>Hostel Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Hostel_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application Issue</fullName>
            </value>
            <value>
                <fullName>Carpentry</fullName>
            </value>
            <value>
                <fullName>Civil</fullName>
            </value>
            <value>
                <fullName>Electrical</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Laundry</fullName>
            </value>
            <value>
                <fullName>Medical Centre</fullName>
            </value>
            <value>
                <fullName>Mess</fullName>
            </value>
            <value>
                <fullName>Network Speed</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Password Issue</fullName>
            </value>
            <value>
                <fullName>Pest Control</fullName>
            </value>
            <value>
                <fullName>Plumbing</fullName>
            </value>
            <value>
                <fullName>Room Cleaning</fullName>
            </value>
            <value>
                <fullName>QR Code Issue</fullName>
            </value>
            <value>
                <fullName>Vending Machine</fullName>
            </value>
            <value>
                <fullName>Washing Machine</fullName>
            </value>
            <value>
                <fullName>Wifi</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentSupportWAppNotificationTest.cls
@istest
public class StudentSupportWAppNotificationTest {
Public class RestMock implements HttpCalloutMock {
       public HTTPResponse respond(HTTPRequest req) {
            String fullJson = '{"unicode":"false","sender":"REVAUN","message":{"text":"1234 is your One Time Password(OTP) for REVA. This OTP is valid till 5Mins - REVA University","recipient":"918951419170"},"extra":{"templateId":null,"dltContentId":"1007494991024424186","corelationId":null}}';
            
            HTTPResponse res = new HTTPResponse();
            res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
            return res;
        }
    }  
     Public class MockHttpResponseGenerator implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
        String fullJson = '{"unicode":"False","sender":"REVAUN","message":{"text":"Dear Applicant\r\n\r\nMake a payment of Rs. 8000.00 to confirm your Provisional Admission at https:/\r\neva-university--couat1908.sandbox.my.site.com/Admissions/s/payment-page?contactId=0030T00000VQx7FQAT&isPAF=true&stupayid=a1P0T000001WIxSUAW.\r\nIn case of confusion connect with your admission counsellor.\r\n\r\nRegards\r\nREVA University","recipient":"918951419170"},"extra":{"templateId":null,"dltContentId":"1007494991024424186","corelationId":null}}';
        HttpResponse res = new HttpResponse();
       res.setHeader('Content-Type', 'text/json');
            res.setBody(fullJson);
            res.setStatusCode(200);
        return res;
    }
   }
      @isTest
    static void testSendChangedCaseWhatsAppNotification() {
        
         Contact testContact = new Contact(LastName = 'Test Contact', MobilePhone = '1234567890',Email = 'test@example.com');
        insert testContact;
        
        // Test data setup
        Case testCase = new Case(
            Hostel_Category__c = 'Maintenance',
            Hostel_Sub_Category__c = 'Electrical',
            Description = 'Test complaint description',
            Status = 'New',
            contactId=testContact.Id
        );
        insert testCase;

        
         Test.setMock(HttpCalloutMock.class, new RestMock());
        Test.startTest();
        // Call the method to test
        Update_Student_Support_WAppNotification.sendChangedCaseWhatsAppNotification(new List<String>{testCase.Id});
        New_Student_Support_WhatsAppNotification.sendNewCaseWhatsAppNotification(new List<String>{testCase.Id});
        Test.stopTest();

        // Assertions
        // Add your assertions here
    }
}