force-app/main/default/objects/Rpl_Student_Registration__c/Rpl_Student_Registration__c.object-meta.xml
<CustomObject>
    <label>Student Registrations</label>
    <nameField>
        <label>Student Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Count_of_non_appeared_drives__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Count_of_non_appeared_drives__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Of Non Appeared Drives</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Is_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RPL_Mark_Number_Of_Drives_Not_Attended.cls
public class RPL_Mark_Number_Of_Drives_Not_Attended {
    
    @InvocableMethod(label='Mark Number Of Drives Not Attended')
    public static void blockAbsentStudents(List<List<string>> studentRegistrationIds){
        List<string> studentRegIds = studentRegistrationIds[0];
        
        List<Rpl_Student_Registration__c> studentRegistrationList = [Select Rpl_Is_Blocked__c, Rpl_Count_of_non_appeared_drives__c From Rpl_Student_Registration__c
                                                                     Where Id In:studentRegIds];
        for(Rpl_Student_Registration__c eachStudentRegistration : studentRegistrationList){	
           eachStudentRegistration.Rpl_Count_of_non_appeared_drives__c = (eachStudentRegistration.Rpl_Count_of_non_appeared_drives__c == NULL) ? 1 : eachStudentRegistration.Rpl_Count_of_non_appeared_drives__c + 1;
        }
        update  studentRegistrationList;               
    }
    
}