force-app/main/default/objects/Rpl_Student_Registration__c/Rpl_Student_Registration__c.object-meta.xml
<CustomObject>
    <label>Student Registrations</label>
    <nameField>
        <label>Student Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Interested_in_placement__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Interested_in_placement__c</fullName>
    <label>Interested In Placement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Personal_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Personal_Mail_ID__c</fullName>
    <label>Personal Mail - ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_University_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_University_Mail_ID__c</fullName>
    <label>University Mail - ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/RPL_PDFViewerController_Test.cls
@isTest
private class RPL_PDFViewerController_Test {
    @testSetup
    private static void createNewContentVersion() {
        Rpl_Student_Registration__c std = new Rpl_Student_Registration__c();
        std.Name = 'Test Data1';
        std.Rpl_Personal_Mail_ID__c = 'test@gmail.com';
        std.Rpl_Interested_in_placement__c = 'Yes';
        std.Rpl_University_Mail_ID__c = '123123123@reva.edu.in';
        insert std;

        ContentVersion newContentVersion = new ContentVersion();
        newContentVersion.Title = '123 - TestDocument';
        newContentVersion.VersionData = EncodingUtil.base64Decode('Test File Data');
        newContentVersion.PathOnClient = '123 - TestDocument.pdf'; // Set this to the desired file name
        newContentVersion.FirstPublishLocationId = std.Id; // Link to the record
        insert newContentVersion;
    }

    @isTest
    private static void getRelatedFilesByRecordId() {
        Rpl_Student_Registration__c std = [Select Id From Rpl_Student_Registration__c Limit 1];
        System.debug('Student Registration ' + std);

        Map<ID, String> mapIdTitle = RPL_PDFViewerController.getRelatedFilesByRecordId(std.Id);
        System.debug('Map Id Title ' + mapIdTitle);

        // Check if there is at least one entry in the map
        System.assertEquals(1, mapIdTitle.size(), 'No Content document found');

        // If there is an entry, check the values
        if (mapIdTitle.size() == 1) {
            String docTitle = mapIdTitle.values()[0];
            // Add any additional assertions related to the docTitle if needed
        }
    }
}