force-app/main/default/objects/Class_Adjustment__c/Class_Adjustment__c.object-meta.xml
<CustomObject>
    <label>Class Adjustment</label>
    <nameField>
        <displayFormat>CA - {0}</displayFormat>
        <label>Class Adjustment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Adjustments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Adjustment__c/fields/Leave_Request__c.field-meta.xml
<CustomField>
    <fullName>Leave_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leave Request</label>
    <referenceTo>Leave_Request__c</referenceTo>
    <relationshipLabel>Class Adjustments</relationshipLabel>
    <relationshipName>Class_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Adjustment__c/fields/Leave_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Leave_Request_Status__c</fullName>
    <formula>TEXT(Leave_Request__r.Leave_Request_Status__c)</formula>
    <label>Leave Request Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Class_Adjustment__c/fields/Requested_Professor__c.field-meta.xml
<CustomField>
    <fullName>Requested_Professor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested Professor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Class_Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Adjustment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR - {0}</displayFormat>
        <label>Leave Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/HCM_Leave_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>HCM_Leave_Record_ID__c</fullName>
    <label>HCM Leave Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Leave_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Leave_Request_Status__c</fullName>
    <label>Leave Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved by Professors</fullName>
            </value>
            <value>
                <fullName>Approved by Manager</fullName>
            </value>
            <value>
                <fullName>Rejected by Professor</fullName>
            </value>
            <value>
                <fullName>Rejected by Manager</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LMS_GetClassAdjestment.cls
@RestResource(urlMapping='/GetClassAdjustment/*')
global class LMS_GetClassAdjestment 
{    
    @HttpPost
    global static list<ReqWrapper> GetLeaveRequest()
    {
        responseWrapper objResWrp = new responseWrapper();
        GetRequest objReqWrp = new GetRequest();
        string jsonbody;        
        list<Adjustmentwrapper> lst_ClsAdj  = new list<Adjustmentwrapper>();        
        RestRequest  objResReq = RestContext.request;
        RestResponse objResResp =  RestContext.response;
        jsonbody = objResReq.requestBody.toString().trim();        
        ReqWrapper reqwrap = new ReqWrapper();
        list<ReqWrapper> lst_reqwrap = new list<ReqWrapper>();
        if(jsonbody != null)
        {
            objReqWrp = (GetRequest)system.JSON.deserialize(jsonbody, GetRequest.class);
            for(Class_Adjustment__c objCls :[select id,Name,Status__c,Leave_Request__r.HCM_Leave_Record_ID__c,Leave_Request__c,
                                             Leave_Request__r.Name,Requested_Professor__c,Requested_Professor__r.Name,
                                             Leave_Request__r.Leave_Request_Status__c  from Class_Adjustment__c where
                                             Leave_Request__r.HCM_Leave_Record_ID__c =: objReqWrp.LeaveRecordId])
            {
                Adjustmentwrapper objwrap = new Adjustmentwrapper();
                objwrap.id = objCls.id;
                objwrap.Name = objCls.Name;
                objwrap.Status = objCls.Status__c;
                objwrap.LeaveReqName = objCls.Leave_Request__r.Name;
                objwrap.Hcmid = objCls.Leave_Request__r.HCM_Leave_Record_ID__c;
                objwrap.ReqProf = objCls.Requested_Professor__r.Name;  
                lst_ClsAdj.add(objwrap);
            }
            reqwrap.Details = lst_ClsAdj;
            lst_reqwrap.add(reqwrap);
        }        
        return lst_reqwrap;
    }
    global class GetRequest
    {
        public string leaveRecordId;
    }
    global class responseWrapper
    {
        public String status;
        public String message;        
    }
    global class ReqWrapper
    {
        @AuraEnabled public list<Adjustmentwrapper> Details{get;set;}
    }
    global class Adjustmentwrapper
    {
        public string id;
        public string Name;
        public string Status;
        public string LeaveReqName;
        public string Hcmid;
        public string ReqProf;
    }
}