force-app/main/default/objects/Meal_Timings__c/Meal_Timings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Meal Timings</label>
</CustomObject>

force-app/main/default/objects/Meal_Timings__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Meal_Timings__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reva_Mess_Menu__c/Reva_Mess_Menu__c.object-meta.xml
<CustomObject>
    <description>Reva Mess Menu is used to store the details of the timings, menu items and total bookings.</description>
    <label>REVA Mess Menu</label>
    <nameField>
        <displayFormat>MENU-{0000}</displayFormat>
        <label>REVA Mess Menu Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVA Mess Menu</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reva_Mess_Menu__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()+1</defaultValue>
    <description>Select the Date which the Menu is being created</description>
    <inlineHelpText>Select the Date which the Menu is being created</inlineHelpText>
    <label>Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reva_Mess_Menu__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <inlineHelpText>Select the End time of the meal</inlineHelpText>
    <label>End Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Reva_Mess_Menu__c/fields/Mess_Items__c.field-meta.xml
<CustomField>
    <fullName>Mess_Items__c</fullName>
    <label>Mess Items</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Mess_Menu_Items</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reva_Mess_Menu__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>Select the start time of the meal</inlineHelpText>
    <label>Start Time</label>
    <required>true</required>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Reva_Mess_Menu__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Select the Meal Type</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Snacks</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Mess_Menu_Items.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Rice Idly</fullName>
    </customValue>
    <customValue>
        <fullName>Medu Vada</fullName>
    </customValue>
    <customValue>
        <fullName>Coconut Chutney</fullName>
    </customValue>
    <customValue>
        <fullName>Breakfast Sambar</fullName>
    </customValue>
    <customValue>
        <fullName>People&apos;s Tea</fullName>
    </customValue>
    <customValue>
        <fullName>Instant Coffee</fullName>
    </customValue>
    <customValue>
        <fullName>Milk</fullName>
    </customValue>
    <customValue>
        <fullName>Masala Dosa</fullName>
    </customValue>
    <customValue>
        <fullName>Bread</fullName>
    </customValue>
    <customValue>
        <fullName>Jam</fullName>
    </customValue>
    <customValue>
        <fullName>Poori</fullName>
    </customValue>
    <customValue>
        <fullName>Potato Sago</fullName>
    </customValue>
    <customValue>
        <fullName>Bisi Bele Bath</fullName>
    </customValue>
    <customValue>
        <fullName>Kara Boondi</fullName>
    </customValue>
    <customValue>
        <fullName>Kanda Batato Poha</fullName>
    </customValue>
    <customValue>
        <fullName>Coriander Mint Chutney</fullName>
    </customValue>
    <customValue>
        <fullName>Omlette for Non Veg</fullName>
    </customValue>
    <customValue>
        <fullName>Masala Vada for Veg</fullName>
    </customValue>
    <customValue>
        <fullName>Minapa Dosa</fullName>
    </customValue>
    <customValue>
        <fullName>Tomato Garlic Green Chilli Chutney</fullName>
    </customValue>
    <customValue>
        <fullName>Pongal</fullName>
    </customValue>
    <customValue>
        <fullName>Vada</fullName>
    </customValue>
    <customValue>
        <fullName>Rava Idly</fullName>
    </customValue>
    <customValue>
        <fullName>Peanut Garlic Chutney</fullName>
    </customValue>
    <customValue>
        <fullName>Chow Chow Bath</fullName>
    </customValue>
    <customValue>
        <fullName>Chitrna</fullName>
    </customValue>
    <customValue>
        <fullName>Coconut Green Chutney</fullName>
    </customValue>
    <customValue>
        <fullName>Vegetable Sago</fullName>
    </customValue>
    <customValue>
        <fullName>Set Dosa</fullName>
    </customValue>
    <customValue>
        <fullName>Beerekaya Sambar</fullName>
    </customValue>
    <masterLabel>Mess Menu Items</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PicklistValuesControllerTest.cls
@IsTest
public class PicklistValuesControllerTest {
    
  @IsTest
    static void testGetPicklistValues() {
        List<String> picklistValues = PicklistValuesController.getPicklistValues('Account', 'Industry');
        System.assertNotEquals(null, picklistValues, 'The returned list should not be null.');
        System.assert(picklistValues.size() > 0, 'The returned list should contain some picklist values.');
    }
    
      @IsTest
    static void testInsertMenuRecords() {
        // Create a sample JSON string to test the method
        String sampleJson = '[{"type": "Breakfast", "menuItems": ["Aloo Paratha", "Idly"], "startTime": "07:00:00.000", "endTime": "09:00:00.000", "mealDate": "2024-08-17"}]';
        
        // Call the method with the sample JSON string
        Test.startTest();
        PicklistValuesController.insertMenuRecords(sampleJson);
        Test.stopTest();

        // Fetch the inserted records to validate
        List<Reva_Mess_Menu__c> insertedRecords = [SELECT Type__c, Mess_Items__c, Start_Time__c, End_Time__c, Date__c FROM Reva_Mess_Menu__c WHERE Type__c = 'Breakfast'];

        // Assertions to ensure the records were inserted correctly
        System.assertEquals(1, insertedRecords.size(), 'One record should have been inserted.');
        System.assertEquals('Breakfast', insertedRecords[0].Type__c, 'The Type__c field should be "Breakfast".');
        System.assertEquals('Aloo Paratha;Idly', insertedRecords[0].Mess_Items__c, 'The Mess_Items__c field should contain "Aloo Paratha;Idly".');
        System.assertEquals(Time.newInstance(7, 0, 0, 0), insertedRecords[0].Start_Time__c, 'The Start_Time__c field should match the parsed time.');
        System.assertEquals(Time.newInstance(9, 0, 0, 0), insertedRecords[0].End_Time__c, 'The End_Time__c field should match the parsed time.');
        System.assertEquals(Date.newInstance(2024, 8, 17), insertedRecords[0].Date__c, 'The Date__c field should match the parsed date.');
    }
 /***************************************************************************/
    @IsTest
    static void testGetMealTimings() {
        // Insert test data for the custom setting Meal_Timings__c directly inside the test method
        Meal_Timings__c breakfastTiming = new Meal_Timings__c(
            Name = 'Breakfast',
            Start_Time__c = '07:00 AM',
            End_Time__c = '09:00 AM'
        );

        Meal_Timings__c lunchTiming = new Meal_Timings__c(
            Name = 'Lunch',
            Start_Time__c = '12:00 PM',
            End_Time__c = '02:00 PM'
        );

        Meal_Timings__c dinnerTiming = new Meal_Timings__c(
            Name = 'Dinner',
            Start_Time__c = '07:00 PM',
            End_Time__c = '09:00 PM'
        );

        // Insert the test data into the custom setting
        insert breakfastTiming;
        insert lunchTiming;
        insert dinnerTiming;

        // Call the Apex method to be tested
        Map<String, Meal_Timings__c> mealTimingsMap = PicklistValuesController.getMealTimings();

        // Perform assertions to verify the behavior
        System.assertNotEquals(null, mealTimingsMap, 'Meal timings map should not be null');
        System.assertEquals(3, mealTimingsMap.size(), 'There should be 3 meal timings in the map');

        // Check specific values in the map
        Meal_Timings__c breakfastTimingResult = mealTimingsMap.get('Breakfast');
        System.assertNotEquals(null, breakfastTimingResult, 'Breakfast timing should be in the map');
        System.assertEquals('07:00 AM', breakfastTimingResult.Start_Time__c, 'Breakfast start time should be 07:00 AM');

        Meal_Timings__c lunchTimingResult = mealTimingsMap.get('Lunch');
        System.assertNotEquals(null, lunchTimingResult, 'Lunch timing should be in the map');
        System.assertEquals('12:00 PM', lunchTimingResult.Start_Time__c, 'Lunch start time should be 12:00 PM');

        Meal_Timings__c dinnerTimingResult = mealTimingsMap.get('Dinner');
        System.assertNotEquals(null, dinnerTimingResult, 'Dinner timing should be in the map');
        System.assertEquals('07:00 PM', dinnerTimingResult.Start_Time__c, 'Dinner start time should be 07:00 PM');
    }
    
}