force-app/main/default/objects/Case/recordTypes/Manodhaara.recordType-meta.xml
<RecordType>
    <fullName>Manodhaara</fullName>
    <active>true</active>
    <businessProcess>Manodhaara</businessProcess>
    <label>Manodhaara</label>
</RecordType>

force-app/main/default/objects/ManodhaaraAppointment__c/ManodhaaraAppointment__c.object-meta.xml
<CustomObject>
    <label>Manodhaara Appointment</label>
    <nameField>
        <displayFormat>MANO-{0000000}</displayFormat>
        <label>Manodhaara Appointment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Manodhaara Appointments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ManodhaaraAppointment__c/fields/Appointment_Date_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Appointment_Date_Formatted__c</fullName>
    <formula>DATEVALUE(Start_Date_Time__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Appointment Date Formatted</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ManodhaaraAppointment__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>ManodhaaraAppointments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ManodhaaraAppointment__c/fields/Reason_For_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Cancellation__c</fullName>
    <description>This field stores the reason for cancellation captured from UI</description>
    <label>Reason For Cancellation</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ManodhaaraAppointment__c/fields/Time_Slot_Formatted__c.field-meta.xml
<CustomField>
    <fullName>Time_Slot_Formatted__c</fullName>
    <formula>IF(VALUE(MID(SD_Time__c, 12, 2)) &gt;= 12, 
   IF(VALUE(MID(SD_Time__c, 12, 2)) = 12, &quot;12&quot;, TEXT(VALUE(MID(SD_Time__c, 12, 2)) - 12)), 
   TEXT(VALUE(MID(SD_Time__c, 12, 2)))) &amp; &quot;:&quot; &amp; 
MID(SD_Time__c, 15, 2) &amp; 
IF(VALUE(MID(SD_Time__c, 12, 2)) &gt;= 12, &quot; PM&quot;, &quot; AM&quot;) &amp; &quot;-&quot; &amp;
IF(VALUE(MID(ED_Time__c, 12, 2)) &gt;= 12, 
   IF(VALUE(MID(ED_Time__c, 12, 2)) = 12, &quot;12&quot;, TEXT(VALUE(MID(ED_Time__c, 12, 2)) - 12)), 
   TEXT(VALUE(MID(ED_Time__c, 12, 2)))) &amp; &quot;:&quot; &amp; 
MID(ED_Time__c, 15, 2) &amp; 
IF(VALUE(MID(ED_Time__c, 12, 2)) &gt;= 12, &quot; PM&quot;, &quot; AM&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Time Slot Formatted</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Notification_Template__mdt/WhatsApp_Notification_Template__mdt.object-meta.xml
<CustomObject>
    <label>WhatsApp Notification Template</label>
    <pluralLabel>WhatsApp Notification Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/WhatsApp_Notification_Template__mdt/fields/Template_Field__c.field-meta.xml
<CustomField>
    <fullName>Template_Field__c</fullName>
    <label>Template Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Cancelled_WhatsappNotification.cls
public class Cancelled_WhatsappNotification {
 @InvocableMethod(label='Send WhatsApp Notifications' description='Send notifications via WhatsApp')
    public static void Appointment_CancelledNotification(List<String> recordIds) {
        // Ensure that recordIds is not empty
        if (recordIds != null && !recordIds.isEmpty()) {
            // Make the callout asynchronously
            Appointment_Cancelled(recordIds);
            
            List<ManodhaaraAppointment__c> mApp = [SELECT Id, Name,Appointment_Date_Formatted__c, Time_Slot_Formatted__c, Case__r.Contact.Name, Case__r.Contact.MobilePhone FROM ManodhaaraAppointment__c WHERE Id IN :recordIds];
        List<SMS_API_Utility.shortMessageWrp> messages = new List<SMS_API_Utility.shortMessageWrp>();

        for (ManodhaaraAppointment__c eachmApp : mApp) {
           // system.debug('eachmApp.Case__r.Contact.Name-->'+eachmApp.Case__r.Contact.Name);
            String message = '';
            string SmsType = 'Appointment Cancelled by counselor';
                message += 'Dear ' + eachmApp.Case__r.Contact.Name + ', your manodhaara appointment scheduled on ' + eachmApp.Appointment_Date_Formatted__c +
                          ' at' + eachmApp.Time_Slot_Formatted__c +
                          ' has been cancelled due to unavailability of the counselor. Kindly reschedule your appointment. REVA University';
            
              SMS_API_Utility.shortMessageWrp messageWrapper = new SMS_API_Utility.shortMessageWrp();
            messageWrapper.message = message;
            messageWrapper.recipient = eachmApp.Case__r.Contact.MobilePhone;
            messages.add(messageWrapper);
        }

        if (!messages.isEmpty()) {
            //SMS_API_Utility.SendSMSOneToMany('Appointment Cancelled by counselor', messages);
        }
        } else {
           // System.debug('Record IDs list is empty or null');
        }
    }
    
     @Future(callout=true)
    public static void Appointment_Cancelled(List<String> recordIds) {
        // Fetch the related record data
        List<ManodhaaraAppointment__c> requiredFields = [
            SELECT Id, Appointment_Date_Formatted__c,Name, Start_Date_Time__c,Time_Slot_Formatted__c, Reason_For_Cancellation__c, End_Date_Time__c, Case__r.Contact.Name, Case__r.Contact.MobilePhone
            FROM ManodhaaraAppointment__c
            WHERE Id IN :recordIds
            LIMIT 1
        ];
 //System.debug('ManodhaaraAppointment__c'+requiredFields);
        // Check if related record is found
        if (!requiredFields.isEmpty() && !String.isBlank(requiredFields[0].Case__r.Contact.MobilePhone)) {
            ManodhaaraAppointment__c requiredField = requiredFields[0];

            // Create WhatsAppNotification instance
            Yellow_AI_Utility.WhatsAppNotification notification1 = new Yellow_AI_Utility.WhatsAppNotification();
            notification1.templateId = 'manodhaara_appointment_cancel';

            // Fetch keys from custom metadata based on templateId
            List<WhatsApp_Notification_Template__mdt> templateMetadata = [
                SELECT Template_Field__c, Template_ID__c
                FROM WhatsApp_Notification_Template__mdt
                WHERE Template_ID__c = :notification1.templateId
            ];
       // System.debug('templateMetadata: ' + templateMetadata);
            // Populate the params map dynamically
            notification1.params = new Map<String, String>();
            for (WhatsApp_Notification_Template__mdt metadata : templateMetadata) {
                // Split values based on comma and add each as a separate key
                String[] keys = metadata.Template_Field__c.split(',');
                for (String key : keys) {
                    // You can set dynamic values for each key based on the related record
                    if (key.trim() == 'appointmentnumber') {
                        notification1.params.put(key.trim(), requiredField.Name);
                        //notification1.params.put(key.trim(), 'requiredField.Name');
                    } else if (key.trim() == 'studentname') {
                        // Assuming Start_Date__c is a Date field
                       // notification1.params.put(key.trim(), String.valueOf(requiredField.Appointment_Date_Formatted__c));
                        notification1.params.put(key.trim(),  requiredField.Case__r.Contact.Name);
                    } else if (key.trim() == 'date') {
                        // Assuming Start_Date__c is a DateTime field
                        notification1.params.put(key.trim(), String.valueOf(requiredField.Appointment_Date_Formatted__c));
                       // notification1.params.put(key.trim(), 'hj');
                    } else if (key.trim() == 'time') {
                        // Assuming End_Date__c is a DateTime field
                        notification1.params.put(key.trim(),  String.valueOf(requiredField.Time_Slot_Formatted__c));
                        //notification1.params.put(key.trim(),'ioo');
                    }else if (key.trim() == 'reason') {
                        // Assuming End_Date__c is a DateTime field
                        notification1.params.put(key.trim(), requiredField.Reason_For_Cancellation__c);
}
                }
            }
			
            // Create list of notifications
            List<Yellow_AI_Utility.WhatsAppNotification> notifications = new List<Yellow_AI_Utility.WhatsAppNotification>{notification1};

            // Create map of phone numbers to notifications
            Map<String, List<Yellow_AI_Utility.WhatsAppNotification>> phoneNumbersToNotifications = new Map<String, List<Yellow_AI_Utility.WhatsAppNotification>>();
            phoneNumbersToNotifications.put(requiredField.Case__r.Contact.MobilePhone, notifications);

            HttpResponse response = new HttpResponse();
            // Send notifications
            if(!Test.isRunningTest()){  
             response = Yellow_AI_Utility.sendWhatsAppNotifications(phoneNumbersToNotifications);
            }
            
           // System.debug('WhatsApp notification response: ' + response);
        } else {
            //System.debug('No related record found for the provided ID');
        }
    }
}