force-app/main/default/objects/Rpl_Training_Assement_Result__c/Rpl_Training_Assement_Result__c.object-meta.xml
<CustomObject>
    <label>Training Assessment Results</label>
    <nameField>
        <displayFormat>RTAS-{000000}</displayFormat>
        <label>Training Assessment Result No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Assessment Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Training_Assement_Result__c/fields/Rpl_Assessment_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Assessment_Date__c</fullName>
    <label>Assessment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Assement_Result__c/fields/Rpl_Percentages_Scored__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Percentages_Scored__c</fullName>
    <formula>(Rpl_Marks_Scored__c  /  Rpl_Total_marks__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percentages Scored</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Assement_Result__c/fields/Rpl_Student__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Student__c</fullName>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Assessment Results</relationshipLabel>
    <relationshipName>Training_Assessment_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Assement_Result__c/fields/Rpl_Topic__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Topic__c</fullName>
    <label>Topic</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Assement_Result__c/fields/Rpl_Training_Module__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Training_Module__c</fullName>
    <label>Training Module</label>
    <referenceTo>Rpl_Training_Module__c</referenceTo>
    <relationshipLabel>Training Assessment Results</relationshipLabel>
    <relationshipName>Training_Assessment_Results</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Attendances__c/Rpl_Training_Attendances__c.object-meta.xml
<CustomObject>
    <label>Training Attendances</label>
    <nameField>
        <displayFormat>RTA-{000000}</displayFormat>
        <label>Training Attendance No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Training_Attendances__c/fields/Rpl_Attendance__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Attendance__c</fullName>
    <label>Attendance</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Present</fullName>
            </value>
            <value>
                <fullName>Absent</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rpl_Training_Attendances__c/fields/Rpl_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Attendances__c/fields/Rpl_Student__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Student__c</fullName>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Training Attendances</relationshipLabel>
    <relationshipName>Training_Attendances</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Attendances__c/fields/Rpl_Training_Module__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Training_Module__c</fullName>
    <label>Training Module</label>
    <referenceTo>Rpl_Training_Module__c</referenceTo>
    <relationshipLabel>Training Attendances</relationshipLabel>
    <relationshipName>Training_Attendances</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Module__c/Rpl_Training_Module__c.object-meta.xml
<CustomObject>
    <label>Training Module</label>
    <nameField>
        <label>Training Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Training Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Training_Module__c/fields/Rpl_Main_Topic__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Main_Topic__c</fullName>
    <label>Main Topic</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Module__c/fields/Rpl_No_of_Hours__c.field-meta.xml
<CustomField>
    <fullName>Rpl_No_of_Hours__c</fullName>
    <label>No of Hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Module__c/fields/Rpl_School__c.field-meta.xml
<CustomField>
    <fullName>Rpl_School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Training Modules</relationshipLabel>
    <relationshipName>Training_Modules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Module__c/fields/Rpl_Semester__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Semester__c</fullName>
    <label>Semester</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Module__c/fields/Rpl_Sub_Topic__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Sub_Topic__c</fullName>
    <label>Sub Topic</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rpl_Training_Module__c/fields/Rpl_Target__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Target__c</fullName>
    <label>Target</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/rpl_Placement_Training_Controller.cls
public without sharing class rpl_Placement_Training_Controller {
	@AuraEnabled(cacheable=true)
	public static List<Rpl_Training_Attendances__c> getAttendanceData(string contactId) {
		return [
			SELECT Id, Rpl_Date__c, Rpl_Training_Module__r.Name, Rpl_Attendance__c
			FROM Rpl_Training_Attendances__c
			WHERE Rpl_Student__c = :contactId
			ORDER BY Rpl_Training_Module__r.Name ASC
		];
	}

	@AuraEnabled(cacheable=true)
	public static list<Rpl_Training_Assement_Result__c> getAssessmentResultData(string contactId) {
		return [
			SELECT Id, Rpl_Assessment_Date__c, Rpl_Percentages_Scored__c, Rpl_Training_Module__r.Name, Rpl_Topic__c
			FROM Rpl_Training_Assement_Result__c
			WHERE Rpl_Student__c = :contactId
		];
	}

	@AuraEnabled(cacheable=true)
	public static list<Rpl_Training_Module__c> getTrainingMaterialData(Decimal semesterNumber, String schoolName) {
		return [
			SELECT Id, Rpl_Main_Topic__c, Rpl_Sub_Topic__c, Rpl_Target__c, School_Name__c, Rpl_No_of_Hours__c
			FROM Rpl_Training_Module__c
			WHERE Rpl_School__r.Name = :schoolName AND Rpl_Semester__c = :semesterNumber
		];
	}
}