force-app/main/default/objects/Reva_Transport__c/Reva_Transport__c.object-meta.xml
<CustomObject>
    <label>REVA Transport</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/RTR_Reva_Transport_Request__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the transport fees concession requests for the students</description>
    <label>REVA Transport Request</label>
    <nameField>
        <displayFormat>TRQ-{0000}</displayFormat>
        <label>REVA Transport Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVA Transport Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_Route_Pick_Up_Point__c.field-meta.xml
<CustomField>
    <fullName>RTR_Route_Pick_Up_Point__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Pick Up Point</label>
    <referenceTo>RTR_Route_Pick_Up_Point__c</referenceTo>
    <relationshipName>Reva_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTR_Route_Master__c/RTR_Route_Master__c.object-meta.xml
<CustomObject>
    <description>This Object will store details about the Bus Routes, Pick up points and its capacity.</description>
    <label>Route Master</label>
    <nameField>
        <label>Route Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/RTR_Route_Pick_Up_Point__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the Pick up points of the route path and its related payments.</description>
    <label>Route Pick Up Point</label>
    <nameField>
        <label>Pick Up Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Pick Up Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/fields/RTR_Route_Master__c.field-meta.xml
<CustomField>
    <fullName>RTR_Route_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Master</label>
    <referenceTo>RTR_Route_Master__c</referenceTo>
    <relationshipLabel>Route Pick Up Points</relationshipLabel>
    <relationshipName>Route_Pick_Up_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/Transport_Registeration__c.object-meta.xml
<CustomObject>
    <label>Transport Registration</label>
    <nameField>
        <displayFormat>RU-{0000}</displayFormat>
        <label>Name/BusPass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/fields/Reva_Transport__c.field-meta.xml
<CustomField>
    <fullName>Reva_Transport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Transport</label>
    <referenceTo>Reva_Transport__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTRCancelledSMSMultipleDaysInvokeTest.cls
@isTest
public class RTRCancelledSMSMultipleDaysInvokeTest {
    
    @isTest
    static void test_busCancelledMultiple() {
        // Generate test data
        Contact con = TestDataFactory.createContact();
        RTR_Reva_Transport_Request__c transportRequests = TestDataFactory.createTestTransportRequests();
        RTR_Route_Pick_Up_Point__c pickupPoint = TestDataFactory.createPickUpPoint();        
        Reva_Transport__c revaTransport = TestDataFactory.createRevaTransport();        
        RTR_Route_Master__c routeMaster = TestDataFactory.createRouteMaster();
        Transport_Registeration__c createTransport = TestDataFactory.createTransport();
           
        // Set the mock callout class
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        List<String> recordIds = new List<String>{transportRequests.Id};
        RTRCancelledSMSMultipleDaysInvoke.cancelledSMS(recordIds);
        Test.stopTest();
    }
    
    // Mock HTTP callout response class
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"user" : "revaerp.trans","password" : "s1Sz2"},"from" : "REVAUn","shortMessages" : [ {"dltContentId" : "1007278312264240472","message" : "Dear Test User1, We’d like to inform you that the University bus will arrive at the pickup point 10 mins earlier than the regular schedule on 26.05.2024 on account of Test Description. REVA University", "recipient" : "1234567890"} ],"unicode" : true}');
            res.setStatusCode(200);
            return res;
        }
    }
}