force-app/main/default/objects/rve_Exam_Time__c/rve_Exam_Time__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Exam Time</label>
</CustomObject>

force-app/main/default/objects/rve_Invigilator_Assignment__c/rve_Invigilator_Assignment__c.object-meta.xml
<CustomObject>
    <label>Invigilator Assignment</label>
    <nameField>
        <label>Invigilator Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invigilator Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/rve_Invigilator_Assignment__c/fields/rve_Date__c.field-meta.xml
<CustomField>
    <fullName>rve_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/rve_Invigilator_Assignment__c/fields/rve_Exam_Time__c.field-meta.xml
<CustomField>
    <fullName>rve_Exam_Time__c</fullName>
    <label>Exam Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/rve_Invigilator_Assignment__c/fields/rve_Professor__c.field-meta.xml
<CustomField>
    <fullName>rve_Professor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Professor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Professor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Invigilator_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/rve_Invigilator_Assignment__c/fields/rve_Shift__c.field-meta.xml
<CustomField>
    <fullName>rve_Shift__c</fullName>
    <label>Shift</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/rve_InvigilatorAssignmentEdit.cls
public class rve_InvigilatorAssignmentEdit {
     @AuraEnabled
public static List<rve_Invigilator_Assignment__c> getInvigilatorAssignments() {
    // Get current time in UTC
    DateTime currentTime = System.now();
    Time currentLocalTime = currentTime.time();
    
    // Debugging to verify current time in IST
    System.debug('Current Time in IST: ' + currentLocalTime);
     System.debug('Current : ' + currentTime);
     // System.debug('Current timezone : ' + Timezone.getTimeZone('Asia/Kolkata'));
    
    // Query for invigilator assignments
    List<rve_Invigilator_Assignment__c> existingAssignments = [
     SELECT Id, rve_Date__c, rve_Shift__c, rve_Professor__r.Name, rve_Exam_Time__c, Name
FROM rve_Invigilator_Assignment__c
WHERE (rve_Date__c > TODAY OR 
       (rve_Date__c = TODAY AND rve_Exam_Time__c > :currentLocalTime))
      AND rve_Professor__r.Name != null

    ];
    
    // Debugging to verify the number of invigilator assignments retrieved
    System.debug('Number of invigilator assignments: ' + existingAssignments.size());
    
    return existingAssignments;
}
 

 
    

   @AuraEnabled
    public static void updateProfessor(String assignmentId, String professorId) {
        rve_Invigilator_Assignment__c assignment = [SELECT Id, rve_Professor__c FROM rve_Invigilator_Assignment__c  WHERE Id = :assignmentId LIMIT 1];
        if (assignment != null) {
            assignment.rve_Professor__c = professorId;
            update assignment;
        
    }}}