force-app/main/default/objects/smt_Summit_Particular__c/smt_Summit_Particular__c.object-meta.xml
<CustomObject>
    <label>Summit Particular</label>
    <nameField>
        <label>Particular Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Summit Particulars</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Achieved__c.field-meta.xml
<CustomField>
    <fullName>smt_Achieved__c</fullName>
    <description>Tracks the achieved target.</description>
    <label>Achieved</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Actual_Percentage_Achieved__c.field-meta.xml
<CustomField>
    <fullName>smt_Actual_Percentage_Achieved__c</fullName>
    <formula>IF(
    NOT(smt_Is_Target_Applicable__c) &amp;&amp; 
    smt_Is_Evidence_Applicable__c &amp;&amp; 
    ISBLANK(smt_Evidence_To_Be_Attached__c), 
    0, 
    IF(
        NOT(smt_Is_Target_Applicable__c) &amp;&amp; 
        smt_Is_Evidence_Applicable__c &amp;&amp; 
        NOT(ISBLANK(smt_Evidence_To_Be_Attached__c)), 
        1, 
        IF(
            ISNULL(smt_Target__c) || smt_Target__c == 0, 
            0, 
            
                (smt_Achieved__c / smt_Target__c) 
            
        )
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Actual Percentage Achieved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Evidence_To_Be_Attached__c.field-meta.xml
<CustomField>
    <fullName>smt_Evidence_To_Be_Attached__c</fullName>
    <label>Evidence To Be Attached</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Is_Evidence_Applicable__c.field-meta.xml
<CustomField>
    <fullName>smt_Is_Evidence_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Evidence Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Is_Target_Applicable__c.field-meta.xml
<CustomField>
    <fullName>smt_Is_Target_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Target Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Percentage_Achieved__c.field-meta.xml
<CustomField>
    <fullName>smt_Percentage_Achieved__c</fullName>
    <label>Percentage Achieved</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Summit_Section__c.field-meta.xml
<CustomField>
    <fullName>smt_Summit_Section__c</fullName>
    <label>Summit Section</label>
    <referenceTo>smt_Summit_Section__c</referenceTo>
    <relationshipLabel>Summit Particulars</relationshipLabel>
    <relationshipName>Summit_Particulars</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Target__c.field-meta.xml
<CustomField>
    <fullName>smt_Target__c</fullName>
    <label>Target</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Target_Text__c.field-meta.xml
<CustomField>
    <fullName>smt_Target_Text__c</fullName>
    <label>Target Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Particular__c/fields/smt_Timeline__c.field-meta.xml
<CustomField>
    <fullName>smt_Timeline__c</fullName>
    <label>Timeline</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Section__c/smt_Summit_Section__c.object-meta.xml
<CustomObject>
    <label>Summit Section</label>
    <nameField>
        <label>Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Summit Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/smt_Summit_Section__c/fields/smt_No_Of_Particulars_Without_Condition__c.field-meta.xml
<CustomField>
    <fullName>smt_No_Of_Particulars_Without_Condition__c</fullName>
    <label>No Of Particulars Without Condition</label>
    <summaryForeignKey>smt_Summit_Particular__c.smt_Summit_Section__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Section__c/fields/smt_Number_Of_Particulars__c.field-meta.xml
<CustomField>
    <fullName>smt_Number_Of_Particulars__c</fullName>
    <label>Number Of Particulars</label>
    <summaryFilterItems>
        <field>smt_Summit_Particular__c.smt_Is_Particular_Considered__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>smt_Summit_Particular__c.smt_Summit_Section__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Section__c/fields/smt_Progress_Made_Summit_Particulars__c.field-meta.xml
<CustomField>
    <fullName>smt_Progress_Made_Summit_Particulars__c</fullName>
    <inlineHelpText>Indicate the count of particulars where progress has been made.</inlineHelpText>
    <label>Progress Made Summit Particulars</label>
    <summaryFilterItems>
        <field>smt_Summit_Particular__c.smt_Actual_Percentage_Achieved__c</field>
        <operation>greaterThan</operation>
        <value>0</value>
    </summaryFilterItems>
    <summaryForeignKey>smt_Summit_Particular__c.smt_Summit_Section__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Section__c/fields/smt_Sum_Of_Percentage_Achieved__c.field-meta.xml
<CustomField>
    <fullName>smt_Sum_Of_Percentage_Achieved__c</fullName>
    <label>Sum Of Percentage Achieved</label>
    <summarizedField>smt_Summit_Particular__c.smt_Percentage_Achieved__c</summarizedField>
    <summaryFilterItems>
        <field>smt_Summit_Particular__c.smt_Is_Particular_Considered__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>smt_Summit_Particular__c.smt_Summit_Section__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Section__c/fields/smt_Summit_Tracker__c.field-meta.xml
<CustomField>
    <fullName>smt_Summit_Tracker__c</fullName>
    <label>Summit Tracker</label>
    <referenceTo>smt_Summit_Tracker__c</referenceTo>
    <relationshipLabel>Summit Sections</relationshipLabel>
    <relationshipName>Summit_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Section__c/fields/smt_Target_Achieved__c.field-meta.xml
<CustomField>
    <fullName>smt_Target_Achieved__c</fullName>
    <formula>smt_Sum_Of_Percentage_Achieved__c /  smt_Number_Of_Particulars__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Target Achieved</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Section__c/fields/smt_Target_Achieved_With_Weightage__c.field-meta.xml
<CustomField>
    <fullName>smt_Target_Achieved_With_Weightage__c</fullName>
    <label>Target Achieved With Weightage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Section__c/fields/smt_Weightage__c.field-meta.xml
<CustomField>
    <fullName>smt_Weightage__c</fullName>
    <label>Weightage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Tracker__c/smt_Summit_Tracker__c.object-meta.xml
<CustomObject>
    <label>Summit Tracker</label>
    <nameField>
        <label>Summit Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Summit Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/smt_Summit_Tracker__c/fields/smt_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>smt_Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Tracker__c/fields/smt_School__c.field-meta.xml
<CustomField>
    <fullName>smt_School__c</fullName>
    <description>Master-Detail (Account)</description>
    <label>School</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Summit Trackers</relationshipLabel>
    <relationshipName>Summit_Trackers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Tracker__c/fields/smt_Total_Weightage_Achieved__c.field-meta.xml
<CustomField>
    <fullName>smt_Total_Weightage_Achieved__c</fullName>
    <label>Total Weightage Achieved</label>
    <summarizedField>smt_Summit_Section__c.smt_Target_Achieved_With_Weightage__c</summarizedField>
    <summaryForeignKey>smt_Summit_Section__c.smt_Summit_Tracker__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/smt_Summit_Tracker__c/fields/smt_Year__c.field-meta.xml
<CustomField>
    <fullName>smt_Year__c</fullName>
    <label>Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summit_Particular__mdt/Summit_Particular__mdt.object-meta.xml
<CustomObject>
    <label>Summit Particular</label>
    <pluralLabel>Summit Particulars</pluralLabel>
</CustomObject>

force-app/main/default/objects/Summit_Particular__mdt/fields/Summit_Section__c.field-meta.xml
<CustomField>
    <fullName>Summit_Section__c</fullName>
    <label>Summit Section</label>
    <referenceTo>Summit_Section_Metadata__mdt</referenceTo>
    <relationshipLabel>Summit Particulars</relationshipLabel>
    <relationshipName>Summit_Particulars</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Summit_Section_Metadata__mdt/Summit_Section_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Summit Section</label>
    <pluralLabel>Summit Sections</pluralLabel>
</CustomObject>

force-app/main/default/objects/Summit_Section_Metadata__mdt/fields/smt_Weightage__c.field-meta.xml
<CustomField>
    <fullName>smt_Weightage__c</fullName>
    <label>Weightage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/smt_Summit_Tracker_Controller.cls
public without sharing class smt_Summit_Tracker_Controller {
    @AuraEnabled
    public static String createSummitTracker(String summitTrackerName, String schoolId, String batch) {
        try {
            
                smt_Summit_Tracker__c smtTracker = new smt_Summit_Tracker__c(
                    Name = summitTrackerName, 
                    smt_School__c = schoolId,
                    smt_Year__c = Decimal.valueOf(batch)
                );
                insert AS USER smtTracker;
                return smtTracker.Id;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
    @AuraEnabled(cacheable = true)
    public static List<smt_Summit_Particular__c> getSummitParticulars(String summitSectionId, String semester){
        
                if(semester == 'Odd'){
                       return [SELECT Id, Name, smt_Achieved__c, smt_Target_Text__c, smt_Timeline__c, smt_Percentage_Achieved__c,
                        smt_Is_Evidence_Applicable__c ,smt_Is_Target_Applicable__c, smt_Evidence_To_Be_Attached__c, 
                        smt_Actual_Percentage_Achieved__c
                        FROM smt_Summit_Particular__c
                        WHERE (smt_Is_Evidence_Applicable__c = TRUE 
                               OR smt_Is_Target_Applicable__c =  TRUE) AND 
                               smt_Summit_Section__c=:summitSectionId AND 
                               (Name Like '%OS' OR Name Like '%Odd')
                        WITH USER_MODE
                        ORDER BY Name ASC];
                    
                }else{
                       return [SELECT Id, Name, smt_Achieved__c, smt_Target_Text__c, smt_Timeline__c, smt_Percentage_Achieved__c,
                        smt_Is_Evidence_Applicable__c ,smt_Is_Target_Applicable__c, smt_Evidence_To_Be_Attached__c, 
                        smt_Actual_Percentage_Achieved__c
                        FROM smt_Summit_Particular__c
                        WHERE (smt_Is_Evidence_Applicable__c = TRUE 
                               OR smt_Is_Target_Applicable__c =  TRUE)AND 
                               smt_Summit_Section__c=:summitSectionId AND 
                               (NOT Name LIKE '%OS') AND (NOT Name LIKE '%Odd')
                        WITH USER_MODE
                        ORDER BY Name ASC];
                }
            
    }
    
    @AuraEnabled(cacheable = true)
    public static List<smt_Summit_Particular__c> getAllSummitParticulars(String summitSectionId){
       
                return [SELECT Id, Name, smt_Achieved__c, smt_Target_Text__c, smt_Timeline__c, 
                        smt_Percentage_Achieved__c,smt_Target__c,smt_Is_Evidence_Applicable__c ,
                        smt_Is_Target_Applicable__c, smt_Evidence_To_Be_Attached__c, 
                        smt_Actual_Percentage_Achieved__c
                        FROM smt_Summit_Particular__c
                        WHERE smt_Summit_Section__c=:summitSectionId
                        WITH USER_MODE
                        ORDER BY Name ASC
                       ];
            }
      
    
    @AuraEnabled(cacheable = true)
    public static List<smt_Summit_Tracker__c> getSummitTracker(String schoolId){
        
                return [SELECT Id, Name, smt_Total_Weightage_Achieved__c, smt_Year__c 
                        FROM smt_Summit_Tracker__c
                        WHERE smt_Is_Active__c = TRUE AND smt_School__c =:schoolId 
                        WITH USER_MODE];
            }
       
    
    
    @AuraEnabled
    public static void updateSummitParticular(String jsonData){
        try{
           
                    JsonToUpdateSummitParticular obj = new JsonToUpdateSummitParticular();
                    obj = obj.parse(jsonData);
                    
                    smt_Summit_Particular__c particular = new smt_Summit_Particular__c(Id = obj.Id);
                    particular.smt_Achieved__c = isDecimal(obj.achievedValue) ? Decimal.valueOf(obj.achievedValue) : 0;
                    particular.smt_Evidence_To_Be_Attached__c = obj.evidenceValue;
                    
                    Update AS USER particular;
                
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void updateAllSummitParticular(String jsonData){
        try{
            
                    JsonToSummitParticular obj = new JsonToSummitParticular();
                    List<JsonToSummitParticular> summitParticulars = obj.parse(jsonData);
                    List<smt_Summit_Particular__c> summitParticularsToUpdate = new List<smt_Summit_Particular__c>();
                    
                    for(JsonToSummitParticular summitParticular : summitParticulars){
                        String timeLineString = summitParticular.timeLine.substring(0, 10); 
                        Date timeLine = Date.valueOf(timeLineString); 
                        smt_Summit_Particular__c particular = 
                            new smt_Summit_Particular__c(Id = summitParticular.summitParticularId);
                        particular.Name = summitParticular.summitParticularName;
                        particular.smt_Timeline__c = timeLine;
                        particular.smt_Target__c = summitParticular.target;
                        particular.smt_Target_Text__c = summitParticular.targetText;
                        particular.smt_Is_Evidence_Applicable__c = summitParticular.isEvidenceApplicable;
                        particular.smt_Is_Target_Applicable__c	= summitParticular.isTargetApplicable;
                        summitParticularsToUpdate.add(particular);
                    }
                    
                    
                    Update AS USER summitParticularsToUpdate;
                
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    public static Boolean isDecimal(String input) {
        try {
            Decimal decimalValue = Decimal.valueOf(input);
            return true;
        } catch (Exception e) {
            return false;
        }
    }
    
    @AuraEnabled(cacheable = true)
    public static List<Summit_Section_Metadata__mdt> getSummitSectionsMetadata(){
        
                return [SELECT Id, MasterLabel, smt_Weightage__c 
                        FROM Summit_Section_Metadata__mdt 
                        WITH USER_MODE
                        ORDER BY MasterLabel ASC];
            
        
    }
    
    @AuraEnabled(cacheable = true)
    public static List<Summit_Particular__mdt> getSummitParticularsMetadata(String summitSectionLabel){
        
                return [SELECT MasterLabel, Summit_Section__c, Id 
                        FROM Summit_Particular__mdt 
                        WHERE Summit_Section__r.MasterLabel =: summitSectionLabel 
                        WITH USER_MODE
                        ORDER BY MasterLabel ASC];
          
    }
    
    @AuraEnabled(cacheable = true)
    public static List<smt_Summit_Section__c> getSummitSectionRecords(String summitTrackerId){
      
                return [ SELECT Id, Name, smt_Weightage__c, smt_Sum_Of_Percentage_Achieved__c, smt_Number_Of_Particulars__c, 
                        smt_Target_Achieved__c, smt_No_Of_Particulars_Without_Condition__c, 
                        smt_Target_Achieved_With_Weightage__c, smt_Progress_Made_Summit_Particulars__c
                        FROM smt_Summit_Section__c 
                        WHERE smt_Summit_Tracker__c =: summitTrackerId
                        ORDER BY Name ASC];
           
    }
    
    @AuraEnabled
    public static void createSummitSections(String jsonData, String summitTrackerId) {
        try {
           
                List<smt_Summit_Section__c> sectionsToCreate = new List<smt_Summit_Section__c>();
                JsonToSummitSection obj = new JsonToSummitSection();
                List<JsonToSummitSection> summitSections = obj.parse(jsonData);
                System.debug(summitSections.size());
                
                // Iterate over each section data
                for (JsonToSummitSection summitSection : summitSections) {
                    smt_Summit_Section__c section = new smt_Summit_Section__c();
                    section.Name = summitSection.sectionName;
                    section.smt_Weightage__c = summitSection.weightage;
                    section.smt_Summit_Tracker__c = summitTrackerId;
                    
                    sectionsToCreate.add(section);
                }
                
                if (!sectionsToCreate.isEmpty()) {
                    insert AS USER sectionsToCreate;
                }
            
        } catch (Exception e) {
            throw new AuraHandledException('Error creating Summit Section records: ' + e.getMessage());
        }
    }
    
    @AuraEnabled
    public static void createSummitParticular(String jsonData, String summitSectionId) {
        try {
                List<smt_Summit_Particular__c> particularsToCreate = new List<smt_Summit_Particular__c>();
                JsonToSummitParticular obj = new JsonToSummitParticular();
                List<JsonToSummitParticular> summitParticulars = obj.parse(jsonData);
                
                for (JsonToSummitParticular summitParticular : summitParticulars) {
                    String timeLineString = summitParticular.timeLine.substring(0, 10); 
                    Date timeLine = Date.valueOf(timeLineString); 
                    smt_Summit_Particular__c particular = new smt_Summit_Particular__c();
                    particular.Name = summitParticular.summitParticularName;
                    particular.smt_Timeline__c = timeLine;
                    particular.smt_Target__c = summitParticular.target;
                    particular.smt_Target_Text__c = summitParticular.targetText;
                    particular.smt_Is_Evidence_Applicable__c = summitParticular.isEvidenceApplicable;
                    particular.smt_Is_Target_Applicable__c	= summitParticular.isTargetApplicable;
                    particular.smt_Summit_Section__c = summitSectionId;
                    particularsToCreate.add(particular);
                }
                
                if (!particularsToCreate.isEmpty()) {
                    insert particularsToCreate;
                }
           
        } catch (Exception e) {
            throw new AuraHandledException('Error creating Summit Section records: ' + e.getMessage());
        }
    }
    
    public class JsonToSummitSection {
        
        public Integer id;
        public String sectionName;
        public Integer weightage;
        
        
        public List<JsonToSummitSection> parse(String json) {
            return (List<JsonToSummitSection>) System.JSON.deserialize(json, List<JsonToSummitSection>.class);
        }
    }
    public class JsonToSummitParticular {
        
        public Integer id;
        public String summitParticularName;
        public String summitParticularId;
        public String timeline;
        public Integer target;
        public String targetText;
        public Boolean isTargetApplicable;
        public Boolean isEvidenceApplicable;
        
        
        public List<JsonToSummitParticular> parse(String json) {
            return (List<JsonToSummitParticular>) System.JSON.deserialize(json, List<JsonToSummitParticular>.class);
        }
    }
    
    public class JsonToUpdateSummitParticular {
        
        public String id;
        public String achievedValue;
        public String evidenceValue;
        
        public JsonToUpdateSummitParticular parse(String json) {
            return (JsonToUpdateSummitParticular) System.JSON.deserialize(json, JsonToUpdateSummitParticular.class);
        }
    }
}