force-app/main/default/objects/Account/recordTypes/HH_Account.recordType-meta.xml
<RecordType>
    <fullName>HH_Account</fullName>
    <active>true</active>
    <description>A Household containing one or more individuals.</description>
    <label>Household Account</label>
</RecordType>

force-app/main/default/objects/Alumni_Activities__c/Alumni_Activities__c.object-meta.xml
<CustomObject>
    <label>Alumni Activities</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alumni Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alumni_Activities__c/fields/Achievement__c.field-meta.xml
<CustomField>
    <fullName>Achievement__c</fullName>
    <label>Achievement</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Blog_Link__c.field-meta.xml
<CustomField>
    <fullName>Blog_Link__c</fullName>
    <label>Blog Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Blog_Name__c.field-meta.xml
<CustomField>
    <fullName>Blog_Name__c</fullName>
    <label>Blog Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Record_Type_Name__c</field>
            <operation>equals</operation>
            <value>Alumni</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alumni Activities</relationshipLabel>
    <relationshipName>Alumni_Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Current_CTC_In_Lakhs__c.field-meta.xml
<CustomField>
    <fullName>Current_CTC_In_Lakhs__c</fullName>
    <label>Current CTC (In Lakhs)</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <label>Organisation</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/fields/Total_Experience_In_Years__c.field-meta.xml
<CustomField>
    <fullName>Total_Experience_In_Years__c</fullName>
    <label>Total Experience(In Years)</label>
    <precision>3</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Alumni_Activities__c/recordTypes/Achievements.recordType-meta.xml
<RecordType>
    <fullName>Achievements</fullName>
    <active>true</active>
    <label>Achievements</label>
</RecordType>

force-app/main/default/objects/Alumni_Event_Registrations__c/Alumni_Event_Registrations__c.object-meta.xml
<CustomObject>
    <label>Alumni Event Registrations</label>
    <nameField>
        <displayFormat>AER -{0000}</displayFormat>
        <label>Alumni Event Registrations Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alumni Event Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alumni_Event_Registrations__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Record_Type_Name__c</field>
            <operation>equals</operation>
            <value>Alumni</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Alumni Event Registrations</relationshipLabel>
    <relationshipName>Alumni_Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Alumni_Event_Registrations__c/fields/Event_Attended__c.field-meta.xml
<CustomField>
    <fullName>Event_Attended__c</fullName>
    <label>Alumni Attended?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alumni_Event_Registrations__c/fields/Registration_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date_Time__c</fullName>
    <label>Registration Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__Gender__c.field-meta.xml
<CustomField>
    <fullName>hed__Gender__c</fullName>
    <description>Indicates the person&apos;s self-identified gender.</description>
    <inlineHelpText>Indicates the person&apos;s self-identified gender.</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ALU_RecordListControllerTest.cls
@isTest
public class ALU_RecordListControllerTest {
    
      public class AchievementsDetailsWrapper{
        @AuraEnabled public Id userId {get;set;}  
        @AuraEnabled public string achievement {get;set;}  
        @AuraEnabled public date dateVal {get;set;}  
        @AuraEnabled public string organization {get;set;}  
        @AuraEnabled public string designation {get;set;}  
        @AuraEnabled public string image {get;set;}  
        @AuraEnabled public string description {get;set;}  
        @AuraEnabled public Id file {get;set;}  
    }
    
    @testSetup
    static void setup() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        
        // Create a test user
        User testUser = new User(Alias = 'standt', Email='standarduser@testorg.com',
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                                 LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles',
                                 UserName='standarduser316316@testorg.com');
        insert testUser;
        //create Account
        Account acc = new Account (Name = 'Test Account',
                                   RecordtypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HH_Account').getRecordTypeId()
                                  );
        Insert acc;
        //create contact
        Contact con = new Contact (AccountId = acc.Id,
                                   RecordtypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Alumni').getRecordTypeId(),
                                   Lastname ='Testcontact',
                                   Mobilephone = '7660975589',
                                   hed__Gender__c='Female',
                                   Email ='test316@gmail.com'
                                  );
        insert con;
    }
    
    @isTest
    static void testGetCaseList() {
        User testUser = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        System.runAs(testUser) {
            // Insert a test case
            Case testCase = new Case(Subject = 'Test Case', Status = 'New');
            insert testCase;
            
            // Call the method being tested
            List<Case> caseList = ALU_RecordListController.getCaseList('New');
            
        }
    }
    @isTest
    static void testGetAlumniActivities() {
        User testUser = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        
        // Create a test Alumni_Activities__c record
        Alumni_Activities__c testRecord = new Alumni_Activities__c(  Total_Experience_In_Years__c = 5,
                                                                   Current_CTC_In_Lakhs__c = 10, Blog_Name__c = 'Test Blog', Blog_Link__c = 'http://testblog.com',
                                                                   OwnerId = testUser.Id,  Achievement__c = 'Test Achievement',
                                                                   Details__c = 'Test Details', Company_Name__c = 'Test Company', Designation__c = 'Test Designation');
        // Status__c = 'Active'
        insert testRecord;
        
        // Call the method being tested
        List<Alumni_Activities__c> activitiesList = ALU_RecordListController.getAlumniActivities('Test Record Type');
    }
    @isTest
    static void testGetAlumniAchievements() {
        User testUser = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        Account acc = [Select Id from Account LIMIT 1];
        Contact con = [Select Id from Contact LIMIT 1];
        Id recordTypeId = Schema.SObjectType.Alumni_Activities__c.getRecordTypeInfosByDeveloperName().get('Achievements').getRecordTypeId();
        system.debug('acheiveemnts rectype id----->'+recordTypeId);
        System.runAs(testUser) {
            // Create a test Alumni_Activities__c record
            Alumni_Activities__c testRecord = new Alumni_Activities__c( OwnerId = testUser.Id,recordtypeId = recordTypeId,
                                                                       Organisation__c = 'test',Contact__c = con.Id,
                                                                       Achievement__c = 'Test Achievement', 
                                                                       Details__c = '<p>Test Details</p>');
            insert testRecord;
            system.debug('testRecord----->'+testRecord);
            // Call the method being tested
            List<ALU_RecordListController.AlumniAchievementsWrapper> achievementsList = ALU_RecordListController.getAlumniAchievements('Achievements');
            system.debug('achievementsList----->'+achievementsList);
        }
    }
    
    @isTest
    static void testGetEventRegistrations() {
       
		User testUser = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        // Create a test Alumni_Event_Registrations__c record
        Alumni_Event_Registrations__c testRecord = new Alumni_Event_Registrations__c(Registration_Date_Time__c = DateTime.now(), Event_Attended__c = 'Yes', OwnerId = testUser.Id);
        insert testRecord;

        // Call the method being tested
        List<ALU_RecordListController.EventRegistrationsWrapper> registrationsList = ALU_RecordListController.getEventRegistrations(testUser.Id);
 
    }
    
    @isTest
    static void testCreateAchievements() {
       
		User testUser = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
         // Create a test wrapper instance
        ALU_RecordListController.AchievementsDetailsWrapper achmntDetails = new ALU_RecordListController.AchievementsDetailsWrapper();
        achmntDetails.achievement = 'Test Achievement';
        achmntDetails.dateVal = Date.today();
        achmntDetails.organization = 'Test Organization';
        achmntDetails.designation = 'Test Designation';
        achmntDetails.image = 'Test Image';
        achmntDetails.description = 'Test Description';
        achmntDetails.userId = testUser.Id;

        // Call the method being tested
        Id insertedRecordId = ALU_RecordListController.createAchievements(achmntDetails);

        // Verify that the record was inserted
        //System.assertNotEquals(null, insertedRecordId);

       
    }
     @isTest
    static void testTagFileToCreatedAchievement() {
        User testUser = [SELECT Id FROM User WHERE LastName = 'Testing' LIMIT 1];
        // Create a test ContentDocument
        ContentVersion testContent = new ContentVersion();
        testContent.Title = 'Test Content';
        testContent.PathOnClient = 'test.pdf';
        testContent.VersionData = Blob.valueOf('Test Content Data');
        insert testContent;

        
        // Create a test Alumni_Activities__c record
        Alumni_Activities__c testRecord = new Alumni_Activities__c(  Total_Experience_In_Years__c = 5,
                                                                   Current_CTC_In_Lakhs__c = 10, Blog_Name__c = 'Test Blog', Blog_Link__c = 'http://testblog.com',
                                                                   OwnerId = testUser.Id,  Achievement__c = 'Test Achievement',
                                                                   Details__c = 'Test Details', Company_Name__c = 'Test Company', Designation__c = 'Test Designation');
        // Status__c = 'Active'
        insert testRecord;

        // Call the method being tested
        ALU_RecordListController.tagFileTocreatedAchievement(testContent.ContentDocumentId, testRecord.Id);

        // Verify that the ContentDocumentLink record was inserted
        List<ContentDocumentLink> result = [SELECT Id FROM ContentDocumentLink WHERE ContentDocumentId = :testContent.ContentDocumentId AND LinkedEntityId = :testRecord.Id];
        
    }
    
    
}