force-app/main/default/objects/Rpl_Interview__c/Rpl_Interview__c.object-meta.xml
<CustomObject>
    <label>Recruitment Stage</label>
    <nameField>
        <label>Recruitment Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Interview__c/fields/Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Placement_Drive__c</fullName>
    <label>Placement Drive ID</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Recruitment Stages</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Interview__c/fields/Rpl_Interview_Time__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Interview_Time__c</fullName>
    <label>Interview Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Rpl_Interview__c/fields/Rpl_Round_Number__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Round_Number__c</fullName>
    <inlineHelpText>Please enter only numeric values to indicate the order of the interview rounds (e.g., 1, 2, 3, 4).</inlineHelpText>
    <label>Round Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/Rpl_Placement_Drive__c.object-meta.xml
<CustomObject>
    <label>Placement Drive</label>
    <nameField>
        <label>Placement Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Drives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/Rpl_Student_Registration_Drive__c.object-meta.xml
<CustomObject>
    <description>This is a junction object for &quot;Student Registration&quot; and &quot;Placement Drives&quot; Objects. As these two objects in many to many relationship. Records in this object will be created when eligibility criteria are been inserted for any particular drive, for the eligible students. By default IsApplied checkbox will be false. When Eligible students applied for any particular drive this checkbox will be turned to true. Once drive completed, those records whose IsApplied are false will be deleted using batch class.</description>
    <label>Student Registration Drive</label>
    <nameField>
        <displayFormat>SRD-{000000}</displayFormat>
        <label>Student Registration Drive No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Registration Drives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Interview__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interview</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rpl_Interview__c.Placement_Drive__c</field>
            <operation>equals</operation>
            <valueField>$Source.Rpl_Placement_Drive__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rpl_Interview__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Is_Failed__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Failed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to note whether a student was passed or failed in an interview.</description>
    <label>Is Failed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Is_Result_Out__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Result_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Result Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Placement_Drive__c</fullName>
    <label>Placement Drive</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RPL_InterviewHandler.cls
/**
 * @description       : This class is used to retrieve data to the LWC thus displaying interview results.
 * @author            : Kiruba Sankar M
 * @group             :
 * @last modified on  : 22-11-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
public without sharing class RPL_InterviewHandler {
	@AuraEnabled(cacheable=true)
	public static RPL_InterviewHandlerWrapperClass getAllInterviews(String studentRegDriveId) {
		try {
			RPL_InterviewHandlerWrapperClass rplInterviewWrapper = new RPL_InterviewHandlerWrapperClass();

			Rpl_Student_Registration_Drive__c studentRegistrationDrive = [
				SELECT
					Rpl_Is_Failed__c,
					Rpl_Interview__r.Name,
					Rpl_Interview__r.Rpl_Round_Number__c,
					Rpl_Placement_Drive__c,
					Rpl_Is_Result_Out__c
				FROM Rpl_Student_Registration_Drive__c
				WHERE Id = :studentRegDriveId AND Rpl_Interview__c != NULL AND Rpl_Placement_Drive__c != NULL
				LIMIT 1
			];

			if (studentRegistrationDrive != null) {
				List<Rpl_Interview__c> interviewList = [
					SELECT Name, Rpl_Interview_Time__c, Rpl_Round_Number__c
					FROM Rpl_Interview__c
					WHERE
						Rpl_Round_Number__c <= :studentRegistrationDrive.Rpl_Interview__r.Rpl_Round_Number__c
						AND Placement_Drive__c = :studentRegistrationDrive.Rpl_Placement_Drive__c
					ORDER BY Rpl_Round_Number__c ASC
				];

				if (interviewList != null) {
					rplInterviewWrapper.interviewList = interviewList;
					rplInterviewWrapper.studentRegistrationDrive = studentRegistrationDrive;
				}
			}

			return rplInterviewWrapper;
		} catch (Exception e) {
			ErrorLogUtility.logError(e);
			throw new AuraHandledException(e.getMessage());
		}
	}

	public class RPL_InterviewHandlerWrapperClass {
		@AuraEnabled
		public List<Rpl_Interview__c> interviewList;
		@AuraEnabled
		public Rpl_Student_Registration_Drive__c studentRegistrationDrive;
	}
}