force-app/main/default/objects/Rpl_Company__c/Rpl_Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Eligibility__c/Rpl_Eligibility__c.object-meta.xml
<CustomObject>
    <label>Eligibility</label>
    <nameField>
        <displayFormat>EN-{0000}</displayFormat>
        <label>Eligibility Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibilities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Any</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Attendance_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Attendance_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Attendance Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Current_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Current_Backlogs__c</fullName>
    <label>Current Backlogs</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Exclude_Students_With_Offer_In__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Exclude_Students_With_Offer_In__c</fullName>
    <label>Exclude Students With Offer In</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Fee_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Fee_Payment_Status__c</fullName>
    <label>Fee Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Include All Students</fullName>
            </value>
            <value>
                <fullName>Exclude Students With Payment Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Gap_Years__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Gap_Years__c</fullName>
    <label>Gap Years</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Include_Students_With_Offer_In__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Include_Students_With_Offer_In__c</fullName>
    <label>Include Students With Offer In</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_PG_Percentage1__c.field-meta.xml
<CustomField>
    <fullName>Rpl_PG_Percentage1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>PG Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Placement_Drive__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Placement Drive</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Eligibilities</relationshipLabel>
    <relationshipName>Eligibilities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Placement_Interest__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Placement_Interest__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Placement Interest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Specialization__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Specialization__c</fullName>
    <label>Specialization</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Tenth_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Tenth_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>10th Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Total_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Total_Backlogs__c</fullName>
    <label>Total Backlogs</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_Twelveth_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Twelveth_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>12th Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Eligibility__c/fields/Rpl_UG_Percentage1__c.field-meta.xml
<CustomField>
    <fullName>Rpl_UG_Percentage1__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UG Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/Rpl_Placement_Drive__c.object-meta.xml
<CustomObject>
    <label>Placement Drive</label>
    <nameField>
        <label>Placement Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Drives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Reva_Placement__c.field-meta.xml
<CustomField>
    <fullName>Reva_Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Placement</label>
    <referenceTo>Rpl_Reva_Placement__c</referenceTo>
    <relationshipLabel>Placement Drives</relationshipLabel>
    <relationshipName>Placement_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Rpl_Company__c</referenceTo>
    <relationshipLabel>Placement Drives</relationshipLabel>
    <relationshipName>Placement_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_Date_Time__c</fullName>
    <label>Event Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_End_Date__c</fullName>
    <label>Application End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Exclude_Students_With_Offer_In__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Exclude_Students_With_Offer_In__c</fullName>
    <label>Exclude Students With Offer In</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Include_Students_With_Offer_In__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Include_Students_With_Offer_In__c</fullName>
    <label>Include Students With Offer In</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Reva_Placement__c/Rpl_Reva_Placement__c.object-meta.xml
<CustomObject>
    <label>REVA Placement</label>
    <nameField>
        <label>REVA Placement  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Reva_Placement__c/fields/Rpl_Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Registration_End_Date__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Reva_Placement__c/fields/Rpl_Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Registration_Start_Date__c</fullName>
    <label>Registration Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/Rpl_Student_Registration__c.object-meta.xml
<CustomObject>
    <label>Student Registrations</label>
    <nameField>
        <label>Student Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Student_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Reva_Placement__c.field-meta.xml
<CustomField>
    <fullName>Reva_Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Placement</label>
    <referenceTo>Rpl_Reva_Placement__c</referenceTo>
    <relationshipName>Student_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Companies_Got_Placed_In__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Companies_Got_Placed_In__c</fullName>
    <label>Companies Got Placed In</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amazon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Current_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Current_Backlogs__c</fullName>
    <label>Current Backlogs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Interested_in_placement__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Interested_in_placement__c</fullName>
    <label>Interested In Placement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Personal_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Personal_Mail_ID__c</fullName>
    <label>Personal Mail - ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Total_Backlogs__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Total_Backlogs__c</fullName>
    <label>Total Backlogs</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_University_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_University_Mail_ID__c</fullName>
    <label>University Mail - ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/Rpl_Student_Registration_Drive__c.object-meta.xml
<CustomObject>
    <description>This is a junction object for &quot;Student Registration&quot; and &quot;Placement Drives&quot; Objects. As these two objects in many to many relationship. Records in this object will be created when eligibility criteria are been inserted for any particular drive, for the eligible students. By default IsApplied checkbox will be false. When Eligible students applied for any particular drive this checkbox will be turned to true. Once drive completed, those records whose IsApplied are false will be deleted using batch class.</description>
    <label>Student Registration Drive</label>
    <nameField>
        <displayFormat>SRD-{000000}</displayFormat>
        <label>Student Registration Drive No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Registration Drives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <formula>Rpl_Placement_Drive__r.Rpl_Company_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Placement_Drive__c</fullName>
    <label>Placement Drive</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Student_Registration__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Student_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Registration</label>
    <referenceTo>Rpl_Student_Registration__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RPL_EligibilityHandlerClass_Test.cls
@isTest
public class RPL_EligibilityHandlerClass_Test {
        @testSetup static void setup() {
        // Create common test accounts
        // Rpl_Student_Registration__c
        
        
        Contact eCon = new Contact();
        eCon.lastName = 'Test Data';
        eCon.Email = 'test@gmail.com';
        
        insert eCon;
        
        
       
        
        //Date startDate = Date.newInstance(2024, 1,24);
        //Date endDate = Date.newInstance(2026, 2, 17);
        //Date endDate1 = Date.newInstance(2026, 2, 19);
        Date startDate = System.Today();
        Date endDate = System.Today().addDays(10);
        Rpl_Reva_Placement__c rpl = new Rpl_Reva_Placement__c();
        rpl.Rpl_Registration_Start_Date__c = startDate;
        rpl.Rpl_Registration_End_Date__c = endDate;
        rpl.Name = 'Test Reva Placement-01';
        
        insert rpl;
        
        Rpl_Student_Registration__c std = new Rpl_Student_Registration__c();
        std.Name = 'Test Data1';
        std.Rpl_Personal_Mail_ID__c = 'test@gmail.com';
        std.Rpl_Interested_in_placement__c = 'yes';
        std.Rpl_University_Mail_ID__c = '123123123@reva.edu.in';
        std.Rpl_Companies_Got_Placed_In__c = 'Company1';
        std.Contact__c = eCon.Id;
        std.Reva_Placement__c = rpl.Id;
        
        
        insert std;
        
        
        
        Rpl_Company__c  cmp = new Rpl_Company__c();
        cmp.Name = 'Amozan';
       
         insert cmp;
        
        Rpl_Placement_Drive__c plc = new Rpl_Placement_Drive__c();
        plc.Name = 'test Name';
        plc.Reva_Placement__c = rpl.Id;
        plc.Rpl_Company_Name__c = cmp.Id;
        plc.Rpl_Event_End_Date__c = endDate;
        //plc.Rpl_Event_Date_Time__c = endDate1;
        
        insert plc;
        
        
        Rpl_Student_Registration_Drive__c stdr = new Rpl_Student_Registration_Drive__c();
        stdr.Rpl_Placement_Drive__c =  plc.Id;
        stdr.Rpl_Student_Registration__c = std.Id;
        
        insert stdr;
              
    }

    @isTest
    static void testGetPlacementDriveId() {
        Rpl_Placement_Drive__c  rplDrive = [SELECT ID FROM Rpl_Placement_Drive__c LIMIT 1]; 
        Rpl_Eligibility__c eligibility = new Rpl_Eligibility__c(
            Rpl_Tenth_Percentage__c = 75,
            Rpl_Twelveth_Percentage__c = 80,
            Rpl_UG_Percentage1__c = 85,
            Rpl_PG_Percentage1__c = 90,
            Rpl_Current_Backlogs__c = 2,
            Rpl_Total_Backlogs__c = 5,
            Gender__c = 'Male',
            Offer_Count__c = 2,
            Rpl_Placement_Drive__c = rplDrive.Id,
            Rpl_Gap_Years__c = 1,
            Rpl_Placement_Interest__c = true,
            Rpl_Fee_Payment_Status__c = 'Exclude Students With Payment Pending',
            Rpl_Attendance_Percentage__c = 80,
             Rpl_Include_Students_With_Offer_In__c = 'Company1',
            Rpl_Exclude_Students_With_Offer_In__c = 'Company2'
            ,  
            Rpl_Specialization__c = 'MBA'
        );
        insert eligibility;

        /*RPL_EligibilityHandlerClass.CriteriaWrapperClass criteria = new RPL_EligibilityHandlerClass.CriteriaWrapperClass();
        criteria.tenthPercentage = 75;
        criteria.twelvePercentage = 80;
        criteria.UGPercentage = 85;
        criteria.PGPercentage = 90;
        criteria.currentBackLog = 2;
        criteria.specializationType = 'Computer Science';
        criteria.totalBacklogs = 5;
        criteria.gender = 'Male';
        criteria.OfferCount = 2;
        criteria.placementDriveId = eligibility.Rpl_Placement_Drive__c;
        criteria.gapYear = 1;
        criteria.placementInterest = true;
        criteria.attendance = 80;
        criteria.includeCompanies = 'Company1';
        criteria.excludeCompanies = 'Company2';*/

        Test.startTest();
        RPL_EligibilityHandlerClass.getPlacementDriveId(new List<Rpl_Eligibility__c>{eligibility}, false);
        Test.stopTest();
    }


    @isTest
    static void testSendEmail() {
        Set<String> toAddresses = new Set<String>{'test@example.com'};

        Test.startTest();
        //RPL_EligibilityHandlerClass.sendEmail(toAddresses);
        Test.stopTest();
    }
}