force-app/main/default/objects/Account/fields/Display_Name_Program__c.field-meta.xml
<CustomField>
    <fullName>Display_Name_Program__c</fullName>
    <label>Display Name (Program)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Alias__c.field-meta.xml
<CustomField>
    <fullName>Program_Alias__c</fullName>
    <label>Program Alias</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UG</fullName>
            </value>
            <value>
                <fullName>PG</fullName>
            </value>
            <value>
                <fullName>Ph.D</fullName>
            </value>
            <value>
                <fullName>PG Diploma</fullName>
            </value>
            <value>
                <fullName>Functional</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Diploma</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Father_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Name__c</fullName>
    <formula>Father__r.FirstName + &apos; &apos; +  Father__r.MiddleName + &apos; &apos; + Father__r.LastName</formula>
    <label>Father Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__Gender__c.field-meta.xml
<CustomField>
    <fullName>hed__Gender__c</fullName>
    <description>Indicates the person&apos;s self-identified gender.</description>
    <inlineHelpText>Indicates the person&apos;s self-identified gender.</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mother_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_Name__c</fullName>
    <label>Mother Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Primary_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Academic_Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <formula>Text( Primary_Academic_Program__r.Program_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rpl_Company__c/Rpl_Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Interview__c/Rpl_Interview__c.object-meta.xml
<CustomObject>
    <label>Recruitment Stage</label>
    <nameField>
        <label>Recruitment Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Interview__c/fields/Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Placement_Drive__c</fullName>
    <label>Placement Drive ID</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Recruitment Stages</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Interview__c/fields/Rpl_Round_Number__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Round_Number__c</fullName>
    <inlineHelpText>Please enter only numeric values to indicate the order of the interview rounds (e.g., 1, 2, 3, 4).</inlineHelpText>
    <label>Round Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/Rpl_Placement_Drive__c.object-meta.xml
<CustomObject>
    <label>Placement Drive</label>
    <nameField>
        <label>Placement Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Drives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Reva_Placement__c.field-meta.xml
<CustomField>
    <fullName>Reva_Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Placement</label>
    <referenceTo>Rpl_Reva_Placement__c</referenceTo>
    <relationshipLabel>Placement Drives</relationshipLabel>
    <relationshipName>Placement_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Rpl_Company__c</referenceTo>
    <relationshipLabel>Placement Drives</relationshipLabel>
    <relationshipName>Placement_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_Date_Time__c</fullName>
    <label>Event Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_End_Date__c</fullName>
    <label>Application End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Reva_Placement__c/Rpl_Reva_Placement__c.object-meta.xml
<CustomObject>
    <label>REVA Placement</label>
    <nameField>
        <label>REVA Placement  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Reva_Placement__c/fields/Rpl_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Academic_Program__c</fullName>
    <label>Academic Program</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rpl_Reva_Placement__c/fields/Rpl_Active__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Reva_Placement__c/fields/Rpl_Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Registration_End_Date__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Reva_Placement__c/fields/Rpl_Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Registration_Start_Date__c</fullName>
    <label>Registration Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/Rpl_Student_Registration__c.object-meta.xml
<CustomObject>
    <label>Student Registrations</label>
    <nameField>
        <label>Student Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Student_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Mother_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_Name__c</fullName>
    <label>Mother Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Reva_Placement__c.field-meta.xml
<CustomField>
    <fullName>Reva_Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Placement</label>
    <referenceTo>Rpl_Reva_Placement__c</referenceTo>
    <relationshipName>Student_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Interested_in_placement__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Interested_in_placement__c</fullName>
    <label>Interested In Placement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Is_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Personal_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Personal_Mail_ID__c</fullName>
    <label>Personal Mail - ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_University_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_University_Mail_ID__c</fullName>
    <label>University Mail - ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/RPL_TestDataFactory.cls
/*********************************************************************************
 * @description       : Test data for Test classes
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 24-01-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
*********************************************************************************/

@isTest
public class RPL_TestDataFactory {
    
    /*********************************************************
     * This method is test data for create Account object
     *********************************************************/
     public static Account createAccount(Boolean doInsert)
    {   
        Id academicProgramRecordId =  Schema.SObjectType.Account.getRecordTypeInfosByName().get('Academic Program').getRecordTypeId();
        system.debug('academicProgramRecordId--------------'+academicProgramRecordId);
        Account acc = new Account();
        acc.RecordTypeId = academicProgramRecordId;
        system.debug('***************'+acc);
        acc.Name = 'B.Tech in Computer Science and Information Technology';
        acc.Display_Name_Program__c = 'B.Tech in Computer Science and Information Technology';
        acc.Program_Alias__c = 'BT-CSIT';
        acc.Program_Type__c = 'UG';
        
        if(doInsert)
        {
            system.debug('beforeInsert***************'+acc);
            insert acc;
            
        }
        return acc;
    }
    
    /*********************************************************
     * This method is test data for create contact object
     *********************************************************/
     public static Contact createParentContact(Boolean doInsert)
    {  //Parent
        
       //child Contact Creation
       Id childId = createContact(true).Id;
        
        //Parent Id
        Id parentId =  Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();
        Contact con = new Contact();
        con.RecordTypeId = parentId;
        con.FirstName = 'Father-01';        
        con.LastName = 'Contact';
        con.hed__Gender__c = 'Male';
        con.Birthdate = Date.today();
        con.ReportsToId = childId;
        //con.Father_Name__c = 'test-father';
        //con.Mother_Name__c = 'test-mother';
        con.Personal_Email__c = 'test@example.com';
        con.hed__WorkEmail__c = 'test@gmail.com';
        con.SRN_Number__c = 'SRN123';
        con.MobilePhone = '1234567890';
        if(doInsert)
        {
            insert con;
        }
        return con;
    }
    
    
    /*********************************************************
     * This method is test data for create contact object
     *********************************************************/
     public static Contact createContact(Boolean doInsert)
    {
        Contact con = new Contact();
        con.FirstName = 'Test';
        con.Primary_Academic_Program__c = createAccount(True).Id;
        con.LastName = 'Contact';
        con.hed__Gender__c = 'Male';
        con.Birthdate = Date.today();
        //con.Mother_Name__c = createParentContact(true).Id;
        //con.Mother_Name__c = 'test-mother';
        con.Personal_Email__c = 'test@example.com';
        //con.hed__WorkEmail__c = 'test@gmail.com';
        con.SRN_Number__c = 'SRN123';
        con.MobilePhone = '1234567890';
        if(doInsert)
        {
            insert con;
        }
        return con;
    }
    
    /*********************************************************
     * This method is test data for create Rpl_Student_Registration__c object
     *********************************************************/
     public static Rpl_Student_Registration__c createStudentRegistration(Boolean doInsert, Id contactId)
    {
        Rpl_Student_Registration__c std = new Rpl_Student_Registration__c();
        std.Name = 'Test Data1';
        std.Rpl_Personal_Mail_ID__c = 'test@gmail.com';
        std.Rpl_Interested_in_placement__c = 'yes';
        std.Rpl_University_Mail_ID__c = '123123123@reva.edu.in';
        std.Contact__c = contactId;
        std.Rpl_Is_Blocked__c = true;
        if(doInsert)
        {
            insert std;
        }
        return std;
    }
    
    /*********************************************************
     * This method is test data for create Reva Placement object
     *********************************************************/
     public static Rpl_Reva_Placement__c createRevaPlacement(Boolean doInsert)
    {
        Date startDate = date.today();
        Date endDate = Date.newInstance(2026, 2, 17);
        Rpl_Reva_Placement__c rpl = new Rpl_Reva_Placement__c();
        rpl.Rpl_Registration_Start_Date__c = startDate;
        rpl.Rpl_Registration_End_Date__c = endDate;
        rpl.Name = 'Test Reva Placement-01';
        rpl.Rpl_Active__c = true;
        rpl.Rpl_Academic_Program__c = 'BT-CSIT';
        if(doInsert)
        {
            insert rpl;
        }
        return rpl;
    }
        
     /*********************************************************
     * This method is test data for create Company object
     *********************************************************/
        public static Rpl_Company__c createCompany(Boolean doInsert) {
            Rpl_Company__c com = new Rpl_Company__c();
            com.Name = 'Tesla';
            if(doInsert)
                {
                    insert com;
                    }
            return com;
            }
     
     /*********************************************************
     * This method is test data for create Placement object
     *********************************************************/
         public static Rpl_Placement_Drive__c createPlacement(Boolean doInsert, Id revaPlacementId, Id companyId){
             Date startDate = Date.newInstance(2024, 1,11);
             Date endDate = Date.newInstance(2026, 2, 17);
             Date endDate1 = Date.newInstance(2026, 2, 19);
             
             Rpl_Placement_Drive__c plc = new Rpl_Placement_Drive__c();
             plc.Name = 'test Name';
             plc.Reva_Placement__c = revaPlacementId;
             plc.Rpl_Company_Name__c = companyId;
             plc.Rpl_Event_End_Date__c = endDate;
             plc.Rpl_Event_Date_Time__c = endDate1;
             if(doInsert)
                {
                    insert plc;
                    }
            return plc;
            }
    
    
    /*********************************************************
     * This method is test data for create Rpl_Interview__c object
     *********************************************************/
         public static Rpl_Interview__c createInterview(Boolean doInsert, Id placementDriveId){
             Rpl_Interview__c stdIntview = new Rpl_Interview__c();
             stdIntview.Placement_Drive__c = placementDriveId;
             stdIntview.Name = 'Test Result 1';
             stdIntview.Rpl_Round_Number__c = 1;
             
             if(doInsert)
                {
                    insert stdIntview;
                    }
            return stdIntview;
            }
}