force-app/main/default/objects/Account/fields/Examination_Vertical_Head__c.field-meta.xml
<CustomField>
    <fullName>Examination_Vertical_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Examination Vertical Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <formula>Primary_Academic_Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Course</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Faculty)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/hed_Time_Table_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Time Table Line Item</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Table Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Time Table Line Items</relationshipLabel>
    <relationshipName>Time_Table_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_Date__c.field-meta.xml
<CustomField>
    <fullName>hed_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_End_Time__c.field-meta.xml
<CustomField>
    <fullName>hed_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>hed_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/Reva_Exam_Notification__c.field-meta.xml
<CustomField>
    <fullName>Reva_Exam_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IA Notification</label>
    <referenceTo>Rve_Exam_Notification__c</referenceTo>
    <relationshipLabel>Time Table Line Items</relationshipLabel>
    <relationshipName>Time_Table_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/IA_Seating_Room_Allotment__c.object-meta.xml
<CustomObject>
    <label>IA Seating Room Allotment</label>
    <nameField>
        <label>IA Seating Room Allotment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Seating Room Allotments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Alloted_Students__c.field-meta.xml
<CustomField>
    <fullName>Alloted_Students__c</fullName>
    <label>Alloted Students</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Assigned_Program_Batches__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Program_Batches__c</fullName>
    <inlineHelpText>This field contain all the assigned program batches to the room</inlineHelpText>
    <label>Assigned Program Batches</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Exam_Name__c.field-meta.xml
<CustomField>
    <fullName>Exam_Name__c</fullName>
    <label>Exam Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Exam_Time__c.field-meta.xml
<CustomField>
    <fullName>Exam_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Facility_Type__c.field-meta.xml
<CustomField>
    <fullName>Facility_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Type</label>
    <referenceTo>hed__Facility__c</referenceTo>
    <relationshipLabel>IA Seating Room Allotments</relationshipLabel>
    <relationshipName>IA_Seating_Room_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/IA_Type__c.field-meta.xml
<CustomField>
    <fullName>IA_Type__c</fullName>
    <label>IA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IA 1</fullName>
            </value>
            <value>
                <fullName>IA 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/InEligible_SRN__c.field-meta.xml
<CustomField>
    <fullName>InEligible_SRN__c</fullName>
    <label>InEligible SRN</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>IA Seating Room Allotments</relationshipLabel>
    <relationshipName>IA_Seating_Room_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/rve_Date_of_Exam__c.field-meta.xml
<CustomField>
    <fullName>rve_Date_of_Exam__c</fullName>
    <label>Date of Exam</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/rveShift__c.field-meta.xml
<CustomField>
    <fullName>rveShift__c</fullName>
    <label>Shift</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>IA Seating Room Allotments</relationshipLabel>
    <relationshipName>IA_Seating_Room_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Total_Students__c.field-meta.xml
<CustomField>
    <fullName>Total_Students__c</fullName>
    <label>Total Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/Rve_Exam_Notification__c.object-meta.xml
<CustomObject>
    <label>REVA Exam Notification</label>
    <nameField>
        <label>Exam Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Exam Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/hed_IA_Type__c.field-meta.xml
<CustomField>
    <fullName>hed_IA_Type__c</fullName>
    <label>IA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IA 1</fullName>
            </value>
            <value>
                <fullName>IA 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/hed_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>hed_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Reva Exam Notifications</relationshipLabel>
    <relationshipName>Reva_Exam_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/rve_Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>rve_Exam_Start_Date__c</fullName>
    <label>Exam Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Publish__c.field-meta.xml
<CustomField>
    <fullName>Rve_Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Semester__c.field-meta.xml
<CustomField>
    <fullName>Rve_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Semester</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipName>Reva_Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/recordTypes/hed_IA_Notification.recordType-meta.xml
<RecordType>
    <fullName>hed_IA_Notification</fullName>
    <active>true</active>
    <label>IA Notification</label>
</RecordType>

force-app/main/default/classes/RoomAllotmentPdfHandlerTest.cls
@isTest
private class RoomAllotmentPdfHandlerTest {
    @isTest
    static void testConstructor() {
        // Create test data
        Date testDate = Date.today();
        String dateParam = String.valueOf(testDate);
        String TimeParam = '11:00:00:000';
        Test.setCurrentPageReference(new PageReference(''));
        ApexPages.currentPage().getParameters().put('DatePass', dateParam);
        ApexPages.currentPage().getParameters().put('TimePass', TimeParam);
        
        Profile p = [Select Id from profile where name = 'Professor'];
        
         User u = new User(
         FirstName = 'Test',
            LastName = 'User',
            Alias = 'tuser',
            Email = 'testuser@example.com',
            Username = 'testuser@example.com' + System.currentTimeMillis(), // unique username
            EmailEncodingKey = 'UTF-8',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            LanguageLocaleKey = 'en_US',
            ProfileId = p.Id
        
        );
        
        insert u;
        // Create test records
        Account acc = new Account(Name = 'Test School',Examination_Vertical_Head__c = u.Id);
        insert acc;
        
        hed__Program_Plan__c ProgramBatch = new hed__Program_Plan__c();
        ProgramBatch.Name = 'TestIAProgramBatch';
        ProgramBatch.hed__Account__c = acc.Id;
        insert ProgramBatch;
        
        hed__Term__c Semester = new hed__Term__c(
            Name = 'TestSemester',
            hed__Account__c = acc.Id,
            hed__Start_Date__c = System.today(),
            hed__End_Date__c = System.today(),
            Term_Number__c = 1,
            Program_Batch__c = ProgramBatch.Id
        );
        
        insert Semester;
        
        RecordType ExamNotificationRecordType = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Rve_Exam_Notification__c' and DeveloperName='hed_IA_Notification'];
        
        Rve_Exam_Notification__c TestNotification = new Rve_Exam_Notification__c();
        TestNotification.Name = 'TestExamNotification';
        TestNotification.rve_Exam_Start_Date__c = System.Today();
        TestNotification.Rve_Publish__c = true;
        TestNotification.hed_Program_Batch__c = ProgramBatch.Id;
        TestNotification.hed_IA_Type__c = 'IA 1';
        TestNotification.RecordTypeId = ExamNotificationRecordType.Id;
        TestNotification.Rve_Semester__c = Semester.Id;
        insert TestNotification;
        
        System.debug('ExamNotification=> '+TestNotification);
        
        hed__Course__c Course = new hed__Course__c(
            Name = 'Test Course',
            hed__Account__c = acc.Id
        );
        
        insert Course;
        
        hed_Time_Table_Line_Item__c TimeTableItem = new hed_Time_Table_Line_Item__c();
        TimeTableItem.Name = 'TestTimeTable';
        TimeTableItem.Reva_Exam_Notification__c = TestNotification.Id;
        TimeTableItem.hed_Date__c = System.today();
        TimeTableItem.hed_Start_Time__c = Time.newInstance(11, 0, 0, 0);
        TimeTableItem.hed_End_Time__c = Time.newInstance(12, 0, 0, 0);
        TimeTableItem.Course__c = Course.Id;

        insert TimeTableItem;
        
        System.debug('TimeTableItem=> '+TimeTableItem);
        
        hed__Facility__c Facility = new hed__Facility__c(
            Name = 'Test Facility',
            hed__Capacity__c = 50,
            Facility_Booked__c = false,
            Room_Name__c = 'TESLA LAB',
            Room__c = '301',
            Floor__c = '1st floor',
            Block__c = 'C.V. Raman Block',
            IA_Type__c = 'IA 1',
            hed__Account__c = acc.Id
        );
        insert Facility;
        
        IA_Seating_Room_Allotment__c SeatingRoom = new IA_Seating_Room_Allotment__c(
            Name = Facility.Room__c,
            Facility_Type__c = Facility.Id,
            Capacity__c = Facility.hed__Capacity__c,
            IA_Type__c = Facility.IA_Type__c,
            School__c = acc.Id,
            Room__c = Facility.Room__c,
            Active__c = true,
            rve_Date_of_Exam__c = Date.today(),
            rveShift__c = 'Morning',
            Exam_Time__c = Time.NewInstance(11, 0, 0, 0),
            End_Time__c = Time.NewInstance(12, 0, 0, 0),
            Alloted_Students__c = 'SA001,SA002',
            InEligible_SRN__c = 'SA003,SA004',
            Course_Name__c = 'Electronic Circuit',
            Exam_Name__c = TestNotification.Name,
            Assigned_Program_Batches__c = ProgramBatch.Id,
            Total_Students__c = 4
        ); 
        
        insert SeatingRoom;
        
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            SRN_Number__c = 'SA001',
            Program_Batch__c = ProgramBatch.Id
        );
        insert testContact;
        
        Contact testContact2 = new Contact(
            FirstName = 'Test',
            LastName = 'Contact2',
            SRN_Number__c = 'SA003',
            Program_Batch__c = ProgramBatch.Id
        );
        insert testContact2;
    
        System.runas(u){
        // Call constructor
        Test.startTest();
        RoomAllotmentPdfHandler handler = new RoomAllotmentPdfHandler(new ApexPages.StandardController(new IA_Seating_Room_Allotment__c()));
        Test.stopTest();
        
        }
    }

    @isTest
    static void testCheckEvenOdd() {
        // Test the checkEvenOdd method
        System.assertEquals('Odd', RoomAllotmentPdfHandler.checkEvenOdd(1));
        System.assertEquals('Even', RoomAllotmentPdfHandler.checkEvenOdd(2));
        System.assertEquals('Odd', RoomAllotmentPdfHandler.checkEvenOdd(3));
        System.assertEquals('Even', RoomAllotmentPdfHandler.checkEvenOdd(4));
    }
}