force-app/main/default/objects/Account/fields/Intake__c.field-meta.xml
<CustomField>
    <fullName>Intake__c</fullName>
    <label>Intake</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Intake_Per_Section__c.field-meta.xml
<CustomField>
    <fullName>Intake_Per_Section__c</fullName>
    <label>Intake Per Section</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Alias__c.field-meta.xml
<CustomField>
    <fullName>Program_Alias__c</fullName>
    <label>Program Alias</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UG</fullName>
            </value>
            <value>
                <fullName>PG</fullName>
            </value>
            <value>
                <fullName>Ph.D</fullName>
            </value>
            <value>
                <fullName>PG Diploma</fullName>
            </value>
            <value>
                <fullName>Functional</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Diploma</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Academic_Program.recordType-meta.xml
<RecordType>
    <fullName>Academic_Program</fullName>
    <active>true</active>
    <description>An Academic Program offered at the educational institution.</description>
    <label>Academic Program</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Application_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>Application_Fee_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies if an Applicant has paid for the Applicant</description>
    <inlineHelpText>True, if Applicant has successfully paid for the application</inlineHelpText>
    <label>Application Fee Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Primary_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Academic_Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <formula>Primary_Academic_Program__r.Program_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <formula>Text( Primary_Academic_Program__r.Program_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Applicant_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Document_Type__c</fullName>
    <description>Various document types that can be uploaded by an applicant</description>
    <inlineHelpText>Various document types that can be uploaded by an applicant</inlineHelpText>
    <label>Applicant Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport Photo</fullName>
            </value>
            <value>
                <fullName>10th/SSLC Marks Card</fullName>
            </value>
            <value>
                <fullName>12th/PUC Marks Card</fullName>
            </value>
            <value>
                <fullName>Degree Marks Card</fullName>
            </value>
            <value>
                <fullName>Degree Certificate</fullName>
            </value>
            <value>
                <fullName>Transfer Certificate</fullName>
            </value>
            <value>
                <fullName>Migration Certificate</fullName>
            </value>
            <value>
                <fullName>Study Certificate</fullName>
            </value>
            <value>
                <fullName>Caste Certificate</fullName>
            </value>
            <value>
                <fullName>Income Certificate</fullName>
            </value>
            <value>
                <fullName>A Certificate</fullName>
            </value>
            <value>
                <fullName>Award for Gallantry</fullName>
            </value>
            <value>
                <fullName>B Certificate</fullName>
            </value>
            <value>
                <fullName>Bonafide letter</fullName>
            </value>
            <value>
                <fullName>C Certificate</fullName>
            </value>
            <value>
                <fullName>Degree Marks Card - Semesterwise</fullName>
            </value>
            <value>
                <fullName>JEE Score Card</fullName>
            </value>
            <value>
                <fullName>Killed/Disabled in action</fullName>
            </value>
            <value>
                <fullName>NATA Score Card</fullName>
            </value>
            <value>
                <fullName>NEET Score Card</fullName>
            </value>
            <value>
                <fullName>PUC ID card</fullName>
            </value>
            <value>
                <fullName>RDC Certificate</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>REVA ID Card</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Single Girl Child</fullName>
            </value>
            <value>
                <fullName>Specially Abled</fullName>
            </value>
            <value>
                <fullName>Sports Highest Level Certificate</fullName>
            </value>
            <value>
                <fullName>TSC Certificate</fullName>
            </value>
            <value>
                <fullName>Twin</fullName>
            </value>
            <value>
                <fullName>CET Allotment Letter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApplicantDocumentUploadTest.cls
@isTest
public class ApplicantDocumentUploadTest {
    
    @testSetup
    public static void createData(){
        String programName = 'Bachelor of Architecture';
        
        RecordType academicProgramRT = [Select id FROM RecordType Where DeveloperName = 'Academic_Program' Limit 1];
        RecordType applicantRT = [Select id FROM RecordType Where DeveloperName = 'Applicant' Limit 1];
        
        Account program= new Account(
        	Name = programName,
            RecordTypeId = academicProgramRT.Id,    
            Program_Alias__c = 'Barch',
            Program_Type__c = 'UG',
            Program_Code__c = 'RA',
            Intake__c = 80,
            Intake_Per_Section__c = 40
        );
        insert program;
        
        Contact Applicant1 = new Contact(
            FirstName = 'sai',
            MiddleName = 'k',
            LastName = 'K',
            Email = 'sai@gmail.com',
            MobilePhone = '9999999999',
            RecordTypeId = applicantRT.Id,
            Application_Fee_Paid__c = false,
            Application_Number__c = '222333555',
            Primary_Academic_Program__c = program.Id
        );
        insert Applicant1;
    }
    
    @isTest
    public static void applicantTest(){
        String programName = 'Bachelor of Architecture';
        
        Account acc =[Select id,Name From Account Where Name  = : programName];
        
        Contact con = [Select id, FirstName, LastName, Email From Contact Where Email = 'sai@gmail.com'];
        
        hed__Application__c Application1 = new hed__Application__c(
	        hed__Applicant__c = con.Id,
            hed__Applying_To__c = acc.Id
         );
         insert Application1;
        
        Test.startTest();
        ApplicantDocumentUpload.getApplicantId(Application1.id);
        Test.stopTest();
    }

    @isTest
    public static void uploadFiles_Test(){
        ApplicantDocumentUpload.FileInfo fileinfo = new ApplicantDocumentUpload.FileInfo();
        // ApplicantDocumentUpload.SavedFileInfo sf = new ApplicantDocumentUpload.SavedFileInfo ();
        // ApplicantDocumentUpload.EducationHistory Ehh = new ApplicantDocumentUpload.EducationHistory();
        // ApplicantDocumentUpload.EducationHistory Ehh = ApplicantDocumentUpload.EducationHistory.create();
        List<ApplicantDocumentUpload.FileInfo> fileinfos = new List<ApplicantDocumentUpload.FileInfo>();
        fileinfo.base64 = 'base64';
        fileinfo.filename = 'test';
        contact con = new contact();
        con.LastName='Mayur';
        insert con;
        fileinfo.recordIds=new List<string>{con.Id, fileinfo.fileType, fileinfo.fileType};
            fileinfo.filesize=2500;
        fileinfos.add(fileinfo);
        contentVersion cv = new contentVersion();
        cv.title ='Test';
        cv.PathOnClient = 'PathTest';
        cv.VersionData = Blob.valueof('this is a test');
        cv.Applicant_Document_Type__c ='Passport Photo';
        insert cv;
        ContentDocument contentDoc = [SELECT Id FROM ContentDocument WHERE LatestPublishedVersionId = :cv.Id];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = contentDoc.Id;
        cdl.LinkedEntityId = con.Id;
        fileinfo.contentDocumentId = contentDoc.Id;
        fileinfo.fileType = 'Passport Photo';
        List<String> cvIds = new List<String>();
        cvIds.add(cv.Id);
        
        // sf.contentDocumentId =  contentDoc.Id;
        // sf.fileType = 'Passport Photo'; 
        contentVersion cv2 = new contentVersion();
        cv2.PathOnClient = 'PathTest';
        cv2.VersionData = Blob.valueof('this is a test');
        cv2.Applicant_Document_Type__c ='Passport Photo';
        insert cv2;
        ContentDocument contentDoc2 = [SELECT Id FROM ContentDocument WHERE LatestPublishedVersionId = :cv.Id];
        ContentDocumentLink cdl2 = new ContentDocumentLink();
        cdl2.ContentDocumentId = contentDoc.Id;
        cdl2.LinkedEntityId = con.Id;
        fileinfo.contentDocumentId = contentDoc.Id;
        fileinfo.fileType = 'Passport Photo';
    
        cvIds.add(cv2.Id);
        String eduHistId = fileinfo.recordIds[1]; 
        String useLocation = 'primaryApplication';
        hed__Education_History__c educationHistory = new hed__Education_History__c();
        educationHistory.Type_Of_Course__c = 'UG';
        educationHistory.hed__Contact__c = con.Id;
        insert educationHistory;
         hed__Education_History__c educationHistory2 = new hed__Education_History__c();
        educationHistory2.Type_Of_Course__c = 'PG';
        educationHistory2.hed__Contact__c = con.Id;
        insert educationHistory2;
    
        List<String> str = ApplicantDocumentUpload.uploadFiles(fileinfos);
        List<ApplicantDocumentUpload.SavedFileInfo> SFI = ApplicantDocumentUpload.getCurrentFiles(con.Id);
        List<ApplicantDocumentUpload.EducationHistory> EH = ApplicantDocumentUpload.getEducationHistories(con.Id);
        ApplicantDocumentUpload.getFileTypes(con.Id,useLocation);
        List<String> cetDocs = ApplicantDocumentUpload.getFileTypes(con.Id,'CET');
        List<String> uqDocs =  ApplicantDocumentUpload.getFileTypes(con.Id,'UQ');
        System.assertEquals(2, cetDocs.size());
        System.assertEquals('Passport Photo', cetDocs[0]);
        System.assertEquals('CET Allotment Letter', cetDocs[1]);      
    }
    
    @isTest
    public static void uploadFiles_Test1(){
        ApplicantDocumentUpload.FileInfo fileinfo = new ApplicantDocumentUpload.FileInfo();
        List<ApplicantDocumentUpload.FileInfo> fileinfos = new List<ApplicantDocumentUpload.FileInfo>();
        fileinfo.base64 = 'base64';
        fileinfo.filename = 'test';
        contact con = new contact();
        con.LastName='Mayur';
        insert con;
        fileinfo.recordIds=new List<string>{con.Id, fileinfo.fileType, fileinfo.fileType};
            fileinfo.filesize=2500;
        fileinfos.add(fileinfo);
        contentVersion cv = new contentVersion();
        cv.title ='Test';
        cv.PathOnClient = 'PathTest';
        cv.VersionData = Blob.valueof('this is a test');
        cv.Applicant_Document_Type__c ='Passport Photo';
            fileinfo.ContentDocumentId= cv.Id;
        insert cv;
   
       
        ContentDocument contentDoc = [SELECT Id FROM ContentDocument WHERE LatestPublishedVersionId = :cv.Id];
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = contentDoc.Id;
        cdl.LinkedEntityId = con.Id;
        fileinfo.fileType = 'Passport Photo';
        List<String> cvIds = new List<String>();
        cvIds.add(cv.Id);
        String eduHistId = fileinfo.recordIds[1]; 
        String useLocation = 'primaryApplication';
        hed__Education_History__c educationHistory = new hed__Education_History__c();
        educationHistory.Type_Of_Course__c = 'UG';
        educationHistory.hed__Contact__c = con.Id;
        insert educationHistory;
        List<String> str = ApplicantDocumentUpload.uploadFiles(fileinfos);
        List<ApplicantDocumentUpload.SavedFileInfo> SFI = ApplicantDocumentUpload.getCurrentFiles(con.Id);
        List<ApplicantDocumentUpload.EducationHistory> EH = ApplicantDocumentUpload.getEducationHistories(con.Id);
        
        ApplicantDocumentUpload.getFileTypes(con.Id,useLocation);
        
    }
}