force-app/main/default/objects/Account/fields/Integrated_with_SAP__c.field-meta.xml
<CustomField>
    <fullName>Integrated_with_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integrated with SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <label>SAP ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Academic_Program.recordType-meta.xml
<RecordType>
    <fullName>Academic_Program</fullName>
    <active>true</active>
    <description>An Academic Program offered at the educational institution.</description>
    <label>Academic Program</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Aadhar_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Card_Number__c</fullName>
    <label>Aadhar Card Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Integrated_with_SAP_Date__c.field-meta.xml
<CustomField>
    <fullName>Integrated_with_SAP_Date__c</fullName>
    <label>Integrated with SAP Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Primary_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Academic_Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>Push_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <label>SAP ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Faculty)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Full_Name__c</fullName>
    <formula>FirstName &amp; &apos; &apos; &amp; MiddleName  &amp; &apos; &apos; &amp;  LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admission Cancelled</fullName>
            </value>
            <value>
                <fullName>Pursuing</fullName>
                <default>true</default>
                <label>Pursuing</label>
            </value>
            <value>
                <fullName>Detained</fullName>
            </value>
            <value>
                <fullName>Year Back</fullName>
            </value>
            <value>
                <fullName>Not Reported</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DB-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Debug Logs</relationshipLabel>
    <relationshipName>Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SAPSLCMIntegrationURL__mdt/SAPSLCMIntegrationURL__mdt.object-meta.xml
<CustomObject>
    <label>SAPSLCMIntegrationURL</label>
    <pluralLabel>SAPSLCMIntegrationURL</pluralLabel>
</CustomObject>

force-app/main/default/objects/SAPSLCMIntegrationURL__mdt/fields/EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>EndPointURL__c</fullName>
    <label>EndPointURL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SAP_SRN_PushtoSAPBatchAPIHandler.cls
public class SAP_SRN_PushtoSAPBatchAPIHandler {
    public static void  StudentMasterCreationMethod(List<Id> ContactIds) {
        //RecursiveTriggerHandler.isFirstTime = false;
        Debug_Log__c debugLog = new Debug_Log__c();
        List<Contact> contactsToUpdate = new List<Contact>();
        List<Debug_Log__c> lst_DbLogs = new List<Debug_Log__c>();
        try {
            
            SAPSLCMIntegrationURL__mdt mdt = SAPSLCMIntegrationURL__mdt.getInstance('Student_Master_Creation');
            String endpointURL = mdt.EndPointURL__c;
            
            List<RequestBodyWrapper> RequestBodyWrapperList = new List<RequestBodyWrapper>();
            for(Contact objCon:[SELECT Id, Program_Batch__c, hed__WorkEmail__c,Email, Aadhar_Card_Number__c, Application_Number__c, SAP_ID__c,
                                Primary_Academic_Program__r.SAP_ID__c, School__c,Program_Batch__r.SAP_ID__c,Personal_Email__c,School__r.SAP_ID__c,
                                SRN_Number__c ,School__r.Parent.SAP_ID__c,
                                Student_Full_Name__c, Student_Status__c FROM Contact WHERE Id IN: ContactIds])
            {
                RequestBodyWrapper requestBody = new RequestBodyWrapper();
                requestBody.Aadhar_Card_Number = objCon.Aadhar_Card_Number__c;
                requestBody.Academic_Program = objCon.Primary_Academic_Program__r.SAP_ID__c;
                requestBody.Application_Number = objCon.Application_Number__c;
                
                requestBody.Faculty = objCon.School__r.Parent.SAP_ID__c;
                
                requestBody.hed_WorkEmail = objCon.hed__WorkEmail__c;
                requestBody.Personal_Email = objCon.Personal_Email__c;
                requestBody.SRN_Number = objCon.SRN_Number__c;
                requestBody.Program_Batch = objCon.Program_Batch__r.SAP_ID__c;
                requestBody.School = objCon.School__r.SAP_ID__c;
                requestBody.Student_Full_Name = objCon.Student_Full_Name__c;
                if(objCon.Student_Status__c =='Pursuing' || objCon.Student_Status__c =='YearBack'){
                    requestBody.Student_Status = true;
                }
                else{
                    requestBody.Student_Status = false;
                }
                requestBody.ContactRecordID = objCon.Id;
                //requestBody.Virtual_Bank_Account_Number = objCon.Application_Number__c;
                /*  if(objCon.SAP_ID__c==null || objCon.SAP_ID__c =='' )
{
requestBody.SAPId = '';
}
else{
requestBody.SAPId= objCon.SAP_ID__c;
}*/
                //requestBody.SAPID = objCon.SAP_ID__c;
                
                
                RequestBodyWrapperList.add(requestBody);
            }
            
            String requestBodyJson = JSON.serialize(RequestBodyWrapperList);
            system.debug('requestBodyJson '+requestBodyJson);
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpointURL);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setBody(requestBodyJson);
            request.setTimeout(120000);
            
            HttpResponse response = new Http().send(request);
            
            Decimal statusCode = response.getStatusCode();
            String responseBody = response.getBody();
            System.debug('statusCode: ' + statusCode);
            System.debug('responseBody: ' + responseBody);
			 System.debug('requestBody: ' + request.getBody());
            System.debug('statuscode: ' +response.getStatusCode());
            
            
            debugLog.Request__c = request.getBody();
            debugLog.Response__c = response.getBody();
            debugLog.Status_Code__c = response.getStatusCode();
            insert debugLog;
            
            
            if (statusCode == 200) {
                OuterResponseWrapper outerResponseWrapper = (OuterResponseWrapper) JSON.deserialize(response.getBody(), OuterResponseWrapper.class);
                List<ResponseWrapper> responseWrappers = outerResponseWrapper.Response;
                //List<ResponseWrapper> responseWrappers = (List<ResponseWrapper>) JSON.deserialize(response.getBody(), List<ResponseWrapper>.class);
                System.debug('responseWrappers: ' + responseWrappers);
                for (ResponseWrapper responseWrapper : responseWrappers) {
                    
                    if (responseWrapper.statusCode == 0 && responseWrapper.SFDCRecordId != null && responseWrapper.SAPID != null) {
                        Contact  contactToUpdate = new Contact(Id = responseWrapper.SFDCRecordId);
                        contactToUpdate.SAP_ID__c = responseWrapper.SAPID;
                        contactToUpdate.Integrated_with_SAP__c =true;
                        contactToUpdate.Push_to_SAP__c = false;
                        contactToUpdate.Integrated_with_SAP_Date__c =system.today();
                        Debug_Log__c dblog = new Debug_Log__c();
                        
                        dblog.Contact__c = responseWrapper.SFDCRecordId;
                        dblog.Response__c = responseWrapper.responseObject;
                        dblog.Request__c = request.getBody();
                        dblog.Status__c = 'Success';
                        dblog.Status_Code__c = responseWrapper.statusCode;
                        lst_DbLogs.add(dblog);
                        contactsToUpdate.add(contactToUpdate);
                    }
                    else if(responseWrapper.statusCode == 1){
                        Contact  contactToUpdate = new Contact(Id = responseWrapper.SFDCRecordId);
                        contactToUpdate.SAP_ID__c = responseWrapper.SAPID;
                        contactToUpdate.Push_to_SAP__c = false;
                        Debug_Log__c dblog = new Debug_Log__c();
                        dblog.Contact__c = responseWrapper.SFDCRecordId;
                        dblog.Response__c = responseWrapper.responseObject;
                        dblog.Request__c = request.getBody();
                        dblog.Status__c = 'Failure';
                        dblog.Status_Code__c = responseWrapper.statusCode;
                            lst_DbLogs.add(dblog);
                        contactsToUpdate.add(contactToUpdate);
                    }
                }
                if (!contactsToUpdate.isEmpty()) {
                    RecursiveTriggerHandler.isFirstTime = false;
                    update contactsToUpdate;
                }
                if (!lst_DbLogs.isEmpty()) {
                    insert lst_DbLogs;
                }
            } else {
                System.debug('Error: ' + statusCode + ' ' + response.getStatus());
            }
        }
        catch (Exception e) {
            System.debug('An error occurred: ' + e.getMessage());
            debugLog.Response__c +='Error:'+'====='+e.getMessage();
            upsert debugLog;
        }
        
    }
    
    public class OuterResponseWrapper {
        public List<ResponseWrapper> Response;
    }
    public class RequestBodyWrapper {
        public String Aadhar_Card_Number;
        public String Academic_Program; 
        public String Application_Number; 
        public String Faculty;
        public String hed_WorkEmail;
        public String Personal_Email;
        public String SRN_Number;
        public String Program_Batch;
        
        public String School;
        
        public String Student_Full_Name;
        public Boolean Student_Status;
        public String ContactRecordID;    
        //public String SAPID;
        //public String Virtual_Bank_Account_Number;
        //SFDCRecordId
    }
    
    public class ResponseWrapper {
        public String SFDCRecordId;
        public Integer statusCode;
        public String statusMessage;
        public String SAPID;
        public String responseObject;
    }
}