force-app/main/default/objects/Account/fields/Integrated_with_SAP__c.field-meta.xml
<CustomField>
    <fullName>Integrated_with_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integrated with SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Aadhar_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Card_Number__c</fullName>
    <label>Aadhar Card Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Afghan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Anguillan</fullName>
            </value>
            <value>
                <fullName>Antiguans</fullName>
            </value>
            <value>
                <fullName>Argentinean</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Barbudans</fullName>
            </value>
            <value>
                <fullName>Batswana</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bermudian</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Botswanan</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Professor_Across_Schools__c.field-meta.xml
<CustomField>
    <fullName>Professor_Across_Schools__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Professor Across Schools</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admission Cancelled</fullName>
            </value>
            <value>
                <fullName>Pursuing</fullName>
                <default>true</default>
                <label>Pursuing</label>
            </value>
            <value>
                <fullName>Detained</fullName>
            </value>
            <value>
                <fullName>Year Back</fullName>
            </value>
            <value>
                <fullName>Not Reported</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/Fee_Payment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Fee Payment Criteria</label>
    <nameField>
        <label>Fee Payment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Payment Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Mess Penalty Fees</fullName>
                <isActive>false</isActive>
                <label>Mess Penalty Fees</label>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Contact__r.Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Payment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Fee_Payment_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Payment Criteria</label>
    <referenceTo>Fee_Payment_Criteria__c</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 1st Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 2nd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 3rd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 4th Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 5th Year</label>
            </value>
            <value>
                <fullName>University Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 1st Year</label>
            </value>
            <value>
                <fullName>University Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 2nd Year</label>
            </value>
            <value>
                <fullName>University Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 3rd Year</label>
            </value>
            <value>
                <fullName>University Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 4th Year</label>
            </value>
            <value>
                <fullName>University Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 5th Year</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Year__c.field-meta.xml
<CustomField>
    <fullName>Fee_Year__c</fullName>
    <label>Fee Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Year</fullName>
            </value>
            <value>
                <fullName>2nd Year</fullName>
            </value>
            <value>
                <fullName>3rd Year</fullName>
            </value>
            <value>
                <fullName>4th Year</fullName>
            </value>
            <value>
                <fullName>5th Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <formula>Contact__r.SRN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <formula>TEXT(Contact__r.Student_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SAP_FirstYear_DemandAPIBatch_Test.cls
@isTest
public class SAP_FirstYear_DemandAPIBatch_Test 
{
    public static testmethod void SAP_FirstYearDemandAPI()
    {
        string UniversityRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_University_Department).getRecordTypeId();
        Account objAccount = ATT_TestDataFactory.CreateAccount('Test Account',UniversityRecId);
        objAccount.RecordtypeId = UniversityRecId;  
        insert objAccount;
        
        Id ContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        Contact objcon = ATT_TestDataFactory.createContact('test Contact');
        objcon.AccountId = objAccount.id;
        objcon.Professor_Across_Schools__c = true;
        objcon.Application_Number__c = '123';
        objcon.hed__WorkEmail__c='123@reva.edu.in';
        objcon.Email = 'test@gmail.com';
        objcon.MobilePhone ='8963210547';
        objcon.SRN_Number__c='Srn123';
        objcon.RecordTypeId = ContactRecTypeId;
        objcon.ownerid = userinfo.getUserId();
        objcon.Nationality__c = 'Indian';
        objcon.Student_Status__c = 'Pursuing';
        objcon.Aadhar_Card_Number__c ='368845632147'; 
        objcon.PAN_Number__c ='HRAPO4561D';
        insert objcon;
        
        ContactHistory conHis =  new ContactHistory();
        conHis.ContactId = objcon.Id;
        conHis.Field = 'SRN_Number__c';
        Insert conHis;
        
        Fee_Payment_Criteria__c objFeeCriteris = FEE_TestDataFactory.createFeePaymentCriteria('University Fee','Full Payment');
        Insert objFeeCriteris;
        
        Student_Fee__c objStudentFee = FEE_TestDataFactory.createStudentFee(objFeeCriteris.Id, objcon.Id,'University Fee');   //'Academic Fee');
        objStudentFee.Contact__c = objcon.Id;
        objStudentFee.Fee_Payment_Criteria__c = objFeeCriteris.Id;
        objStudentFee.Name = 'Fee';
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Integrated_with_SAP__c = false;
        objStudentFee.Fee_Year__c = '1st Year';
        objStudentFee.Session__c='1st year';
        objStudentFee.Due_Date__c = system.today()-10;
        objStudentFee.Amount__c = 5000;
        objStudentFee.Amount_Paid__c = 6000;
        objStudentFee.Amount_Pending__c = 2000;
        Insert objStudentFee;
        
        
        Test.startTest();
        SAP_FirstYear_DemandAPIBatch Batch = new SAP_FirstYear_DemandAPIBatch();
        database.executeBatch(Batch);
        Test.stopTest();
        system.assertequals(conHis.id,conHis.id);
    }  
}