force-app/main/default/objects/Account/fields/No_of_Years__c.field-meta.xml
<CustomField>
    <fullName>No_of_Years__c</fullName>
    <label>No of Years</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Semesters__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Semesters__c</fullName>
    <label>Number of Semesters</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Alias__c.field-meta.xml
<CustomField>
    <fullName>Program_Alias__c</fullName>
    <label>Program Alias</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <label>Program Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UG</fullName>
            </value>
            <value>
                <fullName>PG</fullName>
            </value>
            <value>
                <fullName>Ph.D</fullName>
            </value>
            <value>
                <fullName>PG Diploma</fullName>
            </value>
            <value>
                <fullName>Functional</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Diploma</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Semester</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Semester</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <formula>Primary_Academic_Program__r.Program_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <formula>Text( Primary_Academic_Program__r.Program_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Student Fee Payment</description>
    <inlineHelpText>Student Fee Payment</inlineHelpText>
    <label>Student Fee Payment</label>
    <referenceTo>Student_Fee_Payment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <formula>Contact__r.Active_Semester__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Semester</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Full Payment</fullName>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <formula>Contact__r.Program_Batch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Batch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Line_Item_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Transaction_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date_Time__c</fullName>
    <label>Transaction Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/RHStudentFeePaymentReceiptControllerTest.cls
@isTest
public class RHStudentFeePaymentReceiptControllerTest {
  
    public class MockNumberToWordConversion implements HttpCalloutMock {
    public HTTPResponse respond(HTTPRequest req) {
        HTTPResponse res = new HTTPResponse();
        res.setHeader('Content-Type', 'application/json');
        res.setBody('{"amountInWords": "Five Thousand"}'); // Customize this as needed
        res.setStatusCode(200);
        return res;
    }
}
    
    
    @testSetup
    static void setup() {
        // Create test data
        hed__Program_Plan__c programBatch = new hed__Program_Plan__c(
            Name = 'B. Tech in Civil Engineering-(2020-2024)'
        );
        insert programBatch;
        System.debug('Inserted Program Batch: ' + programBatch.Id);

        Account academicProgram = new Account(Name = 'TestAcademicProgram',
                                              Program_Alias__c = 'MT-CSE(F)',
                                              Program_Type__c = 'PG',
                                              Program_Code__c = 'TC',
                                              Number_of_Semesters__c = 4,
                                              No_of_Years__c = 2);
        insert academicProgram;
        System.debug('Inserted Academic Program: ' + academicProgram.Id);

        hed__Term__c activeSemester = new hed__Term__c(
            Name = 'BT-CE-2020-2024-Sem-7',
            hed__Account__c = academicProgram.Id
        );
        insert activeSemester;
        System.debug('Inserted Active Semester: ' + activeSemester.Id);

        Contact studentContact = new Contact(
            LastName = 'Test Student',
            Program_Batch__c = programBatch.Id,
            Active_Semester__c = activeSemester.Id
        );
        insert studentContact;
        System.debug('Inserted Student Contact: ' + studentContact.Id);

        Student_Fee__c studentFee = new Student_Fee__c(Contact__c = studentContact.Id, Payment_Type__c = 'Full Payment');
        insert studentFee;
        System.debug('Inserted Student Fee: ' + studentFee.Id);

        Student_Fee_Payment__c studentFeePayment = new Student_Fee_Payment__c(
            Student_Fee__c = studentFee.Id,
            Amount__c = 5000,
            Mode_of_Payment__c = 'Online',
            Transaction_Date_Time__c = DateTime.now(),
            Line_Item_Payment_Status__c = 'Success'
        );
        insert studentFeePayment;
        System.debug('Inserted Student Fee Payment: ' + studentFeePayment.Id);

        Test.setCurrentPageReference(new PageReference('/apex/RHStudentFeePaymentReceiptPage'));
        ApexPages.currentPage().getParameters().put('paymentId', studentFeePayment.Id);
        System.debug('Set page parameter paymentId: ' + studentFeePayment.Id);
    }

  @isTest
    static void testController() {
        
         Test.setMock(HttpCalloutMock.class, new MockNumberToWordConversion());
        // Initialize the controller
        RHStudentFeePaymentReceiptController controller = new RHStudentFeePaymentReceiptController();
       
        Boolean paymentAmountFound = false;
        Boolean studentNameFound = false;
        Boolean paymentStatusFound = false;

        for (RHStudentFeePaymentReceiptController.PaymentInfo info : controller.receiptInfoList) {
            System.debug('Field: ' + info.field + ', Value: ' + info.value);
            if (info.field == 'Payment Amount' && info.value == '1,00,000.00') {
                paymentAmountFound = true;
            }
            if (info.field == 'Student Name' && info.value == 'Test Student') {
                studentNameFound = true;
            }
            if (info.field == 'Payment Status' && info.value == 'Success') {
                paymentStatusFound = true;
            }
            if (info.field == 'Course' && info.value == 'B. Tech in Civil Engineering-(2020-2024)') {
                paymentStatusFound = true;
            }
            if (info.field == 'Year of Study' && info.value == 'BT-CE-2020-2024-Sem-7') {
                paymentStatusFound = true;
            }
             if (info.field == 'Payment Mode' && info.value == 'Online') {
                paymentStatusFound = true;
            } if (info.field == 'Payment Type' && info.value == 'Full Payment') {
                paymentStatusFound = true;
            }
        }
    }
 
    @isTest
    static void testConstructor() {
        // Arrange
        String expectedField = 'CreditCard';
        String expectedValue = '1234-5678-9012-3456';
        
        // Act
        RHStudentFeePaymentReceiptController.PaymentInfo paymentInfo = new RHStudentFeePaymentReceiptController.PaymentInfo(expectedField, expectedValue);
        
   
    }
  @isTest
    static void testReceiptInfoList1() {
        // Create related records
        Contact testContact = new Contact(LastName='Test Contact');
        insert testContact;
        
          Account academicProgram = new Account(Name = 'Test School');
        insert academicProgram;
        
        hed__Program_Plan__c ProgramBatch = new hed__Program_Plan__c();
        ProgramBatch.Name = 'TestIAProgramBatch';
        ProgramBatch.hed__Account__c = academicProgram.Id;
        insert ProgramBatch;
        
            hed__Term__c activeSemester = new hed__Term__c(
            Name = 'BT-CE-2020-2024-Sem-7',
            hed__Account__c = academicProgram.Id
        );
        insert activeSemester;
        
        Student_Fee__c testStudentFee = new Student_Fee__c(
            Contact__c = testContact.Id,
            Payment_Type__c = 'Full Payment'
        );
        insert testStudentFee;
        
        Student_Fee_Payment__c testPayment = new Student_Fee_Payment__c(
            Amount__c = 100,
            Student_Fee__c = testStudentFee.Id,
            Mode_of_Payment__c = 'Online',
            Transaction_Date_Time__c = System.now(),
            Line_Item_Payment_Status__c = 'Success'
        );
        insert testPayment;
        
        // Set up test parameters
        Test.setCurrentPage(Page.RevaHostelStudentFeePaymentReceiptpage); // Ensure you have a Visualforce page called MyTestPage for this test
        ApexPages.currentPage().getParameters().put('paymentId', testPayment.Id);
        
        // Instantiate the controller
        RHStudentFeePaymentReceiptController controller = new RHStudentFeePaymentReceiptController();
       
    }
        
        
}