force-app/main/default/objects/Account/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>UG</fullName>
            </value>
            <value>
                <fullName>PG</fullName>
            </value>
            <value>
                <fullName>Ph.D</fullName>
            </value>
            <value>
                <fullName>PG Diploma</fullName>
            </value>
            <value>
                <fullName>Functional</fullName>
            </value>
            <value>
                <fullName>Research</fullName>
            </value>
            <value>
                <fullName>Diploma</fullName>
            </value>
            <value>
                <fullName>Certificate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Admission_Mode__c.field-meta.xml
<CustomField>
    <fullName>Admission_Mode__c</fullName>
    <label>Admission Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>CET</fullName>
            </value>
            <value>
                <fullName>ComedK</fullName>
            </value>
            <value>
                <fullName>DCET</fullName>
            </value>
            <value>
                <fullName>KEA</fullName>
            </value>
            <value>
                <fullName>PGCET</fullName>
            </value>
            <value>
                <fullName>UQ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>Application_Fee_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies if an Applicant has paid for the Applicant</description>
    <inlineHelpText>True, if Applicant has successfully paid for the application</inlineHelpText>
    <label>Application Fee Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Primary_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Academic_Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch_Name__c</fullName>
    <formula>IF( Record_Type_Name__c =&apos;Parent&apos;, ReportsTo.Program_Batch__r.Name,Program_Batch__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Batch Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <formula>Text( Primary_Academic_Program__r.Program_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Provisional_Admission_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>Provisional_Admission_Fee_Paid__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Provisional Admission Fee Paid</description>
    <label>Provisional Admission Fee Paid</label>
    <referenceTo>hed__Application__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date_Time__c</fullName>
    <label>Payment Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WhatsAppMsgTriggeredSummery.cls
public with sharing class WhatsAppMsgTriggeredSummery {
    
    // returns the integer list of batches Fee Not Paid, Fee Paid and Status - Started, Fee Paid and Status - Incomplete , PAF Pending
    @AuraEnabled(cacheable=true)
    public static List<Integer> getWhatsAppTriggerCount(){
        Integer currentYear = Date.today().year();
        String batchYearPrefix = String.valueOf(currentYear);

        List<Integer> batchData = new List<Integer>();
        
            Integer batch1Count = [SELECT Id, Name,Mobilephone, CreatedDate,Primary_Academic_Program__r.Name,Program_Batch_Name__c FROM Contact
            WHERE Program_Batch_Name__c  LIKE : '%'+batchYearPrefix+ '%' AND Application_Fee_Paid__c = False AND Primary_Academic_Program__c != null AND Record_Type_Name__c = 'Applicant'
            AND ((CALENDAR_MONTH(CreatedDate) = 11 AND CALENDAR_YEAR(CreatedDate) = :System.today().year() - 1)OR(CALENDAR_MONTH(CreatedDate) = 12
            AND CALENDAR_YEAR(CreatedDate) = :System.today().year() - 1) OR(CALENDAR_YEAR(CreatedDate) = :System.today().year()))].size();

            batchData.add(batch1Count);          

            Integer batch2Count = [select id, Application_Number__c,hed__Applicant__r.Mobilephone,hed__Applicant__r.name,hed__Application_Status__c,hed__Applicant__r.Application_Fee_Paid__c,hed__Applicant__r.Admission_Mode__c,hed__Applicant__r.Program_Batch__c from hed__Application__c 
            WHERE hed__Applicant__r.Application_Fee_Paid__c = true and hed__Applicant__r.Admission_Mode__c != null and hed__Applicant__r.Program_Batch__c !=null and hed__Applicant__r.Record_Type_Name__c='Applicant'  and hed__Applicant__r.Program_Batch__r.Name LIKE : '%'+batchYearPrefix+ '%' and hed__Application_Status__c='Started'
            AND ((CALENDAR_MONTH(CreatedDate) = 11 AND CALENDAR_YEAR(CreatedDate) = :System.today().year() - 1) OR(CALENDAR_MONTH(CreatedDate) = 12 AND CALENDAR_YEAR(CreatedDate) = :System.today().year() - 1)OR(CALENDAR_YEAR(CreatedDate) = :System.today().year()))].Size();
             
            batchData.add(batch2Count);

            Integer batch3Count = [select id, Application_Number__c,hed__Applicant__r.Mobilephone,hed__Applicant__r.name,hed__Application_Status__c,hed__Applicant__r.Application_Fee_Paid__c,hed__Applicant__r.Admission_Mode__c,hed__Applicant__r.Program_Batch__c from hed__Application__c 
                                       where hed__Applicant__r.Application_Fee_Paid__c = true and hed__Applicant__r.Admission_Mode__c != null and hed__Applicant__r.Program_Batch__c !=null and hed__Applicant__r.Record_Type_Name__c='Applicant' and  hed__Applicant__r.Program_Batch__r.Name LIKE : '%'+batchYearPrefix+ '%' AND hed__Application_Status__c='Incomplete'
                                      AND ((CALENDAR_MONTH(CreatedDate) = 11 AND CALENDAR_YEAR(CreatedDate) = :System.today().year() - 1) OR(CALENDAR_MONTH(CreatedDate) = 12 AND CALENDAR_YEAR(CreatedDate) = :System.today().year() - 1)OR(CALENDAR_YEAR(CreatedDate) = :System.today().year()))].size();
       
            batchData.add(batch3Count);
            
            Integer batchPAFPendingCount = [SELECT id, 
                                                    Application_Number__c,
                                                    hed__Applicant__r.Mobilephone,
                                                    hed__Applicant__r.name,
                                                    hed__Application_Status__c,
                                                    hed__Applicant__r.Application_Fee_Paid__c,
                                                    hed__Applicant__r.Admission_Mode__c,
                                                    hed__Applicant__r.Program_Batch__r.Name,
                                                    Provisional_Admission_Fee_Paid__c, 
                                                    hed__Applicant__r.Owner.Name, 
                                                    hed__Applicant__r.Owner.Phone
                                            FROM hed__Application__c 
                                            WHERE hed__Applicant__r.Application_Fee_Paid__c = true 
                                                AND  hed__Applicant__r.Program_Batch__r.Name LIKE : '%'+'('+batchYearPrefix+'%'
                                                AND hed__Applicant__r.Admission_Mode__c != null 
                                                AND hed__Applicant__r.Record_Type_Name__c='Applicant' 
                                                AND hed__Applicant__r.Program_Type__c != 'Ph.D'										    
                                                AND hed__Application_Status__c IN ('Interested', 'In Review','Awaiting Documents', 'Admit', 'Application Lost')
                                                AND Provisional_Admission_Fee_Paid__c = false].Size();
            
            batchData.add(batchPAFPendingCount);            
            return batchData;    
    }
    
    
    @AuraEnabled(cacheable=true)
    public static AsyncApexJob getWhatsAppTriggerDate(){         
        
            // This Query returns the completed date of WhatsAppFollowUpBatch1 batch
            AsyncApexJob feeNotPaidBatchDate = [SELECT CompletedDate
            FROM AsyncApexJob
            WHERE JobType = 'BatchApex'and ApexClass.Name = 'WhatsAppFollowUpBatch1' 	
           // WHERE JobType = 'BatchApex'and ApexClass.Name = 'EngageCampaignRecipientBatchDelete' 	
            AND Status = 'Completed'
            ORDER BY CompletedDate DESC
           // ORDER BY CompletedDate ASC
            LIMIT 1];
            
            return feeNotPaidBatchDate;        
    }

    // This method returns Fee paid count of WhatsAppMessage Triggered through batch apex
    @AuraEnabled(cacheable=true)
    public static Integer getApplicationFeePaidCount(DateTime lastBatchRanDateTime){    

            Integer feePaidCount = [SELECT Id,Transaction_ID__c,Fee_Type__c, Payment_Status__c, Payment_Date_Time__c 
            FROM Student_Payment__c 
            WHERE Fee_Type__c = 'Application Fee' AND Payment_Status__c = 'Success' AND Payment_Date_Time__c >=: lastBatchRanDateTime].size();

            return feePaidCount;
    }

    // This method returns Provisional Admission Feepaid count of WhatsAppMessage Triggered through batch apex
    @AuraEnabled(cacheable=true)
    public static Integer getProvisionalAdmissionFeePaid(DateTime lastBatchRanDateTime){    
        Integer currentYear = Date.today().year();
        String batchYearPrefix = String.valueOf(currentYear); 

            Integer PAFpaid = [SELECT id,
                    Application_Number__c,
                    hed__Applicant__r.Mobilephone,
                    hed__Applicant__r.name,
                    hed__Application_Status__c,
                    hed__Applicant__r.Application_Fee_Paid__c,
                    hed__Applicant__r.Admission_Mode__c,
                    hed__Applicant__r.Program_Batch__r.Name,
                    Provisional_Admission_Fee_Paid__c, 
                    hed__Applicant__r.Owner.Name, 
                    hed__Applicant__r.Owner.Phone
            FROM hed__Application__c 
            WHERE 
            hed__Applicant__r.Application_Fee_Paid__c = true 
                AND  hed__Applicant__r.Program_Batch__r.Name LIKE : '%'+'('+batchYearPrefix+'%'
                AND hed__Applicant__r.Admission_Mode__c != null 
                AND hed__Applicant__r.Record_Type_Name__c='Applicant' 
                AND hed__Applicant__r.Program_Type__c != 'Ph.D'
                AND hed__Application_Status__c IN ('Interested', 'In Review','Awaiting Documents', 'Admit', 'Application Lost')
                AND Provisional_Admission_Fee_Paid__c = true
                AND SystemModstamp >=: lastBatchRanDateTime].size();
           
            return PAFpaid;
    }

    @AuraEnabled(cacheable=true)
    public static List<hed__Application__History> getLatestStatusChangeList(DateTime lastBatchRanDateTime){
        List<hed__Application__History> listStatusChange = [SELECT Id,CreatedDate,Field,NewValue,OldValue,ParentId 
                                FROM hed__Application__History 
                                WHERE Field = 'hed__Application_Status__c' AND CreatedDate >=: lastBatchRanDateTime];
        return listStatusChange;
    }
}