force-app/main/default/objects/Account/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <label>SAP ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Aadhar_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Card_Number__c</fullName>
    <label>Aadhar Card Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Afghan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Anguillan</fullName>
            </value>
            <value>
                <fullName>Antiguans</fullName>
            </value>
            <value>
                <fullName>Argentinean</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Barbudans</fullName>
            </value>
            <value>
                <fullName>Batswana</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bermudian</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Botswanan</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <label>SAP ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/Fee_Payment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Fee Payment Criteria</label>
    <nameField>
        <label>Fee Payment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Payment Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Billdesk__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Billdesk__c</fullName>
    <label>Merchant ID - Billdesk</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Eazypay__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Eazypay__c</fullName>
    <label>Merchant ID - Eazypay</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Paytm__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Paytm__c</fullName>
    <label>Merchant ID - Paytm</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Razorpay__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Razorpay__c</fullName>
    <label>Merchant ID - Razorpay</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Contact__r.Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Payment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Fee_Payment_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Payment Criteria</label>
    <referenceTo>Fee_Payment_Criteria__c</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <formula>Contact__r.SRN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <label>SAP ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Student, Applicant,Non Teaching,Alumni,Professor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student  Payments</relationshipLabel>
    <relationshipName>Student_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SAP_OnlineAPI_BatchHandler_Test.cls
@isTest
public class SAP_OnlineAPI_BatchHandler_Test {
   public string parentRecordId;
    @isTest
    public static  void Online_API_Response()
    {
        string HouseholdRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Household).getRecordTypeId();
        Account objAcc = FEE_TestDataFactory.CreateAccount('Test Account',HouseholdRecId);
        objAcc.Recordtypeid = HouseholdRecId;
        Insert objAcc;
        
        string StudentRecId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(Utility.Contact_RecType_Student).getRecordTypeId();
        Contact objCon = FEE_TestDataFactory.createContact('Test',objAcc.Id);
        objCon.MobilePhone ='9090909090';
        objCon.Aadhar_Card_Number__c ='098765435612';
        objCon.RecordTypeId = StudentRecId;
        objCon.AccountId = objAcc.Id;
        objcon.Application_Number__c = 'test123';
        objcon.SRN_Number__c ='123';
        objcon.hed__WorkEmail__c  = 'test123@reva.edu.in';
        objcon.Nationality__c ='Indian';
        objcon.SAP_ID__c = '1024514';
        Insert objCon; 
        
        Fee_Payment_Criteria__c objFeeCriteria = FEE_TestDataFactory.createFeePaymentCriteria('Academic Fee','Full Payment');
        objFeeCriteria.Merchant_ID_Billdesk__c ='MIDB232323';
        objFeeCriteria.Merchant_ID_Eazypay__c ='MIDE121212';
        objFeeCriteria.Merchant_ID_Paytm__c ='MIDP343434';
        objFeeCriteria.Merchant_ID_Razorpay__c='MIDR4454545';
        Insert objFeeCriteria;
        
        Student_Fee__c objStudentFee = FEE_TestDataFactory.createStudentFee(objFeeCriteria.Id, objCon.Id,'Academic Fee');
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        insert objStudentFee;
        
        Student_Payment__c objStuPayment = FEE_TestDataFactory.createStudentPayment(objCon.Id);
        objStuPayment.Payment_Status__c ='Success';
        objStuPayment.Transaction_ID__c = 'PaymentId';
        objStuPayment.Reference_Id__c = '1234';
        objStuPayment.Payment_Mode_Type__c= 'Online';
        objStuPayment.Amount__c = 100000;
        objStuPayment.Payment_Link_Id__c= 'plink_JeYmmPJlVpozjh';
        insert objStuPayment;
        
        
        Student_Fee_Payment__c objStuFeePay = FEE_TestDataFactory.CreateStudentFeePayment(objStudentFee.id, objStuPayment.id);
        objStuFeePay.Line_Item_Payment_Status__c = 'Success';
        objStuFeePay.Amount__c=1000;        
        objStuFeePay.Mode_of_Payment__c='Online';
        objStuFeePay.SF_Transaction_ID__c= 'Test213';
        objStuFeePay.Push_to_SAP__c = false;
        objStuFeePay.Integrated_with_SAP__c = false;
        objStuFeePay.Transaction_Status__c = 'Completed';
        objStuFeePay.Transaction_Date_Time__c  = system.now();
        objStuFeePay.Payment_Link_Id__c = 'plink_JeYmmPJlVpozjh';
        objStuFeePay.Student_Fee__c = objStudentFee.id;
        insert objStuFeePay;
        //objStuFeePay.Push_to_SAP__c = true;
        //Update objStuFeePay;
        
        List<id> lst_StudentFee = New List<id>();
        lst_StudentFee.add(objStuFeePay.id);
        
        objStuPayment.Payment_Gateway__c = 'Eazypay';
        update objStuPayment;
        
        string myJSON = '';
        
       /* RestRequest request = new RestRequest();
        request.requestUri ='https://revauniversity9--revadev.my.salesforce.com/services/apexrest/EasyPayResponse';
        request.httpMethod = 'POST';
        RestContext.request = request; 
        request.requestBody = Blob.valueof(myJSON);
        
        RestContext.request = request;*/
        
        EasyPay_Details__c easypaydetails = new EasyPay_Details__c();
        easypaydetails.Value__c ='https://revauat-revauat.cs75.force.com/StudentPortal/s/student-fee';
        easypaydetails.name ='AES key';
        //insert easypaydetails;
        
        EasyPay_Details__c easypaydetails1 = new EasyPay_Details__c();
        easypaydetails1.Value__c ='https://revauat-revauat.cs75.force.com/StudentPortal/s/student-fee';
        easypaydetails1.name ='HomeUrl';
        insert easypaydetails1;
        EasyPay_Details__c easypaydetails2 = new EasyPay_Details__c();
        easypaydetails2.Value__c ='  https://www.reva.edu.in/';
        easypaydetails2.name ='Applicant_HomeUrl';
        //insert easypaydetails2;
        
        EasyPay_Details__c easypaydetails3 = new EasyPay_Details__c();
        easypaydetails3.Value__c ='https://rev--stratosuat.sandbox.my.site.com/Admissions/s/';
        easypaydetails3.name ='Applicant_PortalUrl';
        //insert easypaydetails3;
        
        Payment_Gateway_Error_Msg__c objpayGateway = new Payment_Gateway_Error_Msg__c();
        objpayGateway.Error_Msg__c ='Success';
        objpayGateway.Name='Eazypay-E000';
        objpayGateway.Status__c ='Success';
        //insert objpayGateway;
        
       // SAP_OnlineAPI.RequestBodyWrapper reqWrpBody = new SAP_OnlineAPI.RequestBodyWrapper();
        //reqWrpBody.Contact = objStuFeePay.id;
        //reqWrpBody.Offline_Receipt_Number = '2';
        
        // Set up mock callout response
         //Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        String parentRecordId =objStuFeePay.Id; 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(parentRecordId));

        test.starttest();
        SAP_OnlineAPI_Batch sh1 = new SAP_OnlineAPI_Batch();
        
        String sch = '0 0 23 * * ?'; 
        system.schedule('Test Territory Check', sch, sh1);
      // SAP_OnlineAPI_Batch opBatch = new SAP_OnlineAPI_Batch();
        //Database.executeBatch(opBatch,1);
       
        test.stoptest(); 
        // Mock HTTP callout response class
        
    }

    public class MockHttpResponseGenerator implements HttpCalloutMock {
        private String parentRecordId;
        
        public MockHttpResponseGenerator(String parentRecordId) {
            this.parentRecordId = parentRecordId;
        }
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setStatus('OK');//a1O0T000000gU82UAE
            //res.setBody('{"Response": [{"SFDCRecordId": "a1O0T000000gR8TUAU", "statusCode": 0, "SAPID": "SAP123", "responseObject": "Success"}]}');
            res.setBody('{"Response": [{"SFDCRecordId": "' + parentRecordId + '", "statusCode": 0, "SAPID": "SAP123", "responseObject": "Success"}]}');

            return res;
        }
    }
}