force-app/main/default/objects/Account/fields/Vertical_Head__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vertical Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/hed_Time_Table_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Time Table Line Item</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Table Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Time Table Line Items</relationshipLabel>
    <relationshipName>Time_Table_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_Date__c.field-meta.xml
<CustomField>
    <fullName>hed_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_End_Time__c.field-meta.xml
<CustomField>
    <fullName>hed_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>hed_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/Reva_Exam_Notification__c.field-meta.xml
<CustomField>
    <fullName>Reva_Exam_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IA Notification</label>
    <referenceTo>Rve_Exam_Notification__c</referenceTo>
    <relationshipLabel>Time Table Line Items</relationshipLabel>
    <relationshipName>Time_Table_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/Rve_Exam_Notification__c.object-meta.xml
<CustomObject>
    <label>REVA Exam Notification</label>
    <nameField>
        <label>Exam Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Exam Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/hed_IA_Type__c.field-meta.xml
<CustomField>
    <fullName>hed_IA_Type__c</fullName>
    <label>IA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IA 1</fullName>
            </value>
            <value>
                <fullName>IA 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/hed_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>hed_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Reva Exam Notifications</relationshipLabel>
    <relationshipName>Reva_Exam_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/rve_Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>rve_Exam_Start_Date__c</fullName>
    <label>Exam Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Publish__c.field-meta.xml
<CustomField>
    <fullName>Rve_Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/recordTypes/hed_IA_Notification.recordType-meta.xml
<RecordType>
    <fullName>hed_IA_Notification</fullName>
    <active>true</active>
    <label>IA Notification</label>
</RecordType>

force-app/main/default/classes/rveFacultyTimeTableControllerTest.cls
@isTest
public class rveFacultyTimeTableControllerTest {

    @TestSetup
    static void makeData() {
        Profile professorProfile = [SELECT Id FROM Profile WHERE Name = 'Examination Vertical Head' LIMIT 1];

        // Create test users with 'Professor' profile
        User prof1 = new User(
            Alias = 'prof1',
            Email = 'prof1@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Professor1',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = professorProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            Username = 'prof1@test.com'
        );
        insert prof1;

        Account accparent = new Account(Name = 'TestAccParent', Vertical_Head__c = prof1.Id);
        insert accparent;

        Account acc = new Account(Name = 'TestAcc', parentId = accparent.Id);
        insert acc;

        hed__Program_Plan__c ProgramBatch = new hed__Program_Plan__c(Name = 'TestIAProgramBatch', hed__Account__c = acc.Id);
        insert ProgramBatch;

        hed__Term__c Semester = new hed__Term__c(
            Name = 'TestSemester',
            hed__Account__c = acc.Id,
            hed__Start_Date__c = System.today(),
            hed__End_Date__c = System.today(),
            Term_Number__c = 1,
            Program_Batch__c = ProgramBatch.Id
        );
        insert Semester;

        RecordType ExamNotificationRecordType = [SELECT Id, Name FROM RecordType WHERE SObjectType = 'Rve_Exam_Notification__c' AND DeveloperName = 'hed_IA_Notification'];

        Rve_Exam_Notification__c TestNotification = new Rve_Exam_Notification__c(
            Name = 'TestExamNotification',
            rve_Exam_Start_Date__c = System.Today(),
            Rve_Publish__c = true,
            hed_Program_Batch__c = ProgramBatch.Id,
            hed_IA_Type__c = 'IA 1',
            RecordTypeId = ExamNotificationRecordType.Id
        );
        insert TestNotification;

        hed__Course__c Course = new hed__Course__c(Name = 'Test Course', hed__Account__c = acc.Id);
        insert Course;

        hed_Time_Table_Line_Item__c TimeTableItem = new hed_Time_Table_Line_Item__c(
            Name = 'TestTimeTable',
            Reva_Exam_Notification__c = TestNotification.Id,
            hed_Date__c = System.today(),
            hed_Start_Time__c = Time.newInstance(11, 0, 0, 0),
            hed_End_Time__c = Time.newInstance(12, 0, 0, 0),
            Course__c = Course.Id
        );
        insert TimeTableItem;
    }

    @isTest
    public static void testGetExamScheduleItems() {
        Test.startTest();
        List<hed_Time_Table_Line_Item__c> result = rveFacultyTimeTableController.getExamScheduleItems();
        Test.stopTest();
        System.assertNotEquals(0, result.size(), 'Exam schedule items should not be empty');
    }

    @isTest
    public static void testGetIAExamTimeTable() {
        Test.startTest();
        List<hed_Time_Table_Line_Item__c> result = rveFacultyTimeTableController.getIAExamTimeTable();
        Test.stopTest();
    }

    @isTest
    public static void testSearchProgramBatch() {
        hed__Program_Plan__c programBatch = [SELECT Id, Name FROM hed__Program_Plan__c WHERE Name = 'TestIAProgramBatch' LIMIT 1];
        Test.startTest();
        List<hed__Program_Plan__c> result = rveFacultyTimeTableController.searchProgramBatch(programBatch.Name);
        Test.stopTest();
    }

    @isTest
    public static void testGetActiveSemester() {
        hed__Program_Plan__c programBatch = [SELECT Id, Name FROM hed__Program_Plan__c WHERE Name = 'TestIAProgramBatch' LIMIT 1];
        Test.startTest();
        List<hed__Term__c> result = rveFacultyTimeTableController.getActiveSemester(programBatch.Id);
        Test.stopTest();
        System.assertNotEquals(0, result.size(), 'Active semester search results should not be empty');
    }

    @isTest
    public static void testGetCourses() {
        hed__Term__c Semester = [SELECT Id FROM hed__Term__c LIMIT 1];
        Test.startTest();
        List<hed__Course_Offering__c> result = rveFacultyTimeTableController.getCourses(Semester.Id);
        Test.stopTest();
    }

    @isTest
    public static void testUpdateLineItem() {
        hed_Time_Table_Line_Item__c TimeTable = [SELECT Id FROM hed_Time_Table_Line_Item__c LIMIT 1];
        String JsonString = '[{"Id":"'+TimeTable.Id+'","StartTime":"12:45:00 PM","EndTime":"2:15:00 PM","LineItemDate":"2024-06-17"}]';
        Test.startTest();
        rveFacultyTimeTableController.updategetExamScheduleItems(JsonString);
        Test.stopTest();
        hed_Time_Table_Line_Item__c updatedItem = [SELECT hed_Start_Time__c, hed_End_Time__c, hed_Date__c FROM hed_Time_Table_Line_Item__c WHERE Id = :TimeTable.Id];
       
    }

    @isTest
    public static void testIATimeTableCreation() {
        hed__Term__c Semester = [SELECT Id FROM hed__Term__c LIMIT 1];
        hed__Program_Plan__c programBatch = [SELECT Id FROM hed__Program_Plan__c LIMIT 1];
        String timeTableData = '[{"CourseId":"a0G1l000000pGDM","CourseName":"Test Course","ExamDate":"2024-06-17","StartTime":"12:45:00","EndTime":"2:15:00"}]';
        Test.startTest();
        String result = rveFacultyTimeTableController.IATimeTableCreation('TestNotification', Semester.Id, programBatch.Id, timeTableData, 'IA 1');
        Test.stopTest();
    }

    @isTest
    public static void testGetFormattedTime() {
        String timeString = '01:00:00 PM';
        Test.startTest();
        Time result = rveFacultyTimeTableController.getformattedtime(timeString);
        Test.stopTest();
    }
}