force-app/main/default/objects/Billdesk_Merchant_Details__c/Billdesk_Merchant_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Billdesk Merchant Details</label>
</CustomObject>

force-app/main/default/objects/Billdesk_Merchant_Details__c/fields/MerchantId__c.field-meta.xml
<CustomField>
    <fullName>MerchantId__c</fullName>
    <label>MerchantId</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Student Fee Payment</description>
    <inlineHelpText>Student Fee Payment</inlineHelpText>
    <label>Student Fee Payment</label>
    <referenceTo>Student_Fee_Payment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DB-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Data_Received__c.field-meta.xml
<CustomField>
    <fullName>Data_Received__c</fullName>
    <label>Data Received</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Payment_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference_Id__c</fullName>
    <label>Payment Reference Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Processing_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Processing_API_Name__c</fullName>
    <label>Processing API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student  Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Debug Logs</relationshipLabel>
    <relationshipName>Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 1st Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 2nd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 3rd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 4th Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 5th Year</label>
            </value>
            <value>
                <fullName>University Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 1st Year</label>
            </value>
            <value>
                <fullName>University Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 2nd Year</label>
            </value>
            <value>
                <fullName>University Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 3rd Year</label>
            </value>
            <value>
                <fullName>University Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 4th Year</label>
            </value>
            <value>
                <fullName>University Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 5th Year</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Payment_Mode_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Type__c</fullName>
    <label>Payment Mode Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Payment_Mode_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Type__c</fullName>
    <inlineHelpText>Debit Card / Credit Card / Netbanking / UPI</inlineHelpText>
    <label>Payment Mode Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <label>Reference Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>RazorPay</fullName>
                <isActive>false</isActive>
                <label>RazorPay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date_Time__c</fullName>
    <label>Payment Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Mode_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Type__c</fullName>
    <label>Payment Mode Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <label>Reference Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FEE_BilldeskResponse_API.cls
// @RestResource(UrlMapping='/ResponseDetaiils/*')
global class FEE_BilldeskResponse_API 
{    
    global String responce{get;set;}
    global String paymentId {get;set;}
    global String paymentGateway {get;set;}
    global String successMsg{get;set;}
    global String refId{get;set;}
    global String transactionType{get;set;}
    global String referenceId{get;set;}
    global String transactionId{get;set;}
    global Decimal amount{get;set;}
    global String homeUrl{get;set;}
    global String Applicant_Billdesk_HomeUrl{get;set;}
    global String paymentMode{get;set;}
    global String iSTTransactionDateTime{get;set;}
    global Datetime transactionDateTime{get;set;}
    global String purposeofPayment{get;set;}
    global String statusDescription{get;set;}
    global String statusErrDes{get;set;}
    global String urlRefresh{get;set;}
    global final String SMS_TYPE ='Application_Number';
    global final String APPLICATION_FEE_TYPE ='Application Fee';
    static hed__Application__c appl;
    static list<hed__Application__c> applList;
    static boolean applPAF;
    global string FEE_TYPE{get;set;}
    global string Applicant_PortalUrl{get;set;}
    global String applicationNumber{get;set;}
    global String emailAddress{get;set;}
    
    global static Set<id> sf1 = new set<id>();
    
    global FEE_BilldeskResponse_API(){
    }
    
    global void BilldeskRespon()
    {
        urlRefresh = '';
        homeUrl = Billdesk_Merchant_Details__c.getValues('HomeUrl').MerchantId__c;
        responce = apexpages.currentpage().getparameters().get('msg');
        Debug_Log__c dblog = new Debug_Log__c();
        try{            
            if(responce != null)
            {
                String newStrReq = responce;
                Integer reqLen = newStrReq.split('\\|').size();
                String checkSumValue = newStrReq.split('\\|')[reqLen-1];
                String statusCode = newStrReq.split('\\|')[reqLen-12]; 
                transactionId = newStrReq.split('\\|')[reqLen-24];
                //String ref = newStrReq.split('\\|')[reqLen-25];
                referenceId = newStrReq.split('\\|')[reqLen-25];
                refId = newStrReq.split('\\|')[reqLen-8];
                TransactionType = newStrReq.split('\\|')[reqLen-19];
                StatusErrDes = newStrReq.split('\\|')[reqLen-2];
                
                String noCheckSumValue = newStrReq.removeEnd(newStrReq.split('\\|')[reqLen-1]);
                String requestwithNoCheckSum = noCheckSumValue.Substring(0,noCheckSumValue.length()-1);
                Student_Payment__c stu = [SELECT id,Transaction_ID__c,Mode_of_Payment__c,Payment_Status__c,Payment_Date_Time__c,Payment_Mode_Type__c,
                                          Amount__c,Fee_Type__c FROM Student_Payment__c WHERE Reference_Id__c  =: referenceId];
                if(stu.Payment_Status__c =='Payment Link Created')
                {
                    dblog.Class_Name__c = 'FEE_BilldeskResponse_API';
                    dblog.Method_Name__c = 'BilldeskRespon';
                    dblog.Processing_API_Name__c = 'BillDesk';            
                    dblog.Data_Received__c = responce;
                    
                    string newCheckSum = calculateCheckSum(requestwithNoCheckSum);
                    
                    if(newCheckSum == checkSumValue || test.isRunningTest())
                    {                        
                        if(statusCode == '0300')
                        {
                            if(TransactionType == '01')    stu.Payment_Mode_Type__c ='Netbanking';
                            else if(TransactionType == '02')  stu.Payment_Mode_Type__c ='Credit Card';
                            else if(TransactionType == '03')  stu.Payment_Mode_Type__c ='Debit Card';
                            else if(TransactionType == '04') stu.Payment_Mode_Type__c ='Cash Card';
                            else if(TransactionType == '05') stu.Payment_Mode_Type__c ='Mobile';
                            else if(TransactionType == '06')   stu.Payment_Mode_Type__c ='IMPS';
                            else if(TransactionType == '07')   stu.Payment_Mode_Type__c ='Reward Points';
                            else if(TransactionType == '08')  stu.Payment_Mode_Type__c ='Others';
                            else if(TransactionType == '09') stu.Payment_Mode_Type__c ='Others Wallet';
                            else if(TransactionType == '10')   stu.Payment_Mode_Type__c ='UPI';
                            
                            stu.Transaction_ID__c = transactionId;
                            stu.Payment_Date_Time__c = system.now();
                            //stu.Payment_Date_Time__c = datetime.now();
                            //stu.Payment_Date_Time__c = system.now().addHours(5).addMinutes(30);
                            stu.Payment_Status__c = 'Success';
                            amount = stu.Amount__c;
                            if(stu.Payment_Date_Time__c != null)  TransactionDateTime = stu.Payment_Date_Time__c;//.addHours(5).addMinutes(30);
                            else TransactionDateTime =system.now(); 
                            ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');
                            PurposeofPayment = stu.Fee_Type__c;
                            PaymentMode = 'Online';
                            SuccessMsg = 'Transaction Success..!!';
                            dblog.Status__c = 'Success';
                            dblog.Error_Message__c = StatusErrDes; 
                            dblog.Payment_Reference_Id__c = referenceId;                       
                        }
                        else if(statusCode == '0002')
                        {
                            if(TransactionType == '01')  stu.Payment_Mode_Type__c ='Netbanking';
                            else if(TransactionType == '02') stu.Payment_Mode_Type__c ='Credit Card';
                            else if(TransactionType == '03') stu.Payment_Mode_Type__c ='Debit Card';
                            else if(TransactionType == '04')  stu.Payment_Mode_Type__c ='Cash Card';
                            else if(TransactionType == '05') stu.Payment_Mode_Type__c ='Mobile';
                            else if(TransactionType == '06') stu.Payment_Mode_Type__c ='IMPS';
                            else if(TransactionType == '07') stu.Payment_Mode_Type__c ='Reward Points';
                            else if(TransactionType == '08')  stu.Payment_Mode_Type__c ='Others';
                            else if(TransactionType == '09') stu.Payment_Mode_Type__c ='Others Wallet';
                            else if(TransactionType == '10') stu.Payment_Mode_Type__c ='UPI';
                            
                            stu.Transaction_ID__c = transactionId;
                            stu.Payment_Date_Time__c = system.now();
                            stu.Payment_Status__c = 'Pending';
                            amount = stu.Amount__c;
                            if(stu.Payment_Date_Time__c != null)  TransactionDateTime = stu.Payment_Date_Time__c;
                            else    TransactionDateTime =system.now();
                            ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');
                            PaymentMode = 'Online';
                            PurposeofPayment = stu.Fee_Type__c;
                            SuccessMsg = 'Transaction Pending..!!';
                            dblog.Status__c = 'Pending';     
                            dblog.Error_Message__c = StatusErrDes;
                            dblog.Payment_Reference_Id__c = referenceId;      
                        }
                        else{
                            stu.Transaction_ID__c = transactionId;
                            stu.Payment_Date_Time__c = system.now();//.addHours(5).addMinutes(30);
                            stu.Payment_Status__c = 'Failed';
                            amount = stu.Amount__c;
                            if(stu.Payment_Date_Time__c != null) TransactionDateTime = stu.Payment_Date_Time__c;
                            else TransactionDateTime =system.now();
                            ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');
                            PurposeofPayment = stu.Fee_Type__c;
                            StatusDescription  = StatusErrDes;                            
                            PaymentMode = 'Online';
                            SuccessMsg = 'Transaction Failed..!!';                        
                            dblog.Status__c = 'Failure';
                            dblog.Error_Message__c = StatusErrDes; 
                            dblog.Payment_Reference_Id__c = referenceId;
                        }   
                    }
                    else{
                        
                        stu.Transaction_ID__c = transactionId;
                        stu.Payment_Date_Time__c = system.now();
                        stu.Payment_Status__c = 'Failed';
                        SuccessMsg = 'Failed.CheckSum Not Matched..!!';
                        dblog.Status__c = 'Failure';
                        dblog.Error_Message__c = StatusErrDes; 
                        dblog.Payment_Reference_Id__c = referenceId;
                    }
                    
                    update stu;   
                    
                    list<Student_Fee_Payment__c> lst_Studentfee = new list<Student_Fee_Payment__c>();
                    for(Student_Fee_Payment__c objStuFeePayment : [Select Id,Name,Amount__c,Mode_of_Payment__c,Payment_Link_Id__c,SF_Transaction_ID__c,Student_Fee__c,Line_Item_Payment_Status__c,
                                                                   Student_Payment__c,Transaction_Date_Time__c,Payment_Mode_Type__c from Student_Fee_Payment__c  where
                                                                   Reference_Id__c =: referenceId])
                    {
                        objStuFeePayment.Line_Item_Payment_Status__c = stu.Payment_Status__c;
                        objStuFeePayment.SF_Transaction_ID__c = transactionId;
                        objStuFeePayment.Transaction_Date_Time__c = system.now();
                        objStuFeePayment.Payment_Mode_Type__c = stu.Payment_Mode_Type__c;               
                        lst_Studentfee.add(objStuFeePayment);
                    } 
                    if(lst_Studentfee.size()>0){
                        update lst_Studentfee;
                    }    
                    insert dblog;
                }
                else
                {
                    urlRefresh = 'Dont Refesh the Page.';
                }
            }
        }
        catch(exception ex)
        {
            dblog.Class_Name__c = 'FEE_BilldeskResponse_API';
            dblog.Method_Name__c = 'BilldeskRespon';
            dblog.Processing_API_Name__c = 'BillDesk';            
            dblog.Data_Received__c = responce;
            upsert dblog; 
        }
    }
    
    public static string calculateCheckSum(string mainStr){
        String testKey = Billdesk_Merchant_Details__c.getValues('Checksum').MerchantId__c;
        String algorithmName = 'hmacSHA256';
        Blob hmacData = Crypto.generateMac(algorithmName, Blob.valueOf(mainStr) , Blob.valueOf(testKey));
        //system.debug('++++'+hmacData);
        return EncodingUtil.convertToHEX(hmacData);
        
    }
    
    //Redirecting Applicants after successful Application Fee Payment
    global void updateApplicantFee()
    {
        urlRefresh = '';
        final String APPLICATION_FEE_TYPE ='Application Fee';
        Applicant_Billdesk_HomeUrl = Billdesk_Merchant_Details__c.getValues('Applicant_Billdesk_HomeUrl').MerchantId__c;
        Applicant_PortalUrl = Billdesk_Merchant_Details__c.getValues('Applicant_PortalUrl').MerchantId__c;
        //homeUrl = Billdesk_Merchant_Details__c.getValues('HomeUrl').MerchantId__c;
        // responce = apexpages.currentpage().getparameters().get('msg');
        responce = apexpages.currentpage().getparameters().get('msg');
        System.debug('inside updateapplicant fee');
        Debug_Log__c dblog = new Debug_Log__c();
        try{            
            if(responce != null)
            {
                String newStrReq = responce;
                Integer reqLen = newStrReq.split('\\|').size();
                String checkSumValue = newStrReq.split('\\|')[reqLen-1];
                String statusCode = newStrReq.split('\\|')[reqLen-12]; 
                transactionId = newStrReq.split('\\|')[reqLen-24];
                referenceId = newStrReq.split('\\|')[reqLen-25];
                refId = newStrReq.split('\\|')[reqLen-8];
                TransactionType = newStrReq.split('\\|')[reqLen-19];
                StatusErrDes = newStrReq.split('\\|')[reqLen-2];
                paymentId = transactionId;
                String noCheckSumValue = newStrReq.removeEnd(newStrReq.split('\\|')[reqLen-1]);
                String requestwithNoCheckSum = noCheckSumValue.Substring(0,noCheckSumValue.length()-1);
                List<Student_Payment__c> stuPayListUpdated = new List<Student_Payment__c>();
                List<Student_Payment__c> stuPayList = [SELECT id,Transaction_ID__c,Mode_of_Payment__c,Payment_Status__c,Payment_Date_Time__c,Payment_Mode_Type__c,
                                          Amount__c,Fee_Type__c,Contact__r.Application_Number__c,contact__r.Name,Contact__r.Country_Code__c,Reference_Id__c,
                                          Contact__r.FirstName,contact__r.record_type_name__c,Contact__r.Program_Name__c,Contact__r.School_Name__c,contact__r.Email ,Contact__r.Application_Fee_Paid__c, Contact__r.MobilePhone
                                          FROM Student_Payment__c WHERE Reference_Id__c =: referenceId];
                  if(stuPayList[0].contact__r.record_type_name__c == 'Applicant'){
                     list<hed__Application__c> applList = [Select Provisional_Admission_Fee_Paid__c, Application_Number__c from hed__Application__c
                                                where Application_Number__c =: stuPayList[0].Contact__r.Application_Number__c LIMIT 1];
                     if(applList.size() >0){
                            
                            applPAF = applList[0].Provisional_Admission_Fee_Paid__c;
                            appl = applList[0];
                        }
                  }
                FEE_TYPE=stuPayList[0].Fee_Type__c;
                applicationNumber = stuPayList[0].Contact__r.Application_Number__c;
                emailAddress = stuPayList[0].Contact__r.Email;
                if(stuPayList[0].Payment_Status__c =='Payment Link Created')
                {
                    dblog.Class_Name__c = 'FEE_BilldeskResponse_API';
                    dblog.Method_Name__c = 'updateApplicantFee';
                    dblog.Processing_API_Name__c = 'BillDesk';            
                    dblog.Data_Received__c = responce;
                    system.debug('Response'+responce);
                    for(Student_Payment__c stu : stuPayList){
                        string newCheckSum = getCalculateCheckSum(requestwithNoCheckSum);
                        
                        if(newCheckSum == checkSumValue || test.isRunningTest())
                        {  
                            if(statusCode == '0300')
                            {
                                if(TransactionType == '01')    stu.Payment_Mode_Type__c ='Netbanking';
                                else if(TransactionType == '02')  stu.Payment_Mode_Type__c ='Credit Card';
                                else if(TransactionType == '03')  stu.Payment_Mode_Type__c ='Debit Card';
                                else if(TransactionType == '04') stu.Payment_Mode_Type__c ='Cash Card';
                                else if(TransactionType == '05') stu.Payment_Mode_Type__c ='Mobile';
                                else if(TransactionType == '06')   stu.Payment_Mode_Type__c ='IMPS';
                                else if(TransactionType == '07')   stu.Payment_Mode_Type__c ='Reward Points';
                                else if(TransactionType == '08')  stu.Payment_Mode_Type__c ='Others';
                                else if(TransactionType == '09') stu.Payment_Mode_Type__c ='Others Wallet';
                                else if(TransactionType == '10')   stu.Payment_Mode_Type__c ='UPI';
                                
                                stu.Transaction_ID__c = transactionId;
                                stu.Payment_Date_Time__c = system.now();
                                stu.Payment_Status__c = 'Success';
                                if(stu.Payment_Status__c=='Success'){
                                    //stu.Contact__r.Application_Fee_Paid__c = True;  
                                    //update stu.Contact__r;
                                    stu.Payment_Gateway__c= 'Billdesk';
                                    if(stu.Amount__c != null && amount != null){
                                        amount += stu.Amount__c;
                                    } else {
                                        amount = stu.Amount__c;
                                    }
                                    //TransactionDateTime = DateTime.valueOf(DateTime.now().format('dd-MM-yyyy HH:mm:ss', 'IST'));
                                    TransactionDateTime = stu.Payment_Date_Time__c;
                                    ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');
                                    system.debug(ISTTransactionDateTime);
                                    PurposeofPayment = stu.Fee_Type__c;
                                    PaymentMode = 'Online';
                                    SuccessMsg = 'Transaction Success..!!';
                                    dblog.Status__c = 'Success';   
                                    //Invoke the methods to Generate and send the attachment
                                    if(stu.Fee_Type__c == APPLICATION_FEE_TYPE ){
                                        //Passing the paymentId(Transaction_ID__C) - as the VisualFOrce is not able to retrieve the fields updated in this class.
                                        //Hence we are passing them as parameters and using the values in the VF Controller (StudentPaymentController)
                                        Id cvId = RegistrationFormUtility.generateReceipt(stu.Id, paymentId, stu.Payment_Gateway__c);
                                        RegistrationFormUtility.sendReceipt(stu.Id, cvId); 
                                    }
                                    if(applPAF == false && stu.Fee_Type__c != APPLICATION_FEE_TYPE){
                                        List<Student_Fee__c> sf = [select id, contact__c, fee_year__c from student_fee__c
                                                                   where contact__c =: stu.Contact__c AND Fee_year__c='1st Year']; 
                                        if(!sf.isEmpty()){
                                            AdmissionsProcessUtility.generateOfflineReceipt(stu.Id,stu.Payment_Mode_Type__c,stu.Payment_Gateway__c,paymentId);
                                            
                                        } 
                                    }
                                }
                                
                                dblog.Error_Message__c = StatusErrDes; 
                                dblog.Payment_Reference_Id__c = referenceId;  
                                
                                
                            }
                            else if(statusCode == '0002')
                            {
                                if(TransactionType == '01')  stu.Payment_Mode_Type__c ='Netbanking';
                                else if(TransactionType == '02') stu.Payment_Mode_Type__c ='Credit Card';
                                else if(TransactionType == '03') stu.Payment_Mode_Type__c ='Debit Card';
                                else if(TransactionType == '04')  stu.Payment_Mode_Type__c ='Cash Card';
                                else if(TransactionType == '05') stu.Payment_Mode_Type__c ='Mobile';
                                else if(TransactionType == '06') stu.Payment_Mode_Type__c ='IMPS';
                                else if(TransactionType == '07') stu.Payment_Mode_Type__c ='Reward Points';
                                else if(TransactionType == '08')  stu.Payment_Mode_Type__c ='Others';
                                else if(TransactionType == '09') stu.Payment_Mode_Type__c ='Others Wallet';
                                else if(TransactionType == '10') stu.Payment_Mode_Type__c ='UPI';
                                
                                stu.Transaction_ID__c = transactionId;
                                stu.Payment_Date_Time__c = system.now();
                                stu.Payment_Status__c = 'Pending';
                                stu.Payment_Gateway__c= 'Billdesk';
                                amount += stu.Amount__c;
                                TransactionDateTime = stu.Payment_Date_Time__c;
                                ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');                                
                                PaymentMode = 'Online';
                                PurposeofPayment = stu.Fee_Type__c;
                                SuccessMsg = 'Transaction Pending..!!';
                                dblog.Status__c = 'Pending';     
                                dblog.Error_Message__c = StatusErrDes;
                                dblog.Payment_Reference_Id__c = referenceId;      
                            }
                            else{
                                stu.Transaction_ID__c = transactionId;
                                stu.Payment_Date_Time__c = system.now();
                                stu.Payment_Status__c = 'Failed';
                                stu.Payment_Gateway__c= 'Billdesk';
                                amount += stu.Amount__c;
                                TransactionDateTime = stu.Payment_Date_Time__c;
                                ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');
                                
                                PurposeofPayment = stu.Fee_Type__c;
                                StatusDescription  = StatusErrDes;                            
                                PaymentMode = 'Online';
                                SuccessMsg = 'Transaction Failed..!!';                        
                                dblog.Status__c = 'Failure';
                                dblog.Error_Message__c = StatusErrDes; 
                                dblog.Payment_Reference_Id__c = referenceId;
                                
                                
                                
                            }
                            
                        }
                        else{
                            
                            stu.Transaction_ID__c = transactionId;
                            stu.Payment_Date_Time__c = system.now();
                            stu.Payment_Status__c = 'Failed';
                            stu.Payment_Gateway__c= 'Billdesk';
                            SuccessMsg = 'Failed.CheckSum Not Matched..!!';
                            dblog.Status__c = 'Failure';
                            dblog.Error_Message__c = StatusErrDes; 
                            dblog.Payment_Reference_Id__c = referenceId;
                        }
                        stuPayListUpdated.add(stu);
                    }
                    if(stuPayListUpdated.size() > 0){
                        update stuPayListUpdated;
                    }
                    list<Student_Fee_Payment__c> lst_Studentfee = new list<Student_Fee_Payment__c>();
                    for(Student_Fee_Payment__c objStuFeePayment : [Select Id,Name,Amount__c,Mode_of_Payment__c,Payment_Link_Id__c,SF_Transaction_ID__c,Student_Fee__c,Line_Item_Payment_Status__c,
                                                                   Student_Payment__c,Transaction_Date_Time__c,Payment_Mode_Type__c from Student_Fee_Payment__c  where
                                                                   Reference_Id__c =: referenceId])
                    {
                        objStuFeePayment.Line_Item_Payment_Status__c = stuPayList[0].Payment_Status__c;
                        objStuFeePayment.SF_Transaction_ID__c = transactionId;
                        objStuFeePayment.Transaction_Date_Time__c = system.now();
                        objStuFeePayment.Payment_Mode_Type__c = stuPayList[0].Payment_Mode_Type__c;               
                        lst_Studentfee.add(objStuFeePayment);
                    } 
                    if(lst_Studentfee.size()>0){
                        update lst_Studentfee;
                    }    
                    insert dblog;
                    // Sending Receipt for 1st Year Provisional Admission Fee paid as True
                } //pending status code here...
                if(stuPayList[0].Payment_Status__c =='Pending')
                {
                    dblog.Class_Name__c = 'FEE_BilldeskResponse_API';
                    dblog.Method_Name__c = 'updateApplicantFee';
                    dblog.Processing_API_Name__c = 'BillDesk';            
                    dblog.Data_Received__c = responce;
                    for(Student_Payment__c stu : stuPayList){
                        string newCheckSum = getCalculateCheckSum(requestwithNoCheckSum);
                        
                        if(newCheckSum == checkSumValue || test.isRunningTest())
                        {  
                            if(statusCode == '0300')
                            {
                                if(TransactionType == '01')    stu.Payment_Mode_Type__c ='Netbanking';
                                else if(TransactionType == '02')  stu.Payment_Mode_Type__c ='Credit Card';
                                else if(TransactionType == '03')  stu.Payment_Mode_Type__c ='Debit Card';
                                else if(TransactionType == '04') stu.Payment_Mode_Type__c ='Cash Card';
                                else if(TransactionType == '05') stu.Payment_Mode_Type__c ='Mobile';
                                else if(TransactionType == '06')   stu.Payment_Mode_Type__c ='IMPS';
                                else if(TransactionType == '07')   stu.Payment_Mode_Type__c ='Reward Points';
                                else if(TransactionType == '08')  stu.Payment_Mode_Type__c ='Others';
                                else if(TransactionType == '09') stu.Payment_Mode_Type__c ='Others Wallet';
                                else if(TransactionType == '10')   stu.Payment_Mode_Type__c ='UPI';
                                
                                stu.Transaction_ID__c = transactionId;
                                stu.Payment_Date_Time__c = system.now();
                                stu.Payment_Status__c = 'Success';
                                if(stu.Payment_Status__c=='Success'){
                                    //stu.Contact__r.Application_Fee_Paid__c = True;  
                                    //update stu.Contact__r;
                                    stu.Payment_Gateway__c= 'Billdesk';
                                    if(stu.Amount__c != null && amount != null){
                                        amount += stu.Amount__c;
                                        System.debug('amount421' + amount);
                                    } else {
                                        amount = stu.Amount__c;
                                        System.debug('amount424' + amount);
                                    }
                                    //TransactionDateTime = DateTime.valueOf(DateTime.now().format('dd-MM-yyyy HH:mm:ss', 'IST'));
                                    TransactionDateTime = stu.Payment_Date_Time__c;
                                    ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');
                                    system.debug(ISTTransactionDateTime);
                                    PurposeofPayment = stu.Fee_Type__c;
                                    PaymentMode = 'Online';
                                    SuccessMsg = 'Transaction Success..!!';
                                    dblog.Status__c = 'Success';   
                                    //Invoke the methods to Generate and send the attachment
                                    if(stu.Fee_Type__c == APPLICATION_FEE_TYPE ){
                                        //Passing the paymentId(Transaction_ID__C) - as the VisualFOrce is not able to retrieve the fields updated in this class.
                                        //Hence we are passing them as parameters and using the values in the VF Controller (StudentPaymentController)
                                        Id cvId = RegistrationFormUtility.generateReceipt(stu.Id, paymentId, stu.Payment_Gateway__c);
                                        RegistrationFormUtility.sendReceipt(stu.Id, cvId); 
                                    }
                                    System.debug('applPAF' + applPAF + '\nstu.Fee_Type__c' + stu.Fee_Type__c);
                                    if(applPAF == false && stu.Fee_Type__c != APPLICATION_FEE_TYPE){
                                        List<Student_Fee__c> sf = [select id, contact__c, Amount_Paid__c, Amount_Pending__c, Amount__c, 
                                                                   fee_year__c from student_fee__c
                                                                   where contact__c =: stu.Contact__c AND Fee_year__c='1st Year']; 
                                        System.debug('sf' + sf);
                                        for(Student_Fee__c  s : sf){
                                            sf1.add(s.id);
                                        }
                                        if(!sf.isEmpty()){
                                            AdmissionsProcessUtility.generateOfflineReceipt(stu.Id,stu.Payment_Mode_Type__c,stu.Payment_Gateway__c,paymentId);
                                            FEE_StudentFeeTriggerHandler.updateStudentFeePending(sf1);
                                        } 
                                    }
                                }
                                
                                dblog.Error_Message__c = StatusErrDes; 
                                dblog.Payment_Reference_Id__c = referenceId;  
                                
                                
                            }
                            else if(statusCode == '0002')
                            {
                                if(TransactionType == '01')  stu.Payment_Mode_Type__c ='Netbanking';
                                else if(TransactionType == '02') stu.Payment_Mode_Type__c ='Credit Card';
                                else if(TransactionType == '03') stu.Payment_Mode_Type__c ='Debit Card';
                                else if(TransactionType == '04')  stu.Payment_Mode_Type__c ='Cash Card';
                                else if(TransactionType == '05') stu.Payment_Mode_Type__c ='Mobile';
                                else if(TransactionType == '06') stu.Payment_Mode_Type__c ='IMPS';
                                else if(TransactionType == '07') stu.Payment_Mode_Type__c ='Reward Points';
                                else if(TransactionType == '08')  stu.Payment_Mode_Type__c ='Others';
                                else if(TransactionType == '09') stu.Payment_Mode_Type__c ='Others Wallet';
                                else if(TransactionType == '10') stu.Payment_Mode_Type__c ='UPI';
                                
                                stu.Transaction_ID__c = transactionId;
                                stu.Payment_Date_Time__c = system.now();
                                stu.Payment_Status__c = 'Pending';
                                stu.Payment_Gateway__c= 'Billdesk';
                                amount += stu.Amount__c;
                                TransactionDateTime = stu.Payment_Date_Time__c;
                                ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');                                
                                PaymentMode = 'Online';
                                PurposeofPayment = stu.Fee_Type__c;
                                SuccessMsg = 'Transaction Pending..!!';
                                dblog.Status__c = 'Pending';     
                                dblog.Error_Message__c = StatusErrDes;
                                dblog.Payment_Reference_Id__c = referenceId;      
                            }
                            else{
                                stu.Transaction_ID__c = transactionId;
                                stu.Payment_Date_Time__c = system.now();
                                stu.Payment_Status__c = 'Failed';
                                stu.Payment_Gateway__c= 'Billdesk';
                                amount += stu.Amount__c;
                                TransactionDateTime = stu.Payment_Date_Time__c;
                                ISTTransactionDateTime = TransactionDateTime.format('dd-MM-yyyy HH:mm:ss', 'IST');                                
                                PurposeofPayment = stu.Fee_Type__c;
                                StatusDescription  = StatusErrDes;                            
                                PaymentMode = 'Online';
                                SuccessMsg = 'Transaction Failed..!!';                        
                                dblog.Status__c = 'Failure';
                                
                                dblog.Error_Message__c = StatusErrDes; 
                                dblog.Payment_Reference_Id__c = referenceId;
                                
                                
                                
                            }
                            
                        }
                        else{
                            
                            stu.Transaction_ID__c = transactionId;
                            stu.Payment_Date_Time__c = system.now();
                            stu.Payment_Status__c = 'Failed';
                            stu.Payment_Gateway__c= 'Billdesk';
                            SuccessMsg = 'Failed.CheckSum Not Matched..!!';
                            dblog.Status__c = 'Failure';
                            dblog.Error_Message__c = StatusErrDes; 
                            dblog.Payment_Reference_Id__c = referenceId;
                        }
                        stuPayListUpdated.add(stu);
                    }
                    if(stuPayListUpdated.size() > 0){
                        update stuPayListUpdated;
                    }
                    list<Student_Fee_Payment__c> lst_Studentfee = new list<Student_Fee_Payment__c>();
                    for(Student_Fee_Payment__c objStuFeePayment : [Select Id,Name,Amount__c,Mode_of_Payment__c,Payment_Link_Id__c,SF_Transaction_ID__c,Student_Fee__c,Line_Item_Payment_Status__c,
                                                                   Student_Payment__c,Transaction_Date_Time__c,Payment_Mode_Type__c from Student_Fee_Payment__c  where
                                                                   Reference_Id__c =: referenceId])
                    {
                        objStuFeePayment.Line_Item_Payment_Status__c = stuPayList[0].Payment_Status__c;
                        objStuFeePayment.SF_Transaction_ID__c = transactionId;
                        objStuFeePayment.Transaction_Date_Time__c = system.now();
                        objStuFeePayment.Payment_Mode_Type__c = stuPayList[0].Payment_Mode_Type__c;               
                        lst_Studentfee.add(objStuFeePayment);
                    } 
                    if(lst_Studentfee.size()>0){
                        update lst_Studentfee;
                    }    
                    insert dblog;
                    // Sending Receipt for 1st Year Provisional Admission Fee paid as True
                }
                else
                {
                    urlRefresh = 'Dont Refesh the Page.';
                }
            }
        }
        catch(Exception e)
        {
            dblog.Class_Name__c = 'FEE_BilldeskResponse_API';
            dblog.Method_Name__c = 'updateApplicantFeeFromCatch'; //+e.getLineNumber() + e.getMessage()
            dblog.Processing_API_Name__c = 'BillDesk';            
            dblog.Data_Received__c = responce;
            //System.debug('The following exception has occurred: ' + e.getMessage());
            upsert dblog; 
        }
    }
    
    public static string getCalculateCheckSum(string mainStr){
        String testKey = Billdesk_Merchant_Details__c.getValues('Checksum').MerchantId__c;
        String algorithmName = 'hmacSHA256';
        Blob hmacData = Crypto.generateMac(algorithmName, Blob.valueOf(mainStr) , Blob.valueOf(testKey));
        //system.debug('++++'+hmacData);
        return EncodingUtil.convertToHEX(hmacData);
        
    }
    
}