force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Integrated_with_SAP__c.field-meta.xml
<CustomField>
    <fullName>Integrated_with_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integrated with SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Line_Item_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Push_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>Push_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SAP_OnlineAPI_Batch.cls
global class SAP_OnlineAPI_Batch implements Schedulable,Database.Batchable<sObject>, Database.AllowsCallouts {
     global static final Date specificDate = Date.newInstance(2023, 11, 7);
    global Database.QueryLocator start(Database.BatchableContext bc) {
          
        return Database.getQueryLocator([SELECT Id, Name,Line_Item_Payment_Status__c,Push_to_SAP__c,CreatedDate,
                                         Integrated_with_SAP__c,Mode_of_Payment__c FROM Student_Fee_Payment__c
                                        WHERE Mode_of_Payment__c    = 'Online' AND Line_Item_Payment_Status__c = 'Success'
                                         AND Integrated_with_SAP__c = false AND CreatedDate >=: specificDate]);
    }
    
    global void execute(Database.BatchableContext bc, List<Student_Fee_Payment__c> lst_Std_Fee_Payments) {
        list<Id> lst_Std_Fee_Pay_Ids = new List<Id>();
        
        for(Student_Fee_Payment__c objStdFeePayments:lst_Std_Fee_Payments){
            lst_Std_Fee_Pay_Ids.add(objStdFeePayments.Id);
        }
        if(!lst_Std_Fee_Pay_Ids.isEmpty())
        {
            SAP_OnlineAPI_BatchHandler.OnlineAPIMethod(lst_Std_Fee_Pay_Ids);
        }
    }
    
    global void execute(SchedulableContext ctx){
        // execute Schedule Class
        Database.executeBatch(new SAP_OnlineAPI_Batch(),30);
    }
    
    global void finish(Database.BatchableContext bc) {
        // execute any post-processing operations - send emails, notify clients,
    }
}