force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Line_Item_Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Payment_Gateway__c</fullName>
    <label>Payment Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Razorpay</fullName>
            </value>
            <value>
                <fullName>Eazypay</fullName>
            </value>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>Billdesk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Line_Item_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/SF_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>SF_Transaction_ID__c</fullName>
    <label>SF Transaction ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Transaction_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date_Time__c</fullName>
    <label>Transaction Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>RazorPay</fullName>
                <isActive>false</isActive>
                <label>RazorPay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date_Time__c</fullName>
    <label>Payment Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <label>Payment Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Razorpay</fullName>
            </value>
            <value>
                <fullName>Eazypay</fullName>
            </value>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>Billdesk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Transaction_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date_Time__c</fullName>
    <label>Transaction Date Time(Technical)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateStudentFeePaymentBatch.cls
global class UpdateStudentFeePaymentBatch implements Database.Batchable<SObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        // Return a QueryLocator that retrieves up to 50 million records in batches
        String query = 'SELECT Id, Line_Item_Payment_Gateway__c, Transaction_Date_Time__c,Amount__c, SF_Transaction_ID__c, Student_Payment__c,Student_Payment__r.Transaction_ID__c ' + 
                       'FROM Student_Fee_Payment__c ' +
                       'WHERE Line_Item_Payment_Status__c = \'Success\' ' + 
                       'AND Student_Payment__r.Mode_of_Payment__c = \'Online\' ' + 
                       'AND Student_Payment__r.Payment_Date_Time__c > 2024-01-01T11:22:11.000+0000';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Student_Fee_Payment__c> scope) {
        Set<Id> studentPaymentIds = new Set<Id>();
        
        for(Student_Fee_Payment__c feePayment : scope) {
            studentPaymentIds.add(feePayment.Student_Payment__c);
        }
        
        Map<Id, Student_Payment__c> studentPaymentMap = new Map<Id, Student_Payment__c>([SELECT Id, Payment_Gateway__c, Payment_Date_Time__c, Transaction_ID__c,Amount__c 
                                                                                        FROM Student_Payment__c 
                                                                                        WHERE Id IN :studentPaymentIds]);

        List<Student_Fee_Payment__c> updatedFeePayments = new List<Student_Fee_Payment__c>();

        for(Student_Fee_Payment__c feePayment : scope) {
            Student_Payment__c studentPayment = studentPaymentMap.get(feePayment.Student_Payment__c);
            
            if(studentPayment != null) {
                if(feePayment.Line_Item_Payment_Gateway__c == null) {
                    feePayment.Line_Item_Payment_Gateway__c = studentPayment.Payment_Gateway__c;
                }
                if(feePayment.SF_Transaction_ID__c == null) {
                    feePayment.SF_Transaction_ID__c = studentPayment.Transaction_ID__c;
                }
                if(feePayment.Amount__c == null) {
                    feePayment.Amount__c = studentPayment.Amount__c;
                }
                if(feePayment.Transaction_Date_Time__c == null) {
                    feePayment.Transaction_Date_Time__c = studentPayment.Payment_Date_Time__c;
                }
                
                updatedFeePayments.add(feePayment);
            }
        }

        if(updatedFeePayments.size() > 0) {
            update updatedFeePayments;
        }
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Batch processing completed.');
    }
}