force-app/main/default/objects/Staff_Quarters_Request__c/Staff_Quarters_Request__c.object-meta.xml
<CustomObject>
    <label>Staff Quarters Request</label>
    <nameField>
        <displayFormat>SREQ-{0000000}</displayFormat>
        <label>Staff Quarters Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff Quarters Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff_Quarters_Request__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Staff_Quarters_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Room Allotted</fullName>
            </value>
            <value>
                <fullName>Request Submitted</fullName>
                <default>true</default>
                <label>Request Submitted</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Vacation Initiated</fullName>
                <label>Vacating Initiated</label>
            </value>
            <value>
                <fullName>Vacation Completed</fullName>
                <label>Vacating Completed</label>
            </value>
            <value>
                <fullName>Vacation Approved</fullName>
                <label>Vacating Approved</label>
            </value>
            <value>
                <fullName>Vacation Rejected</fullName>
                <label>Vacating Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Staff_Quarters_Request__c/fields/Vacation_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Date__c</fullName>
    <label>Vacating Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Staff_Quarters_Request__c/fields/Vacation_Initiated_Date__c.field-meta.xml
<CustomField>
    <fullName>Vacation_Initiated_Date__c</fullName>
    <label>Vacating Initiated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/VacationRequestController.cls
public with sharing class VacationRequestController {
    @AuraEnabled
    public static String updateVacationRequest(Date vacateDate,  Id staffQuartersRequestId, string selectedVacateReason) {
        System.debug('vacateDate**********'+vacateDate);
        try {
            Staff_Quarters_Request__c requestToUpdate = new Staff_Quarters_Request__c();
            requestToUpdate = [SELECT id, Name, Vacation_Date__c, Vacation_Initiated_Date__c, Status__c FROM Staff_Quarters_Request__c WHERE id =: staffQuartersRequestId LIMIT 1];
            requestToUpdate.Vacation_Initiated_Date__c = Date.today();
            requestToUpdate.Vacation_Date__c = vacateDate;
            requestToUpdate.Status__c = 'Vacation Initiated';
            requestToUpdate.Cancellation_Reason__c = selectedVacateReason;
            update requestToUpdate;
            
            return 'Success';
        } catch (Exception ex) {
            return 'Error: ' + ex.getMessage();
        }
    }
    @AuraEnabled
    //Confirmation mail sending to Teaching and non-teaching profile users
    public static string sendConfirmationEmail(String userId){
        
        User recipient = [SELECT Email FROM User where id =:userId LIMIT 1];
        
        EmailTemplate emailTemplate = [SELECT Id,Subject FROM EmailTemplate WHERE DeveloperName = 'Vacation_Approval' LIMIT 1];
        
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[]{recipient.Email});
        email.setTemplateId(emailTemplate.Id);
        email.setSubject(emailTemplate.Subject);
        
        //  email.setTargetObjectId(recipientId);
        email.setSaveAsActivity(false);
        email.setPlainTextBody('Vacation request for has been approved.');
        
        Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
        return 'successful';
    }
}