force-app/main/default/objects/Alumni_Registration__c/Alumni_Registration__c.object-meta.xml
<CustomObject>
    <label>Alumni Registration</label>
    <nameField>
        <label>SRN Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Alumni Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Alumni_Registration__c/fields/Confirm_Validation__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Validation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirm Validation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Alumni_Registration__c/fields/Course_Pursued__c.field-meta.xml
<CustomField>
    <fullName>Course_Pursued__c</fullName>
    <label>Course Pursued</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alumni_Registration__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alumni_Registration__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alumni_Registration__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diploma in HR Analytics</fullName>
            </value>
            <value>
                <fullName>Master of Science in Artificial Intelligence</fullName>
            </value>
            <value>
                <fullName>Master of Science in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Master of Science in Cloud Architecture and Security</fullName>
            </value>
            <value>
                <fullName>Master of Science in Cyber Security</fullName>
            </value>
            <value>
                <fullName>MBA in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Artificial Intelligence</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Cloud Architecture and Security</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Finance</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Health care Management</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Human Resource</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Marketing</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Operations Management</fullName>
            </value>
            <value>
                <fullName>Ph.D in Management Studies</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Entrepreneurship</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Strategic Leadership</fullName>
            </value>
            <value>
                <fullName>Ph.D in Biochemistry</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Biochemistry and Microbiology</fullName>
            </value>
            <value>
                <fullName>Bachelor of Physiotherapy</fullName>
            </value>
            <value>
                <fullName>Master of Science in Biochemistry</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Sports Science</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Nutrition and Dietetics</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Medical Laboratory Technology</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Medical Radiology and Diagnostic Imaging</fullName>
            </value>
            <value>
                <fullName>Intensive Certificate Course (ICC) in Laser Assisted Hatching and Embryo Biopsy</fullName>
            </value>
            <value>
                <fullName>PGD in Clinical Embryology and Assisted Reproductive Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Alumni_Registration__c/fields/Specialization__c.field-meta.xml
<CustomField>
    <fullName>Specialization__c</fullName>
    <label>Specialization</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Alumni_Registration__c/fields/Year_of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Graduation__c</fullName>
    <label>Year of Graduation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2004</fullName>
            </value>
            <value>
                <fullName>2005</fullName>
            </value>
            <value>
                <fullName>2006</fullName>
            </value>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ALU_Registr_Component_CMP_Ctrlr_Test.cls
@isTest
public class ALU_Registr_Component_CMP_Ctrlr_Test {
    
    @isTest
    static void testMethod1(){
        Alumni_Registration__c objAl = new Alumni_Registration__c();
        objAl.Course_Pursued__c =  'mexch';
        objAl.DOB__c = system.today(); 
        objAl.Email__c='asdf123@gmail.com';
        objAl.Mobile__c = '9876543212'; 
        objAl.Marital_Status__c =  'Single';
        //objAl.Specialization__c = 'Specializa';
        //objAl.Year_of_Graduation__c =10;
        objAl.Gender__c = 'Male';
        objAl.Name = 'Test';
        objAl.Name__c ='Testing';
        objAl.Program__c = 'Master of Business Administration in Marketing';
        //objAl.Confirm_Validation__c = false;
        Insert objAl;
        
        Test.startTest();
        ALU_Registr_Component_CMP_Ctrlr.getPicklistOptions();
        ALU_Registr_Component_CMP_Ctrlr.createAlumniRegistration('Test', 'asdf123@gmail.com', '9848032919', Date.newInstance(1997, 01, 01), 'Single', 'B+', 'Male', '2017', 'SRNTEST', 
                                                                 'Master of Business Administration in Marketing', 'India (+91)');
        Test.stopTest();
        system.assertEquals(objAl.Id, objAl.Id);
    }
    @isTest
    static void testMethod2(){
        Alumni_Registration__c objAl = new Alumni_Registration__c();
        objAl.Course_Pursued__c =  'mexch';
        objAl.DOB__c = system.today(); 
        objAl.Email__c='asdf123@gmail.com';
        objAl.Mobile__c = '9876543212'; 
        objAl.Marital_Status__c =  'Single';
        //objAl.Specialization__c = 'Specializa';
        //objAl.Year_of_Graduation__c =10;
        objAl.Gender__c = 'Male';
        objAl.Name = 'Test';
        objAl.Name__c ='Testing';
        objAl.Program__c = 'Master of Business Administration in Marketing';
        //objAl.Confirm_Validation__c = false;
        Insert objAl;
        
        Test.startTest();
        ALU_Registr_Component_CMP_Ctrlr.getPicklistOptions();
        ALU_Registr_Component_CMP_Ctrlr.createAlumniRegistration('Test', 'test123@gmail.com', '9848032919', Date.newInstance(1997, 01, 01), 'Single', 'B+', 'Male', '2017', 'SRNTEST', 
                                                                 'Master of Business Administration in Marketing', 'India (+91)');
        Test.stopTest();
        system.assertEquals(objAl.Id, objAl.Id);
    }
    
}