force-app/main/default/objects/RTR_Route_Master__c/RTR_Route_Master__c.object-meta.xml
<CustomObject>
    <description>This Object will store details about the Bus Routes, Pick up points and its capacity.</description>
    <label>Route Master</label>
    <nameField>
        <label>Route Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/RTR_Route_Pick_Up_Point__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the Pick up points of the route path and its related payments.</description>
    <label>Route Pick Up Point</label>
    <nameField>
        <label>Pick Up Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Pick Up Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/fields/RTR_Faculty_Fee__c.field-meta.xml
<CustomField>
    <fullName>RTR_Faculty_Fee__c</fullName>
    <label>Faculty Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/fields/rtr_If_Short_Distance__c.field-meta.xml
<CustomField>
    <fullName>rtr_If_Short_Distance__c</fullName>
    <defaultValue>false</defaultValue>
    <label>If Short Distance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/fields/RTR_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>RTR_Payment_Amount__c</fullName>
    <description>This field is used to store the pickup point amount fee which is payable by the student.</description>
    <label>Student Fee</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/fields/RTR_Route_Master__c.field-meta.xml
<CustomField>
    <fullName>RTR_Route_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Master</label>
    <referenceTo>RTR_Route_Master__c</referenceTo>
    <relationshipLabel>Route Pick Up Points</relationshipLabel>
    <relationshipName>Route_Pick_Up_Points</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTR_routePickupPointController.cls
public without sharing class RTR_routePickupPointController {
    @AuraEnabled(cacheable=true)
    public static List<RTR_Route_Pick_Up_Point__c> getPickUpPoints(String selectedValue) {
        // Query and return the related pick-up points based on the selected route path
        return [SELECT Id, Name,Amount__c,rtr_If_Short_Distance__c,RTR_Payment_Amount__c,RTR_Faculty_Fee__c FROM RTR_Route_Pick_Up_Point__c WHERE RTR_Route_Master__c = :selectedValue];
    }
}