force-app/main/default/objects/API_Setup__mdt/API_Setup__mdt.object-meta.xml
<CustomObject>
    <label>API Setup</label>
    <pluralLabel>API Setup</pluralLabel>
</CustomObject>

force-app/main/default/objects/API_Setup__mdt/fields/Endpoint_1__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_1__c</fullName>
    <label>Endpoint 1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API_Setup__mdt/fields/Endpoint_2__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_2__c</fullName>
    <inlineHelpText>If Endpoint URL is more than 255 characters, enter the remaining value in this field</inlineHelpText>
    <label>Endpoint 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/API_Setup__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
            <value>
                <fullName>PUT</fullName>
            </value>
            <value>
                <fullName>DELETE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/API_Setup__mdt/fields/Timeout__c.field-meta.xml
<CustomField>
    <fullName>Timeout__c</fullName>
    <defaultValue>120000</defaultValue>
    <inlineHelpText>Max 120000</inlineHelpText>
    <label>Timeout</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Logisys_Auth_Details__mdt/Logisys_Auth_Details__mdt.object-meta.xml
<CustomObject>
    <label>Logisys Auth Details</label>
    <pluralLabel>Logisys Auth Details</pluralLabel>
</CustomObject>

force-app/main/default/objects/Logisys_Auth_Details__mdt/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LogisysAPIUtility.cls
/*********************************************
 * This class to is Logisys API Utility
 * It has logic to query Auth Details & Endpoints related to Logisys APIs
 * In this we are mapping the Http Request with all the headers & other params
 * It's called from
 * ********************************************/

public class LogisysAPIUtility {
    public static HttpRequest mapRequest(String apiName, String jsonBody){
        
        if(!test.isRunningtest()){
        //Get API Details
        API_Setup__mdt stdProfAPI = [SELECT Endpoint_1__c,Endpoint_2__c,Method__c,Timeout__c FROM API_Setup__mdt WHERE MasterLabel =: apiName];
        String endpoint = String.isNotBlank(stdProfAPI.Endpoint_2__c) ? stdProfAPI.Endpoint_1__c+stdProfAPI.Endpoint_2__c : stdProfAPI.Endpoint_1__c;
        
        //Get Auth Details
        Logisys_Auth_Details__mdt auth = [SELECT Username__c,Password__c FROM Logisys_Auth_Details__mdt][0];
        Blob headerValue = Blob.valueOf(auth.Username__c+ ':' +auth.Password__c);
        String authHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
        
        //Map Http Request
        HttpRequest hReq = new HttpRequest();
        hReq.setHeader('Authorization', authHeader);
        hReq.setBody(jsonBody);
        hReq.setEndpoint(endpoint);
        hReq.setMethod(stdProfAPI.Method__c);                
        hReq.setTimeout((Integer)stdProfAPI.Timeout__c);
        
        return hReq;
        }
        else{
      //  String jsonBody = '{"status": "success", "data": {"resdata": [{"sem": "Semester", "examdate": "2024-05-15", "regno": "Student ID", "subshort": "COURSE001", "qpcode": "QP001", "doe": "15/05/2024", "session": "9:00 AM to 12:00 PM", "batch": "1"}]}}';
             //Map Http Request
        HttpRequest hReq = new HttpRequest();
        hReq.setHeader('Authorization', 'auth.Username__c'+ ':' +'auth.Password__c');
        hReq.setBody(jsonBody);
        hReq.setEndpoint('https://universitysolutions.in/revaapi/app.php?a=getThtimetable');
        hReq.setMethod('POST');                
        hReq.setTimeout(120000);
            return hReq;
        }
    }
}