force-app/main/default/objects/Contact/fields/Aadhar_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Card_Number__c</fullName>
    <label>Aadhar Card Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Afghan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Anguillan</fullName>
            </value>
            <value>
                <fullName>Antiguans</fullName>
            </value>
            <value>
                <fullName>Argentinean</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Barbudans</fullName>
            </value>
            <value>
                <fullName>Batswana</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bermudian</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Botswanan</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/Fee_Payment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Fee Payment Criteria</label>
    <nameField>
        <label>Fee Payment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Payment Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Billdesk__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Billdesk__c</fullName>
    <label>Merchant ID - Billdesk</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Eazypay__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Eazypay__c</fullName>
    <label>Merchant ID - Eazypay</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Paytm__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Paytm__c</fullName>
    <label>Merchant ID - Paytm</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Razorpay__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Razorpay__c</fullName>
    <label>Merchant ID - Razorpay</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nationality__c/Nationality__c.object-meta.xml
<CustomObject>
    <label>Nationality</label>
    <nameField>
        <label>Nationality (as per 10th Marksheet) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nationalities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Contact__r.Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Payment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Fee_Payment_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Payment Criteria</label>
    <referenceTo>Fee_Payment_Criteria__c</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <formula>Contact__r.SRN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SAP_DemandAPI_Test.cls
@isTest
public class SAP_DemandAPI_Test 
{ 
    public static testMethod void SAP_Demand()
    {
           string HouseholdRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Household).getRecordTypeId();
        Account objAcc = FEE_TestDataFactory.CreateAccount('Test Account',HouseholdRecId);
        objAcc.Recordtypeid = HouseholdRecId;
        Insert objAcc;
        
        string StudentRecId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(Utility.Contact_RecType_Student).getRecordTypeId();
        Contact objCon = FEE_TestDataFactory.createContact('Test',objAcc.Id);
        objCon.MobilePhone ='9090909090';
        objCon.Aadhar_Card_Number__c ='098765435612';
        objCon.RecordTypeId = StudentRecId;
        objCon.AccountId = objAcc.Id;
        objcon.Application_Number__c = 'test123';
        objcon.SRN_Number__c ='123';
        objcon.hed__WorkEmail__c  = 'test123@reva.edu.in';
        objcon.Nationality__c ='Indian';
        Insert objCon; 
        
        Fee_Payment_Criteria__c objFeeCriteria = FEE_TestDataFactory.createFeePaymentCriteria('Tuition Fee','Full Payment');
        objFeeCriteria.Merchant_ID_Billdesk__c ='MIDB232323';
        objFeeCriteria.Merchant_ID_Eazypay__c ='MIDE121212';
        objFeeCriteria.Merchant_ID_Paytm__c ='MIDP343434';
        objFeeCriteria.Merchant_ID_Razorpay__c='MIDR4454545';
        Insert objFeeCriteria;
        
        hed__Program_Enrollment__c objProgenroll = FEE_TestDataFactory.createProgramEnrollment(objCon.Id,null);
        Insert objProgenroll;
        
        Student_Fee__c objStudentFee = FEE_TestDataFactory.createStudentFee(objFeeCriteria.Id, objCon.Id,'Hostel Fee');        //'Academic Fee');
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        Insert objStudentFee;
        
        
        update objStudentFee;
        
        List<id> lst_studentFeeIdsc = new List<id>();
        lst_studentFeeIdsc.add(objStudentFee.id);
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        SAP_DemandAPI.DemandCreationAPI(lst_studentFeeIdsc);
        Test.stopTest();
    }
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setStatus('OK');
            res.setBody('{"Response": [{"SFDCRecordId": "a0q1s000004FwQGAA0", "statusCode": 0, "SAPID": "SAP123", "responseObject": "Success"}]}');
            return res;
        }
    }

}