force-app/main/default/objects/Contact/fields/Aadhar_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Card_Number__c</fullName>
    <label>Aadhar Card Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Afghan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Anguillan</fullName>
            </value>
            <value>
                <fullName>Antiguans</fullName>
            </value>
            <value>
                <fullName>Argentinean</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Barbudans</fullName>
            </value>
            <value>
                <fullName>Batswana</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bermudian</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Botswanan</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EasyPay_Details__c/EasyPay_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>EasyPay Details</label>
</CustomObject>

force-app/main/default/objects/EasyPay_Details__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/Fee_Payment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Fee Payment Criteria</label>
    <nameField>
        <label>Fee Payment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Payment Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Billdesk__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Billdesk__c</fullName>
    <label>Merchant ID - Billdesk</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Eazypay__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Eazypay__c</fullName>
    <label>Merchant ID - Eazypay</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Paytm__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Paytm__c</fullName>
    <label>Merchant ID - Paytm</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Merchant_ID_Razorpay__c.field-meta.xml
<CustomField>
    <fullName>Merchant_ID_Razorpay__c</fullName>
    <label>Merchant ID - Razorpay</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Gateway_Error_Msg__c/Payment_Gateway_Error_Msg__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Payment Gateway Error Msg</label>
</CustomObject>

force-app/main/default/objects/Payment_Gateway_Error_Msg__c/fields/Error_Msg__c.field-meta.xml
<CustomField>
    <fullName>Error_Msg__c</fullName>
    <label>Error Msg</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Contact__r.Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Payment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Fee_Payment_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Payment Criteria</label>
    <referenceTo>Fee_Payment_Criteria__c</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Payment_Mode_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Type__c</fullName>
    <label>Payment Mode Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <formula>Contact__r.SRN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Payment_Mode_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Type__c</fullName>
    <inlineHelpText>Debit Card / Credit Card / Netbanking / UPI</inlineHelpText>
    <label>Payment Mode Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Payment_Gateway__c</fullName>
    <label>Payment Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Razorpay</fullName>
            </value>
            <value>
                <fullName>Eazypay</fullName>
            </value>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>Billdesk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Mode_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Type__c</fullName>
    <label>Payment Mode Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>Transaction_ID__c</fullName>
    <label>Transaction ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FEE_EazyPayS2SResponse_API_Test.cls
@IsTest
public class FEE_EazyPayS2SResponse_API_Test {
    public static testmethod void EazyPayResponse(){
    
        EasyPay_Details__c easypaydetails = new EasyPay_Details__c();
        easypaydetails.Value__c ='1311140119601518';
        easypaydetails.name ='AES key';
        insert easypaydetails;
        
        Payment_Gateway_Error_Msg__c objpayGateway = new Payment_Gateway_Error_Msg__c();
        objpayGateway.Error_Msg__c ='Success';
        objpayGateway.Name='Eazypay-E000';
        objpayGateway.Status__c ='Success';
        insert objpayGateway;
    
        string HouseholdRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Household).getRecordTypeId();
        Account objAcc = FEE_TestDataFactory.CreateAccount('Test Account',HouseholdRecId);
        objAcc.Recordtypeid = HouseholdRecId;
        Insert objAcc;
        
        string StudentRecId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(Utility.Contact_RecType_Student).getRecordTypeId();
        Contact objCon = FEE_TestDataFactory.createContact('Test',objAcc.Id);
        objCon.MobilePhone ='9090909090';
        objCon.Aadhar_Card_Number__c ='098765435612';
        objCon.RecordTypeId = StudentRecId;
        objCon.AccountId = objAcc.Id;
        objcon.Application_Number__c = 'test123';
        objcon.SRN_Number__c ='123';
        objcon.hed__WorkEmail__c  = 'test123@reva.edu.in';
        objcon.Nationality__c ='Indian';
        Insert objCon; 
        
        Fee_Payment_Criteria__c objFeeCriteria = FEE_TestDataFactory.createFeePaymentCriteria('Tuition Fee','Full Payment');
        objFeeCriteria.Merchant_ID_Billdesk__c ='MIDB232323';
        objFeeCriteria.Merchant_ID_Eazypay__c ='MIDE121212';
        objFeeCriteria.Merchant_ID_Paytm__c ='MIDP343434';
        objFeeCriteria.Merchant_ID_Razorpay__c='MIDR4454545';
        Insert objFeeCriteria;
        
        hed__Program_Enrollment__c objProgenroll = FEE_TestDataFactory.createProgramEnrollment(objCon.Id,null);
        Insert objProgenroll;
        
        Student_Fee__c objStudentFee = FEE_TestDataFactory.createStudentFee(objFeeCriteria.Id, objCon.Id,'Hostel Fee');        //'Academic Fee');
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = FEE_TestDataFactory.createStudentPayment(objCon.Id);
        objStuPayment.Payment_Status__c ='Payment Link Created';
        objStuPayment.Transaction_ID__c = 'PaymentId';
        objStuPayment.Payment_Mode_Type__c=  'Online';
        objStuPayment.Payment_Gateway__c = 'Eazypay';
        objStuPayment.Amount__c = 100000;
        objStuPayment.Reference_Id__c ='84757976';
      //  objStuPayment.Payment_Link_Id__c = 'plink_KlkrGKBqAUFbTD';
        //objStuPayment.Mode_of_Payment__c = 'Online';
        
        insert objStuPayment;
        
        Student_Fee_Payment__c objStuFeePay = FEE_TestDataFactory.CreateStudentFeePayment(objStudentFee.id, objStuPayment.id);
        objStuFeePay.Line_Item_Payment_Status__c = 'Success';
        objStuFeePay.Amount__c=1000;
        objStuFeePay.Mode_of_Payment__c='Online';
        objStuFeePay.SF_Transaction_ID__c= 'Test213';
        objStuFeePay.Transaction_Date_Time__c  = system.now();
        objStuFeePay.Reference_Id__c = '84757976';
    //    objStuFeePay.Payment_Link_Id__c ='plink_KlkrGKBqAUFbTD';
        insert objStuFeePay;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/EPS2SRes'; 
        req.httpMethod = 'POST';
        string JSONbody = 'vhFxy8YKG0HlGpPZ4YMSokWuch1JbPvf3B45RVUSbwSU39pty2Rn2QPAJOMSLCYpsdQp6mZoCos9';
        JSONbody += '8BHdUCw0YmXJ+cExFa9vuxcNeO2tlPfgkOJOuY7208yqM3lwCNiATx9pJQMri2aIcxUNT8IceIWv';
        JSONbody += 'xs8flkU0gKO3UYY0GlgZIquuDgOcTKfxdQR2eDWbi3rmIrT3lBnJTUU6eNYDPKc3Cgl9B7YlyQyd';
        JSONbody += 'ox/kTN4XDIzYPKWF1+NLPKGbotByjalnWGuhYJ9447uB3h7NnPCIhmfw+F4uPiIA1A8lcmhWVY4R';
        JSONbody += 'TLSoiyZxaeCSChmf1Bw1WMRMr+a45FT5/QKT6SnC7vnXiqlUfHrXzEXvVrtcRdMIgcp0C1QFYZWJ';
        JSONbody += '8nk+TsDYJ55naybmhPiUrqhGgsf7l8rE6j7E4yrKYnGfpIWQkQS6LnmIIvrfNd37eC2hpf3X/qXq';
        JSONbody += 'It7y1Kz4aPCzay/VtPzbxCrRszT9wqUCAyIORWJuER7fdHPBSdl7WR5MRztPho2AXiPMaRaKSxWv';
        JSONbody += 'TM1zn6DT//FVH83sbzAjf9IhuL5r56seDFtWqaeqKMJDJCk6g5x/LMYPo7NydysZSkhg06pvA5hN';
        JSONbody += '0WIYKf38z4BUIWxyM2V/JxI5ezDRUbXdlcxHwcsdWJWP1241UXouD2fvRBiNePDg3D6oQMFyt/GT';
        JSONbody += 'e0jL7oSBi7VzVPiv3w1xDGWJx9Vb1b5Cl1VSaDMVLdubkF1mUzsRVR2+qpbXY+arhbyRA4ydlII0';
        JSONbody += 'Mw4coEqP4Gf/DumOkK6JcPC0Qe0Sf+6QTGic5+fGtjNli3wHpA8KGo16lI5cbl9P7/Dcs0cK/wiY';
        JSONbody += 'VFkFRTslHb9RAZPfRS9lNbf+bTlsglLQI1HPMFT+9aWbzMd9OktJWiglDNgHjme2PR+kFyE4s+6q';
        JSONbody += 'mfCTeuFXCBLNqCGxlfKiyXgKpc2XVgIco3djTSHOzSbxWyJOAVcx16FlVhAbpVpZhs+P3CbiFoqu';
        JSONbody += 'F7f7qzfbB/JFTA/M3Cch2w52TND1PkBSBHA/rdRGMrmdLB7MBOBTdXdTbqDHN3V6zndcy7Or546u';
        JSONbody += 'J6KJ5qQH1um3IFKOYw+XqIvT/HxkT+spHoBaxJNGlNfqMB3Cluq/xRTknGpmBGR+KBA=';
        
        req.requestBody =  Blob.valueOf(JSONbody);
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        FEE_EazyPayS2SResponse_API.ReceivedData();
        Test.stopTest();
    }
    public static testmethod void EazyPayResponse1(){
        EasyPay_Details__c easypaydetails = new EasyPay_Details__c();
        easypaydetails.Value__c ='1311140119601518';
        easypaydetails.name ='AES key';
        insert easypaydetails;
        
        Payment_Gateway_Error_Msg__c objpayGateway = new Payment_Gateway_Error_Msg__c();
        objpayGateway.Error_Msg__c ='Success';
        objpayGateway.Name='Eazypay-E000';
        objpayGateway.Status__c ='Success';
        insert objpayGateway;
    
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/EPS2SRes'; 
        req.httpMethod = 'POST';
        string JSONbody = 'vhFxy8YKG0HlGpPZ4YMSokWuch1JbPvf3B45RVUSbwSU39pty2Rn2QPAJOMSLCYpsdQp6mZoCos9';
        JSONbody += '8BHdUCw0YmXJ+cExFa9vuxcNeO2tlPfgkOJOuY7208yqM3lwCNiATx9pJQMri2aIcxUNT8IceIWv';
        JSONbody += 'xs8flkU0gKO3UYY0GlgZIquuDgOcTKfxdQR2eDWbi3rmIrT3lBnJTUU6eNYDPKc3Cgl9B7YlyQyd';
        JSONbody += 'ox/kTN4XDIzYPKWF1+NLPKGbotByjalnWGuhYJ9447uB3h7NnPCIhmfw+F4uPiIA1A8lcmhWVY4R';
        JSONbody += 'TLSoiyZxaeCSChmf1Bw1WMRMr+a45FT5/QKT6SnC7vnXiqlUfHrXzEXvVrtcRdMIgcp0C1QFYZWJ';
        JSONbody += '8nk+TsDYJ55naybmhPiUrqhGgsf7l8rE6j7E4yrKYnGfpIWQkQS6LnmIIvrfNd37eC2hpf3X/qXq';
        JSONbody += 'It7y1Kz4aPCzay/VtPzbxCrRszT9wqUCAyIORWJuER7fdHPBSdl7WR5MRztPho2AXiPMaRaKSxWv';
        JSONbody += 'TM1zn6DT//FVH83sbzAjf9IhuL5r56seDFtWqaeqKMJDJCk6g5x/LMYPo7NydysZSkhg06pvA5hN';
        JSONbody += '0WIYKf38z4BUIWxyM2V/JxI5ezDRUbXdlcxHwcsdWJWP1241UXouD2fvRBiNePDg3D6oQMFyt/GT';
        JSONbody += 'e0jL7oSBi7VzVPiv3w1xDGWJx9Vb1b5Cl1VSaDMVLdubkF1mUzsRVR2+qpbXY+arhbyRA4ydlII0';
        JSONbody += 'Mw4coEqP4Gf/DumOkK6JcPC0Qe0Sf+6QTGic5+fGtjNli3wHpA8KGo16lI5cbl9P7/Dcs0cK/wiY';
        JSONbody += 'VFkFRTslHb9RAZPfRS9lNbf+bTlsglLQI1HPMFT+9aWbzMd9OktJWiglDNgHjme2PR+kFyE4s+6q';
        JSONbody += 'mfCTeuFXCBLNqCGxlfKiyXgKpc2XVgIco3djTSHOzSbxWyJOAVcx16FlVhAbpVpZhs+P3CbiFoqu';
        JSONbody += 'F7f7qzfbB/JFTA/M3Cch2w52TND1PkBSBHA/rdRGMrmdLB7MBOBTdXdTbqDHN3V6zndcy7Or546u';
        JSONbody += 'J6KJ5qQH1um3IFKOYw+XqIvT/HxkT+spHoBaxJNGlNfqMB3Cluq/xRTknGpmBGR+KBA=';
        
        req.requestBody =  Blob.valueOf(JSONbody);
        
        RestContext.request = req;
        RestContext.response= res;
        
        Test.startTest();
        FEE_EazyPayS2SResponse_API.ReceivedData();
        Test.stopTest();
    }
}