force-app/main/default/objects/Contact/fields/Aadhar_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Card_Number__c</fullName>
    <label>Aadhar Card Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Form_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Form_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Submitted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>hed__Preferred_Email__c</fullName>
    <description>The email (University, Work, Alternate) that this Contact prefers you to use.</description>
    <inlineHelpText>The email (University, Work, Alternate) that this Contact prefers you to use.</inlineHelpText>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Work Email</fullName>
            </value>
            <value>
                <fullName>Personal Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Afghan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Anguillan</fullName>
            </value>
            <value>
                <fullName>Antiguans</fullName>
            </value>
            <value>
                <fullName>Argentinean</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Barbudans</fullName>
            </value>
            <value>
                <fullName>Batswana</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bermudian</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Botswanan</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Primary_Academic_Program__c.field-meta.xml
<CustomField>
    <fullName>Primary_Academic_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Academic Program</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Academic_Program_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Faculty)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admission Cancelled</fullName>
            </value>
            <value>
                <fullName>Pursuing</fullName>
                <default>true</default>
                <label>Pursuing</label>
            </value>
            <value>
                <fullName>Detained</fullName>
            </value>
            <value>
                <fullName>Year Back</fullName>
            </value>
            <value>
                <fullName>Not Reported</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Nationality__c/Nationality__c.object-meta.xml
<CustomObject>
    <label>Nationality</label>
    <nameField>
        <label>Nationality (as per 10th Marksheet) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nationalities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Trigger_Form_Sub_CheckBox_Handler_Test.cls
@istest
public class Trigger_Form_Sub_CheckBox_Handler_Test 
{
    public static testmethod void ContactTrig()
    {
        string HouseholdRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_University_Department).getRecordTypeId();
        Account objAcc = ALU_TestDataFactory.CreateAccount('Test Account',HouseholdRecId);
        objAcc.Recordtypeid = HouseholdRecId;
        Insert objAcc;
        
       string AcaRecId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Academic_Program).getRecordTypeId();
       Account objAccount1 = ALU_TestDataFactory.CreateAccount('Test Account1',AcaRecId );
       objAccount1.RecordTypeid = AcaRecId;
       objAccount1.Parentid = objAcc.id;
       insert objAccount1;
        
        hed__Program_Plan__c  objProgPlan =  ALU_TestDataFactory.createProgramPlan('Test Program Plan');
        objProgPlan.hed__Start_Date__c = system.today().addyears(-1);
        objProgPlan.hed__End_Date__c = system.today().addyears(+1);
        objProgPlan.hed__Account__c = objAccount1.id;
        insert objProgPlan;
    
        string StudentRecId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(Utility.Contact_RecType_Student).getRecordTypeId();
       Contact objcon = ALU_TestDataFactory.createContact('Test');
        objcon.MobilePhone ='9090909090';
        objcon.Aadhar_Card_Number__c ='098765435612';
        objcon.RecordTypeId = StudentRecId;
        objcon.AccountId = objAcc.Id;
        objcon.School__c = objAcc.id;
        objcon.Application_Number__c = 'test123';
        objcon.SRN_Number__c ='123';
        objcon.Personal_Email__c = 'test@reva.edu.in';
        objcon.hed__Preferred_Email__c = 'Personal Email';
        objcon.Nationality__c ='Indian';
        objcon.Active__c = true;
        objcon.Student_Status__c = 'Pursuing';
        objcon.Program_Batch__c = objProgPlan.id;
        objcon.Primary_Academic_Program__c = objAccount1.id;
        Insert objcon; 
        
        objcon.Form_Submitted__c= true;
        objcon.MobilePhone = '8618909023';
        update objcon;
        
       List<Contact> lst_update = new List<Contact>();
        lst_update.add(objcon);
        
        Set<Id> Set_conId = new Set<Id>();
        Set_conId.Add(objcon.Id);
        
        Map<Id,Contact> Map_con = new Map<Id,Contact>();
        Map_con.put(objcon.id, objcon);
        
        Test.startTest();
        Trigger_Form_Submitted_CheckBox_Handler.Form_Submitted_Contact(lst_update, Map_con);
        Trigger_Form_Submitted_CheckBox_Handler.Form_Submitted_User(lst_update);
        Test.stopTest();
    }
}