force-app/main/default/objects/Contact/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Semester</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Semester</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RH_Current_Pursuing_Year_of_Student__c.field-meta.xml
<CustomField>
    <fullName>RH_Current_Pursuing_Year_of_Student__c</fullName>
    <formula>CASE(
    MOD(VALUE(RIGHT(Active_Semester__r.Name, 1)), 10),
    1, &apos;1st Year&apos;,
    2, &apos;1st Year&apos;,
    3, &apos;2nd Year&apos;,
    4, &apos;2nd Year&apos;,
    5, &apos;3rd Year&apos;,
    6, &apos;3rd Year&apos;,
    7, &apos;4th Year&apos;,
    8, &apos;4th Year&apos;,
    9, &apos;5th Year&apos;,
    0, &apos;5th Year&apos;,
    &apos;Unknown&apos;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Pursuing Year of Student</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getContactDetails.cls
public class getContactDetails {

     @AuraEnabled(cacheable=true)
    public static contact ContactDetails(){
        Id userId = UserInfo.getUserId();
        System.debug('Loggedin User Id---->>> '+userId);

        User userInfos = [SELECT Id, contactId, FirstName, LastName From User WHERE Id=:userId];
        System.debug('ContactId of logged in User---->>> '+userInfos.contactId);

        Contact conDetails = [SELECT Id, Name, FirstName, LastName, Record_Type_Name__c, Program_Batch__r.Name,Active_Semester__r.Name, RH_Current_Pursuing_Year_of_Student__c From Contact Where Id=:userInfos.contactId LIMIT 1];
        System.debug('conDetails=> '+conDetails);
        return conDetails;
        
    }
}