force-app/main/default/objects/Contact/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Semester</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Semester</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Logisys_Integration__c.field-meta.xml
<CustomField>
    <fullName>Logisys_Integration__c</fullName>
    <label>Logisys Integration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DB-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ASM_StdProfileAPIBatch.cls
global class ASM_StdProfileAPIBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
     global Date filterDate;
     global ASM_StdProfileAPIBatch(Date fDate){
     filterDate = fDate;
     }
	global Database.QueryLocator start(Database.BatchableContext BC){
        //semester> start date>10 days before of start date   start(15) = today+5
        return database.getQueryLocator([SELECT Id,Name FROM Contact WHERE SRN_Number__c != '' AND Logisys_Integration__c != 'Yes' 
                                         AND Active_Semester__r.hed__Start_Date__c = :filterDate  ]);
    }
    global void execute(Database.BatchableContext BC, List<Contact> scope){
        Set<Id> set_StdIds = new Set<Id>();
        Map<Id,String> map_DataChanges = new Map<Id,String>();
        for(Contact con : scope){
            set_StdIds.add(con.Id);
            map_DataChanges.put(con.Id, 'No-No-No');
        }
        Debug_Log__c dLog = ASM_StdProfileAPI.sendStdProfiles(set_StdIds,map_DataChanges,true);
        Insert dLog;
    }
    global void finish(Database.BatchableContext BC){       
    }
}