force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Semester</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Semester</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Father__c.field-meta.xml
<CustomField>
    <fullName>Father__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Father</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Father</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Father_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Father_Mobile_Number__c</fullName>
    <formula>Father__r.MobilePhone</formula>
    <label>Father Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Father_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Name__c</fullName>
    <formula>Father__r.FirstName + &apos; &apos; +  Father__r.MiddleName + &apos; &apos; + Father__r.LastName</formula>
    <label>Father Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Guardian)</relationshipLabel>
    <relationshipName>Guardian</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mother</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mother)</relationshipLabel>
    <relationshipName>Mother</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mother_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mother_Mobile_Number__c</fullName>
    <formula>Mother__r.MobilePhone</formula>
    <label>Mother Mobile Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mother_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_Name__c</fullName>
    <label>Mother Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/hed_Time_Table_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Time Table Line Item</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Table Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_Date__c.field-meta.xml
<CustomField>
    <fullName>hed_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_End_Time__c.field-meta.xml
<CustomField>
    <fullName>hed_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>hed_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/Reva_Exam_Notification__c.field-meta.xml
<CustomField>
    <fullName>Reva_Exam_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IA Notification</label>
    <referenceTo>Rve_Exam_Notification__c</referenceTo>
    <relationshipLabel>Time Table Line Items</relationshipLabel>
    <relationshipName>Time_Table_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/Rve_Exam_Application__c.object-meta.xml
<CustomObject>
    <label>REVA Exam Application</label>
    <nameField>
        <label>Exam Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Exam Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Amount__c.field-meta.xml
<CustomField>
    <fullName>Rve_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Applied_Date__c.field-meta.xml
<CustomField>
    <fullName>Rve_Applied_Date__c</fullName>
    <label>Applied Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Exam_Notification__c.field-meta.xml
<CustomField>
    <fullName>Rve_Exam_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam Notification</label>
    <referenceTo>Rve_Exam_Notification__c</referenceTo>
    <relationshipName>Exam_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Logisys_Field_Check__c.field-meta.xml
<CustomField>
    <fullName>Rve_Logisys_Field_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logisys Field Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Rve_Payment_Date__c</fullName>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Rve_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Rve_Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Cash</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Rve_Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Status__c.field-meta.xml
<CustomField>
    <fullName>Rve_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Pending fees</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Rve_Student__c.field-meta.xml
<CustomField>
    <fullName>Rve_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Exam_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <formula>Rve_Student__r.Student_Full_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application_Line_Item__c/Rve_Exam_Application_Line_Item__c.object-meta.xml
<CustomObject>
    <label>REVA Exam Application Line Item</label>
    <nameField>
        <displayFormat>Application Item-{0000}</displayFormat>
        <label>Rve Exam Application Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVA Exam Application Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rve_Exam_Application_Line_Item__c/fields/Rve_Exam_Application__c.field-meta.xml
<CustomField>
    <fullName>Rve_Exam_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rve Exam Application</label>
    <referenceTo>Rve_Exam_Application__c</referenceTo>
    <relationshipLabel>Exam Application Line Items</relationshipLabel>
    <relationshipName>Rve_Exam_Application_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application_Line_Item__c/fields/Rve_QP_Code__c.field-meta.xml
<CustomField>
    <fullName>Rve_QP_Code__c</fullName>
    <label>Rve QP Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application_Line_Item__c/fields/Rve_Semester__c.field-meta.xml
<CustomField>
    <fullName>Rve_Semester__c</fullName>
    <label>Rve Semester</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Application_Line_Item__c/fields/Rve_Subject__c.field-meta.xml
<CustomField>
    <fullName>Rve_Subject__c</fullName>
    <label>Rve Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/Rve_Exam_Notification__c.object-meta.xml
<CustomObject>
    <label>REVA Exam Notification</label>
    <nameField>
        <label>Exam Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Exam Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/hed_IA_Type__c.field-meta.xml
<CustomField>
    <fullName>hed_IA_Type__c</fullName>
    <label>IA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IA 1</fullName>
            </value>
            <value>
                <fullName>IA 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/hed_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>hed_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Reva Exam Notifications</relationshipLabel>
    <relationshipName>Reva_Exam_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rve_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/rve_Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>rve_Exam_Start_Date__c</fullName>
    <label>Exam Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Semester__c.field-meta.xml
<CustomField>
    <fullName>Rve_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Semester</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipName>Reva_Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Exam_Application_Form_whats_Test.cls
@isTest
public class Exam_Application_Form_whats_Test {
     @IsTest//@TestSetUp
    static void testTrsWhatsappNotification() {
        
        Account acc = new Account(Name='TestAcc');
        insert acc;
        
        hed__Program_Plan__c ProgramBatch = new hed__Program_Plan__c();
        ProgramBatch.Name = 'TestProgramBatch';
        ProgramBatch.hed__Account__c = acc.Id;
        insert ProgramBatch;
        
        Contact father = new Contact(
        LastName = 'Father',
        MobilePhone = '7731030243'
        
        );
        
        insert father;
        
         Contact Mother = new Contact(
        LastName = 'Mother',
        MobilePhone = '7731030286'
        
        );
        
        insert Mother;
        
         Contact Guardian = new Contact(
        LastName = 'Guardian',
        MobilePhone = '7731030290'
        
        );
        
        insert Guardian;
        
          // Create Semester (hed__Term__c)
        hed__Term__c semester = new hed__Term__c();
        semester.Name = '3rd Semester';
        semester.Program_Batch__c =ProgramBatch.id;
        semester.hed__Account__c = acc.Id;
        semester.hed__Start_Date__c = Date.today().addDays(-30);
        semester.hed__End_Date__c = Date.today().addDays(30);
        
        insert semester;
        
        
        // Create test data
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            MobilePhone = '7731030343',
            Email = 'revatransport@yopmail.com',
            Active_Semester__c = semester.Id,
            Active__c = true,
            Father__c = father.Id,
            Mother__c = Mother.Id,
            Guardian__c = Guardian.Id
           // Father_Name__c = father.name,
           // Father_Mobile_Number__c = father.MobilePhone
        );
        insert testContact;
        
      
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = 'Rve_Exam_Notification__c' AND Name = 'Semester Notification' LIMIT 1];
        
        Rve_Exam_Notification__c examNotification = new Rve_Exam_Notification__c(
            Name = 'Test Notification',
            hed_Program_Batch__c = ProgramBatch.Id,
            Rve_Semester__c = semester.Id,
          //  hed_Program_Batch__c = 'Test Program Batch',
          //  Rve_Semester__c = 'Test Semester',
            rve_Exam_Start_Date__c = Date.today(),
            Rve_End_Date__c = Date.today().addDays(5),
            RecordTypeId = rt.Id,
            hed_IA_Type__c = 'IA 1'
        );
        insert examNotification;
        
        hed_Time_Table_Line_Item__c TimeTableItem = new hed_Time_Table_Line_Item__c();
        TimeTableItem.Name = 'TestTimeTable';
        TimeTableItem.Reva_Exam_Notification__c = ExamNotification.Id;
        TimeTableItem.hed_Date__c = System.today();
        TimeTableItem.hed_Start_Time__c =Time.newInstance(11,0,0,0);
        TimeTableItem.hed_End_Time__c = Time.newInstance(12,0,0,0);
        insert TimeTableItem;
        
         Rve_Exam_Application__c revExam = new Rve_Exam_Application__c( Name='testExam', 
                                                                      Rve_Amount__c=12000,
                                                                      Rve_Applied_Date__c=System.today(),
                                                                      Rve_Exam_Notification__c=examNotification.Id,
                                                                      Rve_Logisys_Field_Check__c=true,
                                                                      Rve_Payment_Date__c=System.today(),
                                                                      Rve_Payment_Status__c='Success',
                                                                      Rve_Payment_Type__c='Online',
                                                                      Rve_Registration_Number__c='1234tyu', 
                                                                      Rve_Status__c='Active', 
                                                                      
                                                                      Rve_Student__c=testContact.Id);
        insert revExam;
        
        Rve_Exam_Application_Line_Item__c lineItem = new Rve_Exam_Application_Line_Item__c(//Name = 'testLineItem' ,
            Rve_QP_Code__c='abbb223',
            Rve_Semester__c='semester',
            Rve_Subject__c='salesforce',
            Rve_Exam_Application__c= revExam.ID);
        
        insert lineItem;
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        // Call the method to test
        Test.startTest();
                Exam_Application_Form_whats.trsWhatsappNotification(new List<List<String>> { new List<String> { revExam.Id } });

        //Exam_Application_Form_whats.trsWhatsappNotification(new List<String> { revExam.Id });
        Test.stopTest();
    }
    
     /*@IsTest(seeAllData=true)
    static void testBatch() {
     
        Contact con = [Select Id,name,mobilephone,Father_Name__c,Father_Mobile_Number__c,Mother_Mobile_Number__c,Mother_Name__c,
                       Guardian__r.Name ,Guardian__r.MobilePhone
                       from contact where lastname='Contact'];
        
        system.debug('conlist>>'+con);
        Rve_Exam_Application__c applicationtlist = [ SELECT Id, Name, Rve_Exam_Notification__r.hed_Program_Batch__r.Name,
                   Rve_Exam_Notification__r.Rve_Semester__r.Name, Rve_Exam_Notification__r.hed_Program_Batch__c,
                   Rve_Exam_Notification__r.Rve_Semester__c, Rve_Exam_Notification__r.Rve_End_Date__c, 
                   Rve_Exam_Notification__r.RecordType.Name, 
                   Rve_Exam_Notification__r.Rve_Semester__r.IA_2_End_date__c, Rve_Student__r.MobilePhone, Rve_Student__r.Name,
                   Rve_Student__r.Email, Rve_Student__c, Student_Name__c
            FROM Rve_Exam_Application__c 
            WHERE Rve_Exam_Notification__r.RecordType.Name = 'Semester Notification' AND name = 'testExam'];
        
          // Set mock callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        // Execute the batch
        //Exam_Application_Form_whats_batch batch = new Exam_Application_Form_whats_batch(applicationtlist.Id);
        Test.startTest();
        //Database.executeBatch(batch);
        Test.stopTest();
        
        // Verify results
        // Verify that the batch has processed the records
      /*  List<AsyncApexJob> batchJobs = [SELECT Id, Status FROM AsyncApexJob WHERE JobType = 'BatchApex' AND ApexClassId = :Schema.getGlobalDescribe().get('Change_in_Time_Table_whats_batch').getSObjectType().getDescribe().getId() LIMIT 1];
        System.assertEquals(1, batchJobs.size(), 'Batch job should have been executed');
        System.assertEquals('Completed', batchJobs[0].Status, 'Batch job should have completed successfully');
    }*/
    
     public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HttpResponse respond(HttpRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"status":"success"}');
            res.setStatusCode(200);
            return res;
        }
    }

}