force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Semester</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Semester</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Father__c.field-meta.xml
<CustomField>
    <fullName>Father__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Father</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Father</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Notification_Date__c</fullName>
    <label>Last Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mother</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mother)</relationshipLabel>
    <relationshipName>Mother</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch_Name__c</fullName>
    <formula>IF( Record_Type_Name__c =&apos;Parent&apos;, ReportsTo.Program_Batch__r.Name,Program_Batch__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Batch Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <formula>Text( Primary_Academic_Program__r.Program_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <label>Quota</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Management Quota</fullName>
            </value>
            <value>
                <fullName>Government Quota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <formula>School__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>School Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admission Cancelled</fullName>
            </value>
            <value>
                <fullName>Pursuing</fullName>
                <default>true</default>
                <label>Pursuing</label>
            </value>
            <value>
                <fullName>Detained</fullName>
            </value>
            <value>
                <fullName>Year Back</fullName>
            </value>
            <value>
                <fullName>Not Reported</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <formula>Contact__r.Active_Semester__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Semester</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 1st Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 2nd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 3rd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 4th Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 5th Year</label>
            </value>
            <value>
                <fullName>University Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 1st Year</label>
            </value>
            <value>
                <fullName>University Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 2nd Year</label>
            </value>
            <value>
                <fullName>University Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 3rd Year</label>
            </value>
            <value>
                <fullName>University Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 4th Year</label>
            </value>
            <value>
                <fullName>University Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 5th Year</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <formula>Contact__r.Program_Batch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Batch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <formula>TEXT(Contact__r.Student_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SMSNotification_Batch.cls
global class SMSNotification_Batch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        Id ContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        system.debug('RecordType==='+ContactRecTypeId);
        return Database.getQueryLocator([SELECT Id, Name, Active__c, Quota__c, Last_Notification_Date__c, 
                                         ReportsToId, MobilePhone, Father__r.MobilePhone, Mother__r.MobilePhone, 
                                         Program_Batch_Name__c, Program_Batch__r.hed__Start_Date__c, 
                                         Active_Semester__r.hed__Start_Date__c, Active_Semester__r.Term_Number__c
                                         FROM Contact
                                         WHERE Student_Status__c = 'Pursuing'
                                         AND RecordTypeId = :ContactRecTypeId
                                         AND Active_Semester__r.Term_Number__c !=1
                                         AND Program_Type__c != 'Ph.D'
                                         AND School_Name__c NOT IN ('REVA Academy for Corporate Excellence', 'School of Performing Arts and Indic Studies')
                                         AND Program_Batch__r.hed__Start_Date__c != null]);
    }
    
    global void execute(Database.BatchableContext bc, List<Contact> lstCon) {
        List<SMS_API_Utility.shortMessageWrp> lstShortMsg = new List<SMS_API_Utility.shortMessageWrp>();
        Date todayDt = System.today();
        Id ConParentTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Parent').getRecordTypeId();
        Set<Id> set_Reportid = new Set<Id>();
        
        for (Contact con : lstCon) {
            Set<Id> set_BatchIds = new Set<Id>();
            for (hed__Program_Enrollment__c objProgEnroll : [SELECT Id, Active__c, hed__Program_Plan__c, hed__Contact__c 
                                                             FROM hed__Program_Enrollment__c 
                                                             WHERE hed__Contact__c = :con.Id AND Active__c = true]) {
                                                                 set_BatchIds.add(objProgEnroll.hed__Program_Plan__c);
                                                             }
            
            if (!set_BatchIds.isEmpty()) {
                List<hed__Term__c> lst_term = new List<hed__Term__c>();
                for (hed__Term__c objTerm : [SELECT Id, Name, hed__Start_Date__c, Program_Batch__c, Term_Number__c 
                                             FROM hed__Term__c 
                                             WHERE Program_Batch__c IN :set_BatchIds 
                                             AND Term_Number__c IN (3, 5, 7, 9) 
                                             AND hed__Start_Date__c != null]) {
                                                 lst_term.add(objTerm);
                                             }
                
                for (hed__Term__c sem : lst_term) {
                    Date semesterStartDate = sem.hed__Start_Date__c;
                    Date fourWeeksBefore = semesterStartDate.addDays(-28);
                    Date fifteenDaysBefore = semesterStartDate.addDays(-15);
                    Date thirtyDaysAfter = semesterStartDate.addDays(30);
                    Date fortyFiveDaysAfter = semesterStartDate.addDays(45);
                    Date sixtyDaysAfter = semesterStartDate.addDays(60);
                    
                    Boolean sendSMS = false;
                    Boolean sendEmail = false;
                    if (todayDt == fourWeeksBefore || todayDt == fifteenDaysBefore || todayDt == semesterStartDate) {
                        sendSMS = true;
                    } else if (todayDt > semesterStartDate && todayDt <= thirtyDaysAfter && getDayOfWeek(todayDt) == getDayOfWeek(semesterStartDate)) {
                        sendSMS = true;
                    } else if (todayDt > thirtyDaysAfter && todayDt <= fortyFiveDaysAfter && Math.mod(todayDt.daysBetween(thirtyDaysAfter), 3) == 0) {
                        sendSMS = true;
                    } else if (todayDt > fortyFiveDaysAfter && todayDt <= sixtyDaysAfter && Math.mod(todayDt.daysBetween(fortyFiveDaysAfter), 2) == 0) {
                        sendSMS = true;
                    }
                    
                    List<Student_Fee__c> feeList = [SELECT Id, Name, Due_Date__c, Amount__c, Amount_Paid__c, Amount_Pending__c 
                                                    FROM Student_Fee__c 
                                                    WHERE Contact__c = :con.Id 
                                                    AND Amount_Pending__c > 0 
                                                    AND (Due_Date__c <= :semesterStartDate.addDays(30) and Due_Date__c >= :semesterStartDate) 
                                                    AND Fee_Type__c IN ('University Fee','Tuition Fee','Penalty Fee')];
                    
                    if (sendSMS && !feeList.isEmpty()) {
                        set_Reportid.add(con.Id);
                        buildSMSMessages(lstShortMsg, con, feeList);
                    }
                }
            }
        }
        
        System.debug('lstShortMsg size = ' + lstShortMsg.size());
        if (!lstShortMsg.isEmpty()) {
            sendSMS(lstShortMsg);
        }
    }
    private String getDayOfWeek(Date dt) {
        // Convert Date to DateTime to use the format method
        DateTime dtTime = DateTime.newInstance(dt.year(), dt.month(), dt.day());
        return dtTime.format('E'); // Returns day of the week abbreviation (Mon, Tue, etc.)
    }
    private void buildSMSMessages(List<SMS_API_Utility.shortMessageWrp> messages, Contact con, List<Student_Fee__c> feeList) {
        String messageText = 'Dear Student, Your outstanding fees for the current academic year have not been settled. Please make the payment via SLCM to avoid penalties. REVA University';
        
        if (String.isNotBlank(con.MobilePhone)) {
            messages.add(createShortMessage(con.MobilePhone, messageText));
        }
        if (con.Father__r != null && String.isNotBlank(con.Father__r.MobilePhone)) {
            messages.add(createShortMessage(con.Father__r.MobilePhone, messageText));
        }
        if (con.Mother__r != null && String.isNotBlank(con.Mother__r.MobilePhone)) {
            messages.add(createShortMessage(con.Mother__r.MobilePhone, messageText));
        }
    }
    
    private SMS_API_Utility.shortMessageWrp createShortMessage(String mobilePhone, String message) {
        SMS_API_Utility.shortMessageWrp shortMessage = new SMS_API_Utility.shortMessageWrp();
        shortMessage.message = message;
        shortMessage.recipient = '+91' + mobilePhone;
        return shortMessage;
    }
    
    private void sendSMS(List<SMS_API_Utility.shortMessageWrp> messages) {
        HttpRequest request = SMS_API_Utility.SendSMSOneToMany('Penalty SMS', messages);
        
        
    }
    
    global static String getTimeDetails(String timeDetails) {
        String[] outtimesplit = timeDetails.split(':');
        if (Integer.valueOf(outtimesplit[0]) >= 12) {
            Integer outhour = Integer.valueOf(outtimesplit[0]) - 12;
            return String.valueOf(outhour) + ':' + outtimesplit[1];
        } else {
            if (Integer.valueOf(outtimesplit[0]) < 10) {
                return '0' + outtimesplit[0] + ':' + outtimesplit[1];
            } else {
                return outtimesplit[0] + ':' + outtimesplit[1];
            }
        }
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
}