force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reva_Transport__c/Reva_Transport__c.object-meta.xml
<CustomObject>
    <label>REVA Transport</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/RTR_Reva_Transport_Request__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the transport fees concession requests for the students</description>
    <label>REVA Transport Request</label>
    <nameField>
        <displayFormat>TRQ-{0000}</displayFormat>
        <label>REVA Transport Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVA Transport Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_Descriptions__c.field-meta.xml
<CustomField>
    <fullName>RTR_Descriptions__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_Number_of_Minutes__c.field-meta.xml
<CustomField>
    <fullName>RTR_Number_of_Minutes__c</fullName>
    <label>Number of Minutes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTR_Route_Master__c/RTR_Route_Master__c.object-meta.xml
<CustomObject>
    <description>This Object will store details about the Bus Routes, Pick up points and its capacity.</description>
    <label>Route Master</label>
    <nameField>
        <label>Route Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/RTR_Route_Pick_Up_Point__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the Pick up points of the route path and its related payments.</description>
    <label>Route Pick Up Point</label>
    <nameField>
        <label>Pick Up Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Pick Up Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/Transport_Registeration__c.object-meta.xml
<CustomObject>
    <label>Transport Registration</label>
    <nameField>
        <displayFormat>RU-{0000}</displayFormat>
        <label>Name/BusPass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
                <default>true</default>
                <label>Payment Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Reva_Transport__c.field-meta.xml
<CustomField>
    <fullName>Reva_Transport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Transport</label>
    <referenceTo>Reva_Transport__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Route_Master__c.field-meta.xml
<CustomField>
    <fullName>Route_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Master</label>
    <referenceTo>RTR_Route_Master__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Route_Pick_Up_Point__c.field-meta.xml
<CustomField>
    <fullName>Route_Pick_Up_Point__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Pick Up Point</label>
    <referenceTo>RTR_Route_Pick_Up_Point__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTRLatePickupSMS.cls
global class RTRLatePickupSMS implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    public List<String> recordIds;
    
    public RTRLatePickupSMS(List<String> recordIds) {
        this.recordIds = recordIds;
    }
    
    public Database.QueryLocator start(Database.BatchableContext context){
        return Database.getQueryLocator('SELECT Id, Contact__r.Id, Route_Master__r.Name, Contact__r.MobilePhone,Route_Pick_Up_Point__r.Name, Contact__r.Name,Registration_Status__c, Reva_Transport__r.Name ' +
                                        'FROM Transport_Registeration__c ' +
                                        'WHERE (Registration_Status__c = \'Active\' AND Reva_Transport__r.Active__c = true)');               
    }
    public void execute(Database.BatchableContext context, List<Transport_Registeration__c> scope) {
        
        RTR_Reva_Transport_Request__c latePickRequest = [select id,RTR_Number_of_Minutes__c, RTR_Date__c, RTR_Descriptions__c
                                                          from RTR_Reva_Transport_Request__c where id IN: recordIds];
        
        System.debug('latePickRequest-->> '+latePickRequest);
        
        List<SMS_API_Utility.shortMessageWrp> messageList = new List<SMS_API_Utility.shortMessageWrp>();
        
        for(Transport_Registeration__c trReg : scope) {
            
            String phoneNumber = trReg.Contact__r.MobilePhone;
			String name = trReg.Contact__r.name;            
            Date schDate = latePickRequest.RTR_Date__c;            
            Datetime rtrDateTime = Datetime.newInstance(schDate.year(), schDate.month(), schDate.day());
            String scheduleDate = rtrDateTime.format('dd.MM.yyyy');            
            System.debug('Formatted Schedule Date: ' + scheduleDate);     
            String lateTime = String.valueof(latePickRequest.RTR_Number_of_Minutes__c);
            String reason = latePickRequest.RTR_Descriptions__c;
            
            String message = 'Dear '+ name +',' +' We’d like to inform you that the University bus will arrive at the pickup point '
                + lateTime + ' minutes later than the regular schedule on '+ scheduleDate  + ' on account of '+ reason + '.' + ' REVA University';
            
            SMS_API_Utility.shortMessageWrp shrtMessage = new SMS_API_Utility.shortMessageWrp();
            if(phoneNumber!=null && message!=null){
            shrtMessage.dltContentId = '1007287792564177010';
            shrtMessage.message = message;
            shrtMessage.recipient = phoneNumber;
            System.debug('receipent -->> '+phoneNumber);
            messageList.add(shrtMessage);
            }
        }
        
        if(messageList.size() > 0) {
            SMS_API_Utility.SendSMSOneToMany('RTR Late Pickup Single Day SMS', messageList);
        }
        
        
    }
    
    public void finish(Database.BatchableContext context) {
        
    }
    
    
}