force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Semester</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Semester</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Father__c.field-meta.xml
<CustomField>
    <fullName>Father__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Father</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Father</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Guardian__c.field-meta.xml
<CustomField>
    <fullName>Guardian__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Guardian</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Guardian)</relationshipLabel>
    <relationshipName>Guardian</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Faculty)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/hed_Time_Table_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Time Table Line Item</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Table Line Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_Date__c.field-meta.xml
<CustomField>
    <fullName>hed_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_End_Time__c.field-meta.xml
<CustomField>
    <fullName>hed_End_Time__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/hed_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>hed_Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/hed_Time_Table_Line_Item__c/fields/Reva_Exam_Notification__c.field-meta.xml
<CustomField>
    <fullName>Reva_Exam_Notification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IA Notification</label>
    <referenceTo>Rve_Exam_Notification__c</referenceTo>
    <relationshipLabel>Time Table Line Items</relationshipLabel>
    <relationshipName>Time_Table_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/IA_Seating_Room_Allotment__c.object-meta.xml
<CustomObject>
    <label>IA Seating Room Allotment</label>
    <nameField>
        <label>IA Seating Room Allotment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IA Seating Room Allotments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Alloted_Students__c.field-meta.xml
<CustomField>
    <fullName>Alloted_Students__c</fullName>
    <label>Alloted Students</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Assigned_Program_Batches__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Program_Batches__c</fullName>
    <inlineHelpText>This field contain all the assigned program batches to the room</inlineHelpText>
    <label>Assigned Program Batches</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Exam_Name__c.field-meta.xml
<CustomField>
    <fullName>Exam_Name__c</fullName>
    <label>Exam Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Exam_Time__c.field-meta.xml
<CustomField>
    <fullName>Exam_Time__c</fullName>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Facility_Type__c.field-meta.xml
<CustomField>
    <fullName>Facility_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Facility Type</label>
    <referenceTo>hed__Facility__c</referenceTo>
    <relationshipLabel>IA Seating Room Allotments</relationshipLabel>
    <relationshipName>IA_Seating_Room_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/IA_Type__c.field-meta.xml
<CustomField>
    <fullName>IA_Type__c</fullName>
    <label>IA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IA 1</fullName>
            </value>
            <value>
                <fullName>IA 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/InEligible_SRN__c.field-meta.xml
<CustomField>
    <fullName>InEligible_SRN__c</fullName>
    <label>InEligible SRN</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>IA Seating Room Allotments</relationshipLabel>
    <relationshipName>IA_Seating_Room_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/rve_Date_of_Exam__c.field-meta.xml
<CustomField>
    <fullName>rve_Date_of_Exam__c</fullName>
    <label>Date of Exam</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/rveShift__c.field-meta.xml
<CustomField>
    <fullName>rveShift__c</fullName>
    <label>Shift</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morning</fullName>
            </value>
            <value>
                <fullName>Afternoon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>IA Seating Room Allotments</relationshipLabel>
    <relationshipName>IA_Seating_Room_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IA_Seating_Room_Allotment__c/fields/Total_Students__c.field-meta.xml
<CustomField>
    <fullName>Total_Students__c</fullName>
    <label>Total Students</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/Rve_Exam_Notification__c.object-meta.xml
<CustomObject>
    <label>REVA Exam Notification</label>
    <nameField>
        <label>Exam Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Exam Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/hed_IA_Type__c.field-meta.xml
<CustomField>
    <fullName>hed_IA_Type__c</fullName>
    <label>IA Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IA 1</fullName>
            </value>
            <value>
                <fullName>IA 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/hed_Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>hed_Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Reva Exam Notifications</relationshipLabel>
    <relationshipName>Reva_Exam_Notifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/rve_Exam_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>rve_Exam_Start_Date__c</fullName>
    <label>Exam Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Publish__c.field-meta.xml
<CustomField>
    <fullName>Rve_Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Semester__c.field-meta.xml
<CustomField>
    <fullName>Rve_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Semester</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipName>Reva_Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <formula>Contact__r.Active_Semester__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Active Semester</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <formula>Contact__r.Program_Batch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Batch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <formula>Contact__r.School__r.Name</formula>
    <label>School</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <formula>Contact__r.SRN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestrveSeatingArrangementUpdated.cls
@isTest
public class TestrveSeatingArrangementUpdated {
    @TestSetup
    static void makeData(){
        // Creating test data for the tests
        Account accparent = new Account(Name='TestAccParent');
        insert accparent;

        Account acc = new Account(Name='TestAcc',parentId=accparent.Id);
        insert acc;

        hed__Program_Plan__c ProgramBatch = new hed__Program_Plan__c();
        ProgramBatch.Name = 'TestProgramBatch';
        ProgramBatch.hed__Account__c = acc.Id;
        insert ProgramBatch;
        
        hed__Term__c term = new hed__Term__c(
            Name = 'Fall 2024',
            Program_Batch__c = ProgramBatch.Id,
            hed__Start_Date__c = Date.today().addMonths(-1),
            hed__End_Date__c = Date.today().addMonths(5),
            IA_1_Start_date__c = Date.today().addMonths(1),
            Exam_Start_Date__c = Date.today().addMonths(2),
            IA_1_End_date__c = Date.today().addMonths(3),
            IA_2_Start_date__c = Date.today().addMonths(4),
            IA_2_End_date__c = Date.today().addMonths(5),
            hed__Account__c = acc.Id
        );
        insert term;
        
        string IANotification = Schema.SObjectType.Rve_Exam_Notification__c.getRecordTypeInfosByName().get('IA Notification').getRecordTypeId();
        Rve_Exam_Notification__c TestNotification = new Rve_Exam_Notification__c();
        TestNotification.Name = 'Test';
        TestNotification.Rve_Semester__c=term.Id;
        TestNotification.rve_Exam_Start_Date__c = System.Today();
        TestNotification.Rve_Publish__c = true;
        TestNotification.RecordTypeId = IANotification;
        TestNotification.hed_Program_Batch__c = ProgramBatch.Id;
        TestNotification.hed_IA_Type__c = 'IA 1';
        insert TestNotification;

        hed_Time_Table_Line_Item__c TimeTableItem = new hed_Time_Table_Line_Item__c();
        TimeTableItem.Name = 'TestTimeTable';
        TimeTableItem.Reva_Exam_Notification__c = TestNotification.Id;
        TimeTableItem.hed_Date__c = System.today();
        TimeTableItem.hed_Start_Time__c =Time.newInstance(11,0,0,0);
        TimeTableItem.hed_End_Time__c = Time.newInstance(12,0,0,0);
        insert TimeTableItem;

        hed__Facility__c Facility = new hed__Facility__c(
            name = 'Test Facility',
            hed__Capacity__c = 50,
            Facility_Booked__c = false,
            Room_Name__c = 'TESLA LAB',
            Room__c = '301',
            Floor__c = '1st floor',
            Block__c = 'C.V. Raman Block',
            IA_Type__c = 'IA 1',
            hed__Account__c = acc.Id
        );
        insert Facility;

        IA_Seating_Room_Allotment__c SeatingRoom = new IA_Seating_Room_Allotment__c(
            Name = Facility.Room__c,
            Facility_Type__c = Facility.Id,
            Capacity__c = Facility.hed__Capacity__c,
            IA_Type__c = Facility.IA_Type__c,
            School__c = accparent.Id,
            Room__c = Facility.Room__c,
            Active__c = true,
            rve_Date_of_Exam__c = Date.today(),
            rveShift__c = 'Morning',
            Exam_Time__c = Time.NewInstance(11,0,0,0),
            End_Time__c = Time.NewInstance(12,0,0,0),
            Alloted_Students__c = 'SA001,SA002',
            InEligible_SRN__c = 'SA003,Sa004',
            Course_Name__c = 'Electronic Circuit',
            Exam_Name__c = TestNotification.Name,
            Assigned_Program_Batches__c = ProgramBatch.id,
            Total_Students__c = 4
        );

                insert SeatingRoom;

           Contact father = new Contact(
            FirstName = 'John father',
            LastName = 'Doe father',
            MobilePhone = '7894561230',
            Active_Semester__c = term.Id,
            Active__c = true,
            Email = 'Father@test.com'
         );
        insert father;
        Contact guardian = new Contact(
            FirstName = 'John guardian',
            LastName = 'Doe guardian',
            MobilePhone = '7894000000',
            Active_Semester__c = term.Id,
            Active__c = true,
            Email = 'guardian@test.com'
         );
        Insert guardian;
        Contact con = new Contact();
        con.FirstName = 'suraj';
        con.LastName = 'Madala';
        con.Program_Batch__c = ProgramBatch.Id;
        con.SRN_Number__c='SA001';
        con.email = 'test@test.com';
        con.Active__c=true;
        con.MobilePhone='7894561230';
        con.Father__c = father.Id;
        con.Guardian__c =guardian.Id;
        insert con;

        Student_Fee__c StudentFee = new Student_Fee__c(
            Name = 'Test Student Fee',
            contact__c = con.Id,
            Amount_Pending__c=0
        );
        insert StudentFee;
        
         hed__Program_Enrollment__c ProgramEnrollmentEligible = new hed__Program_Enrollment__c(
            hed__Contact__c = con.Id,
            Total_Classes_Completed__c=40,
            Total_Classes_Attended__c=35,
            hed__Program_Plan__c = ProgramBatch.id
        );
        insert ProgramEnrollmentEligible;

        Contact con1 = new Contact();
        con1.FirstName = 'Vaishnavi';
        con1.LastName = 'Madala';
        con1.Program_Batch__c = ProgramBatch.Id;
        con1.SRN_Number__c='SA003';
        con1.Active__c=true;
        con1.MobilePhone='7894561230';
        con1.Email='test1@test.com';
        con1.Father__c = father.Id;
        con1.Guardian__c=guardian.Id;
        insert con1;

        Student_Fee__c StudentInEligibleFee = new Student_Fee__c(
            Name = 'Test Student Fee InEligible',
            contact__c = con1.Id,
            Amount_Pending__c=1,
            Due_Date__c = System.today()

        );
        insert StudentInEligibleFee;

        hed__Program_Enrollment__c ProgramEnrollment = new hed__Program_Enrollment__c(
            hed__Contact__c = con.Id,
            Total_Classes_Completed__c=40,
            Total_Classes_Attended__c=25,
            hed__Program_Plan__c = ProgramBatch.id
        );
        insert ProgramEnrollment;
    }

    @isTest
    static void testGetActivePrograms() {
        List<hed__Program_Plan__c> ProgramBatchList = rveSeatingArrangementUpdated.getActivePrograms();
        System.assertNotEquals(null, ProgramBatchList);
    }
    
    @isTest
    static void testParseTime() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Time parsedTime = rveSeatingArrangementUpdated.parseTime('10:30:00');
        Time expectedTime = Time.newInstance(10, 30, 0, 0);
        System.assertEquals(expectedTime, parsedTime);
    }

    @isTest
    static void testGetAccountId() {
        hed__Program_Plan__c programBatch = [SELECT Id, Name FROM hed__Program_Plan__c WHERE Name = 'TestProgramBatch'];
        Account acc = [SELECT Id, Name, ParentId FROM Account WHERE Name = 'TestAcc'];
        String accountId = rveSeatingArrangementUpdated.getAccountId(programBatch.Id);
        System.assertEquals(acc.ParentId, accountId);
    }

    @isTest
    static void testGetRevaExamNotifications() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        List<contact>InEligiblestudents = [Select Id from Contact where SRN_Number__c='SA003'];
        hed__Program_Plan__c programBatch = [SELECT Id FROM hed__Program_Plan__c WHERE Name = 'TestProgramBatch'];
        List<hed_Time_Table_Line_Item__c> timeTableList = rveSeatingArrangementUpdated.getRevaExamNotifications('IA 1', 'Morning', programBatch.Id);
        List<Rve_Exam_Notification__c> notification =[select id,name from Rve_Exam_Notification__c WHERE Rve_Semester__r.Name='Fall 2024'];
        System.assert(notification.size() > 0, 'Expected at least one Rve_Exam_Notification__c record');
        
        List<String> notificationIds = new List<String>();
        notificationIds.add(notification[0].Id);      
        
        
        HallTicket_Published_whats.trsWhatsappNotification(New List<list<string>>{notificationIds});
        
        System.assertNotEquals(0, timeTableList.size());
    }

    @isTest
    static void testUpdateFacilities() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        hed__Program_Plan__c programBatch = [SELECT Id FROM hed__Program_Plan__c WHERE Name = 'TestProgramBatch'];
        hed__Facility__c facility = [SELECT Id, hed__Capacity__c FROM hed__Facility__c WHERE Room_Name__c = 'TESLA LAB'];
        Map<String, Integer> facilityMap = new Map<String, Integer>();
        facilityMap.put(facility.Id, 50);
        String status = rveSeatingArrangementUpdated.updateFacilities(facilityMap, programBatch.Id);
        //System.assertEquals('successful', status);
    }

    @isTest
    static void testGetRelatedSchool() {
        hed__Program_Plan__c programBatch = [SELECT Id FROM hed__Program_Plan__c WHERE Name = 'TestProgramBatch'];
        IA_Seating_Room_Allotment__c SeatingRoom = [Select Id,Name,Facility_Type__c,Capacity__c,IA_Type__c,School__c,Room__c,Active__c,
                                                    rve_Date_of_Exam__c,rveShift__c,Exam_Time__c,End_Time__c,Alloted_Students__c,InEligible_SRN__c,Course_Name__c,
                                                    Exam_Name__c,Assigned_Program_Batches__c,Total_Students__c from IA_Seating_Room_Allotment__c where name='301'];
        
        rveSeatingArrangementUpdated.getRelatedSchool(String.valueOf(programBatch.Id), 'IA 1', 'Morning', System.today(), String.valueOf(Time.newInstance(11,0,0,0)));
    }

    @isTest
    static void testCheckProgramBatchAllotment() {
        hed__Program_Plan__c programBatch = [SELECT Id FROM hed__Program_Plan__c WHERE Name = 'TestProgramBatch'];
        rveSeatingArrangementUpdated.checkProgramBatchAllotment(String.valueOf(programBatch.Id), System.today(), 'Morning', String.valueOf(Time.newInstance(11,0,0,0)));
    }

    @isTest
    static void testGetAllStudents() {
        hed__Program_Plan__c programBatch = [SELECT Id FROM hed__Program_Plan__c WHERE Name = 'TestProgramBatch'];
        rveSeatingArrangementUpdated.getAllStudents(programBatch.Id);
    }

    @isTest
    static void testCreateAllotments() {
        hed__Program_Plan__c programBatch = [SELECT Id,hed__Account__c,hed__Account__r.ParentId FROM hed__Program_Plan__c WHERE Name = 'TestProgramBatch'];
        hed__Facility__c facility = [SELECT Id, name, hed__Capacity__c, Facility_Booked__c, Room_Name__c, Room__c, Floor__c, Block__c,IA_Type__c FROM hed__Facility__c WHERE Room_Name__c = 'TESLA LAB'];
        Map<String, Integer> facilityMap = new Map<String, Integer>();
        facilityMap.put(facility.Id, 50);
        Set<String> eligibleStudents = new Set<String>{'SA001'};
        Set<String> ineligibleStudents = new Set<String>{'SA003'};
        rveSeatingArrangementUpdated.createAllotments(programBatch.Id, facilityMap, new List<hed__Facility__c>{facility},
                                                      eligibleStudents, ineligibleStudents, System.today(), 'Morning', Time.newInstance(11,0,0,0),
                                                      Time.newInstance(13,0,0,0), 'Data Structure', 'Test Exam');
    }

    @isTest
    static void testCreateOrUpdateAllotment() {
        hed__Program_Plan__c programBatch = [SELECT Id,hed__Account__c,hed__Account__r.ParentId FROM hed__Program_Plan__c WHERE Name = 'TestProgramBatch'];
        hed__Facility__c facility = [SELECT Id, name, hed__Capacity__c, Facility_Booked__c, Room_Name__c, Room__c, Floor__c, Block__c,IA_Type__c FROM hed__Facility__c WHERE Room_Name__c = 'TESLA LAB'];
        List<Object> updateExistingCapacity = new List<Object>{ new List<Object>{facility.Id, 50} };
        List<String> eligibleStudentList = new List<String>{'SA001'};
        List<String> ineligibleStudentList = new List<String>{'SA003'};
        rveSeatingArrangementUpdated.createOrUpdateAllotment(String.valueOf(programBatch.Id), updateExistingCapacity, new List<hed__Facility__c>{facility},
                                                             eligibleStudentList, ineligibleStudentList, Date.today(), 'Morning', String.valueOf(Time.newInstance(11,0,0,0)));
    }
    public class MockHttpResponseGenerator implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            // Create a mock HTTP response
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setBody('{"status": "success", "data": {"resdata": [{"sem": "Semester", "examdate": "2024-05-15", "regno": "SA001", "subshort": "CRS001", "qpcode": "QP001", "doe": "15/05/2024", "session": "9:00 AM to 12:00 PM", "batch": "1"}]}}');     
            return res;
        }
    }
}