force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Reva_Transport__c/Reva_Transport__c.object-meta.xml
<CustomObject>
    <label>REVA Transport</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/RTR_Reva_Transport_Request__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the transport fees concession requests for the students</description>
    <label>REVA Transport Request</label>
    <nameField>
        <displayFormat>TRQ-{0000}</displayFormat>
        <label>REVA Transport Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVA Transport Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_New_Number__c.field-meta.xml
<CustomField>
    <fullName>RTR_New_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Number</label>
    <referenceTo>RTR_Route_Master__c</referenceTo>
    <relationshipName>Reva_Transport_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_Pick_Up_Point__c.field-meta.xml
<CustomField>
    <fullName>RTR_Pick_Up_Point__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pick Up Point</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>$Source.RTR_Routes__c</field>
            <operation>equals</operation>
            <valueField>RTR_Route_Pick_Up_Point__c.RTR_Route_Master__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RTR_Route_Pick_Up_Point__c</referenceTo>
    <relationshipName>Reva_Transport_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_Routes__c.field-meta.xml
<CustomField>
    <fullName>RTR_Routes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Old Number</label>
    <referenceTo>RTR_Route_Master__c</referenceTo>
    <relationshipName>Reva_Transport_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RTR_Route_Master__c/RTR_Route_Master__c.object-meta.xml
<CustomObject>
    <description>This Object will store details about the Bus Routes, Pick up points and its capacity.</description>
    <label>Route Master</label>
    <nameField>
        <label>Route Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/RTR_Route_Pick_Up_Point__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the Pick up points of the route path and its related payments.</description>
    <label>Route Pick Up Point</label>
    <nameField>
        <label>Pick Up Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Pick Up Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/Transport_Registeration__c.object-meta.xml
<CustomObject>
    <label>Transport Registration</label>
    <nameField>
        <displayFormat>RU-{0000}</displayFormat>
        <label>Name/BusPass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
                <default>true</default>
                <label>Payment Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Reva_Transport__c.field-meta.xml
<CustomField>
    <fullName>Reva_Transport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Transport</label>
    <referenceTo>Reva_Transport__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Route_Master__c.field-meta.xml
<CustomField>
    <fullName>Route_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Master</label>
    <referenceTo>RTR_Route_Master__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Route_Pick_Up_Point__c.field-meta.xml
<CustomField>
    <fullName>Route_Pick_Up_Point__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Pick Up Point</label>
    <referenceTo>RTR_Route_Pick_Up_Point__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTRRouteChangeSMS.cls
public class RTRRouteChangeSMS {
    @InvocableMethod(label='RTR Send SMS Notifications for Route Change' description='RTR Send SMS Notification To Route Change')
    public static void RouteChangeSMSNotification(List<String> recordIds){
        if(recordIds != null && !recordIds.isEmpty()){
            makeCalloutAsync(recordIds);           
        } else {
            System.debug('RecordIds List is Empty');
        }   
    }

    @Future(callout=true)
    public static void makeCalloutAsync(List<String> recordIds) {
        
        List<RTR_Reva_Transport_Request__c> requestList = [
            SELECT Id, RTR_Routes__r.Name, RTR_New_Number__r.Name, RTR_Pick_Up_Point__r.Name 
            FROM RTR_Reva_Transport_Request__c 
            WHERE Id IN :recordIds
        ];

        Set<String> oldRoutes = new Set<String>();
        Set<String> newRoutes = new Set<String>();
              
        for (RTR_Reva_Transport_Request__c request : requestList) {
            oldRoutes.add(request.RTR_Routes__r.Name);
            newRoutes.add(request.RTR_New_Number__r.Name);
        }
         
        List<Transport_Registeration__c> trRegList = [
            SELECT Id, Contact__r.Id, Route_Master__r.Name, Route_Pick_Up_Point__r.Name,
                   Registration_Status__c, Reva_Transport__r.Name, Contact__r.MobilePhone 
            FROM Transport_Registeration__c 
            WHERE ((Registration_Status__c = 'Active' AND Reva_Transport__r.Active__c = true) 
                   OR (Registration_Status__c = 'Active' AND Reva_Transport__r.Active__c = NULL))  
            AND Route_Master__r.Name IN :oldRoutes LIMIT 50000
        ];
        System.debug('TrRegList-->> '+trRegList);
        
        if(!trRegList.isEmpty()) {
            List<SMS_API_Utility.shortMessageWrp> messageList = new List<SMS_API_Utility.shortMessageWrp>();
            
            for(RTR_Reva_Transport_Request__c request : requestList) {
                String newRouteNumber = request.RTR_New_Number__r.Name;
                String routeNumber = request.RTR_Routes__r.Name;
                
                for(Transport_Registeration__c trReg : trRegList) {
                    if((trReg.Route_Master__r.Name == routeNumber) && trReg.Contact__r.MobilePhone!= NULL) {
                        String phoneNumber = trReg.Contact__r.MobilePhone;
                        
                        String message = 'Dear Student' + '\nThis is to inform you that the route number '+ routeNumber +
                                         ' is canceled for Today. ' + 'You can take route number '+ newRouteNumber +
                                         ' Instead.'+ '\nWe regret the inconvenience this may cause and appreciate your understanding.' +
                                         '\nREVA University';
                        
                        SMS_API_Utility.shortMessageWrp shrtMessage = new SMS_API_Utility.shortMessageWrp();
                        shrtMessage.dltContentId = '1007503156789986306';
                        shrtMessage.message = message;
                        shrtMessage.recipient = phoneNumber;
                        messageList.add(shrtMessage);
                    }
                }
            }
            
            if(messageList.size() > 0) {
                SMS_API_Utility.SendSMSOneToMany('RTR Route Change SMS', messageList);
            }
        }
    }
}