force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <label>Enrollment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Regular Entry</fullName>
            </value>
            <value>
                <fullName>Lateral Entry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admission Cancelled</fullName>
            </value>
            <value>
                <fullName>Pursuing</fullName>
                <default>true</default>
                <label>Pursuing</label>
            </value>
            <value>
                <fullName>Detained</fullName>
            </value>
            <value>
                <fullName>Year Back</fullName>
            </value>
            <value>
                <fullName>Not Reported</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Actual_Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Actual_Program_Fee__c</fullName>
    <description>Actual program fee - 1st year</description>
    <label>Actual Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 1st Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 2nd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 3rd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 4th Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 5th Year</label>
            </value>
            <value>
                <fullName>University Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 1st Year</label>
            </value>
            <value>
                <fullName>University Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 2nd Year</label>
            </value>
            <value>
                <fullName>University Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 3rd Year</label>
            </value>
            <value>
                <fullName>University Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 4th Year</label>
            </value>
            <value>
                <fullName>University Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 5th Year</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <formula>Contact__r.Program_Batch__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Batch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Program_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Program_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Enrollment</label>
    <referenceTo>hed__Program_Enrollment__c</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <formula>TEXT(Contact__r.Student_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FEE_UpdateDueDateBatch.cls
global class FEE_UpdateDueDateBatch implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext bc) 
    {
        Id ContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        return Database.getQueryLocator([SELECT Id,Name,Fee_Type__c,Due_Date__c,Contact__r.RecordTypeId,Actual_Program_Fee__c,Contact__r.Student_Status__c,Contact__c,Session__c,Amount_Pending__c,Program_Enrollment__c,Program_Enrollment__r.hed__Program_Plan__c,Contact__r.Enrollment_Type__c 
                                         FROM Student_Fee__c WHERE Contact__c != null AND Amount_Pending__c > 0 AND (Fee_Type__c ='University Fee' or Fee_Type__c ='Tuition Fee')
                                         AND Contact__r.Student_Status__c = 'Pursuing' 
                                         AND Contact__r.RecordTypeId = :ContactRecTypeId]);
    }
    global void execute(Database.BatchableContext BC, List<Student_Fee__c> lst_StuFee)
    {
        set<id> set_ConIds = new set<id>();
        set<id> set_BatchIds = new set<id>();
        List<Student_Fee__c> lst_UpStuFee = new List<Student_Fee__c>();
        map<id,list<hed__Term__c>> map_term = new map<id,list<hed__Term__c>>();
        for(Student_Fee__c objStu : lst_StuFee)
        {
            set_ConIds.add(objStu.Contact__c);
        }  
        if(!set_ConIds.isEmpty())
        {
            for(hed__Program_Enrollment__c objProgEnroll : [Select Id,Active__c,hed__Program_Plan__c,hed__Contact__c from 
                                                            hed__Program_Enrollment__c where hed__Contact__c in: set_ConIds and Active__c=true])
            {
                set_BatchIds.add(objProgEnroll.hed__Program_Plan__c);
            }
        }
        if(!set_BatchIds.isEmpty())
        {
            for(hed__Term__c objTerm : [Select Id,Name,hed__Start_Date__c,IA_1_Start_date__c,IA_2_Start_date__c,Program_Batch__c,Term_Number__c from hed__Term__c 
                                        where Program_Batch__c in: set_BatchIds])
            {
                if(map_term.get(objTerm.Program_Batch__c) == null)
                {
                    list<hed__Term__c> lst_term = new list<hed__Term__c>();
                    lst_term.add(objTerm);
                    map_term.put(objTerm.Program_Batch__c,lst_term);
                }
                else
                {
                    map_term.get(objTerm.Program_Batch__c).add(objTerm);
                }
            }
            for(Student_Fee__c objStu : lst_StuFee)
            {
                if(map_term.get(objStu.Program_Enrollment__r.hed__Program_Plan__c) != null)
                {
                    List<String> strList = new list<String>();
                    if(objStu.Session__c != null)
                    {
                        strList = objStu.Session__c.split('');
                    }
                    for(hed__Term__c objTerm : map_term.get(objStu.Program_Enrollment__r.hed__Program_Plan__c))
                    {
                        if(!strList.isEmpty() && strList[0] =='1' &&  objTerm.Term_Number__c ==1)
                        {
                            Student_Fee__c objNewStuFee = new Student_Fee__c();
                            objNewStuFee.Id = objStu.Id;
                            If(objStu.Fee_Type__c == 'University Fee' && objTerm.hed__Start_Date__c != null)
                                objNewStuFee.Due_Date__c =  objTerm.hed__Start_Date__c.adddays(29);
                            else if(objStu.Fee_Type__c == 'Tuition Fee' && objTerm.hed__Start_Date__c != null)
                                objNewStuFee.Due_Date__c =  objTerm.hed__Start_Date__c.adddays(30);
                            lst_UpStuFee.add(objNewStuFee);
                        }
                        if (!strList.isEmpty() && strList[0] == '2' && objTerm.Term_Number__c == 3) {
                            Student_Fee__c objNewStuFee = new Student_Fee__c();
                            objNewStuFee.Id = objStu.Id;
                            
                            if (objStu.Contact__r.Enrollment_Type__c == 'Regular Entry') {
                                // Regular Entry logic
                                if (objStu.Fee_Type__c == 'University Fee' && objTerm.hed__Start_Date__c != null) {
                                    objNewStuFee.Due_Date__c = objTerm.hed__Start_Date__c.addDays(29);
                                } else if (objStu.Fee_Type__c == 'Tuition Fee' && objTerm.hed__Start_Date__c != null) {
                                    objNewStuFee.Due_Date__c = objTerm.hed__Start_Date__c.addDays(30);
                                }
                            } else if (objStu.Contact__r.Enrollment_Type__c == 'Lateral Entry') {
                                // Lateral Entry logic
                                if (objStu.Fee_Type__c == 'University Fee' && objTerm.IA_1_Start_date__c != null) {
                                    objNewStuFee.Due_Date__c = objTerm.IA_1_Start_date__c.addDays(-1);
                                } else if (objStu.Fee_Type__c == 'Tuition Fee' && objTerm.IA_1_Start_date__c != null) {
                                    objNewStuFee.Due_Date__c = objTerm.IA_1_Start_date__c;
                                }
                            }
                            
                            lst_UpStuFee.add(objNewStuFee);
                        }
                        if(!strList.isEmpty() && strList[0] =='3' &&  objTerm.Term_Number__c ==5)
                        {
                            Student_Fee__c objNewStuFee = new Student_Fee__c();
                            objNewStuFee.Id = objStu.Id;
                            If(objStu.Fee_Type__c == 'University Fee' && objTerm.hed__Start_Date__c != null)
                                objNewStuFee.Due_Date__c =  objTerm.hed__Start_Date__c.adddays(29);
                            else if(objStu.Fee_Type__c == 'Tuition Fee' && objTerm.hed__Start_Date__c != null)
                                objNewStuFee.Due_Date__c =  objTerm.hed__Start_Date__c.adddays(30);
                            lst_UpStuFee.add(objNewStuFee);
                        }
                        if(!strList.isEmpty() && strList[0] =='4' &&  objTerm.Term_Number__c ==7)
                        {
                            Student_Fee__c objNewStuFee = new Student_Fee__c();
                            objNewStuFee.Id = objStu.Id;
                            If(objStu.Fee_Type__c == 'University Fee' && objTerm.hed__Start_Date__c != null)
                                objNewStuFee.Due_Date__c =  objTerm.hed__Start_Date__c.adddays(29);
                            else if(objStu.Fee_Type__c == 'Tuition Fee' && objTerm.hed__Start_Date__c != null)
                                objNewStuFee.Due_Date__c =  objTerm.hed__Start_Date__c.adddays(30);
                            lst_UpStuFee.add(objNewStuFee);
                        }
                        if(!strList.isEmpty() && strList[0] =='5' &&  objTerm.Term_Number__c ==9)
                        {
                            Student_Fee__c objNewStuFee = new Student_Fee__c();
                            objNewStuFee.Id = objStu.Id;
                            If(objStu.Fee_Type__c == 'University Fee' && objTerm.hed__Start_Date__c != null)
                                objNewStuFee.Due_Date__c =  objTerm.hed__Start_Date__c.adddays(29);
                            else if(objStu.Fee_Type__c == 'Tuition Fee' && objTerm.hed__Start_Date__c != null)
                                objNewStuFee.Due_Date__c =  objTerm.hed__Start_Date__c.adddays(30);
                            lst_UpStuFee.add(objNewStuFee);
                        }
                    }
                }
            }
        }
        if(lst_UpStuFee.size() >0) update lst_UpStuFee;
    }
    global void finish(Database.BatchableContext BC){
        
    }
}