force-app/main/default/objects/Contact/fields/Active_Semester__c.field-meta.xml
<CustomField>
    <fullName>Active_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Semester</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>hed__Term__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Semester</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Father_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Name__c</fullName>
    <formula>Father__r.FirstName + &apos; &apos; +  Father__r.MiddleName + &apos; &apos; + Father__r.LastName</formula>
    <label>Father Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mother_Name__c.field-meta.xml
<CustomField>
    <fullName>Mother_Name__c</fullName>
    <label>Mother Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Select_Category__c.field-meta.xml
<CustomField>
    <fullName>Select_Category__c</fullName>
    <label>Select Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Non-Karnataka</fullName>
            </value>
            <value>
                <fullName>Indian (SAARC)</fullName>
            </value>
            <value>
                <fullName>Non-Resident Indian(NRI)</fullName>
            </value>
            <value>
                <fullName>Foreign Nationals</fullName>
            </value>
            <value>
                <fullName>1A</fullName>
                <isActive>false</isActive>
                <label>1A</label>
            </value>
            <value>
                <fullName>1G</fullName>
                <isActive>false</isActive>
                <label>1G</label>
            </value>
            <value>
                <fullName>2A</fullName>
                <isActive>false</isActive>
                <label>2A</label>
            </value>
            <value>
                <fullName>2B</fullName>
                <isActive>false</isActive>
                <label>2B</label>
            </value>
            <value>
                <fullName>3A</fullName>
                <isActive>false</isActive>
                <label>3A</label>
            </value>
            <value>
                <fullName>3B</fullName>
                <isActive>false</isActive>
                <label>3B</label>
            </value>
            <value>
                <fullName>BC</fullName>
                <isActive>false</isActive>
                <label>BC</label>
            </value>
            <value>
                <fullName>BC-1</fullName>
                <isActive>false</isActive>
                <label>BC-1</label>
            </value>
            <value>
                <fullName>C-1</fullName>
                <isActive>false</isActive>
                <label>C-1</label>
            </value>
            <value>
                <fullName>C1</fullName>
                <isActive>false</isActive>
                <label>C1</label>
            </value>
            <value>
                <fullName>Cat-1</fullName>
                <isActive>false</isActive>
                <label>Cat-1</label>
            </value>
            <value>
                <fullName>ComedK</fullName>
                <isActive>false</isActive>
                <label>ComedK</label>
            </value>
            <value>
                <fullName>Diploma CET</fullName>
                <isActive>false</isActive>
                <label>Diploma CET</label>
            </value>
            <value>
                <fullName>EARLY BIRD SCHEME PROPOSAL</fullName>
                <isActive>false</isActive>
                <label>EARLY BIRD SCHEME PROPOSAL</label>
            </value>
            <value>
                <fullName>FOREIGN NATIONAL</fullName>
                <isActive>false</isActive>
                <label>FOREIGN NATIONAL</label>
            </value>
            <value>
                <fullName>GM</fullName>
                <isActive>false</isActive>
                <label>GM</label>
            </value>
            <value>
                <fullName>General</fullName>
                <isActive>false</isActive>
                <label>General</label>
            </value>
            <value>
                <fullName>Indian National</fullName>
                <isActive>false</isActive>
                <label>Indian National</label>
            </value>
            <value>
                <fullName>KEA</fullName>
                <isActive>false</isActive>
                <label>KEA</label>
            </value>
            <value>
                <fullName>NRI</fullName>
                <isActive>false</isActive>
                <label>NRI</label>
            </value>
            <value>
                <fullName>NT (B)</fullName>
                <isActive>false</isActive>
                <label>NT (B)</label>
            </value>
            <value>
                <fullName>OBC</fullName>
                <isActive>false</isActive>
                <label>OBC</label>
            </value>
            <value>
                <fullName>OC</fullName>
                <isActive>false</isActive>
                <label>OC</label>
            </value>
            <value>
                <fullName>Open</fullName>
                <isActive>false</isActive>
                <label>Open</label>
            </value>
            <value>
                <fullName>PGCET</fullName>
                <isActive>false</isActive>
                <label>PGCET</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reva_Transport__c/Reva_Transport__c.object-meta.xml
<CustomObject>
    <label>REVA Transport</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Route_Master__c/RTR_Route_Master__c.object-meta.xml
<CustomObject>
    <description>This Object will store details about the Bus Routes, Pick up points and its capacity.</description>
    <label>Route Master</label>
    <nameField>
        <label>Route Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/Transport_Registeration__c.object-meta.xml
<CustomObject>
    <label>Transport Registration</label>
    <nameField>
        <displayFormat>RU-{0000}</displayFormat>
        <label>Name/BusPass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Reva_Transport__c.field-meta.xml
<CustomField>
    <fullName>Reva_Transport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Transport</label>
    <referenceTo>Reva_Transport__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RevaTransportHandlerTest.cls
@isTest
private class RevaTransportHandlerTest {

    @isTest
    static void testRevaTransportRegPage() {
                Id StudentRecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();

        Contact cons = new Contact(FirstName= 'test name',
                                  LastName='Name',
                                 // Active_Semester__c = sem.Id,
                                  Application_Number__c = '1223467',
                                  Select_Category__c ='	Karnataka',
                                  //Father_Name__c= 'rahul',
                                  recordTypeId=StudentRecordTypeId,
                                  Mother_Name__c='sobha',
                                  Email='testuser@example12.com'                                
                                 );
              
        insert cons; 
       // Contact obj2=testDataFactory.createContact();
        Profile p = [SELECT Id, profile.Name FROM Profile WHERE Name='Student Portal Profile'];
        User testUser = new User(
            contactId = cons.Id,
            ProfileId = p.Id,
            LastName = 'TestLastName1',
            FirstName = 'TestFirstName1',
            Email = 'testuser@example12.com',
            UserName = 'testuser@example12.com',
            Alias = 'testuse',
            CommunityNickname = 'testuser1234',
            TimeZoneSidKey = 'GMT',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
        hed__Term__c sem =testDataFactory.createSemester();
        Id UniversityRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('University Department').getRecordTypeId();
        
        system.runAs(testUser){
        
           // RTR_Route_Master__c obj1 = testDataFactory.createRouteMaster();
           // Transport_Registeration__c obj3 = testDataFactory.createTransport();
           Transport_Registeration__c tt=new Transport_Registeration__c();
            tt.Contact__c=cons.id;
            insert tt;
           
            Test.startTest();
            Transport_Registeration__c result = RevaTransportHandler.revaTransportRegPage();
            RevaTransportHandler.ContactDetails();
               
        Test.stopTest();
        System.assertNotEquals(null, result);
        }
    }

    @isTest
    static void testRevaTransportPortal() {
        // Call the RevaTransportHandler method
        Test.startTest();
        List<Reva_Transport__c> result = RevaTransportHandler.revaTransportPortal();
        Test.stopTest();
        System.assertNotEquals(null, result);
    }
}