force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Notification_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Notification_Date__c</fullName>
    <label>Last Notification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <formula>Text( Primary_Academic_Program__r.Program_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Quota__c.field-meta.xml
<CustomField>
    <fullName>Quota__c</fullName>
    <label>Quota</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Management Quota</fullName>
            </value>
            <value>
                <fullName>Government Quota</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/School_Name__c.field-meta.xml
<CustomField>
    <fullName>School_Name__c</fullName>
    <formula>School__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>School Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admission Cancelled</fullName>
            </value>
            <value>
                <fullName>Pursuing</fullName>
                <default>true</default>
                <label>Pursuing</label>
            </value>
            <value>
                <fullName>Detained</fullName>
            </value>
            <value>
                <fullName>Year Back</fullName>
            </value>
            <value>
                <fullName>Not Reported</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SMSCommunication.cls
global class SMSCommunication implements Database.Batchable<sObject>, Database.AllowsCallouts {

    // Declare RecordTypeId at class level
    global Id ContactRecTypeId;

    // Constructor to initialize RecordTypeId
    global SMSCommunication() {
        // Set the RecordTypeId for the "Student" record type
        this.ContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
    }

    // Batch start method to return the query locator
    global Database.QueryLocator start(Database.BatchableContext bc) {
        // Fetch contacts based on criteria
        return Database.getQueryLocator([
            SELECT Id, Name, Active__c, Quota__c, Last_Notification_Date__c, 
                   ReportsToId, MobilePhone
            FROM Contact
            WHERE Student_Status__c = 'Pursuing'
            AND RecordTypeId = :ContactRecTypeId
            AND Program_Type__c != 'Ph.D'
            AND School_Name__c != 'REVA Academy for Corporate Excellence'
            AND Program_Batch__r.hed__Start_Date__c != null
        ]);
    }

    // Batch execute method to process each batch of contacts
    global void execute(Database.BatchableContext bc, List<Contact> lstCon) {
        // List to hold the SMS details
        List<SMS_API_Utility.shortMessageWrp> lstShortMsg = new List<SMS_API_Utility.shortMessageWrp>();
        
        for(Contact con : lstCon) {
            // Create SMS message wrapper for each contact
            SMS_API_Utility.shortMessageWrp objShortMsg = new SMS_API_Utility.shortMessageWrp();
            objShortMsg.message = 'REVA University is NOT associated with any unauthorized fresher\'s events promoted by outsiders. These are false claims and may risk your safety. Disregard such invites.';
            
            // Add to message list only if MobilePhone is not blank
            if(String.isNotBlank(con.MobilePhone)) {
                objShortMsg.recipient = '+91' + con.MobilePhone;
                lstShortMsg.add(objShortMsg);
            }
        }
        
        System.debug('Total messages to be sent: ' + lstShortMsg.size());
        
        if(lstShortMsg.size() > 0) {
            try {
                // Map HTTP Request and send SMS
                HttpRequest hReq = SMS_API_Utility.SendSMSOneToMany('Misleading Information', lstShortMsg);
                //Http http = new Http();
                //HttpResponse hRsp = http.send(hReq);

                
            } catch(Exception ex) {
                // Catch and log any exceptions
                System.debug('Error occurred while sending SMS: ' + ex.getMessage());
            }
        }
    }

    // Time conversion utility method (24-hour to 12-hour format)
    global static String getTimeDetails(String timeDetails) {
        if (String.isBlank(timeDetails)) {
            return ''; // Handle null or empty input
        }
        String[] outTimeSplit = timeDetails.split(':');
        Integer hour = Integer.valueOf(outTimeSplit[0]);
        String minute = outTimeSplit[1];

        if (hour >= 12) {
            hour = hour == 12 ? 12 : hour - 12;
            return String.valueOf(hour) + ':' + minute + ' PM';
        } else {
            return (hour < 10 ? '0' : '') + String.valueOf(hour) + ':' + minute + ' AM';
        }
    }

    // Batch finish method to log completion
    global void finish(Database.BatchableContext bc) {
        
    }
}