force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Father__c.field-meta.xml
<CustomField>
    <fullName>Father__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Father</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Father</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RH_Parent_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>RH_Parent_Phone_Number__c</fullName>
    <label>RH Parent Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Reva_Transport__c/Reva_Transport__c.object-meta.xml
<CustomObject>
    <label>REVA Transport</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/RTR_Reva_Transport_Request__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the transport fees concession requests for the students</description>
    <label>REVA Transport Request</label>
    <nameField>
        <displayFormat>TRQ-{0000}</displayFormat>
        <label>REVA Transport Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVA Transport Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_Descriptions__c.field-meta.xml
<CustomField>
    <fullName>RTR_Descriptions__c</fullName>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_End_Date__c.field-meta.xml
<CustomField>
    <fullName>RTR_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_Number_of_Minutes__c.field-meta.xml
<CustomField>
    <fullName>RTR_Number_of_Minutes__c</fullName>
    <label>Number of Minutes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RTR_Reva_Transport_Request__c/fields/RTR_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>RTR_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/Transport_Registeration__c.object-meta.xml
<CustomObject>
    <label>Transport Registration</label>
    <nameField>
        <displayFormat>RU-{0000}</displayFormat>
        <label>Name/BusPass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Payment Pending</fullName>
                <default>true</default>
                <label>Payment Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Reva_Transport__c.field-meta.xml
<CustomField>
    <fullName>Reva_Transport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Transport</label>
    <referenceTo>Reva_Transport__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/rtr_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>rtr_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Notification_Template__mdt/WhatsApp_Notification_Template__mdt.object-meta.xml
<CustomObject>
    <label>WhatsApp Notification Template</label>
    <pluralLabel>WhatsApp Notification Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/WhatsApp_Notification_Template__mdt/fields/Template_Field__c.field-meta.xml
<CustomField>
    <fullName>Template_Field__c</fullName>
    <label>Template Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RTRLateDropBatchParentwhatsappMul.cls
global class RTRLateDropBatchParentwhatsappMul implements Database.Batchable<sobject>, Database.AllowsCallouts {
  // RecordIds property to store the input parameter
    public String RecordIds { get; set; }

    // Constructor to initialize RecordIds
    global RTRLateDropBatchParentwhatsappMul(String contactIds) {
        this.RecordIds = contactIds;
    }

    // Start method to return query locator
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, RTR_Number_of_Minutes__c, RTR_End_Date__c,RTR_Start_Date__c, RTR_Descriptions__c 
            FROM RTR_Reva_Transport_Request__c 
            WHERE Id = :RecordIds 
        ]);
    }

    // Execute method to process the records
    global void execute(Database.BatchableContext bc, List<RTR_Reva_Transport_Request__c> requestList) {
        try {
            // Lists to store data for notifications
            //List<String> dateValues = new List<String>();
            List<String> StartDate = new List<String>();
            List<String> EndDate = new List<String>();
            List<String> numberOfMinutes = new List<String>();
            List<String> descriptions = new List<String>();

            // Iterate through the records and gather data
            for (RTR_Reva_Transport_Request__c request : requestList) {
                numberOfMinutes.add(String.valueOf(request.RTR_Number_of_Minutes__c));
                descriptions.add(request.RTR_Descriptions__c);
               // dateValues.add(String.valueOf(request.RTR_Date__c));
                StartDate.add(String.valueOf(request.RTR_Start_Date__c));
                EndDate.add(String.valueOf(request.RTR_End_Date__c));
            }

            // Query to fetch related contacts
            List<Contact> contactList = [SELECT Id, Name, MobilePhone,Father__r.name,RH_Parent_Phone_Number__c FROM Contact WHERE Id IN (SELECT Contact__c FROM Transport_Registeration__c WHERE Registration_Status__c = 'Active' AND Reva_Transport__r.Active__c = true) and MobilePhone != null];

            // Fetching template details
            String templateId = 'late_drop_off_multiple_days_parent';
            WhatsApp_Notification_Template__mdt metadata = [
                SELECT Template_Field__c 
                FROM WhatsApp_Notification_Template__mdt 
                WHERE Template_ID__c = :templateId 
                LIMIT 1
            ];

            // Map to store notifications for each contact's phone number
            Map<String, List<Yellow_AI_Utility.WhatsAppNotification>> phoneNumbersToNotifications = new Map<String, List<Yellow_AI_Utility.WhatsAppNotification>>();

            // Iterate through contacts to create notifications
            for (Contact con : contactList) {
                Yellow_AI_Utility.WhatsAppNotification notification = new Yellow_AI_Utility.WhatsAppNotification();
                notification.templateId = templateId;
                notification.params = new Map<String, String>();

                // Set dynamic values for each key based on related record
                notification.params.put('parentname', con.Father__r.name);
                notification.params.put('numberofminutes', String.join(numberOfMinutes, ','));
               // notification.params.put('date', String.join(dateValues, ','));
                notification.params.put('startdate', String.join(StartDate, ','));
                notification.params.put('enddate', String.join(EndDate, ','));
                notification.params.put('reason', String.join(descriptions, ','));

                // Add notification to map
                phoneNumbersToNotifications.put(con.RH_Parent_Phone_Number__c, new List<Yellow_AI_Utility.WhatsAppNotification>{notification});
                
                //Send Whatsapp notifications
                HttpResponse response = Yellow_AI_Utility.sendWhatsAppNotifications(phoneNumbersToNotifications);
                System.debug('Response=> '+response);
            }
          
        } catch (Exception e) {
            System.debug('Line=> ' + e.getLineNumber() + ' Exception=> ' + e.getMessage());
        }
    }

    // Finish method to execute post-processing operations
    global void finish(Database.BatchableContext bc) {
        // execute any post-processing operations
    }
}