force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Student Fee Payment</description>
    <inlineHelpText>Student Fee Payment</inlineHelpText>
    <label>Student Fee Payment</label>
    <referenceTo>Student_Fee_Payment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Actual_Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Actual_Program_Fee__c</fullName>
    <description>Actual program fee - 1st year</description>
    <label>Actual Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Contact__r.Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Concession__c.field-meta.xml
<CustomField>
    <fullName>Concession__c</fullName>
    <description>Fee waiver/concession - 1st year</description>
    <label>Concession</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Course_Name_Course_Code__c.field-meta.xml
<CustomField>
    <fullName>Course_Name_Course_Code__c</fullName>
    <label>Course Name / Course Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Category__c.field-meta.xml
<CustomField>
    <fullName>Fee_Category__c</fullName>
    <label>Fee Category</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 1st Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 2nd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 3rd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 4th Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 5th Year</label>
            </value>
            <value>
                <fullName>University Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 1st Year</label>
            </value>
            <value>
                <fullName>University Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 2nd Year</label>
            </value>
            <value>
                <fullName>University Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 3rd Year</label>
            </value>
            <value>
                <fullName>University Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 4th Year</label>
            </value>
            <value>
                <fullName>University Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 5th Year</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Year__c.field-meta.xml
<CustomField>
    <fullName>Fee_Year__c</fullName>
    <label>Fee Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1st Year</fullName>
            </value>
            <value>
                <fullName>2nd Year</fullName>
            </value>
            <value>
                <fullName>3rd Year</fullName>
            </value>
            <value>
                <fullName>4th Year</fullName>
            </value>
            <value>
                <fullName>5th Year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Number_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Installments__c</fullName>
    <label>Number of times Payment Allowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Paid_Installments__c.field-meta.xml
<CustomField>
    <fullName>Paid_Installments__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Times Payments Made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Premium__c.field-meta.xml
<CustomField>
    <fullName>Premium__c</fullName>
    <description>Premium fee (if any) - 1st year</description>
    <label>Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <formula>Contact__r.SRN_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SRN Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Student, Applicant,Non Teaching,Alumni,Professor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student  Payments</relationshipLabel>
    <relationshipName>Student_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeBalanceFeeTest.cls
@isTest
public class ChangeBalanceFeeTest {
    
    @isTest
    static void testProcessContacts() {
        // Create test data
        List<Contact> testContacts = new List<Contact>();
        for(Integer i = 0; i < 5; i++) {
            testContacts.add(new Contact(
                FirstName = 'TestFirstName' + i,
                LastName = 'TestLastName' + i
            ));
        }
        insert testContacts;
        
        List<ChangeBalanceFee.InputParameters> inputParamsList = new List<ChangeBalanceFee.InputParameters>();
        ChangeBalanceFee.InputParameters inputParams = new ChangeBalanceFee.InputParameters();
        inputParams.contactIds = new List<Id>();
        for(Contact con : testContacts) {
            inputParams.contactIds.add(con.Id);
        }
        inputParamsList.add(inputParams);
        
        // Call the method to be tested
        Test.startTest();
        ChangeBalanceFee.processContacts(inputParamsList);
        Test.stopTest();
        
    }    @istest(SeeAllData= true)
     static void HandleUpdate(){
        Profile p = [select Id,name from Profile where Name ='Counselor' limit 1];       
        User newUser1 = new User(
             profileId = p.Id,
             username = 'newUsertestineuser@epeople.com',
             email = 'pb@f.com',
             emailencodingkey = 'UTF-8',
             localesidkey = 'en_US',
             languagelocalekey = 'en_US',
             timezonesidkey = 'America/Los_Angeles',
             alias='nuser',
             lastname='lastname',
            MobilePhone='+91-9962357136'
             
         );
         insert newUser1;
        Contact testContact = new Contact(
            FirstName = 'Test',
            LastName = 'Contact',
            hed__WorkEmail__c='ugcet260098400001@reva.edu.in',
            OwnerId = newUser1.Id
        );
         insert testContact;
       
        Student_Payment__c student=new Student_Payment__c();
        student.Contact__c=testContact.id;
        student.Payment_Status__c='Pending';
         student.Amount__c=100;
        insert student;
        Student_Payment__c student1=new Student_Payment__c();
        student1.Contact__c=testContact.id;
        student1.Payment_Status__c='Pending';
        
        List<Student_Payment__c> newPayments=new List<Student_Payment__c>();
        newPayments.add(student);
        newPayments.add(student1);
        Student_Fee__c stuFee12 = new Student_Fee__c();
        stuFee12.contact__c = testContact.Id;
        stuFee12.Fee_Year__c = '1st Year';
        stuFee12.Name = 'University Fee 1st year';
        stuFee12.Amount__c = 100;
        stuFee12.Fee_Type__c =  'University Fee';
        insert stuFee12;
        
        Student_Fee_Payment__c stpp=new Student_Fee_Payment__c();
        stpp.Student_Fee__c=stuFee12.id;
        stpp.Student_Payment__c=student.Id;
        stpp.Amount__c= 100;
        insert stpp;
         system.debug('stpp:'+stpp.id);
         list<Id> stulist=new list<Id>{testContact.Id};
         test.starttest();
         ChangeBalanceFee.InsertStudentFeePay(stulist);
         test.stoptest();
    }
   
    
    @isTest
    static void ElseUniversity1Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 5000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'University Fee 1st year';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Success';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 50;
        insert objStuPayment;
        
        list<Id> stulist=new list<Id>{objCon.Id};
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
    }
    
    
    @isTest
    static void University1Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 5000;
        objStudentFee.Amount_Pending__c=4000;
        objStudentFee.Amount_Paid__c=1000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'university fee 1st year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'university Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=50000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Fee__c objStudentFee1 = new Student_Fee__c();     
        objStudentFee1.Amount__c = 4000;
        objStudentFee1.Amount_Pending__c=3000;
        objStudentFee1.Amount_Paid__c=1000;
        objStudentFee1.Contact__c = objCon.id;
        objStudentFee1.name = 'Tuition fee 1st year';
        objStudentFee1.Due_Date__c = system.today() - 1;
        objStudentFee1.Fee_Type__c = 'tuition Fee';
        objStudentFee1.Actual_Program_Fee__c=100000;
        objStudentFee1.Concession__c=6000;
        objStudentFee1.Course_Name_Course_Code__c='230101';
        objStudentFee1.Description__c='Thanks for the Your Interest';
        objStudentFee1.Fee_Category__c='Application';
        objStudentFee1.Number_of_Installments__c=5.0;
        objStudentFee1.Paid_Installments__c=3.0;
        objStudentFee1.Premium__c=12;
        objStudentFee1.Received_Source__c='Manual / Upload';
        objStudentFee1.Room_Sharing_Details__c= 'three';
        objStudentFee1.Scholarship__c= 23;
        objStudentFee1.Scholarship_Category__c= 'sports';
        Insert objStudentFee1;
        
        Student_Fee__c objStudentFee12 = new Student_Fee__c();     
        objStudentFee12.Amount__c = 4000;
        objStudentFee12.Amount_Pending__c=3000;
        objStudentFee12.Amount_Paid__c=1000;
        objStudentFee12.Contact__c = objCon.id;
        objStudentFee12.name = 'University fee 2nd year';
        objStudentFee12.Due_Date__c = system.today() - 1;
        objStudentFee12.Fee_Type__c = 'University Fee';
        objStudentFee12.Actual_Program_Fee__c=100000;
        objStudentFee12.Concession__c=6000;
        objStudentFee12.Course_Name_Course_Code__c='230101';
        objStudentFee12.Description__c='Thanks for the Your Interest';
        objStudentFee12.Fee_Category__c='Application';
        objStudentFee12.Number_of_Installments__c=5.0;
        objStudentFee12.Paid_Installments__c=3.0;
        objStudentFee12.Premium__c=12;
        objStudentFee12.Received_Source__c='Manual / Upload';
        objStudentFee12.Room_Sharing_Details__c= 'three';
        objStudentFee12.Scholarship__c= 23;
        objStudentFee12.Scholarship_Category__c= 'sports';
        Insert objStudentFee12;
        
        Student_Fee__c objStudentFee13 = new Student_Fee__c();     
        objStudentFee13.Amount__c = 6000;
        objStudentFee13.Amount_Pending__c=5000;
        objStudentFee13.Amount_Paid__c=1000;
        objStudentFee13.Contact__c = objCon.id;
        objStudentFee13.name = 'Tuition fee 2nd year';
        objStudentFee13.Due_Date__c = system.today() - 1;
        objStudentFee13.Fee_Type__c = 'Tuition Fee';
        objStudentFee13.Actual_Program_Fee__c=100000;
        objStudentFee13.Concession__c=6000;
        objStudentFee13.Course_Name_Course_Code__c='230101';
        objStudentFee13.Description__c='Thanks for the Your Interest';
        objStudentFee13.Fee_Category__c='Application';
        objStudentFee13.Number_of_Installments__c=5.0;
        objStudentFee13.Paid_Installments__c=3.0;
        objStudentFee13.Premium__c=12;
        objStudentFee13.Received_Source__c='Manual / Upload';
        objStudentFee13.Room_Sharing_Details__c= 'three';
        objStudentFee13.Scholarship__c= 23;
        objStudentFee13.Scholarship_Category__c= 'sports';
        Insert objStudentFee13;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Success';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 1000;
        insert objStuPayment;
        
        Student_Fee_Payment__c sfp = new Student_Fee_Payment__c(Student_Fee__c = objStudentFee12.id,
                                                               Student_Payment__c = objStuPayment.id);
        insert sfp;
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        ChangeBalanceFee.testCoverage();
        Test.stopTest(); 
        
    }
    @isTest
    static void Tuition1Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 5000;
        objStudentFee.Amount_Pending__c=4000;
        objStudentFee.Amount_Paid__c=1000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 1st year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Actual_Program_Fee__c=10000;
        objStudentFee.Concession__c=1000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
    }
    
    @isTest
    static void University2ndYear() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'university fee 2nd year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'university Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void University3Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'University Fee 3rd year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void University4Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'University Fee 4th year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void University5Year() {
        
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'University Fee 5th year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    
    @isTest
    static void Tuition2Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 2nd year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
        
    }
    @isTest
    static void Tuition3Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 3rd year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
        
    }
    @isTest
    static void Tuition4Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 4th year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
        
    }
    @isTest
    static void Tuition5Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 5th year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void Tuition51Year() {
        
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 500000;
        objStudentFee.Amount_Pending__c=400000;
        objStudentFee.Amount_Paid__c=100000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 5th year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void Tuition41Year() {
        
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 500000;
        objStudentFee.Amount_Pending__c=400000;
        objStudentFee.Amount_Paid__c=100000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 4th year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }@isTest
    static void Tuition31Year() {
        
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 500000;
        objStudentFee.Amount_Pending__c=400000;
        objStudentFee.Amount_Paid__c=100000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 3rd year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }@isTest
    static void Tuition21Year() {
        
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 500000;
        objStudentFee.Amount_Pending__c=400000;
        objStudentFee.Amount_Paid__c=100000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 2nd year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }@isTest
    static void Tuition11Year() {
        
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 500000;
        objStudentFee.Amount_Pending__c=400000;
        objStudentFee.Amount_Paid__c=100000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'Tuition Fee 1st year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'Tuition Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    } @isTest
    static void University22ndYear() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 500000;
        objStudentFee.Amount_Pending__c=400000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'university fee 1st year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'university Fee';
        objStudentFee.Actual_Program_Fee__c=1000000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 5000000;
        insert objStuPayment;
        
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void University23Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'University Fee 3rd year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void University44Year() {
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'University Fee 4th year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void University53Year() {
        
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'University Fee 5th year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    @isTest
    static void University22Year() {
        
        contact objCon = new contact();
        objCon.LastName = 'karthi';
        objCon.MobilePhone='+91-9876543210';
        objCon.Email ='kg@gmail.com';
        objCon.Application_Number__c = '1234455';
        objCon.SRN_Number__c = '123';
        objCon.hed__WorkEmail__c='ugcet260098400001@reva.edu.in';
        insert objCon;
        
        Student_Fee__c objStudentFee = new Student_Fee__c();     
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=40000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Contact__c = objCon.id;
        objStudentFee.name = 'University Fee 2nd year';
        objStudentFee.Due_Date__c = system.today() - 1;
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Actual_Program_Fee__c=100000;
        objStudentFee.Concession__c=10000;
        objStudentFee.Course_Name_Course_Code__c='230101';
        objStudentFee.Description__c='Thanks for the Your Interest';
        objStudentFee.Fee_Category__c='Application';
        objStudentFee.Number_of_Installments__c=5.0;
        objStudentFee.Paid_Installments__c=3.0;
        objStudentFee.Premium__c=12;
        objStudentFee.Received_Source__c='Manual / Upload';
        objStudentFee.Room_Sharing_Details__c= 'three';
        objStudentFee.Scholarship__c= 23;
        objStudentFee.Scholarship_Category__c= 'sports';
        Insert objStudentFee;
        
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Pending';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee, Tuition Fee';
        objStuPayment.Amount__c = 500000;
        insert objStuPayment;
        
        list<Id> stulist=new list<Id>{objCon.Id};
            
            
            Test.startTest();
        ChangeBalanceFee.InsertStudentFeePay(stulist);
        Test.stopTest();
        
    }
    
}