force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Push_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>Push_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <label>SAP ID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Student Fee Payment</description>
    <inlineHelpText>Student Fee Payment</inlineHelpText>
    <label>Student Fee Payment</label>
    <referenceTo>Student_Fee_Payment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DB-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_Log__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Debug Logs</relationshipLabel>
    <relationshipName>Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Status_Code__c</fullName>
    <label>Status Code</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Debug Logs</relationshipLabel>
    <relationshipName>Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Student_Fee_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee Payment</label>
    <referenceTo>Student_Fee_Payment__c</referenceTo>
    <relationshipLabel>Debug Logs</relationshipLabel>
    <relationshipName>Debug_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAPSLCMIntegrationURL__mdt/SAPSLCMIntegrationURL__mdt.object-meta.xml
<CustomObject>
    <label>SAPSLCMIntegrationURL</label>
    <pluralLabel>SAPSLCMIntegrationURL</pluralLabel>
</CustomObject>

force-app/main/default/objects/SAPSLCMIntegrationURL__mdt/fields/EndPointURL__c.field-meta.xml
<CustomField>
    <fullName>EndPointURL__c</fullName>
    <label>EndPointURL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <formula>Contact__r.Application_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Demand_Number__c.field-meta.xml
<CustomField>
    <fullName>Demand_Number__c</fullName>
    <label>Demand Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Payment_Mode_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Type__c</fullName>
    <label>Payment Mode Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Cheque_DD_Date__c.field-meta.xml
<CustomField>
    <fullName>Cheque_DD_Date__c</fullName>
    <description>The Date mentioned on the Cheque/DD</description>
    <inlineHelpText>Date mentioned on the Cheque/DD</inlineHelpText>
    <label>Cheque/DD Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Cheque_DD_Number__c.field-meta.xml
<CustomField>
    <fullName>Cheque_DD_Number__c</fullName>
    <description>To Enter the Cheque/DD number of the payment by the Applicant</description>
    <inlineHelpText>Enter Cheque/DD number</inlineHelpText>
    <label>Cheque/DD Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Cheque_DD_Realisation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cheque_DD_Realisation_Date__c</fullName>
    <description>Captures Cheque/DD Realisation Date</description>
    <inlineHelpText>Capture Cheque/DD Realisation Date</inlineHelpText>
    <label>Cheque/DD Realisation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Integrated_with_SAP__c.field-meta.xml
<CustomField>
    <fullName>Integrated_with_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integrated with SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Line_Item_Payment_Gateway__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Payment_Gateway__c</fullName>
    <label>Payment Gateway</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Razorpay</fullName>
            </value>
            <value>
                <fullName>Eazypay</fullName>
            </value>
            <value>
                <fullName>Paytm</fullName>
            </value>
            <value>
                <fullName>Billdesk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <inlineHelpText>For offline payment through reference number.</inlineHelpText>
    <label>Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Payment_Mode_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Type__c</fullName>
    <inlineHelpText>Debit Card / Credit Card / Netbanking / UPI</inlineHelpText>
    <label>Payment Mode Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Push_to_SAP__c.field-meta.xml
<CustomField>
    <fullName>Push_to_SAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Push to SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_ID__c</fullName>
    <label>SAP ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Transaction_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date_Time__c</fullName>
    <label>Transaction Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status (Technical)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SAP_OnlineAPI.cls
public class SAP_OnlineAPI {
    @future(callout=true)
    public static void OnlineAPIMethod(List<Id> studentFeePayIds){
        RecursiveTriggerHandler.isFirstTime = false;
        Debug_Log__c debugLog = new Debug_Log__c();
        List<Debug_Log__c> lst_DbLogs = new List<Debug_Log__c>();
        List<Student_Fee_Payment__c>lst_StduentFeePayments = new List<Student_Fee_Payment__c>();
        
        try
        {
            SAPSLCMIntegrationURL__mdt mdt = SAPSLCMIntegrationURL__mdt.getInstance('Online_Payment_API');
            String endpointURL = mdt.EndPointURL__c;
            
            List<RequestBodyWrapper> RequestBodyWrapperList = new List<RequestBodyWrapper>();
            for(Student_Fee_Payment__c objStudentFeePay :[SELECT Mode_of_Payment__c, Payment_Mode_Type__c,Line_Item_Payment_Gateway__c, Transaction_Status__c, Transaction_Date_Time__c, Id, Amount__c, Cheque_DD_Date__c,
                                                          Student_Fee__r.Contact__c,Push_to_SAP__c,Student_Fee__r.Demand_Number__c,  Student_Fee__r.Contact__r.SAP_ID__c,Student_Fee__r.Contact__r.Application_Number__c,
                                                          Cheque_DD_Realisation_Date__c, Cheque_DD_Number__c, Payment_Date__c FROM Student_Fee_Payment__c where 
                                                          Id In : studentFeePayIds])
            {
                RequestBodyWrapper objReqWrp = new RequestBodyWrapper();
                objReqWrp.Contact =objStudentFeePay.Student_Fee__r.Contact__r.Application_Number__c ;
                objReqWrp.Offline_Receipt_Number = '';
                objReqWrp.Amount =objStudentFeePay.Amount__c;
                objReqWrp.PaymentStatus = objStudentFeePay.Transaction_Status__c;
                objReqWrp.Payment_Date_Time = objStudentFeePay.Transaction_Date_Time__c.addHours(5).addMinutes(30);

                //objReqWrp.Payment_Date_Time =  objStudentFeePay.Transaction_Date_Time__c.addHours(-objStudentFeePay.Transaction_Date_Time__c.hourGmt());
                objReqWrp.Demand_Number = objStudentFeePay.Student_Fee__r.Demand_Number__c;
                objReqWrp.Mode_of_Payment = objStudentFeePay.Mode_of_Payment__c;
                objReqWrp.Payment_Mode_Type = objStudentFeePay.Line_Item_Payment_Gateway__c;
                objReqWrp.PayAmount = objStudentFeePay.Amount__c;
                objReqWrp.CheckNumber = objStudentFeePay.Cheque_DD_Number__c;
                objReqWrp.Cheque_DD_Date = objStudentFeePay.Cheque_DD_Date__c;
                objReqWrp.Cheque_DD_Realisation_Date =objStudentFeePay.Cheque_DD_Realisation_Date__c;
                objReqWrp.SFDCRecordId = objStudentFeePay.Id;
                RequestBodyWrapperList.add(objReqWrp);
            }
            
            String requestBodyJson = JSON.serialize(RequestBodyWrapperList);
             System.debug('requestBodyJson: ' + requestBodyJson);
            
            HttpRequest request = new HttpRequest();
            request.setEndpoint(endpointURL);
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setBody(requestBodyJson);
            request.setTimeout(120000);
            
            HttpResponse response = new Http().send(request);
            system.debug('response'+response);
            Decimal statusCode = response.getStatusCode();
            String responseBody = response.getBody();
            System.debug('statusCode: ' + statusCode);
            System.debug('responseBody: ' + responseBody);
            
            
            debugLog.Request__c = request.getBody();
            debugLog.Response__c = response.getBody();
              debugLog.Status_Code__c = response.getStatusCode();
            insert debugLog;
            
            
            if (statusCode == 200) 
            {
                OuterResponseWrapper outerResponseWrapper = (OuterResponseWrapper) JSON.deserialize(response.getBody(), OuterResponseWrapper.class);
                List<ResponseWrapper> responseWrappers = outerResponseWrapper.Response;
                //List<ResponseWrapper> responseWrappers = (List<ResponseWrapper>) JSON.deserialize(response.getBody(), List<ResponseWrapper>.class);
                System.debug('responseWrappers: ' + responseWrappers);
                for (ResponseWrapper responseWrapper : responseWrappers) 
                {
                    if (responseWrapper.statusCode == 0 && responseWrapper.SFDCRecordId != null && responseWrapper.SAPID != null) 
                    {
                        Student_Fee_Payment__c update_Student_Fee_Pay = new Student_Fee_Payment__c(Id = responseWrapper.SFDCRecordId);
                        update_Student_Fee_Pay.SAP_ID__c = responseWrapper.SAPID;
                        update_Student_Fee_Pay.Integrated_with_SAP__c = true;
                        update_Student_Fee_Pay.Push_to_SAP__c = false;
                        Debug_Log__c dblog = new Debug_Log__c();
                        dblog.Student_Fee_Payment__c = responseWrapper.SFDCRecordId;
                        dblog.Response__c = responseWrapper.responseObject;
                        dblog.Request__c = request.getBody();
                         dblog.Status__c = 'Success';
                        dblog.Status_Code__c = responseWrapper.statusCode;
                        lst_DbLogs.add(dblog);
                        lst_StduentFeePayments.add(update_Student_Fee_Pay);
                    }
                    else if(responseWrapper.statusCode == 1){
                        Student_Fee_Payment__c update_Student_Fee_Pay = new Student_Fee_Payment__c(Id = responseWrapper.SFDCRecordId);
                        update_Student_Fee_Pay.SAP_ID__c = responseWrapper.SAPID;
                        update_Student_Fee_Pay.Push_to_SAP__c = false;
                        Debug_Log__c dblog = new Debug_Log__c();
                        dblog.Student_Fee_Payment__c = responseWrapper.SFDCRecordId;
                        dblog.Response__c = responseWrapper.responseObject;
                        dblog.Request__c = request.getBody();
                         dblog.Status__c = 'Failure';
                         dblog.Status_Code__c = responseWrapper.statusCode;
                        
                        lst_DbLogs.add(dblog);
                        lst_StduentFeePayments.add(update_Student_Fee_Pay);
                    }
                }
                if (!lst_StduentFeePayments.isEmpty()) 
                {
                    //update lst_StduentFeePayments;
                    Database.UpsertResult[] upsertResults = Database.upsert(lst_StduentFeePayments, Student_Fee_Payment__c.Fields.Id, false);
                    for (Integer i = 0; i < upsertResults.size(); i++) {
                        if (!upsertResults[i].isSuccess()) {
                            lst_DbLogs[i].Response__c += upsertResults[i].getErrors()[0].getMessage();
                        }
                    }
                }
                if (!lst_DbLogs.isEmpty()) {
                    insert lst_DbLogs;
                }
                
            } 
            else 
            {
                System.debug('Error: ' + statusCode + ' ' + response.getStatus());
            }
            
        }
        catch (Exception e) 
        {
            System.debug('An error occurred: ' + e.getMessage());
            debugLog.Response__c +='====='+e.getMessage();
            upsert debugLog;
        }
    }
    public class OuterResponseWrapper {
        public List<ResponseWrapper> Response;
    }
    public class RequestBodyWrapper 
    {
        public String Contact;
        public String Offline_Receipt_Number;
        public Decimal Amount;
        public String PaymentStatus;
        public Datetime Payment_Date_Time;
        public String Demand_Number;
        public String Mode_of_Payment;
        public String Payment_Mode_Type;
        public Decimal PayAmount;
        public String CheckNumber;
        public Date Cheque_DD_Date;
        public Date Cheque_DD_Realisation_Date;
        public String SFDCRecordId;
        
        
    }
    
    public class ResponseWrapper 
    {
        public String SFDCRecordId;
        public Integer statusCode;
        public String statusMessage;
        public String SAPID;
        public String responseObject;
    }
}