force-app/main/default/objects/Contact/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>hed__Preferred_Email__c</fullName>
    <description>The email (University, Work, Alternate) that this Contact prefers you to use.</description>
    <inlineHelpText>The email (University, Work, Alternate) that this Contact prefers you to use.</inlineHelpText>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Work Email</fullName>
            </value>
            <value>
                <fullName>Personal Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee_Payment_Criteria__c/Fee_Payment_Criteria__c.object-meta.xml
<CustomObject>
    <label>Fee Payment Criteria</label>
    <nameField>
        <label>Fee Payment Criteria Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fee Payment Criterias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee_Payment_Criteria__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Mess Penalty Fees</fullName>
                <isActive>false</isActive>
                <label>Mess Penalty Fees</label>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Payment_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Fee_Payment_Criteria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee Payment Criteria</label>
    <referenceTo>Fee_Payment_Criteria__c</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 1st Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 2nd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 3rd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 4th Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 5th Year</label>
            </value>
            <value>
                <fullName>University Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 1st Year</label>
            </value>
            <value>
                <fullName>University Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 2nd Year</label>
            </value>
            <value>
                <fullName>University Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 3rd Year</label>
            </value>
            <value>
                <fullName>University Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 4th Year</label>
            </value>
            <value>
                <fullName>University Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 5th Year</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Number_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Installments__c</fullName>
    <label>Number of times Payment Allowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Paid_Installments__c.field-meta.xml
<CustomField>
    <fullName>Paid_Installments__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Times Payments Made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Student, Applicant,Non Teaching,Alumni,Professor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student  Payments</relationshipLabel>
    <relationshipName>Student_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OfflinePaymentRestAPI_Test.cls
@isTest
public class OfflinePaymentRestAPI_Test {
 @isTest
    public static  void SAP_Offline(){
        string houseHoldRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Household).getRecordTypeId();
        Account objAcc = new Account();
        objAcc.Name  = 'Testing';
        objAcc.Recordtypeid = houseHoldRecType;
        Insert objAcc;
        
        Id ContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        Id ProgramrecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Academic_Program).getRecordTypeId();
        
        Contact objCon = new Contact();
        objCon.LastName = 'testing';
        objcon.RecordTypeId = ContactRecTypeId;            
        objcon.RecordTypeId = ContactRecTypeId;
        objcon.hed__WorkEmail__c='123@reva.edu.in';
        //objcon.Email = 'test@reva.edu.in';            
        objcon.MobilePhone ='8963210547';
        objcon.AccountId = objAcc.id;            
        //objcon.hed__Preferred_Email__c='Personal Email';
        Insert objCon;
        
        
         Fee_Payment_Criteria__c objFeeCriteria = ASM_TestDataFactory.createFeePaymentCriteria1('Full Payment');
        Insert objFeeCriteria;
        Student_Fee__c objStudentFee = ASM_TestDataFactory.createStudentFee(objFeeCriteria.Id, objCon.Id,'Hostel Fee'); //Academic Fee'
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=2;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Number_of_Installments__c =3;
        objStudentFee.Paid_Installments__c =1;  
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Due_Date__c = system.today().addDays(-1);
      
        Insert objStudentFee;
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Success';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Fee_Type__c = 'University Fee';
        
        insert objStuPayment;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/StudentPaymentOfflineAPI'; 
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res; 
        
        /* OfflinePaymentRestAPI.PaymentData wrprdata = new OfflinePaymentRestAPI.PaymentData();
wrprdata.Contact = '';*/
        
        // Assuming you have the Contact Id and other relevant data
        OfflinePaymentRestAPI.PaymentData wrprdata = new OfflinePaymentRestAPI.PaymentData();
        wrprdata.Contact = objCon.Id; 
        
        wrprdata.Offline_Receipt_Number = '2023001'; 
        wrprdata.Amount = 1000.00; 
        wrprdata.Mode_of_Payment = 'Offline'; 
        wrprdata.Payment_Date_Time = Datetime.now();
      
        wrprdata.SFDCRecordID = objStuPayment.Id; 
        wrprdata.Demand_Number = 'D2023-001'; 
        wrprdata.Payment_Status = 'Success'; 
        wrprdata.Payment_Mode_Type = 'Offline'; 
        wrprdata.Cheque_DD_Number = '123456'; 
         Date todayDate = Date.today();
        
        String formattedDate= String.valueOf(todayDate.year()) + '-' + String.valueOf(todayDate.month()).leftPad(2, '0') + '-' + String.valueOf(todayDate.day()).leftPad(2, '0');
        wrprdata.Cheque_DD_Date =  formattedDate;
        wrprdata.Cheque_DD_Realisation_Date = formattedDate;
       
        wrprdata.Cheque_DD_Realisation_Date =formattedDate;
        wrprdata.Cheque_Bank_Name = 'ABC Bank'; 
        wrprdata.SAP_Code = 'SAP123'; 
        //wrprdata.PaymentStatus = 'Success'; 
        
        List<OfflinePaymentRestAPI.PaymentData> lst_offPdata = new List<OfflinePaymentRestAPI.PaymentData>();    
        lst_offPdata.add(wrprdata);
        list<Student_Payment__c> lst_Std_Pay = new list<Student_Payment__c>();
        lst_Std_Pay.add(objStuPayment);
        Test.startTest();
        OfflinePaymentRestAPI.createOrUpdateStudentPayments(lst_offPdata);
        Test.stopTest();  
    }
    @isTest
    public static  void SAP_Offline2(){
        string houseHoldRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Household).getRecordTypeId();
        Account objAcc = new Account();
        objAcc.Name  = 'Testing';
        objAcc.Recordtypeid = houseHoldRecType;
        Insert objAcc;
        
        Id ContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        Id ProgramrecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Academic_Program).getRecordTypeId();
        
        Contact objCon = new Contact();
        objCon.LastName = 'testing';
        objcon.RecordTypeId = ContactRecTypeId;            
        objcon.RecordTypeId = ContactRecTypeId;
        objcon.hed__WorkEmail__c='123@reva.edu.in';
        //objcon.Email = 'test@reva.edu.in';            
        objcon.MobilePhone ='8963210547';
        objcon.AccountId = objAcc.id;            
        //objcon.hed__Preferred_Email__c='Personal Email';
        Insert objCon;
        
          Fee_Payment_Criteria__c objFeeCriteria = ASM_TestDataFactory.createFeePaymentCriteria1('Full Payment');
        Insert objFeeCriteria;
        Student_Fee__c objStudentFee = ASM_TestDataFactory.createStudentFee(objFeeCriteria.Id, objCon.Id,'Hostel Fee'); //Academic Fee'
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=2000000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Number_of_Installments__c =3;
        objStudentFee.Paid_Installments__c =1;  
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Due_Date__c = null;
      
        Insert objStudentFee;
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Success';
        objStuPayment.Contact__c = objcon.id;
        insert objStuPayment;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/StudentPaymentOfflineAPI'; 
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res; 
        
        /* OfflinePaymentRestAPI.PaymentData wrprdata = new OfflinePaymentRestAPI.PaymentData();
wrprdata.Contact = '';*/
        
        // Assuming you have the Contact Id and other relevant data
        OfflinePaymentRestAPI.PaymentData wrprdata = new OfflinePaymentRestAPI.PaymentData();
        wrprdata.Contact = objCon.Id; 
        
        wrprdata.Offline_Receipt_Number = '2023001'; 
        wrprdata.Amount = 1000.00; 
        wrprdata.Mode_of_Payment = 'Offline'; 
        wrprdata.Payment_Date_Time = Datetime.now();
      
        wrprdata.SFDCRecordID = objStuPayment.Id; 
        wrprdata.Demand_Number = 'D2023-001'; 
        wrprdata.Payment_Status = 'Success'; 
        wrprdata.Payment_Mode_Type = 'Offline'; 
        wrprdata.Cheque_DD_Number = '123456'; 
         Date todayDate = Date.today();
        
        String formattedDate= String.valueOf(todayDate.year()) + '-' + String.valueOf(todayDate.month()).leftPad(2, '0') + '-' + String.valueOf(todayDate.day()).leftPad(2, '0');
        wrprdata.Cheque_DD_Date = formattedDate;
        wrprdata.Cheque_DD_Realisation_Date =formattedDate;
       
        wrprdata.Cheque_DD_Realisation_Date = formattedDate;
        wrprdata.Cheque_Bank_Name = 'ABC Bank'; 
        wrprdata.SAP_Code = ''; 
        //wrprdata.PaymentStatus = 'Success'; 
        
        List<OfflinePaymentRestAPI.PaymentData> lst_offPdata = new List<OfflinePaymentRestAPI.PaymentData>();    
        lst_offPdata.add(wrprdata);
        list<Student_Payment__c> lst_Std_Pay = new list<Student_Payment__c>();
        lst_Std_Pay.add(objStuPayment);
        Test.startTest();
        OfflinePaymentRestAPI.createOrUpdateStudentPayments(lst_offPdata);
        Test.stopTest();  
    }
     @isTest
    public static  void SAP_Offline3(){
        string houseHoldRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Household).getRecordTypeId();
        Account objAcc = new Account();
        objAcc.Name  = 'Testing';
        objAcc.Recordtypeid = houseHoldRecType;
        Insert objAcc;
        
        Id ContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        Id ProgramrecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Academic_Program).getRecordTypeId();
        
        Contact objCon = new Contact();
        objCon.LastName = 'testing';
        objcon.RecordTypeId = ContactRecTypeId;            
        objcon.RecordTypeId = ContactRecTypeId;
        objcon.hed__WorkEmail__c='123@reva.edu.in';
        //objcon.Email = 'test@reva.edu.in';            
        objcon.MobilePhone ='8963210547';
        objcon.AccountId = objAcc.id;            
        //objcon.hed__Preferred_Email__c='Personal Email';
        Insert objCon;
        
          Fee_Payment_Criteria__c objFeeCriteria = ASM_TestDataFactory.createFeePaymentCriteria1('Full Payment');
        Insert objFeeCriteria;
        Student_Fee__c objStudentFee = ASM_TestDataFactory.createStudentFee(objFeeCriteria.Id, objCon.Id,'Hostel Fee'); //Academic Fee'
        objStudentFee.Amount__c = 50000;
        objStudentFee.Amount_Pending__c=2000000;
        objStudentFee.Amount_Paid__c=10000;
        objStudentFee.Number_of_Installments__c =3;
        objStudentFee.Paid_Installments__c =1;  
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Due_Date__c = null;
      
        Insert objStudentFee;
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Success';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Amount__c = 2000;
        insert objStuPayment;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/StudentPaymentOfflineAPI'; 
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res; 
        
        /* OfflinePaymentRestAPI.PaymentData wrprdata = new OfflinePaymentRestAPI.PaymentData();
wrprdata.Contact = '';*/
        
        // Assuming you have the Contact Id and other relevant data
        OfflinePaymentRestAPI.PaymentData wrprdata = new OfflinePaymentRestAPI.PaymentData();
        wrprdata.Contact = objCon.Id; 
        
        wrprdata.Offline_Receipt_Number = '2023001'; 
        wrprdata.Amount = 1000.00; 
        wrprdata.Mode_of_Payment = 'Offline'; 
        wrprdata.Payment_Date_Time = Datetime.now();
      
        wrprdata.SFDCRecordID = objStuPayment.Id; 
        wrprdata.Demand_Number = 'D2023-001'; 
        wrprdata.Payment_Status = 'Success'; 
        wrprdata.Payment_Mode_Type = 'Offline'; 
        wrprdata.Cheque_DD_Number = '123456'; 
         Date todayDate = Date.today();
        
        String formattedDate= String.valueOf(todayDate.year()) + '-' + String.valueOf(todayDate.month()).leftPad(2, '0') + '-' + String.valueOf(todayDate.day()).leftPad(2, '0');
        wrprdata.Cheque_DD_Date =  formattedDate;
        wrprdata.Cheque_DD_Realisation_Date = formattedDate;
       
        wrprdata.Cheque_DD_Realisation_Date =formattedDate;
        wrprdata.Cheque_Bank_Name = 'ABC Bank'; 
        wrprdata.SAP_Code = 'SAP123'; 
        //wrprdata.PaymentStatus = 'Success'; 
        
        List<OfflinePaymentRestAPI.PaymentData> lst_offPdata = new List<OfflinePaymentRestAPI.PaymentData>();    
        lst_offPdata.add(wrprdata);
        list<Student_Payment__c> lst_Std_Pay = new list<Student_Payment__c>();
        lst_Std_Pay.add(objStuPayment);
        Test.startTest();
        OfflinePaymentRestAPI.createOrUpdateStudentPayments(lst_offPdata);
        Test.stopTest();  
    }
     @isTest
    public static  void SAP_Offline4(){
        string houseHoldRecType = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Household).getRecordTypeId();
        Account objAcc = new Account();
        objAcc.Name  = 'Testing';
        objAcc.Recordtypeid = houseHoldRecType;
        Insert objAcc;
        
        Id ContactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Student').getRecordTypeId();
        Id ProgramrecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByName().get(Utility.Acc_RecType_Academic_Program).getRecordTypeId();
        
        Contact objCon = new Contact();
        objCon.LastName = 'testing';
        objcon.RecordTypeId = ContactRecTypeId;            
        objcon.RecordTypeId = ContactRecTypeId;
        objcon.hed__WorkEmail__c='123@reva.edu.in';
        //objcon.Email = 'test@reva.edu.in';            
        objcon.MobilePhone ='8963210547';
        objcon.AccountId = objAcc.id;            
        //objcon.hed__Preferred_Email__c='Personal Email';
        Insert objCon;
        
          Fee_Payment_Criteria__c objFeeCriteria = ASM_TestDataFactory.createFeePaymentCriteria1('Full Payment');
        Insert objFeeCriteria;
        Student_Fee__c objStudentFee = ASM_TestDataFactory.createStudentFee(objFeeCriteria.Id, objCon.Id,'Hostel Fee'); //Academic Fee'
        objStudentFee.Amount__c = 2000000;
        objStudentFee.Amount_Pending__c=2000000;
        objStudentFee.Amount_Paid__c=1000;
        objStudentFee.Number_of_Installments__c =3;
        objStudentFee.Paid_Installments__c =1;  
        objStudentFee.Fee_Type__c = 'University Fee';
        objStudentFee.Due_Date__c = null;
      
        Insert objStudentFee;
        Student_Payment__c objStuPayment = new Student_Payment__c();
        objStuPayment.Payment_Status__c = 'Success';
        objStuPayment.Contact__c = objcon.id;
        objStuPayment.Amount__c = 2000;
        insert objStuPayment;
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/StudentPaymentOfflineAPI'; 
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json'); 
        RestContext.request = req;
        RestContext.response = res; 
        
        /* OfflinePaymentRestAPI.PaymentData wrprdata = new OfflinePaymentRestAPI.PaymentData();
wrprdata.Contact = '';*/
        
        // Assuming you have the Contact Id and other relevant data
        OfflinePaymentRestAPI.PaymentData wrprdata = new OfflinePaymentRestAPI.PaymentData();
        wrprdata.Contact = objCon.Id; 
        
        wrprdata.Offline_Receipt_Number = '2023001'; 
        wrprdata.Amount = 1000.00; 
        wrprdata.Mode_of_Payment = 'Offline'; 
        wrprdata.Payment_Date_Time = Datetime.now();
      
        wrprdata.SFDCRecordID = objStuPayment.Id; 
        wrprdata.Demand_Number = 'D2023-001'; 
        wrprdata.Payment_Status = 'Success'; 
        wrprdata.Payment_Mode_Type = 'Offline'; 
        wrprdata.Cheque_DD_Number = '123456'; 
         Date todayDate = Date.today();
        
        String formattedDate= String.valueOf(todayDate.year()) + '-' + String.valueOf(todayDate.month()).leftPad(2, '0') + '-' + String.valueOf(todayDate.day()).leftPad(2, '0');
        wrprdata.Cheque_DD_Date = formattedDate;
        wrprdata.Cheque_DD_Realisation_Date = formattedDate;
       
        wrprdata.Cheque_DD_Realisation_Date =formattedDate;
        wrprdata.Cheque_Bank_Name = 'ABC Bank'; 
        wrprdata.SAP_Code = 'SAP123'; 
        //wrprdata.PaymentStatus = 'Success'; 
        
        List<OfflinePaymentRestAPI.PaymentData> lst_offPdata = new List<OfflinePaymentRestAPI.PaymentData>();    
        lst_offPdata.add(wrprdata);
        list<Student_Payment__c> lst_Std_Pay = new list<Student_Payment__c>();
        lst_Std_Pay.add(objStuPayment);
        Test.startTest();
        OfflinePaymentRestAPI.createOrUpdateStudentPayments(lst_offPdata);
        Test.stopTest();  
    }
}