force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Blood_Group__c.field-meta.xml
<CustomField>
    <fullName>Blood_Group__c</fullName>
    <label>Blood Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A+</fullName>
            </value>
            <value>
                <fullName>A-</fullName>
            </value>
            <value>
                <fullName>AB+</fullName>
            </value>
            <value>
                <fullName>AB-</fullName>
            </value>
            <value>
                <fullName>B+</fullName>
            </value>
            <value>
                <fullName>B-</fullName>
            </value>
            <value>
                <fullName>O+</fullName>
            </value>
            <value>
                <fullName>O-</fullName>
            </value>
            <value>
                <fullName>NOT KNOWN</fullName>
                <isActive>false</isActive>
                <label>NOT KNOWN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Employee_Number__c.field-meta.xml
<CustomField>
    <fullName>Employee_Number__c</fullName>
    <externalId>true</externalId>
    <label>Employee Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/File_Passport_Size_Photo__c.field-meta.xml
<CustomField>
    <fullName>File_Passport_Size_Photo__c</fullName>
    <label>File Passport Size Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Form_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Form_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Form Submitted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__Gender__c.field-meta.xml
<CustomField>
    <fullName>hed__Gender__c</fullName>
    <description>Indicates the person&apos;s self-identified gender.</description>
    <inlineHelpText>Indicates the person&apos;s self-identified gender.</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>hed__Preferred_Email__c</fullName>
    <description>The email (University, Work, Alternate) that this Contact prefers you to use.</description>
    <inlineHelpText>The email (University, Work, Alternate) that this Contact prefers you to use.</inlineHelpText>
    <label>Preferred Email</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Work Email</fullName>
            </value>
            <value>
                <fullName>Personal Email</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
                <isActive>false</isActive>
                <label>Divorced</label>
            </value>
            <value>
                <fullName>Divorced and not remarried</fullName>
                <isActive>false</isActive>
                <label>Divorced and not remarried</label>
            </value>
            <value>
                <fullName>Female</fullName>
                <isActive>false</isActive>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
                <isActive>false</isActive>
                <label>Male</label>
            </value>
            <value>
                <fullName>Married but separated.</fullName>
                <isActive>false</isActive>
                <label>Married but separated.</label>
            </value>
            <value>
                <fullName>Spinster</fullName>
                <isActive>false</isActive>
                <label>Spinster</label>
            </value>
            <value>
                <fullName>Widowed</fullName>
                <isActive>false</isActive>
                <label>Widowed</label>
            </value>
            <value>
                <fullName>Widowed and not remarried</fullName>
                <isActive>false</isActive>
                <label>Widowed and not remarried</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Afghan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Anguillan</fullName>
            </value>
            <value>
                <fullName>Antiguans</fullName>
            </value>
            <value>
                <fullName>Argentinean</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Barbudans</fullName>
            </value>
            <value>
                <fullName>Batswana</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bermudian</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Botswanan</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Professor_School_Name__c.field-meta.xml
<CustomField>
    <fullName>Professor_School_Name__c</fullName>
    <formula>Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Professor School Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Batch</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Primary_Academic_Program__c</field>
            <operation>equals</operation>
            <valueField>hed__Program_Plan__c.hed__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>hed__Program_Plan__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>hed__Program_Plan__c</referenceTo>
    <relationshipLabel>Contacts (Program)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Name_New__c.field-meta.xml
<CustomField>
    <fullName>Program_Name_New__c</fullName>
    <label>Program Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>University Department</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts (Faculty)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_No__c.field-meta.xml
<CustomField>
    <fullName>SRN_No__c</fullName>
    <label>SRN No</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Status__c.field-meta.xml
<CustomField>
    <fullName>Student_Status__c</fullName>
    <label>Student Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admission Cancelled</fullName>
            </value>
            <value>
                <fullName>Pursuing</fullName>
                <default>true</default>
                <label>Pursuing</label>
            </value>
            <value>
                <fullName>Detained</fullName>
            </value>
            <value>
                <fullName>Year Back</fullName>
            </value>
            <value>
                <fullName>Not Reported</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Block</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Year_Of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Year_Of_Graduation__c</fullName>
    <label>Year of Graduation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nationality__c/Nationality__c.object-meta.xml
<CustomObject>
    <label>Nationality</label>
    <nameField>
        <label>Nationality (as per 10th Marksheet) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nationalities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Trigger_Form_Submitted_CheckBox_Handler.cls
public class Trigger_Form_Submitted_CheckBox_Handler 
{    
    public static Void Form_Submitted_Contact(List<Contact>ConList, Map<Id,Contact>oldMap)
    {
        id ConRecId1 = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Alumni').getRecordTypeId();
        Set<Id> Set_conId = new Set<Id>();
        List<Contact> lst_update = new List<Contact>();
        List<Contact> lst_Con_Stud = new List<Contact>();
        List<User> lst_User = new List<User>();
        
        For(Contact Con : ConList)
        {
            If(oldMap != null && (oldMap.get(Con.Id).Form_Submitted__c !=Con.Form_Submitted__c && Con.Form_Submitted__c))
            {
                Set_conId.add(Con.Id);
            } 
        }
        if(Set_conId.size()>0)
        {
            for(User objUser :[SELECT Id,Name,ContactId,Contact.Form_Submitted__c,IsActive,Contact.Student_Status__c FROM User WHERE Id =: userInfo.getUserId()
                                and Contact.Student_Status__c = 'Completed' and ContactId != null And ContactId IN:Set_conId])
            {
                objUser.IsActive = false;
                lst_User.Add(objUser);
            }
            for(Contact con:[Select id,Program_Batch__r.hed__End_Date__c,LastName,FirstName,File_Passport_Size_Photo__c,SRN_Number__c,
                             Personal_Email__c,Blood_Group__c,MobilePhone,Marital_Status__c,hed__Gender__c,Nationality__c,Student_Status__c,
                             Birthdate,Company__c,Program_Name_New__c,School__c,Location__c,AccountId
                             from Contact where id IN:Set_conId])
            {
                con.Student_Status__c = 'Completed';
                system.debug('=====con====='+con);
                Contact ObjCon = new Contact();
                ObjCon.AccountId =Con.AccountId;
                ObjCon.LastName = Con.LastName;
                ObjCon.FirstName =  Con.FirstName;
                ObjCon.RecordTypeId = ConRecId1; 
                if(!Test.isRunningTest())
                    //ObjCon.Application_Number__c = '123';
                    objCon.SRN_No__c = Con.SRN_Number__c;
                ObjCon.Email=Con.Personal_Email__c;
                ObjCon.Blood_Group__c = Con.Blood_Group__c;
                ObjCon.MobilePhone = Con.MobilePhone;
                ObjCon.Marital_Status__c = Con.Marital_Status__c;
                ObjCon.hed__Gender__c = Con.hed__Gender__c;
                ObjCon.Nationality__c= Con.Nationality__c;
                ObjCon.Birthdate = Con.Birthdate;
                ObjCon.Company__c = Con.Company__c;
                ObjCon.Year_Of_Graduation__c = string.valueof(Con.Program_Batch__r.hed__End_Date__c.year());
                ObjCon.Program_Name_New__c = Con.Program_Name_New__c;
                ObjCon.School__c = Con.School__c;
                ObjCon.Location__c  = Con.Location__c;
                ObjCon.File_Passport_Size_Photo__c=Con.File_Passport_Size_Photo__c;
               // ObjCon.hed__WorkEmail__c= '123@reva.edu.in';
                if(Test.isRunningTest()) 
                {
                    objcon.Personal_Email__c = 'test@reva.edu.in';
                    objcon.hed__Preferred_Email__c = 'Personal Email';
                }
                lst_Con_Stud.add(ObjCon);
                lst_update.add(Con);
            }
            if(lst_Con_Stud.size()>0)
            {
                system.debug('=====lst_Con_Stud===='+lst_Con_Stud.size());
                insert lst_Con_Stud;
            }
             if(lst_update.size()>0)
            {
                update lst_update;
            }
            if(lst_User.size()>0)
            {
                update lst_User;
            }
        }
    }
    
    public static void Form_Submitted_User(List<Contact> lstContact)
    {
        String Alumni = utility.Contact_RecType_Alumni;
        Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get(Alumni).getRecordTypeId();
        Set<Id> set_ContactIds = new Set<Id>();
        List<User> lst_User = new List<User>();
        Id profileId = [SELECT Id FROM Profile WHERE Name =: Label.Alumni_Portal_Profile_Value Limit 1].Id;
        
        For(Contact objContact : lstContact)
        {
            if(objContact.RecordTypeId == recordTypeId)
            {
                set_ContactIds.add(objContact.Id);
            }
        }
        if(set_ContactIds.size()>0)
        {
            for(Contact objContact:[Select id,Name,Employee_Number__c,Email,LastName,FirstName,Designation__c,MiddleName,Professor_School_Name__c,
                                    hed__WorkEmail__c from Contact where id IN:set_ContactIds])
                
            {
                User objUser = new User();
                objUser.FirstName = objContact.FirstName;
                objUser.MiddleName = objContact.MiddleName;
                objUser.LastName = objContact.LastName;
                if(objUser.LastName.Length()>=3)
                {
                    objuser.alias =  objUser.LastName.substring(0, 3);
                }        
                else if(objUser.LastName.Length()>=2)
                {
                    objuser.alias =  objUser.LastName.substring(0, 2);
                }
                else if(objUser.LastName.Length()>=1)
                {
                    objuser.alias =  objUser.LastName.substring(0, 1);
                } 
                objUser.Email = objContact.Email;
                objUser.Username = objContact.Email;
                objUser.TimeZoneSidKey = 'GMT';
                objUser.LanguageLocaleKey = 'en_US';
                objUser.EmailEncodingKey = 'UTF-8';
                objUser.LocaleSidKey = 'en_US';
                objUser.IsActive = true;
                objUser.FederationIdentifier = objContact.Email;
                objUser.ProfileId = profileId;
                objUser.ContactId= objContact.id;
                objUser.CommunityNickname = objContact.Name+System.currentTimeMillis();
                lst_User.add(objUser);
            }
            if(lst_User.size()>0 && !Test.isRunningTest())
            {
                insert lst_User;
            }
        }
    }
}