force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RTR_Route_Master__c/RTR_Route_Master__c.object-meta.xml
<CustomObject>
    <description>This Object will store details about the Bus Routes, Pick up points and its capacity.</description>
    <label>Route Master</label>
    <nameField>
        <label>Route Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RTR_Route_Pick_Up_Point__c/RTR_Route_Pick_Up_Point__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the Pick up points of the route path and its related payments.</description>
    <label>Route Pick Up Point</label>
    <nameField>
        <label>Pick Up Point Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Route Pick Up Points</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/Transport_Registeration__c.object-meta.xml
<CustomObject>
    <label>Transport Registration</label>
    <nameField>
        <displayFormat>RU-{0000}</displayFormat>
        <label>Name/BusPass Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transport_Registeration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <formula>Contact__r.Record_Type_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Registration Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Route_Master__c.field-meta.xml
<CustomField>
    <fullName>Route_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Master</label>
    <referenceTo>RTR_Route_Master__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport_Registeration__c/fields/Route_Pick_Up_Point__c.field-meta.xml
<CustomField>
    <fullName>Route_Pick_Up_Point__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Route Pick Up Point</label>
    <referenceTo>RTR_Route_Pick_Up_Point__c</referenceTo>
    <relationshipLabel>Transport Registrations</relationshipLabel>
    <relationshipName>Transport_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RTRStudentRegSMS.cls
public class RTRStudentRegSMS {
    @InvocableMethod(label='RTR Send SMS Notifications to Student' description='RTR Send notifications via SMS')
    public static void rtrSMSNotificationStudent(List<String> recordIds) {
        if(recordIds != null && !recordIds.isEmpty()) { 
            makeCalloutAsync(recordIds);  
        } else {
            System.debug('RecordIds List is Empty');
        }
    }
    
    @Future(callout=true)
    public static void makeCalloutAsync(List<String> recordIds) {
        List<Transport_Registeration__c> TrRegList = [Select id, Contact__r.id, Route_Master__r.Name, Route_Pick_Up_Point__r.Name, Contact__r.Name, 
                                                      Contact__r.Application_Number__c, Contact__r.MobilePhone From Transport_Registeration__c 
                                                      Where Id IN:recordIds AND Registration_Type__c='Student' LIMIT 50000];
        
        if(!TrRegList.isEmpty()) {
            List<SMS_API_Utility.shortMessageWrp> messageList = new List<SMS_API_Utility.shortMessageWrp>();
            
            for(Transport_Registeration__c trReg : TrRegList) {
                String stuName = trReg.Contact__r.Name;
                String appNumber = trReg.Contact__r.Application_Number__c;
                String routeNumber = trReg.Route_Master__r.Name;
                String pickPoint = trReg.Route_Pick_Up_Point__r.Name;
                String phoneNumber = trReg.Contact__r.MobilePhone;
                
				String message = 'Dear ' + stuName +', ' +'We are pleased to inform you that your transport registration for REVA transport has been successfully processed and approved for Route Number: '+ routeNumber + ' REVA University';
                
                SMS_API_Utility.shortMessageWrp shrtMessage = new SMS_API_Utility.shortMessageWrp();
                shrtMessage.dltContentId = '1007662471495875508';
                shrtMessage.message = message;
                shrtMessage.recipient = phoneNumber;
                messageList.add(shrtMessage);
            }
            
            if(messageList.size() > 0) {
                SMS_API_Utility.SendSMSOneToMany('RTRStudent Registration Confirmation', messageList);
            }
        }
    }  
}