force-app/main/default/objects/Contact/fields/Application_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>Application_Fee_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies if an Applicant has paid for the Applicant</description>
    <inlineHelpText>True, if Applicant has successfully paid for the application</inlineHelpText>
    <label>Application Fee Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country Code for the mobile phone number</description>
    <inlineHelpText>Country code of the Mobile number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Country_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>India (+91)</fullName>
        <default>true</default>
        <label>India (+91)</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan (+93)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania (+355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa (+1684)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>United States of America (+1)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada (+1)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <masterLabel>Country Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QueueableSendApplicationNumberSMS.cls
public class QueueableSendApplicationNumberSMS  implements System.Queueable , Database.AllowsCallouts {
    Public Static final String SMS_TYPE = 'Application_Number';
    
    List<contact> conRecords;
    set<Id> batchContactIds = new set<Id>();
   
    public QueueableSendApplicationNumberSMS (list<contact> conRecords){
        this.conRecords = conRecords;
        for(contact c : conRecords){
            batchContactIds.add(c.id);
        }
    } 
    
    public void execute(QueueableContext context){
        QueueableSendApplicationNumberSMS.sendApplicationNumber(conRecords);
        Appl_ContactTriggerHandler.createApplicantUser(batchContactIds);
    }
    
    
    public static void sendApplicationNumber(list<contact> conRecords){
        System.debug('QueueableSendApplicationNumberSMS.sendApplicationNumber(conRecords);');
        System.debug(conRecords);
        for(contact contact : conRecords){
            if( contact.Application_Fee_Paid__C == true && contact.Record_Type_Name__c == 'Applicant'){
                
                string mobile = contact.MobilePhone;
                // mobile = mobile.remove('+91-');
                
                List<String> requiredVariables =  new List<String>();
                if(contact.Country_Code__c == 'India (+91)'){
                    requiredVariables.add(contact.Application_Number__C);
                    RegistrationFormUtility.futureSMS(SMS_TYPE, mobile, requiredVariables); 
                }
            }
        }
        
    }
    
   
}