force-app/main/default/objects/Contact/fields/Application_Fee_Paid__c.field-meta.xml
<CustomField>
    <fullName>Application_Fee_Paid__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Specifies if an Applicant has paid for the Applicant</description>
    <inlineHelpText>True, if Applicant has successfully paid for the application</inlineHelpText>
    <label>Application Fee Paid</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Number__c</fullName>
    <description>Applicant Number reference for Application Process</description>
    <inlineHelpText>Reference Number for Application Process</inlineHelpText>
    <label>Application Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country Code for the mobile phone number</description>
    <inlineHelpText>Country code of the Mobile number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Nick_Name__c.field-meta.xml
<CustomField>
    <fullName>Nick_Name__c</fullName>
    <formula>LOWER(SUBSTITUTE(FirstName,&quot; &quot;,&quot;&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nick Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <inlineHelpText>Capture the UTM Source from URL Parameter.</inlineHelpText>
    <label>UTM Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Country_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>India (+91)</fullName>
        <default>true</default>
        <label>India (+91)</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan (+93)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania (+355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa (+1684)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>United States of America (+1)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada (+1)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <masterLabel>Country Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Appl_ContactTriggerHandler.cls
public without sharing class Appl_ContactTriggerHandler {
    
    public static final string APPL_RT_NAME = 'Applicant';
    
    public static void applicantUserCreation(List<Contact> contactsList, Map<Id,Contact> oldMap){
        List<Contact> conRec = new List<Contact>();
        Set<Id> contactIds = new Set<Id>();
        set<Id> batchContactIds = new Set<Id>();
        for (Contact c : contactsList){
            if (c.Record_Type_Name__c == 'Applicant' &&
                oldMap.get(c.id).Application_Fee_Paid__c != c.Application_Fee_Paid__c &&
                c.Application_Fee_Paid__c == true){
                    if (!System.isBatch()){ //Future methods cannot be called from batch
                        contactIds.add(c.Id);
                    }
                    else
                    {
                        batchContactIds.add(c.Id);
                    }
                }
        }
        
        
        /* Custom Metadata can be used to configure Test_Mode to avoid user creation during testing other features. */
        if(!contactIds.isEmpty() || !batchContactIds.isEmpty()){
            try{
                if(!contactIds.isEmpty()){
                    createApplicantUser(contactIds);
                }
                else if(!batchContactIds.isEmpty()){
                    conRec = [select id, Application_Fee_Paid__C,Record_Type_Name__c,MobilePhone,Country_Code__c,Application_Number__C from contact where Id IN : batchContactIds];
                    System.enqueueJob(new QueueableSendApplicationNumberSMS(conRec));
                    
                }
                
            }
            catch (Exception e){
                System.debug('Exception Error:'+ e);
            }
        }
    }
    
    @future
    public static void createApplicantUser(Set<Id> contactIds){
        
        Id profileId = [SELECT Id FROM Profile WHERE Name = : 'Applicant Profile'].Id;
        Organization orgDetails = [Select Name, IsSandbox from Organization Limit 1];
        
        List<User> usersToBeCreated = new List<User>();
        List<User> users = [Select Id, ContactId from User Where ContactId In : contactIds];
        
        if(users.size() == 0){ //All contacts do not have user records
            for(List<Contact> contacts : [Select Id, FirstName, MiddleName, LastName, Email, Application_Number__c, Nick_Name__c,
                                          Record_Type_Name__c, Application_Fee_Paid__c, MobilePhone from Contact
                                          Where Id in : contactIds]){
                                              
                                              for(Contact c :contacts){
                                                  usersToBeCreated.add(setUserInfo(c, profileId, orgDetails));  
                                              }                                   
                                          }
        }else{ //Few contacts have user records. Creates for those who doesnt have user records.
            Map<Id,User> contactIdUserMap = new Map<Id,USer>();
            
            for(User u : users){
                contactIdUserMap.put(u.ContactId, u);
            }
            
            for(Contact c : [Select Id, FirstName, MiddleName, LastName, Email, Application_Number__c, Nick_Name__c,
                             Record_Type_Name__c, Application_Fee_Paid__c, MobilePhone from Contact
                             Where Id in : contactIds]){
                                 if(!contactIdUserMap.keySet().contains(c.Id)){
                                     usersToBeCreated.add(setUserInfo(c, profileId, orgDetails));
                                 }
                             }
        }
        if(!Test.isRunningTest()){
            system.debug('the user >>'+JSON.serializePretty(usersToBeCreated));
            insert usersToBeCreated;
        }
    }
    
    
    private static User setUserInfo(Contact c, String profileId, Organization orgDetails){
        
        User applUser = new User();
        String userFullName = c.FirstName + c.LastName;
        
        applUser.FirstName = c.FirstName;
        applUser.MiddleName = c.MiddleName;
        applUser.LastName = c.LastName;
        applUser.ContactId = c.Id;
        applUser.ProfileId = profileId;
        applUser.Email = c.Email;
        applUser.MobilePhone = c.MobilePhone;
        applUser.TimeZoneSidKey = 'Asia/Kolkata'; // CAN BE SET ALSO BASED ON THE COUNTRY OF THE CONTACT
        applUser.LanguageLocaleKey = 'en_US';
        applUser.EmailEncodingKey = 'UTF-8';
        applUser.LocaleSidKey = 'en_IN';
        applUser.IsActive = true;
        applUser.CommunityNickname = c.Nick_Name__c + System.currentTimeMillis();
        applUser.FederationIdentifier = c.Email;
        applUser.UserPreferencesDisableMessageEmail = true;
        
        
        if(userFullName.length() > 8){
            applUser.alias = userFullName.substring(0,8);
        }
        else {
            applUser.alias = userFullName;
        }
        
        if(orgDetails.IsSandbox){
            applUser.Username = c.Application_Number__c+ '@' + 'reva.edu.in.' + orgDetails.Name.deleteWhiteSpace();
        }else{
            applUser.Username = c.Application_Number__c+ '@' + 'reva.edu.in';
        }
        
        return applUser;
    }
    
    public static void updateContactSource(Map<Id,Contact> oldContactMap, List<Contact> newContacts){
        
        for(Contact eachContact : newContacts){

            if(eachContact.Record_Type_Name__C == APPL_RT_NAME){
                // Making sure that the update is from the sync -- D0nt pass utmsource in the flow. (not for creatio nor for update)
                if (eachContact.pi__last_activity__c != oldContactMap.get(eachContact.Id).pi__last_activity__c) {

 
                    if ((eachContact.utm_source__c == '' || eachContact.utm_source__c == null) 
                            && eachContact.pi__first_touch_url__c !='' && (oldContactMap.get(eachContact.Id).pi__first_touch_url__c == '' || oldContactMap.get(eachContact.Id).pi__first_touch_url__c == null)) {
                        eachContact.utm_source__c = 'Organic';
                    }
                    else if ((eachContact.utm_source__c == '' || eachContact.utm_source__c == null) 
                            && eachContact.pi__first_touch_url__c == '' && (oldContactMap.get(eachContact.Id).pi__first_touch_url__c == '' || oldContactMap.get(eachContact.Id).pi__first_touch_url__c == null)) {
                        eachContact.utm_source__c = 'Direct';
                    }
                    if (oldContactMap.get(eachContact.Id).utm_source__c != eachContact.utm_source__c) {
                        PardotSourceUtility.setSourcesOnContact(eachContact, oldContactMap.get(eachContact.Id)); 
                    }
                     
               }
            }

            
         
     }
    }
}