force-app/main/default/objects/Contact/fields/Blood_Group__c.field-meta.xml
<CustomField>
    <fullName>Blood_Group__c</fullName>
    <label>Blood Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A+</fullName>
            </value>
            <value>
                <fullName>A-</fullName>
            </value>
            <value>
                <fullName>AB+</fullName>
            </value>
            <value>
                <fullName>AB-</fullName>
            </value>
            <value>
                <fullName>B+</fullName>
            </value>
            <value>
                <fullName>B-</fullName>
            </value>
            <value>
                <fullName>O+</fullName>
            </value>
            <value>
                <fullName>O-</fullName>
            </value>
            <value>
                <fullName>NOT KNOWN</fullName>
                <isActive>false</isActive>
                <label>NOT KNOWN</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/hed__Gender__c.field-meta.xml
<CustomField>
    <fullName>hed__Gender__c</fullName>
    <description>Indicates the person&apos;s self-identified gender.</description>
    <inlineHelpText>Indicates the person&apos;s self-identified gender.</inlineHelpText>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
                <isActive>false</isActive>
                <label>Divorced</label>
            </value>
            <value>
                <fullName>Divorced and not remarried</fullName>
                <isActive>false</isActive>
                <label>Divorced and not remarried</label>
            </value>
            <value>
                <fullName>Female</fullName>
                <isActive>false</isActive>
                <label>Female</label>
            </value>
            <value>
                <fullName>Male</fullName>
                <isActive>false</isActive>
                <label>Male</label>
            </value>
            <value>
                <fullName>Married but separated.</fullName>
                <isActive>false</isActive>
                <label>Married but separated.</label>
            </value>
            <value>
                <fullName>Spinster</fullName>
                <isActive>false</isActive>
                <label>Spinster</label>
            </value>
            <value>
                <fullName>Widowed</fullName>
                <isActive>false</isActive>
                <label>Widowed</label>
            </value>
            <value>
                <fullName>Widowed and not remarried</fullName>
                <isActive>false</isActive>
                <label>Widowed and not remarried</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diploma in HR Analytics</fullName>
            </value>
            <value>
                <fullName>Master of Science in Artificial Intelligence</fullName>
            </value>
            <value>
                <fullName>Master of Science in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Master of Science in Cloud Architecture and Security</fullName>
            </value>
            <value>
                <fullName>Master of Science in Cyber Security</fullName>
            </value>
            <value>
                <fullName>MBA in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Artificial Intelligence</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Cloud Architecture and Security</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Finance</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Health care Management</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Human Resource</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Marketing</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Operations Management</fullName>
            </value>
            <value>
                <fullName>Ph.D in Management Studies</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Entrepreneurship</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Strategic Leadership</fullName>
            </value>
            <value>
                <fullName>Ph.D in Biochemistry</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Biochemistry and Microbiology</fullName>
            </value>
            <value>
                <fullName>Bachelor of Physiotherapy</fullName>
            </value>
            <value>
                <fullName>Master of Science in Biochemistry</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Sports Science</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Nutrition and Dietetics</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Medical Laboratory Technology</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Medical Radiology and Diagnostic Imaging</fullName>
            </value>
            <value>
                <fullName>Intensive Certificate Course (ICC) in Laser Assisted Hatching and Embryo Biopsy</fullName>
            </value>
            <value>
                <fullName>PGD in Clinical Embryology and Assisted Reproductive Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_No__c.field-meta.xml
<CustomField>
    <fullName>SRN_No__c</fullName>
    <label>SRN No</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Year_Of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Year_Of_Graduation__c</fullName>
    <label>Year of Graduation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/REVA_AlumniContactDetailsCtrl.cls
public class REVA_AlumniContactDetailsCtrl 
{
    @AuraEnabled
    public static wrapperCls fetchContact()
    {
        wrapperCls wrp=new wrapperCls();
        string ContactId;
        User u = [SELECT id,ContactId FROM User WHERE id=:userInfo.getUserId()];
        if(u.ContactId != null)
        {
            Contact objcon = new Contact();
            objcon =[select Id,Name,Recordtype.Name,ReportsToId from Contact where id=: u.ContactId];
            if(objcon.Recordtype.Name == utility.Contact_RecType_Alumni) ContactId =objcon.id;
        }
        if(ContactId != null)
        {
            wrp.Con= [Select Name,Id,MobilePhone,Email,SRN_No__c,Blood_Group__c,Marital_Status__c,hed__Gender__c,Program__c,Year_Of_Graduation__c,Company__c
                      
                      from Contact where id=: ContactId];
        }
        return wrp;
    }
    public class wrapperCls
    {
        @AuraEnabled public Contact con{get;set;}

    }
}