force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country Code for the mobile phone number</description>
    <inlineHelpText>Country code of the Mobile number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Revisit_OTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Revisit_OTP_Code__c</fullName>
    <label>Revisit OTP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Revisit_OTP_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Revisit_OTP_Expiration__c</fullName>
    <label>Revisit OTP Expiration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_OTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Email_OTP_Code__c</fullName>
    <description>Verification code received by the Applicant on Email</description>
    <inlineHelpText>Verification code received on Email</inlineHelpText>
    <label>Email OTP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_OTP_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Email_OTP_Expiration__c</fullName>
    <description>Expiration date/ time for Email Verification Code</description>
    <inlineHelpText>Specifies the validity for Email Verification code</inlineHelpText>
    <label>Email OTP Expiration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mobile_OTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Mobile_OTP_Code__c</fullName>
    <description>Verification code received by the Applicant on Mobile</description>
    <inlineHelpText>Verification code received on Mobile</inlineHelpText>
    <label>Mobile OTP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mobile_OTP_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Mobile_OTP_Expiration__c</fullName>
    <description>Expiration date/ time for Mobile Verification Code</description>
    <inlineHelpText>Specifies the validity for Mobile Verification code</inlineHelpText>
    <label>Mobile OTP Expiration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Country_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>India (+91)</fullName>
        <default>true</default>
        <label>India (+91)</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan (+93)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania (+355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa (+1684)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>United States of America (+1)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada (+1)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <masterLabel>Country Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/YAI_ValidateOTP.cls
@RestResource(urlMapping='/validateOtp')
global with sharing class YAI_ValidateOTP {
    
    @HttpPost
    global static YAI_Wrapper.APIResponse validateOtp() {
        RestRequest restRequest = RestContext.request;
        RestResponse restResponse = RestContext.response; 
        YAI_Wrapper.APIResponse apiResponse = new YAI_Wrapper.APIResponse();
        YAI_Wrapper.APIRequest apiRequest = new YAI_Wrapper.APIRequest();
        
        String jsonException;
        String SobjectType;
        
        //retrieve the requestBody and deserialize the json
        String jsonString = restRequest.requestBody.toString();
        try{
            apiRequest = (YAI_Wrapper.APIRequest) JSON.deserialize(jsonString, YAI_Wrapper.APIRequest.class);
        }
        catch(exception ex){
            jsonException = String.valueOf(ex.getTypeName());
            
        }        
        system.debug(apiRequest);
        //fetch all the values from the deserialized json.
        Id leadOrContactId    = apiRequest.leadOrContactId;
        string otpText = apiRequest.otpText;
        String validationType = apiRequest.validationType;
        system.debug('leadOrContactId' +leadOrContactId);
        List<Sobject> existingObject = new List<Sobject>();
       
		// Find Lead/Contact Record. 
       try{
            try{
                
                	contact con = [Select Id, Name, Revisit_OTP_Expiration__c, Revisit_OTP_Code__c from contact where Id=:leadOrContactId Limit 1];
                	System.debug('Contact'+con);
               		existingObject.add(con);
               
            	}
            	catch (Exception ex){
                	system.debug(ex.getMessage());
           		}
            if(existingObject.isEmpty()){
                
                Lead lead = [Select id,status,Country_Code__c,Mobile_OTP_Code__c,Mobile_OTP_Expiration__c,Revisit_OTP_Expiration__c,Revisit_OTP_Code__c,Email_OTP_Code__c,Email_OTP_Expiration__c from Lead where Id=:leadOrContactId Limit 1];
                existingObject.add(lead);
                System.debug('Lead'+lead);
            }           
            
        }
        catch (Exception ex){
            system.debug(ex.getMessage());
            system.debug(ex.getLineNumber());
            system.debug(ex.getTypeName());
        } 
        
        if(existingObject.size()>0){
            if(String.valueOf(existingObject[0].id.getsobjecttype())=='Contact' && validationType=='Revisit'){
                
                dateTime expirationDateTime = (dateTime)[select Id,Revisit_OTP_Expiration__c from contact where Id =:existingObject[0].id].Revisit_OTP_Expiration__c;
                
                if(existingObject[0].get('Revisit_OTP_Code__c') ==  apiRequest.otpText && expirationDateTime>System.now()){
                    apiResponse.status='valid';
                } else if(existingObject[0].get('Revisit_OTP_Code__c') ==  apiRequest.otpText && expirationDateTime<System.now()){
                    apiResponse.status = 'invalid';
                    apiResponse.reason = 'expired';
                }else if(existingObject[0].get('Revisit_OTP_Code__c') !=  apiRequest.otpText){
                    apiResponse.status = 'invalid';
                    apiResponse.reason = 'mismatch';
                }
                
            }
            else if(String.valueOf(existingObject[0].id.getsobjecttype())=='Lead' && validationType=='Revisit'){
                
                dateTime expirationDateTime = (dateTime)[select Id,Revisit_OTP_Expiration__c from lead where Id =:existingObject[0].id].Revisit_OTP_Expiration__c;
         
                if(existingObject[0].get('Revisit_OTP_Code__c') ==  apiRequest.otpText && expirationDateTime>System.now() ){
                    apiResponse.status='valid';
                } else if(existingObject[0].get('Revisit_OTP_Code__c') ==  apiRequest.otpText && expirationDateTime<System.now()){
                    apiResponse.status = 'invalid';
                    apiResponse.reason = 'expired';
                }else if(existingObject[0].get('Revisit_OTP_Code__c') !=  apiRequest.otpText){
                    apiResponse.status = 'invalid';
                    apiResponse.reason = 'mismatch';
                }
                
            }
            else if(String.valueOf(existingObject[0].id.getsobjecttype())=='Lead' && validationType=='New'&& existingObject[0].get('Country_Code__c')=='India (+91)'){
                                
                dateTime expirationDateTime = (dateTime)[select Id,Mobile_OTP_Expiration__c from lead where Id =:existingObject[0].id].Mobile_OTP_Expiration__c;

                if(existingObject[0].get('Mobile_OTP_Code__c') ==  apiRequest.otpText && expirationDateTime>System.now()){
                    apiResponse.status='valid';
                } else if(existingObject[0].get('Mobile_OTP_Code__c') ==  apiRequest.otpText && expirationDateTime<System.now()){
                    apiResponse.status = 'invalid';
                    apiResponse.reason = 'expired';
                }else if(existingObject[0].get('Mobile_OTP_Code__c') !=  apiRequest.otpText){
                    apiResponse.status = 'invalid';
                    apiResponse.reason = 'mismatch';
                }
                
            }
            else if(String.valueOf(existingObject[0].id.getsobjecttype())=='Lead' && validationType=='New'&& existingObject[0].get('Country_Code__c')!='India (+91)'){
              
                dateTime expirationDateTime = (dateTime)[select Id,Email_OTP_Expiration__c from lead where Id =:existingObject[0].id].Email_OTP_Expiration__c;
                
                if(existingObject[0].get('Email_OTP_Code__c') ==  apiRequest.otpText && expirationDateTime>System.now()){
                    apiResponse.status='valid';
                } else if(existingObject[0].get('Email_OTP_Code__c') ==  apiRequest.otpText && expirationDateTime<System.now()){
                    apiResponse.status = 'invalid';
                    apiResponse.reason = 'expired';
                }else if(existingObject[0].get('Email_OTP_Code__c') !=  apiRequest.otpText){
                    apiResponse.status = 'invalid';
                    apiResponse.reason = 'mismatch';
                }
                
            }
            
            restResponse.statusCode = 200;
        }
        
        
        else if (jsonException == 'System.JSONException') {
            
            restResponse.statusCode = 400;
            apiResponse.errorDescription ='Invalid Argument';
        }
        
        return apiResponse;
    }
}