force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>Country Code for the mobile phone number</description>
    <inlineHelpText>Country code of the Mobile number</inlineHelpText>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Revisit_OTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Revisit_OTP_Code__c</fullName>
    <label>Revisit OTP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Revisit_OTP_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Revisit_OTP_Expiration__c</fullName>
    <label>Revisit OTP Expiration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_OTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Email_OTP_Code__c</fullName>
    <description>Verification code received by the Applicant on Email</description>
    <inlineHelpText>Verification code received on Email</inlineHelpText>
    <label>Email OTP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Email_OTP_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Email_OTP_Expiration__c</fullName>
    <description>Expiration date/ time for Email Verification Code</description>
    <inlineHelpText>Specifies the validity for Email Verification code</inlineHelpText>
    <label>Email OTP Expiration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mobile_OTP_Code__c.field-meta.xml
<CustomField>
    <fullName>Mobile_OTP_Code__c</fullName>
    <description>Verification code received by the Applicant on Mobile</description>
    <inlineHelpText>Verification code received on Mobile</inlineHelpText>
    <label>Mobile OTP Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Mobile_OTP_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Mobile_OTP_Expiration__c</fullName>
    <description>Expiration date/ time for Mobile Verification Code</description>
    <inlineHelpText>Specifies the validity for Mobile Verification code</inlineHelpText>
    <label>Mobile OTP Expiration</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/globalValueSets/Country_Code.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>India (+91)</fullName>
        <default>true</default>
        <label>India (+91)</label>
    </customValue>
    <customValue>
        <fullName>Afghanistan (+93)</fullName>
    </customValue>
    <customValue>
        <fullName>Albania (+355)</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria (+213)</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa (+1684)</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra (+376)</fullName>
    </customValue>
    <customValue>
        <fullName>Angola (+244)</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla (+1264)</fullName>
    </customValue>
    <customValue>
        <fullName>Australia (+61)</fullName>
    </customValue>
    <customValue>
        <fullName>United States of America (+1)</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda (+1268)</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina (+54)</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia (+374)</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba (+297)</fullName>
    </customValue>
    <customValue>
        <fullName>Austria (+43)</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan (+994)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas (+1242)</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain (+973)</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh (+880)</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados (+1246)</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus (+375)</fullName>
    </customValue>
    <customValue>
        <fullName>Canada (+1)</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium (+32)</fullName>
    </customValue>
    <customValue>
        <fullName>Belize (+501)</fullName>
    </customValue>
    <customValue>
        <fullName>Benin (+229)</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda (+1441)</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan (+975)</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia (+591)</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina (+387)</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana (+267)</fullName>
    </customValue>
    <masterLabel>Country Code</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/YAI_SendOtp_Test.cls
@isTest
public class YAI_SendOtp_Test {
    
    @isTest
    public static void sendOtpLeadTest(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        Lead testLead = new Lead(Email='test@gmail.com', FirstName='Test', LastName='Tesla',Status='Verified',Country_Code__c='India (+91)',MobilePhone ='9876543211',Mobile_OTP_Code__c='7377',Mobile_OTP_Expiration__c=system.now(),Email_OTP_Code__c='1555',Email_OTP_Expiration__c=system.now());
        insert testLead;
        string testleadId=string.valueOf(testLead.Id);
        req.requestURI = '/services/apexrest/sendOtp';
        req.httpMethod = 'POST';
        YAI_Wrapper.APIRequest testApiRequest = new YAI_Wrapper.APIRequest();
        testApiRequest.leadOrContactId = testLead.Id;
        testApiRequest.otpDestination = 'Email';
        String Body = '{"leadOrContactId":"'+testLeadId +'","otpDestination":"email"}';
        Blob requestBody = Blob.valueOf(Body);
        req.requestBody=requestBody;
        RestContext.request = req;
        RestContext.response = res;
        YAI_Wrapper.APIResponse testApiResponse = new YAI_Wrapper.APIResponse();
        testApiResponse = YAI_SendOtp.sendOtp();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMocks_Test());
        testApiResponse.status = 'Success';
        System.assertNotEquals(null, testApiResponse.status);
        
        
    }
    @isTest
    public static void sendOtpunverifiedLeadTest(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        List<Sobject> sobjList= new List<Sobject>();
        Lead testLead = new Lead(Email='test@gmail.com', FirstName='Test', LastName='Tesla',Status='Unverified',Country_Code__c='India (+91)',MobilePhone ='9876543211',Mobile_OTP_Code__c='7377',Mobile_OTP_Expiration__c=system.now(),Email_OTP_Code__c='1555',Email_OTP_Expiration__c=system.now());
        insert testLead;
        string testleadId=string.valueOf(testLead.Id);
        sobjList.add(testlead);
        req.requestURI = '/services/apexrest/sendOtp';
        req.httpMethod = 'POST';
        YAI_Wrapper.APIRequest testApiRequest = new YAI_Wrapper.APIRequest();
        testApiRequest.leadOrContactId = testLead.Id;
        testApiRequest.otpDestination = 'Email';
        String Body = '{"leadOrContactId":"'+testLeadId +'","otpDestination":"mobile"}';
        Blob requestBody = Blob.valueOf(Body);
        req.requestBody=requestBody;
        RestContext.request = req;
        RestContext.response = res;
        YAI_Wrapper.APIResponse testApiResponse = new YAI_Wrapper.APIResponse();
        testApiResponse = YAI_SendOtp.sendOtp();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMocks_Test());
        testApiResponse.status = 'Success';
        System.assertNotEquals(null, testApiResponse.status);
        
        
    }
    @isTest
    public static void sendOtpUnVerifiedLead(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        Lead testLead = new Lead(Email='test@gmail.com', FirstName='Test', LastName='Tesla',Status='Unverified',Country_Code__c='India (+91)',MobilePhone ='9876543211',Mobile_OTP_Code__c='7377',Mobile_OTP_Expiration__c=system.now(),Email_OTP_Code__c='1555',Email_OTP_Expiration__c=system.now());
        insert testLead;
        string testLeadId = string.valueOf(testLead.Id);
        req.requestURI = 'services/apexrest/checkApplicant';
        req.httpMethod = 'POST';
        String Body = '{"leadOrContactId":"'+testLeadId +'","otpDestination":"email"}';
        system.debug('22222'+Body);
        Blob requestBody = Blob.valueOf(Body);
        req.requestBody=requestBody;
        RestContext.request = req;
        RestContext.response = res;
        YAI_Wrapper.APIResponse testApiResponse = new YAI_Wrapper.APIResponse();
        testApiResponse = YAI_SendOtp.sendOtp();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMocks_Test());
        testApiResponse.status = 'Success';
        System.assertNotEquals(null, testApiResponse.status);
        
        
    }
    
    @isTest
    public static void sendOtpContactTest(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        contact testContact = new contact(Email='tesla@gmail.com', FirstName='Star', LastName='Link',Revisit_OTP_Code__c='9900',Revisit_OTP_Expiration__c=system.now());
        insert testContact;
        string testContactId= string.valueOf(testContact.Id);
        req.requestURI = '/services/apexrest/sendOtp';
        req.httpMethod = 'POST';
        String Body = '{"leadOrContactId":"'+testcontact.Id +'","otpDestination":"Email"}';
        Blob requestBody = Blob.valueOf(Body);
        req.requestBody=requestBody;
        RestContext.request = req;
        RestContext.response = res;
        YAI_Wrapper.APIResponse testApiResponse = new YAI_Wrapper.APIResponse();
        testApiResponse = YAI_SendOtp.sendOtp();
        Test.setMock(HttpCalloutMock.class, new HttpCalloutMocks_Test());
        testApiResponse.status = 'Success';
        System.assertNotEquals(null, testApiResponse.status);
        
        
    }
    @isTest
    public static void jsonExceptionSendOtpTest(){
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/sendOtp';
        req.httpMethod = 'POST';
        String Body = '{"leadOrContactId":"0031s00000w3zXTyAY"}';
        Blob requestBody = Blob.valueOf(Body);
        req.requestBody=requestBody;
        RestContext.request = req;
        RestContext.response = res;
        YAI_Wrapper.APIResponse testApiResponse = new YAI_Wrapper.APIResponse();
        testApiResponse = YAI_SendOtp.sendOtp();
       
        testApiResponse.errorDescription = 'Invalid Argument';
        
    }
    
    
}