force-app/main/default/objects/Contact/fields/Digital_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Digital_Card_Number__c</fullName>
    <displayFormat>DG-{0000000000}</displayFormat>
    <label>Digital Card Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/File_Passport_Size_Photo__c.field-meta.xml
<CustomField>
    <fullName>File_Passport_Size_Photo__c</fullName>
    <label>File Passport Size Photo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Diploma in HR Analytics</fullName>
            </value>
            <value>
                <fullName>Master of Science in Artificial Intelligence</fullName>
            </value>
            <value>
                <fullName>Master of Science in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Master of Science in Cloud Architecture and Security</fullName>
            </value>
            <value>
                <fullName>Master of Science in Cyber Security</fullName>
            </value>
            <value>
                <fullName>MBA in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Artificial Intelligence</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Business Analytics</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Cloud Architecture and Security</fullName>
            </value>
            <value>
                <fullName>Post Graduate Diploma in Cybersecurity</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Finance</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Health care Management</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Human Resource</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Marketing</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Operations Management</fullName>
            </value>
            <value>
                <fullName>Ph.D in Management Studies</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Banking and Insurance</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Entrepreneurship</fullName>
            </value>
            <value>
                <fullName>Master of Business Administration in Strategic Leadership</fullName>
            </value>
            <value>
                <fullName>Ph.D in Biochemistry</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Biochemistry and Microbiology</fullName>
            </value>
            <value>
                <fullName>Bachelor of Physiotherapy</fullName>
            </value>
            <value>
                <fullName>Master of Science in Biochemistry</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Sports Science</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Nutrition and Dietetics</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Medical Laboratory Technology</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science in Medical Radiology and Diagnostic Imaging</fullName>
            </value>
            <value>
                <fullName>Intensive Certificate Course (ICC) in Laser Assisted Hatching and Embryo Biopsy</fullName>
            </value>
            <value>
                <fullName>PGD in Clinical Embryology and Assisted Reproductive Technology</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Name_New__c.field-meta.xml
<CustomField>
    <fullName>Program_Name_New__c</fullName>
    <label>Program Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/School_Department__c.field-meta.xml
<CustomField>
    <fullName>School_Department__c</fullName>
    <label>School/Department</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_No__c.field-meta.xml
<CustomField>
    <fullName>SRN_No__c</fullName>
    <label>SRN No</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Image__c.field-meta.xml
<CustomField>
    <fullName>Student_Image__c</fullName>
    <formula>IMAGE(File_Passport_Size_Photo__c,&apos; &apos; , 180, 150)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Image</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Year_Of_Graduation__c.field-meta.xml
<CustomField>
    <fullName>Year_Of_Graduation__c</fullName>
    <label>Year of Graduation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ALU_DigitalCard_Ext.cls
public class ALU_DigitalCard_Ext
{
    public user objUser{get;set;}
    public contact objContact{get;set;}
    public ContentDocumentLink objContDoc{get;set;}
    public boolean docExists{get;set;}
    public string programValue{get;set;}
    public ALU_DigitalCard_Ext()
    {
        string pageId = Apexpages.currentPage().getParameters().get('id');
        objContact  = new Contact();
        objUser = new user();
        objContDoc = new ContentDocumentLink();
        docExists=false;
        Id Alumni_Activities_Event_RecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Alumni').getRecordTypeId();
        objUser = [SELECT id, Name, ContactId FROM user WHERE id =: UserInfo.getUserId()];
        if(objuser.ContactId != NULL)
        {
            objContact = [SELECT id, Name, Email, SRN_No__c,MobilePhone, Birthdate,RecordTypeId, School_Department__c, Year_Of_Graduation__c, Student_Image__c,
                          File_Passport_Size_Photo__c,Digital_Card_Number__c,Program__c,Program_Name_New__c,
                          (SELECT ContentDocumentId, LinkedEntityId, ContentDocument.LatestPublishedVersionId  FROM ContentDocumentLinks
                           where LinkedEntityId =: objUser.ContactId order by ContentDocument.ContentModifiedDate desc limit 1)
                          FROM Contact WHERE id=:objuser.ContactId and  RecordTypeId =: Alumni_Activities_Event_RecType];
            if(!objContact.ContentDocumentLinks.isempty())
                docExists=true;
            if(objContact.Program__c != null)
            {
                programValue = objContact.Program__c;
            }
            else
            {
                programValue = objContact.Program_Name_New__c;
            }
        }
    }

}