force-app/main/default/objects/Contact/fields/Father__c.field-meta.xml
<CustomField>
    <fullName>Father__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Father</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Father</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mother</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mother)</relationshipLabel>
    <relationshipName>Mother</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Company__c/Rpl_Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Placement_Drive__c/Rpl_Placement_Drive__c.object-meta.xml
<CustomObject>
    <label>Placement Drive</label>
    <nameField>
        <label>Placement Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Drives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Application_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Application_End_Time__c</fullName>
    <label>Application End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Rpl_Company__c</referenceTo>
    <relationshipLabel>Placement Drives</relationshipLabel>
    <relationshipName>Placement_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_End_Date__c</fullName>
    <label>Application End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_For_Graduating_Year__c.field-meta.xml
<CustomField>
    <fullName>Rpl_For_Graduating_Year__c</fullName>
    <inlineHelpText>For which graduating year batch of student this drive is conducted for , eg:2024</inlineHelpText>
    <label>For Graduating Year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/Rpl_Student_Registration__c.object-meta.xml
<CustomObject>
    <label>Student Registrations</label>
    <nameField>
        <label>Student Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Student_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Contact_No__c</fullName>
    <label>Contact No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Personal_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Personal_Mail_ID__c</fullName>
    <label>Personal Mail - ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/Rpl_Student_Registration_Drive__c.object-meta.xml
<CustomObject>
    <description>This is a junction object for &quot;Student Registration&quot; and &quot;Placement Drives&quot; Objects. As these two objects in many to many relationship. Records in this object will be created when eligibility criteria are been inserted for any particular drive, for the eligible students. By default IsApplied checkbox will be false. When Eligible students applied for any particular drive this checkbox will be turned to true. Once drive completed, those records whose IsApplied are false will be deleted using batch class.</description>
    <label>Student Registration Drive</label>
    <nameField>
        <displayFormat>SRD-{000000}</displayFormat>
        <label>Student Registration Drive No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Registration Drives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <formula>Rpl_Placement_Drive__r.Rpl_Company_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_For_Graduating_Year__c.field-meta.xml
<CustomField>
    <fullName>Rpl_For_Graduating_Year__c</fullName>
    <formula>TEXT(Rpl_Placement_Drive__r.Rpl_For_Graduating_Year__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>For Graduating Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Is_Notification_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Notification_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be checked when an email notification is sent to the students regarding the eligibility of any particular drive.</description>
    <label>Is Notification Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Placement_Drive__c</fullName>
    <label>Placement Drive</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Student_Registration__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Student_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Registration</label>
    <referenceTo>Rpl_Student_Registration__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RPL_SendEmailToEligibleStudents.cls
public class RPL_SendEmailToEligibleStudents implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
	public String driveId;
	public String eligibleNotificationTemplate = Label.RPL_Eligible_Drive_Notifcation_Template;
	public String eligibleNotificationToFatherTemplate = Label.RPL_Drive_Registration_Message_Email_Template_To_Father;
	public String eligibleNotificationToMotherTemplate = Label.RPL_Drive_Registration_Message_Email_Template_To_Mother;
	public String studentPortalLink = Label.RPL_Student_Portal_Link;

	private Map<String, String> smsMap = new Map<String, String>();
	private Map<String, String> smsMapToParent = new Map<String, String>();

	public RPL_SendEmailToEligibleStudents(String driveId) {
		this.driveId = driveId;
	}

	@InvocableMethod(label='Activate Drive And Send Notificaiton To Eligible Students')
	public static void activateRPL_SendEmailToEligibleStudentsBatch(List<String> driveId) {
		Database.executeBatch(new RPL_SendEmailToEligibleStudents(driveId[0]), 30);
	}

	public Database.QueryLocator start(Database.BatchableContext context) {
		// Query the records you want to process
		String query =
			'SELECT Id, Rpl_Student_Registration__r.Contact__c, Rpl_Student_Registration__r.Rpl_Personal_Mail_ID__c, Rpl_Student_Registration__r.Rpl_Contact_No__c, Rpl_Student_Registration__r.Name, Rpl_Placement_Drive__r.Rpl_Company_Name__r.Name, Rpl_Placement_Drive__r.Rpl_Event_End_Date__c, Rpl_Placement_Drive__r.Rpl_For_Graduating_Year__c, Rpl_Placement_Drive__r.Rpl_Application_End_Time__c, Rpl_Student_Registration__r.Contact__r.Father__r.Email, Rpl_Student_Registration__r.Contact__r.Father__r.Name, Rpl_Student_Registration__r.Contact__r.Father__r.MobilePhone, Rpl_Student_Registration__r.Contact__r.Father__c, Rpl_Student_Registration__r.Contact__r.Mother__c, Rpl_Student_Registration__r.Contact__r.Mother__r.Email, Rpl_Student_Registration__r.Contact__r.Mother__r.Name, Rpl_Student_Registration__r.Contact__r.Mother__r.MobilePhone  FROM Rpl_Student_Registration_Drive__c Where Rpl_Placement_Drive__c = \'' +
			this.driveId +
			'\' AND Rpl_Student_Registration__r.Contact__r.Email != NULL';
		return Database.getQueryLocator(query);
	}

	// Execute method to perform the actual processing
	public void execute(Database.BatchableContext context, List<Rpl_Student_Registration_Drive__c> scope) {
		Set<String> userIds = new Set<String>();

		List<Rpl_Student_Registration_Drive__c> studentRegDriveToUpdate = new List<Rpl_Student_Registration_Drive__c>();

		Map<String, Map<String, String>> toAddressToValues = new Map<String, Map<String, String>>();

		for (Rpl_Student_Registration_Drive__c eachStudentRegistrationDrive : scope) {
			Map<String, Map<String, String>> phoneNumberToValues = new Map<String, Map<String, String>>();
			// Updating Rpl_Is_Notification_Email_Sent__c to true and updating.

			// Send Email notification
			List<String> toAddresses = new List<String>();
			if (eachStudentRegistrationDrive.Rpl_Student_Registration__r.Rpl_Contact_No__c != null) {
				Map<String, String> whatsAppvalues = new Map<String, String>();
				String studentName = eachStudentRegistrationDrive.Rpl_Student_Registration__r.Name != null
					? eachStudentRegistrationDrive.Rpl_Student_Registration__r.Name
					: 'REVA Student';
				String companyName = eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_Company_Name__r.Name != null
					? eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_Company_Name__r.Name
					: '____';
				String registrationEndDate = String.valueOf(
					eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_Event_End_Date__c
				);
				String forGraduatingYear = eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_For_Graduating_Year__c !=
					null
					? String.valueOf(eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_For_Graduating_Year__c)
					: '____';
				String contactNumber = String.valueOf(
					eachStudentRegistrationDrive.Rpl_Student_Registration__r.Rpl_Contact_No__c
				);
				String endTime = '11:59 PM';
				if (eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_Application_End_Time__c != null) {
					String hour = String.valueOf(
						eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_Application_End_Time__c.hour()
					);
					hour = hour == '0' ? '12' : hour;
					String minute = String.valueOf(
						eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_Application_End_Time__c.minute()
					);
					String AMorPM = eachStudentRegistrationDrive.Rpl_Placement_Drive__r.Rpl_Application_End_Time__c.hour() >= 12
						? 'PM'
						: 'AM';
					endTime = hour + ':' + minute + ' ' + AMorPM;
				}

				whatsAppvalues.put('studentname', studentName);
				whatsAppvalues.put('date', registrationEndDate);
				whatsAppvalues.put('companyname', companyName);
				whatsAppvalues.put('graduatingyear', forGraduatingYear);
				whatsAppvalues.put('time', endTime);
				whatsAppvalues.put('registrationurl', studentPortalLink);

				phoneNumberToValues.put(
					eachStudentRegistrationDrive.Rpl_Student_Registration__r.Rpl_Contact_No__c,
					whatsAppvalues
				);
				try {
					Rpl_UtilityClass.sendWhatsAppNotification('drive_intimation_registration_copy1', phoneNumberToValues);
					eachStudentRegistrationDrive.Rpl_Is_Notification_Email_Sent__c = true;
					studentRegDriveToUpdate.add(eachStudentRegistrationDrive);
				} catch (Exception e) {
					ErrorLogUtility.logError(e);
				}
				String message =
					'Dear ' +
					studentName +
					', ' +
					companyName +
					' Hiring Process has been scheduled for ' +
					forGraduatingYear +
					' graduating batch. Please register yourself if, interested. Last date to register is ' +
					registrationEndDate +
					' before ' +
					endTime +
					'. Check email for more information. REVA UNIVERSITY';
				smsMap.put(eachStudentRegistrationDrive.Rpl_Student_Registration__r.Rpl_Contact_No__c, message);

				if (eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Mother__r.MobilePhone != null) {
					Map<String, Map<String, String>> phoneNumberToValuesMother = new Map<String, Map<String, String>>();
					whatsAppvalues.put(
						'parentname',
						eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Mother__r.Name
					);
					phoneNumberToValuesMother.put(
						eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Mother__r.MobilePhone,
						whatsAppvalues
					);
					try {
						Rpl_UtilityClass.sendWhatsAppNotification(
							'drive_intimation_registration_message2',
							phoneNumberToValuesMother
						);
						eachStudentRegistrationDrive.Rpl_Is_Notification_Email_Sent__c = true;
					} catch (Exception e) {
						ErrorLogUtility.logError(e);
					}
					String messageToMother =
						'Dear ' +
						eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Mother__r.Name +
						' ' +
						companyName +
						' Hiring Process has been scheduled for ' +
						forGraduatingYear +
						' graduating batch. Please inform your ward to register themselves, if interested. Last date to register is ' +
						registrationEndDate +
						' before ' +
						endTime +
						'. Check email for more information. REVA University';
					smsMapToParent.put(
						eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Mother__r.MobilePhone,
						messageToMother
					);
				}
				if (eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Father__r.MobilePhone != null) {
					Map<String, Map<String, String>> phoneNumberToValuesFather = new Map<String, Map<String, String>>();
					whatsAppvalues.put(
						'parentname',
						eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Father__r.Name
					);
					phoneNumberToValuesFather.put(
						eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Father__r.MobilePhone,
						whatsAppvalues
					);
					try {
						Rpl_UtilityClass.sendWhatsAppNotification(
							'drive_intimation_registration_message2',
							phoneNumberToValuesFather
						);
						eachStudentRegistrationDrive.Rpl_Is_Notification_Email_Sent__c = true;
					} catch (Exception e) {
						ErrorLogUtility.logError(e);
					}
					String messageToFather =
						'Dear ' +
						eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Father__r.Name +
						' ' +
						companyName +
						' Hiring Process has been scheduled for ' +
						forGraduatingYear +
						' graduating batch. Please inform your ward to register themselves, if interested. Last date to register is ' +
						registrationEndDate +
						' before ' +
						endTime +
						'. Check email for more information. REVA University';
					smsMapToParent.put(
						eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Father__r.MobilePhone,
						messageToFather
					);
				}
			}

			// Rpl_UtilityClass.whatsappDriveIntimationNotification(studentName ,companyName , registrationEndDate, '11:59 PM', forGraduatingYear, studentPortalLink, contactNumber);
			if (!String.isEmpty(eachStudentRegistrationDrive.Rpl_Student_Registration__r.Rpl_Personal_Mail_ID__c)) {
				// Rpl_UtilityClass.sendEmailsUsingTemplate(eligibleNotificationTemplate, eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__c, eachStudentRegistrationDrive.Id, toAddresses);
				Map<String, String> emailValues = new Map<String, String>();
				emailValues.put('whatId', eachStudentRegistrationDrive.Id);
				emailValues.put('targetObjectId', eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__c);
				emailValues.put('emailTemplateId', eligibleNotificationTemplate);
				toAddressToValues.put(
					eachStudentRegistrationDrive.Rpl_Student_Registration__r.Rpl_Personal_Mail_ID__c,
					emailValues
				);
			}
			if (!String.isEmpty(eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Father__r.Email)) {
				Map<String, String> emailValuesFather = new Map<String, String>();
				emailValuesFather.put('whatId', eachStudentRegistrationDrive.Id);
				emailValuesFather.put(
					'targetObjectId',
					eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Father__c
				);
				emailValuesFather.put('emailTemplateId', eligibleNotificationToFatherTemplate);
				toAddressToValues.put(
					eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Father__r.Email,
					emailValuesFather
				);
			}
			if (!String.isEmpty(eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Mother__r.Email)) {
				Map<String, String> emailValuesMother = new Map<String, String>();
				emailValuesMother.put('whatId', eachStudentRegistrationDrive.Id);
				emailValuesMother.put(
					'targetObjectId',
					eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Mother__c
				);
				emailValuesMother.put('emailTemplateId', eligibleNotificationToMotherTemplate);
				toAddressToValues.put(
					eachStudentRegistrationDrive.Rpl_Student_Registration__r.Contact__r.Mother__r.Email,
					emailValuesMother
				);
			}
		}

		if (!toAddressToValues.isEmpty()) {
			try {
				Rpl_UtilityClass.sendEmailsUsingTemplate(toAddressToValues);
			} catch (Exception e) {
				ErrorLogUtility.logError(e);
			}
		}

		if (!studentRegDriveToUpdate.isEmpty()) {
			try {
				update studentRegDriveToUpdate;
			} catch (Exception e) {
				ErrorLogUtility.logError(e);
			}
		}
	}

	// Finish method to perform any post-processing
	public void finish(Database.BatchableContext context) {
		if (!smsMap.isEmpty()) {
			try {
				Rpl_UtilityClass.sendSMS('Drive Intimation Message Template', smsMap);
			} catch (Exception e) {
				ErrorLogUtility.logError(e);
			}
		}
		if (!smsMapToParent.isEmpty()) {
			try {
				Rpl_UtilityClass.sendSMS('Drive registration to parent', smsMapToParent);
			} catch (Exception e) {
				ErrorLogUtility.logError(e);
			}
		}

		// Perform any post-processing logic here
	}
}