force-app/main/default/objects/Contact/fields/Father__c.field-meta.xml
<CustomField>
    <fullName>Father__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Father</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Father</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mother</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Mother)</relationshipLabel>
    <relationshipName>Mother</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Company__c/Rpl_Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Placement_Drive__c/Rpl_Placement_Drive__c.object-meta.xml
<CustomObject>
    <label>Placement Drive</label>
    <nameField>
        <label>Placement Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Drives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Reva_Placement__c.field-meta.xml
<CustomField>
    <fullName>Reva_Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Placement</label>
    <referenceTo>Rpl_Reva_Placement__c</referenceTo>
    <relationshipLabel>Placement Drives</relationshipLabel>
    <relationshipName>Placement_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Rpl_Company__c</referenceTo>
    <relationshipLabel>Placement Drives</relationshipLabel>
    <relationshipName>Placement_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_Date_Time__c</fullName>
    <label>Event Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_End_Date__c</fullName>
    <label>Application End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Reva_Placement__c/Rpl_Reva_Placement__c.object-meta.xml
<CustomObject>
    <label>REVA Placement</label>
    <nameField>
        <label>REVA Placement  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Placements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Reva_Placement__c/fields/Rpl_Registration_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Registration_End_Date__c</fullName>
    <label>Registration End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Reva_Placement__c/fields/Rpl_Registration_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Registration_Start_Date__c</fullName>
    <label>Registration Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/Rpl_Student_Registration__c.object-meta.xml
<CustomObject>
    <label>Student Registrations</label>
    <nameField>
        <label>Student Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Student_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Reva_Placement__c.field-meta.xml
<CustomField>
    <fullName>Reva_Placement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REVA Placement</label>
    <referenceTo>Rpl_Reva_Placement__c</referenceTo>
    <relationshipName>Student_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Contact_No__c</fullName>
    <label>Contact No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Interested_in_placement__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Interested_in_placement__c</fullName>
    <label>Interested In Placement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Personal_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Personal_Mail_ID__c</fullName>
    <label>Personal Mail - ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_University_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_University_Mail_ID__c</fullName>
    <label>University Mail - ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/Rpl_Student_Registration_Drive__c.object-meta.xml
<CustomObject>
    <description>This is a junction object for &quot;Student Registration&quot; and &quot;Placement Drives&quot; Objects. As these two objects in many to many relationship. Records in this object will be created when eligibility criteria are been inserted for any particular drive, for the eligible students. By default IsApplied checkbox will be false. When Eligible students applied for any particular drive this checkbox will be turned to true. Once drive completed, those records whose IsApplied are false will be deleted using batch class.</description>
    <label>Student Registration Drive</label>
    <nameField>
        <displayFormat>SRD-{000000}</displayFormat>
        <label>Student Registration Drive No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Registration Drives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <formula>Rpl_Placement_Drive__r.Rpl_Company_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Placement_Drive__c</fullName>
    <label>Placement Drive</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Student_Registration__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Student_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Registration</label>
    <referenceTo>Rpl_Student_Registration__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RPL_AdmitCardTemplateControllerTest.cls
@isTest
public class RPL_AdmitCardTemplateControllerTest {

    @isTest
    static void testGenerateAdmitCard() {
		
		Contact Father = new Contact();
        Father.lastName = 'Test Data';
        Father.Email = 'testfather@gmail.com';
        Father.MobilePhone = '8234823428';
        insert Father;
        
        Contact Mother = new Contact();
        Mother.lastName = 'Test Data';
        Mother.Email = 'testmother@gmail.com';
        Mother.MobilePhone = '9233492348';
        insert Mother;        
        
        Contact eCon = new Contact();
        eCon.lastName = 'Test Data';
        eCon.Email = 'test@gmail.com';
        eCon.Mother__c = Mother.Id;
        eCon.Father__c = Father.Id;
        eCon.MobilePhone = '7812938493';
        insert eCon;
        
        
        Rpl_Student_Registration__c std = new Rpl_Student_Registration__c();
        std.Name = 'Test Data1';
        std.Rpl_Personal_Mail_ID__c = 'test@gmail.com';
        std.Rpl_Interested_in_placement__c = 'yes';
        std.Rpl_University_Mail_ID__c = '123123123@reva.edu.in';
         std.Rpl_Contact_No__c ='9553052925';
        std.Contact__c = eCon.Id;
        insert std;
        
        
        
        //Date startDate = Date.newInstance(2024, 1,26);
        Date startDate = System.Today();
        Date endDate = System.Today().addDays(10);
       // Date endDate1 = Date.newInstance(2026, 2, 19);
        Rpl_Reva_Placement__c rpl = new Rpl_Reva_Placement__c();
        rpl.Rpl_Registration_Start_Date__c = startDate;
        rpl.Rpl_Registration_End_Date__c = endDate;
        rpl.Name = 'Test Reva Placement-01';
        
        insert rpl;
        
        
        Rpl_Company__c  cmp = new Rpl_Company__c();
        cmp.Name = 'Amozan';
       
         insert cmp;
        
        Rpl_Placement_Drive__c plc = new Rpl_Placement_Drive__c();
        //plc.Rpl_Drive_Name__c = 'test Name';
        plc.Reva_Placement__c = rpl.Id;
        plc.Rpl_Company_Name__c = cmp.Id;
        plc.Rpl_Event_End_Date__c = endDate;
        //plc.Rpl_Event_Date_Time__c = endDate1;
        
        insert plc;
        
        
        Rpl_Student_Registration_Drive__c testStudentRegDrive = new Rpl_Student_Registration_Drive__c();
        testStudentRegDrive.Rpl_Placement_Drive__c =  plc.Id;
        testStudentRegDrive.Rpl_Student_Registration__c = std.Id;
        
        insert testStudentRegDrive;
       

        // Call the method to test
        Test.startTest();
        RPL_AdmitCardTemplateController.generateAdmitCard(testStudentRegDrive.Id, 'test@example.com');
        Test.stopTest();

        // Add assertions as needed
        // Example: Check if the attachment is created
        List<Attachment> attachments = [SELECT Id FROM Attachment WHERE ParentId = :testStudentRegDrive.Id];
       // System.assertEquals(1, attachments.size(), 'Attachment not created.');
    }

    @isTest
    static void testSavePDFAsAttachment() {
        Contact Father = new Contact();
        Father.lastName = 'Test Data';
        Father.Email = 'testfather@gmail.com';
        Father.MobilePhone = '8234823428';
        insert Father;
        
        Contact Mother = new Contact();
        Mother.lastName = 'Test Data';
        Mother.Email = 'testmother@gmail.com';
        Mother.MobilePhone = '9233492348';
        insert Mother;
        
        Contact eCon = new Contact();
        eCon.lastName = 'Test Data';
        eCon.Email = 'test@gmail.com';eCon.Mother__c = Mother.Id;
        eCon.Father__c = Father.Id;
        eCon.MobilePhone = '8323940234';
       
        
        insert eCon;
        
        
        Rpl_Student_Registration__c std = new Rpl_Student_Registration__c();
        std.Name = 'Test Data1';
        std.Rpl_Personal_Mail_ID__c = 'test@gmail.com';
        std.Rpl_Interested_in_placement__c = 'yes';
        std.Rpl_University_Mail_ID__c = '123123123@reva.edu.in';
         std.Rpl_Contact_No__c ='9553052925';
        std.Contact__c = eCon.Id;
        
        
        insert std;
        
        
        
        //Date startDate = Date.newInstance(2024, 1,26);
        Date startDate = System.Today();
        Date endDate = System.Today().addDays(10);
        //Date endDate = Date.newInstance(2026, 2, 17);
        //Date endDate1 = Date.newInstance(2026, 2, 19);
        Rpl_Reva_Placement__c rpl = new Rpl_Reva_Placement__c();
        rpl.Rpl_Registration_Start_Date__c = startDate;
        rpl.Rpl_Registration_End_Date__c = endDate;
        rpl.Name = 'Test Reva Placement-01';
        
        insert rpl;
        
        
        Rpl_Company__c  cmp = new Rpl_Company__c();
        cmp.Name = 'Amozan';
       
         insert cmp;
        
        Rpl_Placement_Drive__c plc = new Rpl_Placement_Drive__c();
       // plc.Rpl_Drive_Name__c = 'test Name';
        plc.Reva_Placement__c = rpl.Id;
        plc.Rpl_Company_Name__c = cmp.Id;
        plc.Rpl_Event_End_Date__c = endDate;
        //plc.Rpl_Event_Date_Time__c = endDate1;
        
        insert plc;
        
        
        Rpl_Student_Registration_Drive__c testStudentRegDrive = new Rpl_Student_Registration_Drive__c();
        testStudentRegDrive.Rpl_Placement_Drive__c =  plc.Id;
        testStudentRegDrive.Rpl_Student_Registration__c = std.Id;
        
        insert testStudentRegDrive;

        Blob pdfBlob = Blob.valueOf('Test PDF Content');

        // Call the method to test
        Test.startTest();
        RPL_AdmitCardTemplateController.savePDFAsAttachment(testStudentRegDrive.Id, pdfBlob, 'test@example.com');
        Test.stopTest();

        // Add assertions as needed
        // Example: Check if the attachment is created
        List<Attachment> attachments = [SELECT Id FROM Attachment WHERE ParentId = :testStudentRegDrive.Id];
        System.assertEquals(1, attachments.size(), 'Attachment not created.');
    }
}