force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Program_Batch_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Batch_Name__c</fullName>
    <formula>IF( Record_Type_Name__c =&apos;Parent&apos;, ReportsTo.Program_Batch__r.Name,Program_Batch__r.Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Program Batch Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/WhatsApp_Notification_Template__mdt/WhatsApp_Notification_Template__mdt.object-meta.xml
<CustomObject>
    <label>WhatsApp Notification Template</label>
    <pluralLabel>WhatsApp Notification Templates</pluralLabel>
</CustomObject>

force-app/main/default/objects/WhatsApp_Notification_Template__mdt/fields/Template_Field__c.field-meta.xml
<CustomField>
    <fullName>Template_Field__c</fullName>
    <label>Template Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RegNotificationForParent.cls
global class RegNotificationForParent implements Database.Batchable<sobject>, Database.AllowsCallouts {
       
	private String semName;    
    private Contact contact;
    private List<Contact> parentList;            
    
    public RegNotificationForParent(Contact conObjParam, List<Contact> parentListParam, string semNameParam){
        contact = conObjParam;
        semName = semNameParam;   
        parentList = parentListParam;
    }
    // Start method to return query locator
    global Database.QueryLocator start(Database.BatchableContext bc)  {
         System.debug('Start Method');
        
      //  Contact contactStudObj = [SELECT Id, Name,SRN_Number__c,hed__WorkEmail__c, MobilePhone, Program_Batch_Name__c FROM Contact WHERE Id = :contactId LIMIT 1];
        
        return Database.getQueryLocator([SELECT Id, Name,SRN_Number__c,hed__WorkEmail__c, MobilePhone FROM Contact LIMIT 1]);
        
	 }
     
    
 global void execute(Database.BatchableContext bc, List<Contact> contactList) {  
      try {                                     
            // Fetching template details
             String templateId = 'semester_regis_parent'; 
            WhatsApp_Notification_Template__mdt metadata = [
                SELECT Template_Field__c 
                FROM WhatsApp_Notification_Template__mdt 
                WHERE Template_ID__c = :templateId 
                LIMIT 1
            ];
            
            // Map to store notifications for each contact's phone number
            Map<String, List<Yellow_AI_Utility.WhatsAppNotification>> phoneNumbersToNotifications = new Map<String, List<Yellow_AI_Utility.WhatsAppNotification>>();         
          	String studName = contact.Name;
            String srnNumber = contact.SRN_Number__c;      
                    
            // Iterate through contacts to create notifications
            for (Contact clist : parentList) {
                Yellow_AI_Utility.WhatsAppNotification notification = new Yellow_AI_Utility.WhatsAppNotification();
                notification.templateId = templateId;
                notification.params = new Map<String, String>();
                notification.params.put('Parent_or_Guardian', clist.Name);
                notification.params.put('Semester_Name', semName);
                notification.params.put('Student_Name', studName);
                notification.params.put('SRN', srnNumber);              
                               
                // Add notification to map               
                if(clist.MobilePhone !=null){
                    String plusRemoved = clist.MobilePhone.replace('+', '');
                    String correctedWhatsappNumber = plusRemoved.replace('-', '');
                    phoneNumbersToNotifications.put(correctedWhatsappNumber, new List<Yellow_AI_Utility.WhatsAppNotification>{notification});                    
                }    //Send Whatsapp notifications
             
                HttpResponse response = Yellow_AI_Utility.sendWhatsAppNotifications(phoneNumbersToNotifications);
                System.debug('Response=> '+response);        
              
            }            
          	
         
        } catch (Exception e) {
            System.debug('Line=> ' + e.getLineNumber() + ' Exception=> ' + e.getMessage());
        }
    }

    // Finish method 
    global void finish(Database.BatchableContext bc) {
         System.debug('Finish Method');      
    }    
}