force-app/main/default/objects/Contact/fields/hed__WorkEmail__c.field-meta.xml
<CustomField>
    <fullName>hed__WorkEmail__c</fullName>
    <description>The work email for this person.</description>
    <inlineHelpText>The work email for this person.</inlineHelpText>
    <label>Work Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RegNotificationForStudentTest.cls
@isTest
private class RegNotificationForStudentTest {
    
   static testMethod void testBatchExecution() {              

        // Test data setup for hed__Application__c and hed__Applicant__c
        List<Contact> contacts = new List<Contact>();
       
            Contact con = new Contact(
                FirstName = 'TestFirstName1',
                LastName = 'TestLastName1',
                MobilePhone = '1234567890',                
                SRN_Number__c = '656TY',
                hed__WorkEmail__c = 'sanm@gmail.com'
            );           
       
        	insert con;
       
         String contactId = con.Id;
         String semName = 'MCA-3rd-Sem';
         String srnNum = 'SRN786';       

        // Start the batch
        Test.startTest();
        RegNotificationForStudent batch = new RegNotificationForStudent(contactId,semName,srnNum);
        Database.executeBatch(batch);
        Test.stopTest();
    }
}