force-app/main/default/objects/Contact/fields/Primary_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Source__c</fullName>
    <description>Specifies the source through which the Applicant landed for the first time</description>
    <inlineHelpText>First time Source of the Applicant</inlineHelpText>
    <label>Primary Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Secondary_Source__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Source__c</fullName>
    <description>Specifies the source through which the Applicant landed for the second time</description>
    <inlineHelpText>Second-time Source of the Applicant</inlineHelpText>
    <label>Secondary Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tertiary_Source__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Source__c</fullName>
    <description>Specifies the source through which the Applicant landed for the third time</description>
    <inlineHelpText>Third-time Source of the Applicant</inlineHelpText>
    <label>Tertiary Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <inlineHelpText>Capture the UTM Source from URL Parameter.</inlineHelpText>
    <label>UTM Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Primary_Source__c.field-meta.xml
<CustomField>
    <fullName>Primary_Source__c</fullName>
    <description>Specifies the source  through which the Applicant landed for the first time</description>
    <inlineHelpText>First time Source of the Applicant</inlineHelpText>
    <label>Primary Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Secondary_Source__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Source__c</fullName>
    <description>Specifies the source through which the Applicant landed for the second time</description>
    <inlineHelpText>Second-time Source of the Applicant</inlineHelpText>
    <label>Secondary Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Tertiary_Source__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Source__c</fullName>
    <description>Specifies the source through which the Applicant landed for the third time</description>
    <inlineHelpText>Third-time Source of the Applicant</inlineHelpText>
    <label>Tertiary Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/utm_source__c.field-meta.xml
<CustomField>
    <fullName>utm_source__c</fullName>
    <inlineHelpText>Capture the UTM Source from the URL Parameter.</inlineHelpText>
    <label>UTM Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PardotSourceUtility.cls
public with sharing class PardotSourceUtility {

    public static void setSourcesOnLead(Lead newLead, Lead oldLead){

        if (oldLead.Primary_Source__c == null) {
            newLead.Primary_Source__c = newLead.utm_source__c;
        }   
        else if (oldLead.Secondary_Source__c == null) {
            newLead.Secondary_Source__c = newLead.utm_source__c;
        }
        else if (oldLead.Tertiary_Source__c == null) {
            newLead.Tertiary_Source__c = newLead.utm_source__c;
        }
       
    }
    public static void setSourcesOnContact(Contact newContact, Contact oldContact){
       
        if (oldContact.Primary_Source__c == null) {
            newContact.Primary_Source__c = newContact.utm_source__c;
        }  
        else if (oldContact.Secondary_Source__c == null) {
            newContact.Secondary_Source__c = newContact.utm_source__c;
        }
        else if (oldContact.Tertiary_Source__c == null) {
            newContact.Tertiary_Source__c = newContact.utm_source__c;
        }
    }

}