force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rpl_Company__c/Rpl_Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Company Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Company__c/fields/Company_Image__c.field-meta.xml
<CustomField>
    <fullName>Company_Image__c</fullName>
    <inlineHelpText>Include high-quality images with dimensions less than 200 x 200 pixels for improved clarity when utilized in the Admit Card.</inlineHelpText>
    <label>Company Image</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Rpl_Interview__c/Rpl_Interview__c.object-meta.xml
<CustomObject>
    <label>Recruitment Stage</label>
    <nameField>
        <label>Recruitment Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recruitment Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Interview__c/fields/Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Placement_Drive__c</fullName>
    <label>Placement Drive ID</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Recruitment Stages</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Interview__c/fields/Rpl_Round_Number__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Round_Number__c</fullName>
    <inlineHelpText>Please enter only numeric values to indicate the order of the interview rounds (e.g., 1, 2, 3, 4).</inlineHelpText>
    <label>Round Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/Rpl_Placement_Drive__c.object-meta.xml
<CustomObject>
    <label>Placement Drive</label>
    <nameField>
        <label>Placement Drive Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Placement Drives</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Application_End_Time__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Application_End_Time__c</fullName>
    <label>Application End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <referenceTo>Rpl_Company__c</referenceTo>
    <relationshipLabel>Placement Drives</relationshipLabel>
    <relationshipName>Placement_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_Date__c</fullName>
    <label>Application Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_Date_Time__c</fullName>
    <label>Event Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Event_End_Date__c</fullName>
    <label>Application End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/Rpl_Job_Description_URL__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Job_Description_URL__c</fullName>
    <label>Job Description URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Rpl_Placement_Drive__c/fields/RPL_Number_Of_Applicants__c.field-meta.xml
<CustomField>
    <fullName>RPL_Number_Of_Applicants__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Applicants</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/Rpl_Student_Registration__c.object-meta.xml
<CustomObject>
    <label>Student Registrations</label>
    <nameField>
        <label>Student Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Student_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Contact_No__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Contact_No__c</fullName>
    <label>Contact No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Is_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Offer_Count__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Offer_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <description>To save the Number of Offer  for particular student</description>
    <label>Offer Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_Personal_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Personal_Mail_ID__c</fullName>
    <label>Personal Mail - ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration__c/fields/Rpl_University_Mail_ID__c.field-meta.xml
<CustomField>
    <fullName>Rpl_University_Mail_ID__c</fullName>
    <label>University Mail - ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/Rpl_Student_Registration_Drive__c.object-meta.xml
<CustomObject>
    <description>This is a junction object for &quot;Student Registration&quot; and &quot;Placement Drives&quot; Objects. As these two objects in many to many relationship. Records in this object will be created when eligibility criteria are been inserted for any particular drive, for the eligible students. By default IsApplied checkbox will be false. When Eligible students applied for any particular drive this checkbox will be turned to true. Once drive completed, those records whose IsApplied are false will be deleted using batch class.</description>
    <label>Student Registration Drive</label>
    <nameField>
        <displayFormat>SRD-{000000}</displayFormat>
        <label>Student Registration Drive No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Registration Drives</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Company_Name__c</fullName>
    <formula>Rpl_Placement_Drive__r.Rpl_Company_Name__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Interview__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interview</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Rpl_Interview__c.Placement_Drive__c</field>
            <operation>equals</operation>
            <valueField>$Source.Rpl_Placement_Drive__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Rpl_Interview__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Is_Offered__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Offered__c</fullName>
    <formula>AND( Rpl_Interview__r.Rpl_Round_Number__c = Rpl_Placement_Drive__r.Rpl_Total_Interview_Round__c , Rpl_Is_Result_Out__c, !Rpl_Is_Failed__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Offered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Is_Present__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Is_Present__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox ensures whether a student attends the drive.</description>
    <label>Is Present</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_IsApplied__c.field-meta.xml
<CustomField>
    <fullName>Rpl_IsApplied__c</fullName>
    <defaultValue>false</defaultValue>
    <description>At first, this checkbox will be unchecked, when students apply for that particular drive then it will be checked</description>
    <label>Is Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Job_Description_URL__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Job_Description_URL__c</fullName>
    <formula>Rpl_Placement_Drive__r.Rpl_Job_Description_URL__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Job Description URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Placement_Drive__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Placement_Drive__c</fullName>
    <label>Placement Drive</label>
    <referenceTo>Rpl_Placement_Drive__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rpl_Student_Registration_Drive__c/fields/Rpl_Student_Registration__c.field-meta.xml
<CustomField>
    <fullName>Rpl_Student_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Registration</label>
    <referenceTo>Rpl_Student_Registration__c</referenceTo>
    <relationshipLabel>Student Registration Drives</relationshipLabel>
    <relationshipName>Student_Registration_Drives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RPL_StudentRegisterDriveController.cls
public without sharing class RPL_StudentRegisterDriveController {
	
	@AuraEnabled(cacheable=true)
	public static List<Rpl_Student_Registration_Drive__c> getAllEligibleDrives(Id contactId) {
		Set<Id> studentRegSet = new Set<Id>();
		for (Rpl_Student_Registration__c eStd : [
			SELECT Id
			FROM Rpl_Student_Registration__c
			WHERE Contact__c = :contactId
		]) {
			studentRegSet.add(eStd.Id);
		}

		List<Rpl_Student_Registration_Drive__c> studentRegDriveList = [
			SELECT
				Id,
				Rpl_Placement_Drive__c,
				Rpl_Student_Registration__c,
				Rpl_Is_Offered__c,
				Rpl_Placement_Drive__r.Rpl_Company_Name__r.Company_Image__c,
				Rpl_Placement_Drive__r.Name,
				Rpl_Placement_Drive__r.Rpl_Company_Name__r.Name,
				Rpl_Placement_Drive__r.Rpl_Event_Date_Time__c,
				Rpl_Placement_Drive__r.Rpl_Event_Date__c,
				Rpl_Placement_Drive__r.Rpl_Job_Description_URL__c,
				Rpl_Placement_Drive__r.Rpl_Event_End_Date__c,
				Rpl_IsApplied__c,
				Rpl_Placement_Drive__r.Rpl_Application_End_Time__c,
				Rpl_Student_Registration__r.Rpl_University_Mail_ID__c,
				Rpl_Student_Registration__r.Rpl_Is_Blocked__c,
				Rpl_Student_Registration__r.Rpl_Personal_Mail_ID__c,
				Rpl_Student_Registration__r.Rpl_Contact_No__c
			FROM Rpl_Student_Registration_Drive__c
			WHERE
				Rpl_Student_Registration__c IN :studentRegSet
				AND Rpl_Placement_Drive__c != NULL
				AND Rpl_Student_Registration__c != NULL
				AND Rpl_Is_Active__c = TRUE
			ORDER BY Rpl_Placement_Drive__r.Rpl_Event_Date_Time__c DESC
		];

		return studentRegDriveList;
	}

	@AuraEnabled(cacheable=true)
	public static Integer getTotalNumberOfEligibleDrives() {
		Id loggedInUserId = UserInfo.getUserId();
		List<User> loggedInUser = [SELECT ContactId FROM User WHERE Id = :loggedInUserId LIMIT 1];
		if (!loggedInUser.isEmpty()) {
			String contactId = loggedInUser[0].Id;
			if (!String.isEmpty(contactId)) {
				List<Rpl_Student_Registration__c> studentRegistration = [
					SELECT Id
					FROM Rpl_Student_Registration__c
					WHERE Contact__c = :contactId
				];
				if (!studentRegistration.isEmpty()) {
					List<Rpl_Student_Registration_Drive__c> studentRegDriveList = [
						SELECT Id
						FROM Rpl_Student_Registration_Drive__c
						WHERE Rpl_Student_Registration__c = :studentRegistration[0].Id
					];
					return studentRegDriveList.size();
				}
			}
		}
		return 0;
	}

	@AuraEnabled(cacheable=true)
	public static String getUpcomingDrive() {
		Id loggedInUserId = UserInfo.getUserId();
		List<User> loggedInUser = [SELECT ContactId FROM User WHERE Id = :loggedInUserId LIMIT 1];
		if (!loggedInUser.isEmpty()) {
			String contactId = loggedInUser[0].Id;
			if (!String.isEmpty(contactId)) {
				List<Rpl_Student_Registration__c> studentRegistration = [
					SELECT Id
					FROM Rpl_Student_Registration__c
					WHERE Contact__c = :contactId
				];
				if (!studentRegistration.isEmpty()) {
					DateTime currentDateTime = System.now();

					List<Rpl_Student_Registration_Drive__c> studentRegDriveList = [
						SELECT Id, Rpl_Placement_Drive__r.Rpl_Event_Date_Time__c
						FROM Rpl_Student_Registration_Drive__c
						WHERE
							Rpl_Student_Registration__c = :studentRegistration[0].Id
							AND Rpl_Placement_Drive__r.Rpl_Event_Date_Time__c > :currentDateTime
						ORDER BY Rpl_Placement_Drive__r.Rpl_Event_Date_Time__c
					];
					if (!studentRegDriveList.isEmpty()) {
						String dateString = studentRegDriveList[0]
							.Rpl_Placement_Drive__r.Rpl_Event_Date_Time__c.format('yyyy-MM-dd');
						return dateString;
					}
				}
			}
		}
		return 'N/A';
	}

	@AuraEnabled(cacheable=true)
	public static Integer getOfferCount() {
		Id loggedInUserId = UserInfo.getUserId();
		List<User> loggedInUser = [SELECT ContactId FROM User WHERE Id = :loggedInUserId LIMIT 1];
		if (!loggedInUser.isEmpty()) {
			String contactId = loggedInUser[0].Id;
			if (!String.isEmpty(contactId)) {
				List<Rpl_Student_Registration__c> studentRegistration = [
					SELECT Id, Rpl_Offer_Count__c
					FROM Rpl_Student_Registration__c
					WHERE Contact__c = :contactId
				];
				if (!studentRegistration.isEmpty()) {
					return studentRegistration[0].Rpl_Offer_Count__c != null
						? (Integer) studentRegistration[0].Rpl_Offer_Count__c
						: 0;
				}
			}
		}
		return 0;
	}
	
	@AuraEnabled
	public static String updateIsApplied(String studentRegistrationDriveId) {
		try {
			Boolean isUpdated = false;
			if (String.isNotBlank(studentRegistrationDriveId)) {
				Rpl_Student_Registration_Drive__c studentRegDrive = [
					SELECT Id, Rpl_IsApplied__c, Rpl_Placement_Drive__c, Rpl_Interview__c
					FROM Rpl_Student_Registration_Drive__c
					WHERE Id = :studentRegistrationDriveId
				];

				List<Rpl_Placement_Drive__c> placementDrive = [
					SELECT Id, RPL_Number_Of_Applicants__c, (SELECT Id FROM Interviews__r WHERE Rpl_Round_Number__c = 1)
					FROM Rpl_Placement_Drive__c
					WHERE Id = :studentRegDrive.Rpl_Placement_Drive__c
				];

				if (!placementDrive.isEmpty()) {
					placementDrive[0].RPL_Number_Of_Applicants__c = (placementDrive[0].RPL_Number_Of_Applicants__c == null)
						? 1
						: placementDrive[0].RPL_Number_Of_Applicants__c + 1;
					if (!placementDrive[0].Interviews__r.isEmpty() && studentRegDrive.Rpl_Interview__c == null) {
						studentRegDrive.Rpl_Interview__c = placementDrive[0].Interviews__r[0].Id;
					}
				}

				if (studentRegDrive.Id != null) {
					studentRegDrive.Rpl_IsApplied__c = true;
					update studentRegDrive;
					update placementDrive;
					isUpdated = true;
				}
			}

			return (isUpdated) ? 'true' : 'false';
		} catch (Exception e) {
			// Log the error using ErrorLogUtility
			ErrorLogUtility.logError(e);
			return e.getMessage();
		}
	}


	@AuraEnabled(cacheable=true)
	public static AttachmentWrapper getAttachmentContent(String studentRegistrationDriveId) {
		AttachmentWrapper attWrapper = new AttachmentWrapper();

		List<Attachment> attachmentList = [
			SELECT Body, Name
			FROM Attachment
			WHERE ParentId = :studentRegistrationDriveId
			ORDER BY CreatedDate DESC
			LIMIT 1
		];

		if (!attachmentList.isEmpty()) {
			if (attachmentList[0].Body != null) {
				attWrapper.Body = EncodingUtil.base64Encode(attachmentList[0].Body);
			}
			attWrapper.Name = attachmentList[0].Name;
		}
		return attWrapper;
	}

	@AuraEnabled
	public static String updateIsPresent(String SRN_Number, String DriveName) {
		try {
			if (String.isNotBlank(SRN_Number) && String.isNotBlank(DriveName)) {
				List<Rpl_Student_Registration_Drive__c> studentRegDrive = [
					SELECT Id, Rpl_Is_Present__c, Rpl_Student_Registration__r.Rpl_Is_Blocked__c
					FROM Rpl_Student_Registration_Drive__c
					WHERE
						Rpl_Student_Registration__r.Contact__r.SRN_Number__c = :SRN_Number
						AND Rpl_Placement_Drive__r.Name = :DriveName
					LIMIT 1
				];

				if (!studentRegDrive.isEmpty() && studentRegDrive[0].Rpl_Student_Registration__r.Rpl_Is_Blocked__c) {
					return 'false';
				} else if (!studentRegDrive.isEmpty()) {
					studentRegDrive[0].Rpl_Is_Present__c = true;
					update studentRegDrive;
					return 'true';
				}
			}
			// Add a default return statement outside the if conditions
			return 'false';
		} catch (Exception e) {
			// Log the exception
			ErrorLogUtility.logError(e);
			// Return an error message
			return e.getMessage();
		}
	}

	public class AttachmentWrapper {
		@AuraEnabled
		public string Body;
		@AuraEnabled
		public string Name;
	}

	@AuraEnabled
	public static PlacementSummaryDetailsWrapper getPlacementSummaryDetails() {
		PlacementSummaryDetailsWrapper wrapper = new PlacementSummaryDetailsWrapper();
		wrapper.offerCount = getOfferCount();
		wrapper.totalDrives = getTotalNumberOfEligibleDrives();
		wrapper.upcomingDriveDate = getUpcomingDrive();
		return wrapper;
	}

	public class PlacementSummaryDetailsWrapper {
		@AuraEnabled
		public Integer offerCount;
		@AuraEnabled
		public Integer totalDrives;
		@AuraEnabled
		public String upcomingDriveDate;
	}
}