force-app/main/default/objects/Contact/fields/SRN_Number__c.field-meta.xml
<CustomField>
    <fullName>SRN_Number__c</fullName>
    <externalId>true</externalId>
    <label>SRN Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <formula>IF(Record_Type_Name__c = &apos;Student&apos;, true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DB-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/No_of_Records__c.field-meta.xml
<CustomField>
    <fullName>No_of_Records__c</fullName>
    <label>No of Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Processing_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Processing_API_Name__c</fullName>
    <label>Processing API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <label>Request</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/Rve_Exam_Notification__c.object-meta.xml
<CustomObject>
    <label>REVA Exam Notification</label>
    <nameField>
        <label>Exam Notification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REVA Exam Notifications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/rve_Active__c.field-meta.xml
<CustomField>
    <fullName>rve_Active__c</fullName>
    <formula>IF(
    AND(
        rve_Exam_Start_Date__c &gt;= TODAY(),
        rve_Exam_Start_Date__c &lt;= (TODAY() + 4)
    ),
    true,
    IF(
        TODAY() &lt;= Rve_End_Date__c,
        true,
        false
    )
)</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Course__c.field-meta.xml
<CustomField>
    <fullName>Rve_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipName>Reva_Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Publish__c.field-meta.xml
<CustomField>
    <fullName>Rve_Publish__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rve_Exam_Notification__c/fields/Rve_Semester__c.field-meta.xml
<CustomField>
    <fullName>Rve_Semester__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Semester</label>
    <referenceTo>hed__Term__c</referenceTo>
    <relationshipName>Reva_Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Semester_Room_Allotment__c/Rve_Semester_Room_Allotment__c.object-meta.xml
<CustomObject>
    <description>This Object is using for storing Semester Room allotments getting from logisys</description>
    <label>Semester Room Allotment</label>
    <nameField>
        <label>Semester  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Semester Room Allotments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rve_Semester_Room_Allotment__c/fields/Rve_Course__c.field-meta.xml
<CustomField>
    <fullName>Rve_Course__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course</label>
    <referenceTo>hed__Course__c</referenceTo>
    <relationshipLabel>Semester Room Allotments</relationshipLabel>
    <relationshipName>Semester_Room_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rve_Semester_Room_Allotment__c/fields/Rve_Message__c.field-meta.xml
<CustomField>
    <fullName>Rve_Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rve_Semester_Room_Allotment__c/fields/Rve_QP_Code__c.field-meta.xml
<CustomField>
    <fullName>Rve_QP_Code__c</fullName>
    <label>QP Code</label>
    <length>125</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rve_Semester_Room_Allotment__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Semester Room Allotments</relationshipLabel>
    <relationshipName>Semester_Room_Allotments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Rve_FetchSemesterRoomAllotmentBatch.cls
/**
* @description       : This batch is used to fetch Semester room allotments from logisys.
* @author            : Aditya Dhulipala
* @group             : Cloud Odyssey
* @last modified on  : 05-04-2024
* @last modified by  : 
* @Comments          : this class will call from Schedule, It will run everyday 
**/
public with sharing class Rve_FetchSemesterRoomAllotmentBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    
    public Database.QueryLocator start(Database.BatchableContext bc)
    {
        return database.getQueryLocator([SELECT Id,Rve_Semester__r.Exam_Start_Date__c, Rve_Semester__r.Exam_End_Date__c, 
                                         Rve_Publish__c, rve_Active__c  FROM Rve_Exam_Notification__c 
                                         WHERE Rve_Publish__c =true AND Rve_Semester__r.Exam_Start_Date__c<=TODAY 
                                         AND Rve_Semester__r.Exam_End_Date__c>=TODAY]);
    }
    public void execute(Database.BatchableContext Bc, List<Rve_Exam_Notification__c> lstNotifications)
    {
        List<Rve_Semester_Room_Allotment__c> roomArrangmentsToInsert = new List<Rve_Semester_Room_Allotment__c>();
        Debug_Log__c dLog = new Debug_Log__c();
        dLog.Class_Name__c = 'Rve_FetchSemesterRoomAllotmentBatch';
        dLog.Status__c = 'Failure';
        dLog.Processing_API_Name__c = 'Student semester Room Allotments from Logisys to SLCM';
        dLog.Object_Name__c = 'Rve_Semester_Room_Allotment__c';
        dLog.No_of_Records__c = lstNotifications.size();
        
        Integer MAX_REQ_LOG_SIZE = Schema.SObjectType.Debug_Log__c.fields.Request__c.length;
        Integer MAX_RES_LOG_SIZE = Schema.SObjectType.Debug_Log__c.fields.Response__c.length;
        List<String> sessions =new List<string>{'M','N'};
        for(string session: sessions){
            Rve_Exam_Notification__c notification = lstNotifications[0];
            Datetime today = Datetime.now(); 
            String formattedDate = today.format('yyyy-MM-dd'); 
                ExamDatesWrapper wrapper = new ExamDatesWrapper();
                wrapper.edate= '2024-01-08';//formattedDate;
                wrapper.esession=session;
                String jsonBody = json.serialize(wrapper);
                dLog.Request__c = jsonBody.abbreviate(MAX_REQ_LOG_SIZE);
                HttpRequest hReq = LogisysAPIUtility.mapRequest('Rve_GetSemesterRoomAllotment',jsonBody);
                Http http = new Http();
                HttpResponse hRsp = http.send(hReq);
            
                String response = hRsp+' ::: '+hRsp.getBody();
                dLog.Response__c = response.abbreviate(MAX_RES_LOG_SIZE);
                system.debug('response-->'+response);
                if(hRsp.getStatusCode() == 200){
                    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(hRsp.getBody());
                    String status = (String) responseMap.get('status');
                    String resBody = hRsp.getBody();
                    system.debug('resBody-->'+resBody);
                    system.debug('status-->'+status);
                    dLog.Status__c=Status;
                    If(Status=='success'){
                        rspWpr rsp = (rspWpr) Json.deserialize(resBody, rspWpr.class);
                        system.debug('rsp-->'+rsp.data);
                        system.debug('resData-->'+responseMap.get('data'));
                        set<string> courseCode = new Set<string>();
                        set<String> studentSRN = new set<String>();
                        Map<string,Id> srnStudentIdMap = new Map<string,Id>();
                        Map<string,Id> courseCodeCourseIdMap = new Map<string,Id>();
                        For(resdata reswrapper: rsp.data.resdata ){
                            courseCode.add(reswrapper.subshort);
                            studentSRN.add(reswrapper.regno);
                        }
                        
                        For(hed__Course__c course : [Select Id,hed__Course_ID__c from hed__Course__c where hed__Course_ID__c IN :courseCode]){
                            courseCodeCourseIdMap.put(course.hed__Course_ID__c,course.Id);
                        }
                        for(Contact student :[Select Id,SRN_Number__c from Contact  where SRN_Number__c IN :studentSRN]){
                            srnStudentIdMap.put(student.SRN_Number__c,student.Id);
                        }
                        For(resdata responsewrp: rsp.data.resdata ){
                            system.debug('Response-->'+responsewrp);
                            If(srnStudentIdMap.get(responsewrp.regno)!=NULL){
                                Rve_Semester_Room_Allotment__c seating = new Rve_Semester_Room_Allotment__c();
                                seating.Name =responsewrp.regno;
                                seating.Rve_QP_Code__c=responsewrp.qpcode;
                                seating.Student__c= srnStudentIdMap.get(responsewrp.regno);
                                seating.Rve_Course__c=courseCodeCourseIdMap.get(responsewrp.subshort);
                                seating.Rve_Message__c=responsewrp.msg;
                                roomArrangmentsToInsert.add(seating);
                            }
                        }
                    }
                } 
        }
        If(roomArrangmentsToInsert.size()>0){
            insert roomArrangmentsToInsert;
        } 
    }
    public void finish(DataBase.BatchableContext bc)
    {
        
    }
    public class ExamDatesWrapper{
        public string edate;
        public string esession;
    }
    public class rspWpr{
        public String status{get;set;}
        public dataWpr data;
        public Integer error_code{get;set;}
  }
  public class resdata{
      public String regno{get;set;}
      public String qpcode{get;set;}
      public String msg{get;set;}
      public String subshort{get;set;}   
  }
  public class dataWpr{
    public list<resdata> resdata{get;set;}
 }
}