force-app/main/default/objects/Contact/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Student_Fee_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Student Fee Payment</description>
    <inlineHelpText>Student Fee Payment</inlineHelpText>
    <label>Student Fee Payment</label>
    <referenceTo>Student_Fee_Payment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Student, Applicant,Non Teaching,Alumni,Professor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student  Payments</relationshipLabel>
    <relationshipName>Student_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OneTimeOwnerChangeTest.cls
@isTest
public class OneTimeOwnerChangeTest {
  @isTest
    static void testBatchExecution() {
        // Create test data for Contact
        User newUser = new User(
            FirstName = '',
            LastName = 'Aman V C',
            Alias = 'oldaman',
            Email = 'oldaman@example.com',
            Username = 'oldaman@example.com',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'counselor'].Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive = true
        );
        insert newUser;

        User oldUser = new User(
            FirstName = 'New',
            LastName = 'Aman V C',
            Alias = 'newaman',
            Email = 'newaman@example.com',
            Username = 'newaman@example.com',
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'counselor'].Id,
            TimeZoneSidKey = 'Asia/Kolkata',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive = true
        );
        insert oldUser;

         Account testAccount = new Account(Name = 'Test Account', OwnerId = newUser.Id);
        insert testAccount;
        
        Contact testContact = new Contact(FirstName = 'Test', LastName = 'Contact', OwnerId = newUser.Id);
        insert testContact;
        
        Lead testLead = new Lead(FirstName = 'Test', LastName = 'Lead', OwnerId = newUser.Id);
        insert testLead;
        
        hed__Application__c testapp = new hed__Application__c(OwnerId = newUser.Id);
        insert testapp;
              
       //randa__Application_Review__c testAppRe = new randa__Application_Review__c(OwnerId = newUser.Id);
        //insert testAppRe;
        
        Student_fee__c StuFee = new Student_fee__c(contact__c=testContact.Id,OwnerId = newUser.Id);
        insert StuFee;
        
        Student_payment__c StuPay = new Student_payment__c(contact__c=testContact.Id,OwnerId = newUser.Id);
        insert StuPay;
        
       student_Fee_payment__c StuFeePay = new student_Fee_payment__c(OwnerId = newUser.Id);
        insert StuFeePay;        
        
   
       Test.startTest();
        OneTimeOwnerChange batchClassInstance = new OneTimeOwnerChange();
        Database.executeBatch(batchClassInstance);
        Test.stopTest();
}
}