force-app/main/default/objects/Batch_Failure_Emails__c/Batch_Failure_Emails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Batch Failure Emails</label>
</CustomObject>

force-app/main/default/objects/Batch_Failure_Emails__c/fields/Email_Ids__c.field-meta.xml
<CustomField>
    <fullName>Email_Ids__c</fullName>
    <label>Email Ids</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Student_Semester_Mapping__c/Student_Semester_Mapping__c.object-meta.xml
<CustomObject>
    <label>Student Semester Mapping</label>
    <nameField>
        <label>Student Semester Mapping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Semester Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchClass_Utility_Test.cls
@isTest
public class BatchClass_Utility_Test 
{
    public static testMethod void BatchClassUtility()
    {
        Batch_Failure_Emails__c btEmail = new Batch_Failure_Emails__c();
        btEmail.name='Assessment Module';
        btEmail.Email_Ids__c = 'chetan@epeoplebc.com';
        insert btEmail;
        
        Test.startTest();         
        ASM_UpdateCourseConnectionBatch btch = new ASM_UpdateCourseConnectionBatch();
        Id jobid= Database.executeBatch(btch,5);
        BatchClass_Utility.sendBatchClassFailureMail('Assessment Module',jobid,'Create Course Connection Batch','Student_Semester_Mapping__c');
        Test.stopTest();
        system.assertEquals('Assessment Module', btEmail.name);
    }
    
}