force-app/main/default/objects/REVA_Hostel_Leave_Request__c/REVA_Hostel_Leave_Request__c.object-meta.xml
<CustomObject>
    <label>REVA Hostel Leave Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>REVA Hostel Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVA Hostel Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/REVA_Hostel_Leave_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Id</field>
            <operation>equals</operation>
            <valueField>$User.ContactId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>REVA Hostel Leave Requests</relationshipLabel>
    <relationshipName>REVA_Hostel_Leave_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REVA_Hostel_Leave_Request__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>DATEVALUE( End_Date_and_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REVA_Hostel_Leave_Request__c/fields/End_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_and_Time__c</fullName>
    <label>End Date and Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/REVA_Hostel_Leave_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leave Requested</fullName>
                <default>true</default>
                <label>Leave Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Check Out</fullName>
            </value>
            <value>
                <fullName>Check In</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MissedMealFee.cls
public class MissedMealFee implements Database.Batchable<sObject>, Database.Stateful {
   
    public Database.QueryLocator Start(Database.BatchableContext bc) {
        Date tomorrowDate = Date.today().addDays(1);  
        system.debug('tomorrowDate::'+tomorrowDate);
        system.debug('RecordId::'+[SELECT Id,End_Date__c,status__C, End_Date_and_Time__c,Contact__c FROM REVA_Hostel_Leave_Request__c WHERE End_Date__c = :tomorrowDate]);
        // Query leave requests ending tomorrow
        String query = 'SELECT Id,End_Date__c,Status__c, End_Date_and_Time__c,Contact__c ,Contact__r.Email FROM REVA_Hostel_Leave_Request__c WHERE End_Date__c = :tomorrowDate and Status__c =\'Approved\' ';
        
        return Database.getQueryLocator(query);
    }
   
    public void Execute(Database.BatchableContext BC, List<REVA_Hostel_Leave_Request__c> scope) {
        
    }
    
    public void Finish(Database.BatchableContext leadContext) {
        
        
    }
}