force-app/main/default/objects/REVA_Hostel_Leave_Request__c/REVA_Hostel_Leave_Request__c.object-meta.xml
<CustomObject>
    <label>REVA Hostel Leave Request</label>
    <nameField>
        <displayFormat>REQ-{0000}</displayFormat>
        <label>REVA Hostel Leave Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REVA Hostel Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/REVA_Hostel_Leave_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Contact.Id</field>
            <operation>equals</operation>
            <valueField>$User.ContactId</valueField>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>System Administrator</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>REVA Hostel Leave Requests</relationshipLabel>
    <relationshipName>REVA_Hostel_Leave_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REVA_Hostel_Leave_Request__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>DATEVALUE( End_Date_and_Time__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REVA_Hostel_Leave_Request__c/fields/End_Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Date_and_Time__c</fullName>
    <label>End Date and Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/REVA_Hostel_Leave_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Leave Requested</fullName>
                <default>true</default>
                <label>Leave Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Check Out</fullName>
            </value>
            <value>
                <fullName>Check In</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendNotificationBeforeOneday.cls
public class SendNotificationBeforeOneday implements Database.Batchable<sObject>, Database.Stateful {
/*
SendNotificationBeforeOnedaySCH sch = new SendNotificationBeforeOnedaySCH();
System.schedule('Hostel Leave Request Batch Schedule - I', '0 00 * * * ? ' , sch);
System.schedule('Hostel Leave Request Batch Schedule - II', '0 15 * * * ? ' , sch);
System.schedule('Hostel Leave Request Batch Schedule - III', '0 30 * * * ? ' , sch);
System.schedule('Hostel Leave Request Batch Schedule - IV', '0 45 * * * ? ' , sch);
*/
    public Database.QueryLocator Start(Database.BatchableContext bc) {
        Date tomorrowDate = Date.today().addDays(1);  
        system.debug('tomorrowDate::'+tomorrowDate);
        system.debug('RecordId::'+[SELECT Id,End_Date__c,status__C, End_Date_and_Time__c,Contact__c FROM REVA_Hostel_Leave_Request__c WHERE End_Date__c = :tomorrowDate]);
        // Query leave requests ending tomorrow
        String query = 'SELECT Id,End_Date__c,Status__c, End_Date_and_Time__c,Contact__c ,Contact__r.Email FROM REVA_Hostel_Leave_Request__c WHERE End_Date__c = :tomorrowDate and Status__c =\'Approved\' ';
        
        return Database.getQueryLocator(query);
    }
   
    public void Execute(Database.BatchableContext BC, List<REVA_Hostel_Leave_Request__c> scope) {
         DateTime now = DateTime.now();
         Id templateId = '00X1e000000SeQeEAK';
         List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
         for (REVA_Hostel_Leave_Request__c record : scope) {
             system.debug('now.hour()::'+now.hour());
              system.debug('now.minute()::'+now.minute());
         if (record.End_Date_and_Time__c != null && record.End_Date_and_Time__c.hour() == now.hour() && record.End_Date_and_Time__c.minute() == now.minute()) {
              system.debug('Hello');
             // Create an email
             Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
             mail.setTargetObjectId(record.Contact__c);
             mail.setWhatId(record.Id); 
             mail.setTemplateId(templateId);
             mail.setSaveAsActivity(false); //
             // mail.setSubject('Hostel Leave Request Reminder');
             //mail.setPlainTextBody('This is a reminder that your hostel leave request is ending soon.');
             emails.add(mail);
            }
         }
        
        // Send all emails
        if (!emails.isEmpty()) {
            Messaging.sendEmail(emails);
        }
    }
    
    public void Finish(Database.BatchableContext leadContext) {
        
        
    }
}