force-app/main/default/objects/Sequence_Number__c/Sequence_Number__c.object-meta.xml
<CustomObject>
    <description>Object enabling generation of sequence numbers of various types</description>
    <label>Sequence Number</label>
    <nameField>
        <displayFormat>SEQ-{00000000}</displayFormat>
        <label>Sequence Number #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sequence Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sequence_Number__c/fields/Integer_Five__c.field-meta.xml
<CustomField>
    <fullName>Integer_Five__c</fullName>
    <defaultValue>0</defaultValue>
    <description>5 digit sequence number</description>
    <inlineHelpText>5 digit sequence number</inlineHelpText>
    <label>Integer Five</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sequence_Number__c/fields/Key_Field__c.field-meta.xml
<CustomField>
    <fullName>Key_Field__c</fullName>
    <description>The external id key field - named generically as the object can be used to generate various numbers</description>
    <externalId>true</externalId>
    <inlineHelpText>The external id key field</inlineHelpText>
    <label>Key Field</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RegistrationProcessUtilityTest.cls
@isTest
public class RegistrationProcessUtilityTest {
    
    @isTest
    public static void sequenceNumberMethod(){
        Sequence_Number__c sequenceNo = new Sequence_Number__c();
        sequenceNo.Key_Field__c = '230401';
        sequenceNo.Integer_Five__c = 94;
        insert sequenceNo;
        Test.startTest();
       
   		 //RegistrationProcessUtility.getNextSequence('230401');
       	 RegistrationProcessUtility.generateApplNoSequence('230401');
        Test.stopTest();
    }

    @isTest
    public static void challanNumberMethod(){
        Sequence_Number__c sequenceNo = new Sequence_Number__c();
        sequenceNo.Key_Field__c = 'RU23';
        sequenceNo.Integer_Five__c = 94;
        insert sequenceNo;
        Test.startTest();
       
   		 //RegistrationProcessUtility.getNextSequence('230401');
       	 RegistrationProcessUtility.generateChallanNoSequence('RU23');
        Test.stopTest();
    }

    @isTest
    public static void testCETApplicationNumber(){
        Sequence_Number__c sequenceNo = new Sequence_Number__c();
        sequenceNo.Key_Field__c = 'CET';
        sequenceNo.Integer_Five__c = 0;
        insert sequenceNo;
        
        Test.startTest();
       	String cetApplNo = RegistrationProcessUtility.getCETApplicationNumber('UG','CET');
        Test.stopTest();

        System.assertEquals('UGCET2400001', cetApplNo);
    }
     @isTest
    public static void testPGCETApplicationNumber(){
        Sequence_Number__c sequenceNo = new Sequence_Number__c();
        sequenceNo.Key_Field__c = 'PGCET';
        sequenceNo.Integer_Five__c = 0;
        insert sequenceNo;
        
        Test.startTest();
       	String cetApplNo = RegistrationProcessUtility.getCETApplicationNumber('UG','PGCET');
        Test.stopTest();

        System.assertEquals('PGCET2400001', cetApplNo);
    }
     @isTest
    public static void testComedKApplicationNumber(){
        Sequence_Number__c sequenceNo = new Sequence_Number__c();
        sequenceNo.Key_Field__c = 'CDK';
        sequenceNo.Integer_Five__c = 0;
        insert sequenceNo;
        
        Test.startTest();
       	String cetApplNo = RegistrationProcessUtility.getCETApplicationNumber('UG','CDK');
       RegistrationProcessUtility.getCounselorIndex();
        Test.stopTest();

        System.assertEquals('UGCDK2400001', cetApplNo);
    }
}