force-app/main/default/objects/Pincode_Master__c/Pincode_Master__c.object-meta.xml
<CustomObject>
    <label>Pincode Master</label>
    <nameField>
        <displayFormat>PIN-{000000}</displayFormat>
        <label>Pincode Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pincode Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pincode_Master__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Captures the City name</description>
    <inlineHelpText>Enter the City name</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pincode_Master__c/fields/Post_Office__c.field-meta.xml
<CustomField>
    <fullName>Post_Office__c</fullName>
    <label>Post Office</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PincodeDetails.cls
public with sharing class PincodeDetails {

    @AuraEnabled(cacheable = true)
    public static List < Pincode_Master__c > getPincodeDetails(String pincode) {
        System.debug('Got accStrName: ' + pincode);
        List < Pincode_Master__c > pincodeAddresses = [SELECT Id, State__c, Post_Office__c, Pincode__c, District__c, City__c
            FROM Pincode_Master__c
            WHERE Pincode__c =: pincode
        ];
        return (pincodeAddresses);
    }
    @AuraEnabled(cacheable = true)
    public static Pincode_Master__c selectedPincodeDetails(string selectedPincodeId) {
        return [select Id, State__c, Post_Office__c, Pincode__c, City__c
                From Pincode_Master__c 
                WHERE Id =: selectedPincodeId 
                limit 1
                ];
    }
}