force-app/main/default/objects/Pincode_Master__c/Pincode_Master__c.object-meta.xml
<CustomObject>
    <label>Pincode Master</label>
    <nameField>
        <displayFormat>PIN-{000000}</displayFormat>
        <label>Pincode Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pincode Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Pincode_Master__c/fields/Circle__c.field-meta.xml
<CustomField>
    <fullName>Circle__c</fullName>
    <description>Post office circle</description>
    <inlineHelpText>Post office circle</inlineHelpText>
    <label>Circle</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pincode_Master__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>Captures the City name</description>
    <inlineHelpText>Enter the City name</inlineHelpText>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pincode_Master__c/fields/Delivery_Non_Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Non_Delivery__c</fullName>
    <description>Whether the post office delivers mail</description>
    <inlineHelpText>Whether the post office delivers mail</inlineHelpText>
    <label>Delivery / Non Delivery</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pincode_Master__c/fields/Division__c.field-meta.xml
<CustomField>
    <fullName>Division__c</fullName>
    <description>Post office division</description>
    <inlineHelpText>Post office division</inlineHelpText>
    <label>Division</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pincode_Master__c/fields/Office_Type__c.field-meta.xml
<CustomField>
    <fullName>Office_Type__c</fullName>
    <description>Post office type</description>
    <inlineHelpText>Post office type</inlineHelpText>
    <label>Office Type</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pincode_Master__c/fields/Post_Office__c.field-meta.xml
<CustomField>
    <fullName>Post_Office__c</fullName>
    <label>Post Office</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pincode_Master__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Post office region</description>
    <inlineHelpText>Post office region</inlineHelpText>
    <label>Region</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PincodeDetails_Test.cls
@isTest
public class PincodeDetails_Test {
    @TestSetup
    static void createTestData() {
        Pincode_Master__c recWithPincode = new Pincode_Master__c();
        recWithPincode.State__c =  'Tamil Nadu';
        recWithPincode.City__c =  'CBE';
        recWithPincode.Pincode__c = '641062';
        recWithPincode.District__c = 'Coimbatore';
        recWithPincode.Post_Office__c = 'Neelambur';
        recWithPincode.Circle__c = 'Test Circle';
        recWithPincode.Region__c = 'Test Regio';
        recWithPincode.Division__c = 'Test Division';
        recWithPincode.Office_Type__c = 'Type';
        recWithPincode.Delivery_Non_Delivery__c = 'Test Delivery';
        insert recWithPincode;
    }

    @isTest 
    static void testPincodeDetails() {
        List<Pincode_Master__c> getPicodeRecId = [SELECT Id FROM Pincode_Master__c Where Pincode__c = '641062' limit 1 ];
        PincodeDetails.getPincodeDetails('641062');
        PincodeDetails.selectedPincodeDetails(getPicodeRecId[0].Id);
        System.assertEquals(1, getPicodeRecId.size());
    }
}