force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Demand_Number__c.field-meta.xml
<CustomField>
    <fullName>Demand_Number__c</fullName>
    <label>Demand Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Display_No__c.field-meta.xml
<CustomField>
    <fullName>Display_No__c</fullName>
    <label>Display No</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 1st Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 2nd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 3rd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 4th Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 5th Year</label>
            </value>
            <value>
                <fullName>University Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 1st Year</label>
            </value>
            <value>
                <fullName>University Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 2nd Year</label>
            </value>
            <value>
                <fullName>University Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 3rd Year</label>
            </value>
            <value>
                <fullName>University Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 4th Year</label>
            </value>
            <value>
                <fullName>University Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 5th Year</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Line_Item_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Transaction_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date_Time__c</fullName>
    <label>Transaction Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Auto_Allocate__c.field-meta.xml
<CustomField>
    <fullName>Auto_Allocate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Allocate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Auto_Allocate_isDone__c.field-meta.xml
<CustomField>
    <fullName>Auto_Allocate_isDone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Allocate isDone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Student, Applicant,Non Teaching,Alumni,Professor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student  Payments</relationshipLabel>
    <relationshipName>Student_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Demand_Number__c.field-meta.xml
<CustomField>
    <fullName>Demand_Number__c</fullName>
    <label>Demand Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>RazorPay</fullName>
                <isActive>false</isActive>
                <label>RazorPay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date_Time__c</fullName>
    <label>Payment Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/SAP_Code__c.field-meta.xml
<CustomField>
    <fullName>SAP_Code__c</fullName>
    <externalId>true</externalId>
    <label>SAP Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Transaction_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date_Time__c</fullName>
    <label>Transaction Date Time(Technical)</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SAP_PaymentAllocationHandler.cls
public class SAP_PaymentAllocationHandler {
    public static void handlePaymentAllocation(List<Student_Payment__c> newPayments, Map<Id, Student_Payment__c> oldPaymentsMap) {
        Set<String> setSp = new Set<String>();
        Set<String> setSpDemandnotnull = new Set<String>();
        Set<String> setSpIdDemandNull = new Set<String>();
        Map<Id,string> mapStdPayment = new Map<Id,string>();
        for (Student_Payment__c sp : newPayments) {
            // Student_Payment__c oldPayment = oldPaymentsMap.get(sp.Id);
            /* if (sp.Auto_Allocate__c && !oldPayment.Auto_Allocate__c && !sp.Auto_Allocate_isDone__c) {
setSp.add(sp.Contact__c);
}*/
            if (sp.Auto_Allocate__c && (sp.SAP_Code__c != '' || sp.SAP_Code__c !=null )&& sp.Demand_Number__c == null)
                setSp.add(sp.Contact__c);
            /*if(sp.Demand_Number__c == null)
                setSpIdDemandNull.add(sp.Id);*/
            if(sp.Demand_Number__c != null && (sp.Auto_Allocate__c && (sp.SAP_Code__c != '' || sp.SAP_Code__c !=null ))){
                 setSpDemandnotnull.add(sp.Contact__c);
                mapStdPayment.put(sp.Id,sp.Demand_Number__c);
            }
               
        }
        
       /* if (setSp.isEmpty()) {
            return;
        }*/
        
        if(!setSp.isEmpty()){
            
            
            
            
            Set<String> feeTypes = new Set<String>{'University Fee', 'Tuition Fee'};
                Map<String, List<Student_Fee__c>> mapStuFees = new Map<String, List<Student_Fee__c>>();
            
            for(Student_Fee__c sf : [SELECT id,Contact__c,Fee_Type__c,Amount__c,Amount_Paid__c,Amount_Pending__c,Due_Date__c FROM Student_Fee__c 
                                     WHERE Contact__c =: setSp AND Due_Date__c != Null AND Amount_Pending__c > 0 AND 
                                     Fee_Type__c =: feeTypes ORDER By Due_Date__c ASC]){
                                         if(mapStuFees.containsKey(sf.Contact__c)){
                                             mapStuFees.get(sf.Contact__c).add(sf);
                                         }
                                         else{
                                             mapStuFees.put(sf.Contact__c,new list<Student_Fee__c>{sf});
                                         }
                                     }
            
            
            for(Student_Fee__c sf : [SELECT id,Contact__c,Fee_Type__c,Amount__c,Amount_Paid__c,Amount_Pending__c,Due_Date__c FROM Student_Fee__c 
                                     WHERE Contact__c =: setSp AND Due_Date__c = Null AND Amount_Pending__c > 0 AND 
                                     Fee_Type__c =: feeTypes  ORDER By Display_No__c ASC]){
                                         if(mapStuFees.containsKey(sf.Contact__c)){
                                             mapStuFees.get(sf.Contact__c).add(sf);
                                         }
                                         else{
                                             mapStuFees.put(sf.Contact__c,new list<Student_Fee__c>{sf});
                                         }
                                     }
            /* 
for(Student_Fee__c sf : [SELECT id,Contact__c,Fee_Type__c,Amount__c,Amount_Paid__c,Amount_Pending__c,Due_Date__c FROM Student_Fee__c 
WHERE Contact__c =: setSp AND Due_Date__c = Null AND Amount_Pending__c > 0 AND 
Fee_Type__c !=: type]){
if(mapStuFees.containsKey(sf.Contact__c)){
mapStuFees.get(sf.Contact__c).add(sf);
}
else{
mapStuFees.put(sf.Contact__c,new list<Student_Fee__c>{sf});
}
}

*/
            
            
            system.debug('mapStuFees++++++++'+mapStuFees);
            list<Student_Payment__c> updateStuPay = new  list<Student_Payment__c>();
            map<string,Student_Fee__c> updateStuFee = new  map<string,Student_Fee__c>();
            list<Student_Fee_Payment__c> updateSfp = new list<Student_Fee_Payment__c>();
            
            for(Student_Payment__c sp : newPayments){
                if(mapStuFees.containsKey(sp.Contact__c)){
                    //sp.Auto_Allocate_isDone__c = true;
                    updateStuPay.add(sp);
                    decimal paidAmount = sp.Amount__c;
                    
                    integer recSize = mapStuFees.get(sp.Contact__c).size();
                    integer count = 0;
                    for(Student_Fee__c sf : mapStuFees.get(sp.Contact__c)){
                        system.debug('paidAmount++++++++'+paidAmount);
                        count = count + 1;
                        
                        if(paidAmount > 0){
                            system.debug('Count+++++++++'+count);
                            system.debug('recSize+++++++++'+recSize);
                            if(sf.Amount_Pending__c > paidAmount && paidAmount > 0 && ((sf.Amount_Pending__c > 0 && recSize != count)|| recSize == count)){
                                
                                system.debug('sf.Amount_Paid__c+++++++++'+sf.Amount_Paid__c);
                                system.debug('sf.Amount__c+++++++++'+sf.Amount__c);
                                system.debug('sf.Amount_Pending__c+++++++++'+sf.Amount_Pending__c);
                                system.debug('paidAmount+++++++++'+paidAmount);
                                
                                Student_Fee_Payment__c sfp = new Student_Fee_Payment__c();
                                sf.Amount_Paid__c = sf.Amount_Paid__c + paidAmount;
                                sf.Amount_Pending__c = sf.Amount__c - sf.Amount_Paid__c;
                                sfp.Amount__c = paidAmount;
                                sfp.Mode_of_Payment__c = sp.Mode_of_Payment__c;
                                sfp.Student_Fee__c = sf.id;
                                sfp.Student_Payment__c = sp.id;
                                sfp.Line_Item_Payment_Status__c = sp.Payment_Status__c;
                                sfp.Transaction_Date_Time__c = sp.Payment_Date_Time__c;
                                sfp.Line_Item_Payment_Gateway__c = sp.Payment_Gateway__c;
                                sfp.Payment_Mode_Type__c = sp.Payment_Mode_Type__c;
                                sfp.Remarks__c = sp.Description__c;
                                updateSfp.add(sfp);
                                paidAmount = 0;
                            }
                            else if(sf.Amount_Pending__c < paidAmount && paidAmount > 0 && ((sf.Amount_Pending__c > 0 && recSize != count)|| recSize == count)){
                                
                                system.debug('sf.Amount_Paid__c+++++++++'+sf.Amount_Paid__c);
                                system.debug('sf.Amount__c+++++++++'+sf.Amount__c);
                                system.debug('sf.Amount_Pending__c+++++++++'+sf.Amount_Pending__c);
                                system.debug('paidAmount+++++++++'+paidAmount);
                                
                                Student_Fee_Payment__c sfp = new Student_Fee_Payment__c();
                                
                                if(recSize == count){
                                    sf.Amount_Paid__c = sf.Amount_Paid__c + paidAmount;
                                    sfp.Amount__c = paidAmount;
                                }
                                else{
                                    sf.Amount_Paid__c = sf.Amount_Paid__c + sf.Amount_Pending__c;
                                    sfp.Amount__c = sf.Amount_Pending__c;
                                }
                                paidAmount = paidAmount - sf.Amount_Pending__c;
                                sf.Amount_Pending__c = sf.Amount__c - sf.Amount_Paid__c;
                                sfp.Mode_of_Payment__c = sp.Mode_of_Payment__c;
                                sfp.Student_Fee__c = sf.id;
                                sfp.Student_Payment__c = sp.id;
                                sfp.Line_Item_Payment_Status__c = sp.Payment_Status__c;
                                sfp.Transaction_Date_Time__c = sp.Payment_Date_Time__c;
                                sfp.Line_Item_Payment_Gateway__c = sp.Payment_Gateway__c;
                                sfp.Payment_Mode_Type__c = sp.Payment_Mode_Type__c;
                                sfp.Remarks__c = sp.Description__c;
                                updateSfp.add(sfp);
                                
                            }
                            else if(sf.Amount_Pending__c == paidAmount && paidAmount > 0 && ((sf.Amount_Pending__c > 0 && recSize != count)|| recSize == count)){
                                
                                system.debug('sf.Amount_Paid__c+++++++++'+sf.Amount_Paid__c);
                                system.debug('sf.Amount__c+++++++++'+sf.Amount__c);
                                system.debug('sf.Amount_Pending__c+++++++++'+sf.Amount_Pending__c);
                                system.debug('paidAmount+++++++++'+paidAmount);
                                
                                sf.Amount_Paid__c = sf.Amount_Paid__c + paidAmount;
                                sf.Amount_Pending__c = sf.Amount__c - sf.Amount_Paid__c;
                                sf.Amount_Pending__c = 0;
                                Student_Fee_Payment__c sfp = new Student_Fee_Payment__c();
                                sfp.Amount__c = paidAmount;
                                sfp.Mode_of_Payment__c = sp.Mode_of_Payment__c;
                                sfp.Student_Fee__c = sf.id;
                                sfp.Student_Payment__c = sp.id;
                                sfp.Line_Item_Payment_Status__c = sp.Payment_Status__c;
                                sfp.Transaction_Date_Time__c = sp.Payment_Date_Time__c;
                                sfp.Line_Item_Payment_Gateway__c = sp.Payment_Gateway__c;
                                sfp.Payment_Mode_Type__c = sp.Payment_Mode_Type__c;
                                sfp.Remarks__c = sp.Description__c;
                                updateSfp.add(sfp);
                                paidAmount = 0;
                            }
                            updateStuFee.put(sf.id,sf);
                        }
                    }
                }
            }
            
            // Update student fees and payments
            if (!updateStuFee.isEmpty()) {
                update updateStuFee.values();
            }
            
            if (!updateStuPay.isEmpty()) {
                //update updateStuPay;
            }
            
            if (!updateSfp.isEmpty()) {
                insert updateSfp;
            }
        } 
         if(!setSpDemandnotnull.isEmpty()){
            
            
            Map<String, List<Student_Fee__c>> mapStuFees = new Map<String, List<Student_Fee__c>>();
            
            
            for(Student_Fee__c sf : [SELECT id,Contact__c,Fee_Type__c,Amount__c,Amount_Paid__c,Amount_Pending__c,Due_Date__c FROM Student_Fee__c 
                                     WHERE Contact__c =: setSpDemandnotnull AND Demand_Number__c IN:mapStdPayment.values()]){
                                         if(mapStuFees.containsKey(sf.Contact__c)){
                                             mapStuFees.get(sf.Contact__c).add(sf);
                                         }
                                         else{
                                             mapStuFees.put(sf.Contact__c,new list<Student_Fee__c>{sf});
                                         }
                                     }
            
            system.debug('mapStuFees++++++++'+mapStuFees);
            list<Student_Payment__c> updateStuPay = new  list<Student_Payment__c>();
            map<string,Student_Fee__c> updateStuFee = new  map<string,Student_Fee__c>();
            list<Student_Fee_Payment__c> updateSfp = new list<Student_Fee_Payment__c>();
            
            for(Student_Payment__c sp : newPayments){
                if(mapStuFees.containsKey(sp.Contact__c)){
                    //sp.Auto_Allocate_isDone__c = true;
                    updateStuPay.add(sp);
                    decimal paidAmount = sp.Amount__c;
                    
                    integer recSize = mapStuFees.get(sp.Contact__c).size();
                    integer count = 0;
                    for(Student_Fee__c sf : mapStuFees.get(sp.Contact__c)){
                        system.debug('paidAmount++++++++'+paidAmount);
                        count = count + 1;
                        
                        if(paidAmount > 0){
                            system.debug('Count+++++++++'+count);
                            system.debug('recSize+++++++++'+recSize);
                            if(sf.Amount_Pending__c > paidAmount && paidAmount > 0 && ((sf.Amount_Pending__c > 0 && recSize != count)|| recSize == count)){
                                
                                system.debug('sf.Amount_Paid__c+++++++++'+sf.Amount_Paid__c);
                                system.debug('sf.Amount__c+++++++++'+sf.Amount__c);
                                system.debug('sf.Amount_Pending__c+++++++++'+sf.Amount_Pending__c);
                                system.debug('paidAmount+++++++++'+paidAmount);
                                
                                Student_Fee_Payment__c sfp = new Student_Fee_Payment__c();
                                sf.Amount_Paid__c = sf.Amount_Paid__c + paidAmount;
                                sf.Amount_Pending__c = sf.Amount__c - sf.Amount_Paid__c;
                                sfp.Amount__c = paidAmount;
                                sfp.Mode_of_Payment__c = sp.Mode_of_Payment__c;
                                sfp.Student_Fee__c = sf.id;
                                sfp.Student_Payment__c = sp.id;
                                sfp.Line_Item_Payment_Status__c = sp.Payment_Status__c;
                                sfp.Transaction_Date_Time__c = sp.Payment_Date_Time__c;
                                sfp.Line_Item_Payment_Gateway__c = sp.Payment_Gateway__c;
                                sfp.Payment_Mode_Type__c = sp.Payment_Mode_Type__c;
                                sfp.Remarks__c = sp.Description__c;
                                updateSfp.add(sfp);
                                paidAmount = 0;
                            }
                            else if(sf.Amount_Pending__c < paidAmount && paidAmount > 0 && ((sf.Amount_Pending__c > 0 && recSize != count)|| recSize == count)){
                                
                                system.debug('sf.Amount_Paid__c+++++++++'+sf.Amount_Paid__c);
                                system.debug('sf.Amount__c+++++++++'+sf.Amount__c);
                                system.debug('sf.Amount_Pending__c+++++++++'+sf.Amount_Pending__c);
                                system.debug('paidAmount+++++++++'+paidAmount);
                                
                                Student_Fee_Payment__c sfp = new Student_Fee_Payment__c();
                                
                                if(recSize == count){
                                    sf.Amount_Paid__c = sf.Amount_Paid__c + paidAmount;
                                    sfp.Amount__c = paidAmount;
                                }
                                else{
                                    sf.Amount_Paid__c = sf.Amount_Paid__c + sf.Amount_Pending__c;
                                    sfp.Amount__c = sf.Amount_Pending__c;
                                }
                                paidAmount = paidAmount - sf.Amount_Pending__c;
                                sf.Amount_Pending__c = sf.Amount__c - sf.Amount_Paid__c;
                                sfp.Mode_of_Payment__c = sp.Mode_of_Payment__c;
                                sfp.Student_Fee__c = sf.id;
                                sfp.Student_Payment__c = sp.id;
                                sfp.Line_Item_Payment_Status__c = sp.Payment_Status__c;
                                sfp.Transaction_Date_Time__c = sp.Payment_Date_Time__c;
                                sfp.Line_Item_Payment_Gateway__c = sp.Payment_Gateway__c;
                                sfp.Payment_Mode_Type__c = sp.Payment_Mode_Type__c;
                                sfp.Remarks__c = sp.Description__c;
                                updateSfp.add(sfp);
                                
                            }
                            else if(sf.Amount_Pending__c == paidAmount && paidAmount > 0 && ((sf.Amount_Pending__c > 0 && recSize != count)|| recSize == count)){
                                
                                system.debug('sf.Amount_Paid__c+++++++++'+sf.Amount_Paid__c);
                                system.debug('sf.Amount__c+++++++++'+sf.Amount__c);
                                system.debug('sf.Amount_Pending__c+++++++++'+sf.Amount_Pending__c);
                                system.debug('paidAmount+++++++++'+paidAmount);
                                
                                sf.Amount_Paid__c = sf.Amount_Paid__c + paidAmount;
                                sf.Amount_Pending__c = sf.Amount__c - sf.Amount_Paid__c;
                                sf.Amount_Pending__c = 0;
                                Student_Fee_Payment__c sfp = new Student_Fee_Payment__c();
                                sfp.Amount__c = paidAmount;
                                sfp.Mode_of_Payment__c = sp.Mode_of_Payment__c;
                                sfp.Student_Fee__c = sf.id;
                                sfp.Student_Payment__c = sp.id;
                                sfp.Line_Item_Payment_Status__c = sp.Payment_Status__c;
                                sfp.Transaction_Date_Time__c = sp.Payment_Date_Time__c;
                                sfp.Line_Item_Payment_Gateway__c = sp.Payment_Gateway__c;
                                sfp.Payment_Mode_Type__c = sp.Payment_Mode_Type__c;
                                sfp.Remarks__c = sp.Description__c;
                                updateSfp.add(sfp);
                                paidAmount = 0;
                            }
                            updateStuFee.put(sf.id,sf);
                        }
                    }
                }
            }
            
            // Update student fees and payments
            if (!updateStuFee.isEmpty()) {
                update updateStuFee.values();
            }
            
            if (!updateStuPay.isEmpty()) {
                //update updateStuPay;
            }
            
            if (!updateSfp.isEmpty()) {
                insert updateSfp;
            }
        }
    }
}