force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Actual_Program_Fee__c.field-meta.xml
<CustomField>
    <fullName>Actual_Program_Fee__c</fullName>
    <description>Actual program fee - 1st year</description>
    <label>Actual Program Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Calculated_Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Amount_Pending__c</fullName>
    <formula>Calculated_Total_Amount__c - Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Calculated_Total_Amount__c - Amount_Paid__c</inlineHelpText>
    <label>Calculated Amount Pending</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Calculated_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Calculated_Total_Amount__c</fullName>
    <formula>Actual_Program_Fee__c + Premium__c - Concession__c - Scholarship__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This is SF Calculated Value.
Actual_Program_Fee__c + Premium__c - Concession__c - Scholarship__c</inlineHelpText>
    <label>Calculated Total Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Based on Application Number / SRN Number</description>
    <label>Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Non Teaching, Student, Applicant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Fees</relationshipLabel>
    <relationshipName>Student_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BulkStudentFeeUpdate.cls
public class BulkStudentFeeUpdate implements Database.Batchable<Student_Fee__c> { //, Database.Stateful
    public List<Id> recordIds;
    public List<Student_Fee__c> query =new List<Student_Fee__c>();
    // public Id newOwnerId;
    // List<Lead> leadsToUpdate = new List<Lead>();
    List<Student_Fee__c> stuFeeListUpdate = new List<Student_Fee__c>();

    public BulkStudentFeeUpdate(List<Id> recordIds) {
        this.recordIds = recordIds;
        // this.newOwnerId = newOwnerId;
    }

    public Iterable<Student_Fee__c> start(Database.BatchableContext context) {
        query = [SELECT Id, Name, Actual_Program_Fee__c, Amount_Paid__c, Amount_Pending__c, Calculated_Total_Amount__c, Calculated_Amount_Pending__c, Contact__c FROM Student_Fee__c WHERE Id IN :recordIds];
        return query;
    }

    public void execute(Database.BatchableContext context, List<Student_Fee__c> scope) {
        for (Student_Fee__c stufee : scope) {
            // lead.OwnerId = newOwnerId;
            stufee.Amount_Pending__c = stufee.Calculated_Amount_Pending__c;
            stufee.Amount__c = stufee.Calculated_Total_Amount__c;
            stuFeeListUpdate.add(stufee);
        }
        if(stuFeeListUpdate.size() > 0){
            update stuFeeListUpdate;
        }
    }

    public void finish(Database.BatchableContext context) {
        System.debug('student fee batch apex has been finished');
    }

    public class UpdateStuFeeInput {
        @InvocableVariable(required=true)
        public List<Id> recordIds;
    }
}