force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <description>seat blocking paid - 1st year</description>
    <label>Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Balance fee to be paid - 1st year</description>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Fee_Type__c</fullName>
    <label>Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Examination &amp; Valuation Fee</fullName>
            </value>
            <value>
                <fullName>Hostel Fee</fullName>
            </value>
            <value>
                <fullName>Miscellaneous Fee</fullName>
            </value>
            <value>
                <fullName>Transportation Fee</fullName>
            </value>
            <value>
                <fullName>University Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Academic Fee</fullName>
            </value>
            <value>
                <fullName>Application Fee</fullName>
            </value>
            <value>
                <fullName>Missed Meal Fee</fullName>
            </value>
            <value>
                <fullName>Penalty Fee</fullName>
            </value>
            <value>
                <fullName>Guest House Fee</fullName>
            </value>
            <value>
                <fullName>Tuition Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 1st Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 2nd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 3rd Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 4th Year</label>
            </value>
            <value>
                <fullName>Tuition Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>Tuition Fee 5th Year</label>
            </value>
            <value>
                <fullName>University Fee 1st Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 1st Year</label>
            </value>
            <value>
                <fullName>University Fee 2nd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 2nd Year</label>
            </value>
            <value>
                <fullName>University Fee 3rd Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 3rd Year</label>
            </value>
            <value>
                <fullName>University Fee 4th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 4th Year</label>
            </value>
            <value>
                <fullName>University Fee 5th Year</fullName>
                <isActive>false</isActive>
                <label>University Fee 5th Year</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Hostel_Late_Fee__c.field-meta.xml
<CustomField>
    <fullName>Hostel_Late_Fee__c</fullName>
    <description>Every Day 200 Fine, REVA-103</description>
    <formula>IF(
NOT(ISBLANK(Student_Hostel_Fee__c)),
IF(
TODAY() &gt; Student_Hostel_Fee__r.Date_of_Joining_Hostel__c + 30,
200 * (TODAY() - Student_Hostel_Fee__r.Date_of_Joining_Hostel__c - 30),
0
),
0
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hostel Late Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Number_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Installments__c</fullName>
    <label>Number of times Payment Allowed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student_Fee__c/fields/Paid_Installments__c.field-meta.xml
<CustomField>
    <fullName>Paid_Installments__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Times Payments Made</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateTotalAmountInPenaltyFeeBatch.cls
global class UpdateTotalAmountInPenaltyFeeBatch implements Database.Batchable<sObject> {
    
    /*
UpdateTotalAmountInPenaltyFeeScheduler sch = new UpdateTotalAmountInPenaltyFeeScheduler();
System.schedule('Hostel Panality Batch Schedule - I', '0 21 * * * ? ' , sch);
*/
    // Replace 'Student_Fee__c' with your object API name
    global Database.QueryLocator start(Database.BatchableContext BC) {
        // Query records that you want to update
        String query = 'SELECT Id, Hostel_Late_Fee__c, Amount__c,Amount_Paid__c, Amount_Pending__c FROM Student_Fee__c WHERE Fee_Type__c = \'Hostel Fee\' AND Name = \'Hostel Late Fee Payment\'';
        System.debug(query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Student_Fee__c> recordsToUpdate = new List<Student_Fee__c>();
        System.debug(scope);
        for (sObject s : scope) {
            Student_Fee__c record = (Student_Fee__c)s;
            System.debug('formula field: '+ record.Hostel_Late_Fee__c);
            // Replace 'Hostel_Late_Fee__c' with your formula field API name
            // Replace 'Amount__c' with the field API name you want to update
            record.Amount__c = record.Hostel_Late_Fee__c;
            record.Amount_Pending__c = record.Hostel_Late_Fee__c  - record.Amount_Paid__c;
            System.debug('amount field: '+ record.Amount__c);
             record.Number_of_Installments__c = 1;
            record.Paid_Installments__c = 0;
            recordsToUpdate.add(record);
        }
        
        // Update the records
        update recordsToUpdate;
    }

    global void finish(Database.BatchableContext BC) {
        // Execute any post-processing logic here
    }
}