force-app/main/default/objects/Student_Fee__c/Student_Fee__c.object-meta.xml
<CustomObject>
    <label>Student Fee</label>
    <nameField>
        <label>Student Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Student Fees</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Actual fee fixed - 1st year</description>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/Student_Fee_Payment__c.object-meta.xml
<CustomObject>
    <label>Student Fee Payment</label>
    <nameField>
        <displayFormat>SFP-{0000}</displayFormat>
        <label>Student Fee Payments Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Fee Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Line_Item_Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Item_Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Link Created</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/SF_Transaction_ID__c.field-meta.xml
<CustomField>
    <fullName>SF_Transaction_ID__c</fullName>
    <label>SF Transaction ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Fee__c.field-meta.xml
<CustomField>
    <fullName>Student_Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Fee</label>
    <referenceTo>Student_Fee__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Student_Payment__c.field-meta.xml
<CustomField>
    <fullName>Student_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Payment</label>
    <referenceTo>Student_Payment__c</referenceTo>
    <relationshipLabel>Student Fee Payments</relationshipLabel>
    <relationshipName>Student_Fee_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Fee_Payment__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status (Technical)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/Student_Payment__c.object-meta.xml
<CustomObject>
    <label>Student  Payment</label>
    <nameField>
        <displayFormat>SP-{0000}</displayFormat>
        <label>Student Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student  Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Offline</fullName>
            </value>
            <value>
                <fullName>Card Swipe</fullName>
                <isActive>false</isActive>
                <label>Card Swipe</label>
            </value>
            <value>
                <fullName>Cash</fullName>
                <isActive>false</isActive>
                <label>Cash</label>
            </value>
            <value>
                <fullName>Cash Collected in Bank</fullName>
                <isActive>false</isActive>
                <label>Cash Collected in Bank</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
                <isActive>false</isActive>
                <label>Cheque</label>
            </value>
            <value>
                <fullName>RazorPay</fullName>
                <isActive>false</isActive>
                <label>RazorPay</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student_Payment__c/fields/Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Status__c</fullName>
    <label>Transaction Status(Technical)</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QueueableStudentFeeBalanceUpdate.cls
public class QueueableStudentFeeBalanceUpdate  implements System.Queueable , Database.AllowsCallouts {
    Set<Id> stuFeeSet = new Set<Id>();

    public QueueableStudentFeeBalanceUpdate (Set<Id> stufeeSet){
        stuFeeSet = stufeeSet;
    } 
    
    public void execute(QueueableContext context){
        List<Student_Fee_Payment__c> stuFeePayList = [SELECT Id, Name, Amount__c, Line_Item_Payment_Status__c, Student_Payment__c, Mode_of_Payment__c, SF_Transaction_ID__c, Student_Fee__c, Transaction_Status__c FROM Student_Fee_Payment__c WHERE Student_Fee__c =: stuFeeSet];
        FEE_StudentFeePaymentTriggerHandler.RollupAmount(stuFeePayList,Null);
    }
}