force-app/main/default/objects/Debug_Log__c/Debug_Log__c.object-meta.xml
<CustomObject>
    <label>Debug Log</label>
    <nameField>
        <displayFormat>DB-{000000}</displayFormat>
        <label>Debug Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Debug Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Debug_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <label>Class Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Data_Received__c.field-meta.xml
<CustomField>
    <fullName>Data_Received__c</fullName>
    <label>Data Received</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Payment_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Reference_Id__c</fullName>
    <label>Payment Reference Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Processing_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Processing_API_Name__c</fullName>
    <label>Processing API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Debug_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FEE_BilldeskServerResponseAPI.cls
@RestResource(UrlMapping='/BillDeskServerResponse/*')
global without sharing class FEE_BilldeskServerResponseAPI 
{    
    @HttpPost
    global static string ReceivedData()
    {
        Debug_Log__c dblog = new Debug_Log__c();
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        try{
            system.debug('request+++++++++++'+req);
            system.debug('request+++++++++++'+req.params.get('msg'));
            system.debug('requestBody+++++++++++'+req.requestBody.toString());
            string data = req.params.get('msg');
            
            dblog.Class_Name__c = 'FEE_BilldeskServerResponseAPI';
            dblog.Method_Name__c = 'ReceivedData';
            dblog.Processing_API_Name__c = 'BillDesk';            
            dblog.Data_Received__c = data;
            dblog.Status__c = 'Success'; 
                  
            String newStrReq = data;
            Integer reqLen = newStrReq.split('\\|').size();
            system.debug('reqLen.Size+++++++++++'+reqLen);           
            String checkSumValue = newStrReq.split('\\|')[reqLen-1];
            string referenceId = newStrReq.split('\\|')[reqLen-25];
            string PaymentMode = newStrReq.split('\\|')[reqLen-19];
            string statusCode = newStrReq.split('\\|')[reqLen-12];
            string transactionId = newStrReq.split('\\|')[reqLen-24];
            string StatusErrDes = newStrReq.split('\\|')[reqLen-2];
            system.debug('+++++++++'+referenceId);            
            dblog.Payment_Reference_Id__c = referenceId;
            dblog.Status__c = 'Success'; 
            insert dblog;
        }
        catch(Exception Ex){
            dblog.Status__c = 'Failure';
            dblog.Error_Message__c = string.valueof(Ex);
            upsert dblog;
        }
         return dblog.Status__c;
    }
}